src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Describes relationship with AECOM - Choose all that might apply</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Client/Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subcontractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime/Teaming Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concessionaire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrollment_Comments__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will be filled in for the person who created the approver comments.</description>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Enrollment_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EnrollmentApplication__c</fullName>
        <label>Enrollment Application</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Enrollment Comments</relationshipLabel>
        <relationshipName>Enrollment_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_Codes__c</fullName>
        <description>When rejection is required, use the dropdown list to select from the most commonly noted reasons. Comments must be logged with each rejection for the reference of the original submitter, prior approvers, and DTW Admin. If corrections to the application</description>
        <inlineHelpText>When rejection is required, use the dropdown list to select from the most commonly noted reasons. Comments must be logged with each rejection for the reference of the original submitter, prior approvers, and DTW Admin. If corrections to the application</inlineHelpText>
        <label>Reason Codes</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Poor Project Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project on Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project in Litigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Nearing Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More Suitable for T&amp;M Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More Suitable for FP Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project is Intercompany – Client is AECOM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected For Corrections (explain in comments)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Comment Type</label>
        <picklist>
            <controllingField>IsRejection__c</controllingField>
            <picklistValues>
                <fullName>General</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Exception</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejection for Corrections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interim Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Enrollment Comment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>EC-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EnrollmentPlan__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW Enrollment Plans under review by Approvers</description>
    <label>Enrollment Application</label>
    <nameField>
        <label>Enrollment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Applications</pluralLabel>
    <recordTypes>
        <fullName>Exception</fullName>
        <active>true</active>
        <label>Exception</label>
    </recordTypes>
    <recordTypes>
        <fullName>Workflow</fullName>
        <active>true</active>
        <label>Workflow</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/INC_EACreateRejectComments_Controller.cls
public with sharing class INC_EACreateRejectComments_Controller {

	  public EnrollmentPlan__c oEnrollmentPlan{get;set;}
    public Enrollment_Comments__c oEnrollComment{get;set;}
    public boolean shouldRedirect {get;set;}
    public String url{get;set;}
    public String sMessage{get;set;}
    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public INC_EACreateRejectComments_Controller(ApexPages.StandardController stdController) {
        this.oEnrollmentPlan = (EnrollmentPlan__c)stdController.getRecord();
        this.oEnrollmentPlan = INC_Service_EnrollmentPlan.getEnrollmentPlan(new set<id>{oEnrollmentPlan.id})[0];
        shouldRedirect = false;
        url = '/' + oEnrollmentPlan.ID;
        getLatestRejectionComment();
    }

    private void getLatestRejectionComment(){
        list<Enrollment_Comments__c> lComments = [Select ID
                                                          , Comments__c
                                                          , Type__c
                                                          , Reason_Codes__c
                                                          , Approver__c
                                                          , Approver__r.Name
                                                 From Enrollment_Comments__c
                                                 Where EnrollmentApplication__c =: oEnrollmentPlan.ID
                                                 and (Type__c = 'Rejection' or Type__c ='Rejection for Corrections')
                                                 and (Reason_Codes__c = null)
                                                 Order by CreatedDate];
        //find the latest one, hopefully the query should only return one.  But I have to account for bad data
        System.Debug(logginglevel.error,'lcomments: ' + lComments);
        if(lComments != Null && lComments.size() > 0){
                oEnrollComment = lComments[0];
                sMessage = lComments[0].Approver__r.Name + ' rejected the application.  A rejection code must be selected before any changes to the';
                sMessage += ' application are possible.';
        }else{
          oEnrollComment = new Enrollment_Comments__c(EnrollmentApplication__c = oEnrollmentPlan.ID);
        }

    }

    public pageReference save(){
      System.Debug(logginglevel.error,'Saving');
        if(oEnrollComment.Reason_Codes__c == null){
            System.debug(logginglevel.error,'oEnrollComment.Reason_Codes__c ');
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,'You must choose a reason code before saving.'));
        }else{
            ID workFlowID = ECO_Utils_sObject.getRecordTypeId(EnrollmentPlan__c.sObjectType,'Workflow');
            System.Debug(logginglevel.error,'Workflowid ' + workFlowID);
            if(workFlowID != null){
              oEnrollmentPlan.RecordTypeID=workFlowID;
              System.savePoint sp = Database.setSavePoint();
              try{
                  system.debug(logginglevel.error,'Updating records');
                  update oEnrollmentPlan;
                  update oEnrollComment;
                  shouldRedirect = true;
                  return null;
              }catch(Exception e){
                  system.debug('Handling Exception:  '+e.getMessage() + ' ' + e.getStackTraceString());
                  system.debug(logginglevel.error, 'enrollmentPlan creation error: ' + e);
                  Database.rollBack(sp);
              }  
            }
              
        }

        return null;
    }
}