src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <formula>IF (ISBLANK( State_Province_Emerate__c ), &quot;None&quot;, 
IF (CONTAINS(&quot;New Brunswick:Newfoundland:Ontario:Prince Edward Island&quot;, State_Province_Emerate__r.Name ), &quot;Canada&quot;, 
IF (CONTAINS(&quot;Nova Scotia:Quebec&quot;, State_Province_Emerate__r.Name ), &quot;Canada&quot;, 
IF (CONTAINS(&quot;Alberta:British Columbia:Manitoba:Northwest Territories:Nunavut:Saskatchewan:Yukon Territory&quot;, State_Province_Emerate__r.Name ), &quot;Canada&quot;, 
IF (CONTAINS(&quot;Arkansas:Illinois:Indiana:Iowa:Kansas:Kentucky:Michigan:Minnesota:Missouri:Nebraska:North Dakota:Ohio:South Dakota:Delaware:Wisconsin&quot;,State_Province_Emerate__r.Name ), &quot;US North&quot;, 
IF (CONTAINS(&quot;Connecticut:Maine:Massachusetts:New Hampshire:Pennsylvania:New Jersey:New York:Rhode Island:Vermont:West Virginia&quot;,State_Province_Emerate__r.Name ),&quot;US North&quot;, 
IF (CONTAINS(&quot;Alabama:Florida:Georgia:Mississippi:North Carolina:District of Columbia:Maryland:Virginia:Puerto Rico:South Carolina:Tennessee:U.S. Virgin Islands&quot;,State_Province_Emerate__r.Name ), &quot;US South&quot;, 
IF (CONTAINS(&quot;Texas :Louisiana:Oklahoma&quot;,State_Province_Emerate__r.Name ), &quot;US South&quot;, 
IF (CONTAINS(&quot;Alaska:American Samoa:Arizona:California:Colorado:Hawaii:Idaho:Montana:Nevada:New Mexico:Oregon:Utah:Washington:Wyoming:Guam: Midway Atoll:Wake Island:Mariana Islands&quot;, State_Province_Emerate__r.Name ), &quot;US West&quot;, 
IF (CONTAINS(&quot;United Arab Emirates&quot;, CountryLookup__r.Name) , BillingCity , 
CountryLookup__r.Name ))))))))))</formula>
        <inlineHelpText>autofilled based on address state</inlineHelpText>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>OrganizationString__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization String</label>
        <referenceTo>OrganizationString__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <label>Person ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>If this person moves to another account: (a) change this field to &quot;No Longer with Client,&quot; (b) enter a note in the &quot;Need to Know&quot; field below, and (c) create a new Contact record under the new account.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No longer with client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EnrollmentParticipant__c.object
<CustomObject>
    <fields>
        <fullName>EmployeeName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>PSA Resource, AECOM Employee</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Salesforce_User__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollment Participants</relationshipLabel>
        <relationshipName>Enrollment_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentPlan__c</fullName>
        <label>Enrollment Plan</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Enrollment Participants</relationshipLabel>
        <relationshipName>EnrollmentParticipants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EnrollmentPlan__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW Enrollment Plans under review by Approvers</description>
    <fields>
        <fullName>CustomerName__c</fullName>
        <formula>IncentiveProject__r.CustomerName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTWAdmin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DTW Admin</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Enrollment_Applications4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending PM Action</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 1 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 2 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 3 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending DTW Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected for Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unenrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Corp Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - No Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt-Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IncentiveProject__c</fullName>
        <label>Project Name</label>
        <referenceTo>IncentiveProject__c</referenceTo>
        <relationshipLabel>Enrollment Applications</relationshipLabel>
        <relationshipName>Enrollment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>IncentiveProject__r.RegionDescription__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <label>Enrollment Application</label>
    <nameField>
        <label>Enrollment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IncentiveProject__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW eligible projects to be considered for enrollment in DTW Incentive Plans</description>
    <fields>
        <fullName>CustomerName__c</fullName>
        <label>Customer Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTWAdmin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DTW Administrator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Incentive_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enrollment Application</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Incentive Projects</relationshipLabel>
        <relationshipName>IncentiveProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <formula>IF( PaymentRequest__c &lt;&gt; &quot;&quot;,  Text(PaymentRequest__r.EnrollmentStatus__c),

IF(
    AND(
       (EnrollmentPlan__c=&quot;&quot;), 
        OR(
           TEXT(FPPOverallEligibility__c)=&quot;Yes&quot;,
           TEXT(TMPlanOverallEligibility__c)=&quot;Yes&quot;
           )
         ),
&quot;Pending DTW Action&quot;, 
IF(
   (EnrollmentPlan__c=&quot;&quot;), &quot;Not Eligible&quot;,
   TEXT(EnrollmentPlan__r.EnrollmentStatus__c)
   )
   )
)</formula>
        <label>Enrollment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationString__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization String</label>
        <referenceTo>OrganizationString__c</referenceTo>
        <relationshipLabel>Incentive Projects</relationshipLabel>
        <relationshipName>Incentive_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Incentive Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OrganizationString__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLineName__c</fullName>
        <label>Business Line Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GeographyName__c</fullName>
        <label>Geography Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OUID__c</fullName>
        <externalId>true</externalId>
        <label>OUID</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgID__c</fullName>
        <description>This is the ID of the Operating Unit</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the ID of the Operating Unit</inlineHelpText>
        <label>OrgID</label>
        <length>240</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <externalId>true</externalId>
        <label>Organization Name</label>
        <length>240</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Organization String</label>
    <nameField>
        <label>Organization String Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization String</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RoutingMember__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>&quot;...how we would want to be able to program DTW administrator assignments based on certain attributes of the organization string of a project&quot;</description>
    <fields>
        <fullName>DTWAdmin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Renamed Label from DTW Admin to User Name</description>
        <inlineHelpText>Renamed Label from DTW Admin to User Name</inlineHelpText>
        <label>DTW Admin</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RoutingMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Routing Member</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>RoutingMember</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RoutingMembers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <inlineHelpText>District name</inlineHelpText>
        <label>District</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <inlineHelpText>Region name</inlineHelpText>
        <label>Region</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the overall profile</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/INC_Utils_Testing.cls
public without sharing class INC_Utils_Testing {
	
	public static OrganizationString__c createTestOrg(){
		return ECO_Utils_Testing.createTestOrg();
	}

	public static IncentiveProject__c createIncentiveProject(){
		Integer randomNumber = Integer.valueOf(Math.random()*1000);
		IncentiveProject__c Test_IncentiveProject = new IncentiveProject__c();
		Test_IncentiveProject.Name = 'MP' + randomNumber +'-PM CENTRAL SERVICE';
		Test_IncentiveProject.CustomerName__c = 'REGIONAL MUNICIPALITY OF YORK';
		
		return Test_IncentiveProject;
	}

	public static User createTestUser(String sProfileName){
		return ECO_Utils_Testing.createTestUser(sProfileName);
	}
 
	public static RoutingMember__c createRoutingMember(User DTW_Admin){
		RoutingMember__c member = new RoutingMember__c();
		member.DTWAdmin__c = DTW_Admin.ID;
		return member;
	}

	public static Group createPublicGroup(String sName){
		Group grp = new Group(Name=sName,
							  Type='Regular',
							  DeveloperName=sName.Replace(' ','_'));
		return grp;
	}

	public static list<OrganizationString__c> createOrganizationString(){

		List<OrganizationString__c> lOrgStrings = new List<OrganizationString__c>();
		OrganizationString__c Org1 = INC_Utils_Testing.createTestOrg();
		OrganizationString__c Org2 = INC_Utils_Testing.createTestOrg();
		Org1.Name = Org1.OrganizationName__c;
		Org1.Region__c = 'Test Region';

		Org2.OrganizationName__c = 'Water Organization';
		Org2.Name = 'Water Organization';
		Org2.BusinessLineName__c = 'Water';
		Org2.Department__c = 'Water Department';
		Org2.District__c = 'Water District';
		Org2.Description__c = 'Water org string';
		Org2.GeographyName__c = 'Water Geo';
		Org2.Region__c = 'Water Region';
		Org2.OrgID__c = '227';
		Org2.OUID__c = '999';

		return new list<OrganizationString__c>{Org1,Org2};

	}
    
    /**
     * This method is responsible for creating test Enrollment Application record
     */
    public static EnrollmentPlan__c createEnrollmentApplication(IncentiveProject__c incentiveProject) {
        EnrollmentPlan__c eP = new EnrollmentPlan__c();
        eP.RecordTypeId = Schema.SObjectType.EnrollmentPlan__c.getRecordTypeInfosByName().get('Edit Application').getRecordTypeId();
        eP.IncentiveProject__c = incentiveProject.Id;
        eP.Name = 'Test Enrollment Plan';
        eP.CurrencyIsoCode = 'USD';
        eP.EnrollmentStatus__c = 'Pending PM Action';
        return eP;
    }
    
    public static Contact createEmployee() {
        User managerUser = INC_Utils_Testing.createTestUser('System Administrator');
        insert managerUser;
        
        User EmployeeUser = INC_Utils_Testing.createTestUser('System Administrator');
        EmployeeUser.ManagerId = managerUser.Id;
        insert EmployeeUser;
        
        Account account = new Account();
        account.Name = 'AECOM Test';
        insert account;
        
        Contact contact = new Contact();
        contact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('AECOM Employee').getRecordTypeId();
        contact.FirstName = 'FirstName';
        contact.LastName = 'LastName';
        contact.AccountId = account.Id;
        contact.Email = EmployeeUser.Email;
        contact.pse__Salesforce_User__c = EmployeeUser.Id;
        contact.Person_ID__c = '99999999';
        contact.Status__c = 'Active';            					
        
        return contact;        
    }
    
    public static EnrollmentParticipant__c createEnrollmentParticipant(EnrollmentPlan__c ePlan, Contact employee) {
        EnrollmentParticipant__c ePart = new EnrollmentParticipant__c();
        ePart.EnrollmentPlan__c = ePlan.Id;
        ePart.EmployeeName__c = employee.Id;
        ePart.ParticipantCategory__c = 'Technical Leader';
        ePart.TargetIncentivePoolAllocated__c = 25;
        
        return ePart;
    }
 

}