src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Describes relationship with AECOM - Choose all that might apply</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Client/Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subcontractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime/Teaming Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concessionaire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Used in reporting, to determine number of contacts associated with an account.</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrganizationString__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization String</label>
        <referenceTo>OrganizationString__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>If this person moves to another account: (a) change this field to &quot;No Longer with Client,&quot; (b) enter a note in the &quot;Need to Know&quot; field below, and (c) create a new Contact record under the new account.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No longer with client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the Contact to the User object.  This is for the representation of Employees.  Specifically, this is for the Shared Services Case Management.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Is_Resource__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resource</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Delegate__c.object
<CustomObject>
    <description>This object stores the delegate records.</description>
    <fields>
        <fullName>Active__c</fullName>
        <formula>AND ( 
     End_Date__c &gt; TODAY(),  
     ISPICKVAL (Approval_Status__c, &quot;APPROVED&quot;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Delegated to contact. Contact to whom a role has been delegated.</description>
        <label>Delegate</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Is_Resource__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Delegates</relationshipLabel>
        <relationshipName>Delegates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegator__c</fullName>
        <description>The contact who delegates to another contact</description>
        <label>Delegator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Delegates</relationshipLabel>
        <relationshipName>Delegates1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Key_Member_Role__c</fullName>
        <description>The role for which delegation is done</description>
        <label>Key Member Role</label>
        <picklist>
            <picklistValues>
                <fullName>Project Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Accountant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Net_Margin_age_of_NSR__c</fullName>
        <label>Project Approved Net Margin (% of NSR) &gt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date at which the delegation would begin</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>age_Change_in_Forecast_Net_Margin__c</fullName>
        <label>%age Change in Forecast Net Margin &gt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Delegate</label>
    <nameField>
        <displayFormat>DLGT-{0000000000}</displayFormat>
        <label>Delegate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegates</pluralLabel>
    <recordTypes>
        <fullName>Vacation</fullName>
        <active>true</active>
        <label>Vacation</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ECO_Delegate_Limits__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Project_Net_Margin_age_of_NSR__c</fullName>
        <label>Project Net Margin (%age of NSR) &gt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>age_Change_in_Forecast_Net_Margin__c</fullName>
        <label>%age Change in Forecast Net Margin &gt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Eco Delegate Limit Criteria</label>
</CustomObject>

src/objects/OrganizationString__c.object
<CustomObject>
    <fields>
        <fullName>PLManagerContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Approver 2 on stakeholders screen.</inlineHelpText>
        <label>Project Approver 2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>PSA Resource</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Salesforce_User__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization String</relationshipLabel>
        <relationshipName>Organization_String</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectAccountant2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Accountant 2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>PSA Resource</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Salesforce_User__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization String (Project Accountant 2)</relationshipLabel>
        <relationshipName>OrganizationStringProjectAccountant2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Organization String</label>
    <nameField>
        <label>Organization String Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization String</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipName>ProjectSites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Site</label>
    <nameField>
        <displayFormat>ProjectSite-{0000000000}</displayFormat>
        <label>Project Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProjectRole__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Key Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>ProjectRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Role</label>
        <referenceTo>ProjectRole__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersRole</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User must be active</description>
        <inlineHelpText>User must be active</inlineHelpText>
        <label>Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>User must be active</errorMessage>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>User must be active</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectTeamMemberUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000000}</displayFormat>
        <label>Project Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the overall profile</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ECO_DelegateManagerControllerTest.cls
/*
	Purpose: - Test Class ECO_DelegateManager Class

	Created By: Aaron Pettitt (NTT Data)

	Revision Log: 
		v1.0 - (AP 10/09/2015) -- created 
*/
@isTest
private class ECO_DelegateManagerControllerTest {
	Static User testUser;
	Static Contact testContact;
	Static Id recordTypeId;
	Static pse__Proj__c project;
	Static Site__c testSite;
	Static List<ProjectRole__c> projectRoles;
	Static List<ProjectTeamMember__c> projectMembers;

	@isTest static void testConstructor() {
		setupTestData();
		PageReference pg = Page.ECO_DelegateManager;
		pg.getParameters().put('retURL', '/' + testContact.Id);
		Test.setCurrentPage(pg);
		System.runAs(testUser){
			ECO_DelegateManagerController controller = new ECO_DelegateManagerController();
			system.assertEquals('Key Roles', controller.currentRecordType);
			system.assertEquals(4, controller.delegateRecordTypeMap.size());
			system.assertEquals(true, controller.canEdit);
			system.assertEquals(true, controller.canCreateAlternate);
		}
		pg = Page.ECO_DelegateManager;
		pg.getParameters().put('contactId', testContact.Id);
		pg.getParameters().put('retURL', '/' + testContact.Id);
		Test.setCurrentPage(pg);
		ECO_DelegateManagerController controller = new ECO_DelegateManagerController();
		system.assertEquals(false, controller.isError);
		system.assertEquals(true, controller.canEdit);
		system.assertEquals(false, controller.canCreateAlternate);
		system.assertEquals(UserInfo.getDefaultCurrency(), controller.currentCurrency);
		system.assertEquals(2, controller.yesNoOptions.size());

	}
	
	@isTest static void testChangeTabFields() {
		setupTestData();
		PageReference pg = Page.ECO_DelegateManager;
		pg.getParameters().put('contactId', testContact.Id);
		pg.getParameters().put('retURL', '/' + testContact.Id);
		Test.setCurrentPage(pg);
		System.runAs(testUser){
			ECO_DelegateManagerController controller = new ECO_DelegateManagerController();
			system.assertEquals('Key Roles', controller.currentRecordType);
			pg.getParameters().put('recordTypeId', controller.delegateRecordTypeMap.get('Vacation'));
			controller.changeTabFields();
			system.assertEquals('Vacation', controller.currentRecordType);
		}
	}

	@isTest static void testAddNewDelegate() {
		setupTestData();
		User testUser2 = ECO_Utils_Testing.createTestUser('Standard User');
		insert testUser2;

		Contact testContact2 = new Contact();
		testContact2.Email = testUser2.Email;
		testContact2.FirstName = testUser2.FirstName;
		testContact2.LastName =  testUser2.LastName;
		testContact2.Phone = '55555555555';
		testContact2.pse__Salesforce_User__c = testUser2.Id;
		testContact2.RecordTypeId = recordTypeId;
		testContact2.User__c = testUser2.Id;
		testContact2.OwnerId = testUser2.Id;
		testContact2.Status__c = 'Active';
		testContact2.pse__Is_Resource__c = true;
		insert testContact2;

		PageReference pg = Page.ECO_DelegateManager;
		pg.getParameters().put('contactId', testContact.Id);
		pg.getParameters().put('retURL', '/' + testContact.Id);
		Test.setCurrentPage(pg);

		System.runAs(testUser){
			ECO_DelegateManagerController controller = new ECO_DelegateManagerController();
			controller.delegate.CurrencyIsoCode = 'USD';
			controller.delegate.Delegate__c = testContact2.Id;
			controller.delegate.Key_Member_Role__c = 'Project Manager';
			controller.delegate.Start_Date__c = Date.today().addDays(5);
			controller.owningOrganizations[0].checked = true;
			controller.agreementAmountBypass = 'Yes';
			controller.projectRevenueBudgetBypass = 'Yes';
			controller.backlogValueBypass = 'Yes';
			controller.projectNetMarginValueBypass = 'Yes';
			controller.projectNetMarginNSRBypass = 'Yes';
			controller.percentageChangeInForecastBypass = 'Yes';
			controller.valueChangeInForecastNetMarginBypass = 'Yes';
			controller.projectRevenueBudgetBypassLT = 'Yes';
			controller.backlogValueBypassLT = 'Yes';
			controller.projectNetMarginValueBypassLT = 'Yes';
			controller.projectNetMarginNSRBypassLT = 'Yes';
			controller.percentageChangeInForecastBypassLT = 'Yes';
			controller.valueChangeInForecastNetMarginBypassLT = 'Yes';
			controller.c0Bypass = 'Yes';
			controller.c1Bypass = 'Yes';
			controller.c2Bypass = 'Yes';
			controller.c3Bypass = 'Yes';
			controller.c4Bypass = 'Yes';
			controller.addNewDelegate();
			system.assertEquals(0, controller.contact.Delegates1__r.size());
			controller = new ECO_DelegateManagerController();
			controller.agreementAmountBypass = 'No';
			controller.projectRevenueBudgetBypass = 'No';
			controller.backlogValueBypass = 'No';
			controller.projectNetMarginValueBypass = 'No';
			controller.projectNetMarginNSRBypass = 'No';
			controller.percentageChangeInForecastBypass = 'No';
			controller.valueChangeInForecastNetMarginBypass = 'No';
			controller.projectRevenueBudgetBypassLT = 'No';
			controller.backlogValueBypassLT = 'No';
			controller.projectNetMarginValueBypassLT = 'No';
			controller.projectNetMarginNSRBypassLT = 'No';
			controller.percentageChangeInForecastBypassLT = 'No';
			controller.valueChangeInForecastNetMarginBypassLT = 'No';
			controller.c0Bypass = 'No';
			controller.c1Bypass = 'No';
			controller.c2Bypass = 'No';
			controller.c3Bypass = 'No';
			controller.c4Bypass = 'No';
			controller.delegate.age_Change_in_Forecast_Net_Margin__c = 6;
			controller.delegate.Project_Net_Margin_age_of_NSR__c = 6;
			controller.delegate.Delegate__c = testContact2.Id;
			controller.delegate.Key_Member_Role__c = 'Project Manager';
			controller.delegate.Start_Date__c = Date.today().addDays(20);
			ECO_Delegate_Limits__c delegateLimitSettings = ECO_Delegate_Limits__c.getOrgDefaults();
			controller.owningOrganizations[0].checked = true;
			controller.addNewDelegate();
			//system.assertEquals(2, controller.contact.Delegates1__r.size());
			testContact2.Status__c = 'Inactive';
			update testContact2;
			controller.delegate.Delegate__c = testContact2.Id;
			controller.delegate.Key_Member_Role__c = 'Project Approver';
			controller.delegate.Start_Date__c = Date.today().addDays(25);
			controller.addNewDelegate();
		}
	}


	static void setupTestData(){

		Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
		recordTypeId = ECO_Utils_sObject.getRecordTypeId(Contact.sObjectType, 'PSA Resource');

		Account testAccount = new Account();
		testAccount.Name = 'test account';
		insert testAccount;

		testUser = ECO_Utils_Testing.createTestUser('Standard User');
		testUser.CurrencyISOCode = 'USD';
		insert testUser;

		testContact = new Contact();
		testContact.Email = testUser.Email;
		testContact.FirstName = testUser.FirstName;
		testContact.LastName =  testUser.LastName;
		testContact.Phone = '55555555555';
		testContact.pse__Salesforce_User__c = testUser.Id;
		testContact.RecordTypeId = recordTypeId;
		testContact.User__c = testUser.Id;
		testContact.OwnerId = testUser.Id;
		insert testContact;

		projectRoles = new List<ProjectRole__c>();
		projectRoles.add(new ProjectRole__c(Name = 'Project Manager', Type__c = 'Key Member', Active__c = true));
		projectRoles.add(new ProjectRole__c(Name = 'Project Approver 2', Type__c = 'Key Member', Active__c = true));
		projectRoles.add(new ProjectRole__c(Name = 'Project Approver', Type__c = 'Key Member', Active__c = true));
		projectRoles.add(new ProjectRole__c(Name = 'Resilience Director', Type__c = 'Key Member', Active__c = true));
		projectRoles.add(new ProjectRole__c(Name = 'Project Worker', Active__c = true));
		insert projectRoles;

		OrganizationString__c organizationString = new OrganizationString__c(Name = 'Test Organization', ProjectAccountant2__c = testContact.Id, PLManagerContact__c = testContact.Id);
		insert organizationString;

		project = new pse__Proj__c(CarryingOutOrganization__c = organizationString.Id, pse__Account__c = testAccount.Id, pse__Start_Date__c = Date.today().addDays(30), pse__End_Date__c = Date.today().addDays(60));
	    insert project;

	    //project sites
		testSite = new Site__c();
		testSite.Account__c = testAccount.Id;
		testSite.CurrencyIsoCode = 'USD';
		testSite.City__c = 'Winnipeg';		
		testSite.VendorSiteID__c = '654321';
		testSite.CustomerAccountSiteID__c = '666666';

		insert testSite;

		Project_Site__c testProjectSite = new Project_Site__c();
		
		testProjectSite.BillingContactID__c	= '1234';
		//testProjectSite.OracleProjectSiteId__c = '1111';
		testProjectSite.Project__c = project.Id;
		testProjectSite.Site__c = testSite.Id;
		testProjectSite.Contribution__c = 100;

		insert testProjectSite;
		
		projectMembers = new List<ProjectTeamMember__c>();
		projectMembers.add(new ProjectTeamMember__c(Project__c = project.Id, CurrencyIsoCode = 'USD', ProjectRole__c = projectRoles[0].Id, Contact__c = testContact.Id, StartDate__c = Date.today(), EndDate__c = Date.today().addDays(1)));
		projectMembers.add(new ProjectTeamMember__c(Project__c = project.Id, CurrencyIsoCode = 'USD', ProjectRole__c = projectRoles[1].Id, Contact__c = testContact.Id, StartDate__c = Date.today().addDays(2), EndDate__c = Date.today().addDays(3)));
		projectMembers.add(new ProjectTeamMember__c(Project__c = project.Id, CurrencyIsoCode = 'USD', ProjectRole__c = projectRoles[3].Id, Contact__c = testContact.Id, StartDate__c = Date.today().addDays(4), EndDate__c = Date.today().addDays(5)));
		projectMembers.add(new ProjectTeamMember__c(Project__c = project.Id, CurrencyIsoCode = 'USD', ProjectRole__c = projectRoles[1].Id, Contact__c = testContact.Id, StartDate__c = Date.today().addDays(5), EndDate__c = Date.today().addDays(6)));
		insert projectMembers;

		
		ECO_Delegate_Limits__c delegateLimitSettings = ECO_Delegate_Limits__c.getOrgDefaults();
		delegateLimitSettings.age_Change_in_Forecast_Net_Margin__c = 5;
		delegateLimitSettings.Agreement_Amount__c = 1000;
		delegateLimitSettings.Backlog_Value__c = 1000;
		delegateLimitSettings.Project_Net_Margin_age_of_NSR__c = 5;
		delegateLimitSettings.Project_Net_Margin_Value__c	 = 1000;
		delegateLimitSettings.Project_Revenue_Budget__c = 1000;
		delegateLimitSettings.Value_Change_In_Forecast_Net_Margin__c = 1000;
		upsert delegateLimitSettings;

	}
	
}