src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Describes relationship with AECOM - Choose all that might apply</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Client/Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subcontractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime/Teaming Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concessionaire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrollment_Comments__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will be filled in for the person who created the approver comments.</description>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Enrollment_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EnrollmentApplication__c</fullName>
        <label>Enrollment Application</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Enrollment Comments</relationshipLabel>
        <relationshipName>Enrollment_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_Codes__c</fullName>
        <description>When rejection is required, use the dropdown list to select from the most commonly noted reasons. Comments must be logged with each rejection for the reference of the original submitter, prior approvers, and DTW Admin. If corrections to the application</description>
        <inlineHelpText>When rejection is required, use the dropdown list to select from the most commonly noted reasons. Comments must be logged with each rejection for the reference of the original submitter, prior approvers, and DTW Admin. If corrections to the application</inlineHelpText>
        <label>Reason Codes</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Poor Project Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project on Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project in Litigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Nearing Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More Suitable for T&amp;M Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More Suitable for FP Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project is Intercompany – Client is AECOM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected For Corrections (explain in comments)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Comment Type</label>
        <picklist>
            <controllingField>IsRejection__c</controllingField>
            <picklistValues>
                <fullName>General</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Exception</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejection for Corrections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interim Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Enrollment Comment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>EC-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EnrollmentPlan__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW Enrollment Plans under review by Approvers</description>
    <fields>
        <fullName>ApprovalRecentlyProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Recently Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractType__c</fullName>
        <description>Displays the contract type as per AECOM Insight.  For Oracle projects, this will reflect the Oracle contract type.  DTW data is updated weekly by Insight.</description>
        <formula>IncentiveProject__r.ContractType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the contract type as per AECOM Insight.  For Oracle projects, this will reflect the Oracle contract type.  DTW data is updated weekly by Insight.</inlineHelpText>
        <label>Contract Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending PM Action</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 1 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 2 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 3 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending DTW Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected for Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unenrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Corp Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - No Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt-Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IncentivePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incentive Plan</label>
        <referenceTo>IncentivePlanTemplate__c</referenceTo>
        <relationshipName>Enrollment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IncrementalGMvsBaseline__c</fullName>
        <formula>MAX(IF(
	ISPICKVAL(
				ApplicationType__c,&apos;PAY&apos;
			 )
	,IF(
		ISPICKVAL(
					IncentivePlan__r.ContractSubType__c,&apos;Gross Margin&apos;
				  )
		,AcutalGMofNSRITD__c
		,ActualNMofNSRITD__c
		)
	,IF(
		ISPICKVAL(
					IncentivePlan__r.ContractSubType__c,&apos;Gross Margin&apos;
				  )
		,ForecastGrossMarginofNSR__c
		,ForecastNetMarginofNSR__c
		)
) - BaselineGMofNSR__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Gross or Net Margin % vs Baseline</inlineHelpText>
        <label>Incremental Margin % vs Baseline</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Enrollment Application</label>
    <nameField>
        <label>Enrollment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Applications</pluralLabel>
    <recordTypes>
        <fullName>Enrolled</fullName>
        <active>true</active>
        <label>Enrolled</label>
    </recordTypes>
    <recordTypes>
        <fullName>Exception</fullName>
        <active>true</active>
        <label>Exception</label>
    </recordTypes>
    <recordTypes>
        <fullName>Workflow</fullName>
        <active>true</active>
        <label>Workflow</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IncentivePlanTemplate__c.object
<CustomObject>
    <fields>
        <fullName>ContractType__c</fullName>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time &amp; Material</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Incentive Plan Template</label>
    <nameField>
        <label>Incentive Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Plan Template</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/INC_EnrollmentApp_Controller.cls
public with sharing class INC_EnrollmentApp_Controller {

	private EnrollmentPlan__c oEnrollmentApp;
    public string enrollcharId {get;set;}
    private final ApexPages.StandardController stdController;
    public Enrollment_Comments__c oEnrollComment{get;set;}
    public String sMessage{get;set;}
    public String sRectypeName{get;set;}
    public boolean isRejectedRecType {get;set;}
    public boolean bTandM {get;set;}
    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public INC_EnrollmentApp_Controller(ApexPages.StandardController stdController) {
        
        this.stdController = stdController;
        if(!Test.isRunningTest()){
          stdController.addFields(new list<String>{'IncentivePlan__r.ContractType__c'});
        }
        this.oEnrollmentApp = (EnrollmentPlan__c)stdController.getRecord();
        enrollcharId = String.ValueOF(oEnrollmentApp.id).mid(0,15);
        ID rejectedRecTypeID = Schema.SObjectType.EnrollmentPlan__c.getRecordTypeInfosByName().get('Rejected').getRecordTypeId();
        if(rejectedRecTypeID == oEnrollmentApp.RecordTypeID){
            isRejectedRecType = true;
            getLatestRejectionComment();
        }else{
            isRejectedRecType = false;
        }
        if(oEnrollmentApp.IncrementalGMvsBaseline__c > 4){
          ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning,'Incremental GM% vs Baseline is greater than 4%'));
        }
        bTandM = oEnrollmentApp.IncentivePlan__r.ContractType__c == 'Time & Material'?true:false;
        System.Debug(logginglevel.error,'isRejectedRecType ' + isRejectedRecType);
    }

    public String getRecordName() {
        return 'Hello ';
    }
    public pageReference save(){
        System.debug(logginglevel.error,'Save in custom controller');
        stdController.save();
        pageReference pf = new pageReference('/apex/INC_EnrollmentApp?id=' + oEnrollmentApp.Id);
        return pf;
    }

    public PageReference submit(){
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();  
        req1.setComments('Submitted for Approval');
        req1.setObjectId(oEnrollmentApp.ID);
        req1.setSubmitterID(UserInfo.getUserId());
        try{
            Approval.ProcessResult result = Approval.process(req1); 
            }catch(Exception e){
                System.Debug(logginglevel.error,'Exception: ' + e.getMessage());
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'All criteria has not be met.'));
            }
        pageReference pf = new pageReference('/apex/INC_EnrollmentApp?id=' + oEnrollmentApp.Id);
        return null;   

    } 
    public pageReference saveAndReturnToBudget(){
        stdController.save();
        pageReference pr = ApexPages.currentPage();
        pr.setAnchor('budgetsection');
        pr.setredirect(true);
        return pr;
    }
    public pageReference chooseplan(){
        pageReference pr = new pageReference('/apex/INC_Chose?id=' + oEnrollmentApp.id);
        pr.setredirect(true);
        return pr;
    }

    public pageReference showAppMetrics(){
        pageReference pr = new pageReference('/apex/INC_ShowEnrollmentMetrics?id=' + oEnrollmentApp.id);
        pr.setredirect(true);
        return pr;
    }

    public pageReference reassignApprovers(){
        pageReference pr = new pageReference('/apex/INC_AssignApprovers?id=' + oEnrollmentApp.id);
        pr.setredirect(true);
        return pr;
    }
   
    public pageReference createChangeRequest(){
        pageReference pr = null;
        if(oEnrollmentApp.EnrollmentStatus__c == 'Enrolled'){
            pr = new pageReference('/apex/INC_EnrollmentApp?id='+INC_Service_EnrollmentPlan.cloneEnrollment(oEnrollmentApp.id,INC_Service_EnrollmentPlan.RequestType.CHANGE));
            pr.setredirect(true);
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Current application needs to be Enrolled to create a change request.'));
        }

        return pr;
    }

    public pageReference createPaymentRequest(){
      pageReference pr = null;
      if(oEnrollmentApp.EnrollmentStatus__c == 'Enrolled'){
        pr = new pageReference('/apex/INC_EnrollmentApp?id='+INC_Service_EnrollmentPlan.cloneEnrollment(oEnrollmentApp.id,INC_Service_EnrollmentPlan.RequestType.PAYMENT));
            pr.setredirect(true);
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Current application needs to be Enrolled to create a change request.'));
        }

        return pr;
    }

    public void updateCommentsfromApprovals(){
        oEnrollmentApp = INC_Service_EnrollmentPlan.getEnrollmentPlan(new set<id>{oEnrollmentApp.ID})[0];
        if(oEnrollmentApp.ApprovalRecentlyProcessed__c){
            INC_Service_EnrollmentPlan.createEnrollmentCommentsFromApproval(new set<id>{oEnrollmentApp.ID});
        }
       
    }
//code for rejection comments section
    private void getLatestRejectionComment(){
        list<Enrollment_Comments__c> lComments = [Select ID
                                                          , Comments__c
                                                          , Type__c
                                                          , Reason_Codes__c
                                                          , Approver__c
                                                          , Approver__r.Name
                                                 From Enrollment_Comments__c
                                                 Where EnrollmentApplication__c =: oEnrollmentApp.ID
                                                 and (Type__c = 'Rejection' or Type__c ='Rejection for Corrections')
                                                 and (Reason_Codes__c = null)
                                                 Order by CreatedDate];
        //find the latest one, hopefully the query should only return one.  But I have to account for bad data
        System.Debug(logginglevel.error,'lcomments: ' + lComments);
        if(lComments != Null && lComments.size() > 0){
                oEnrollComment = lComments[0];
                sMessage = lComments[0].Approver__r.Name + ' rejected the application.  A rejection code must be selected before any changes to the';
                sMessage += ' application are possible.';
        }else{
          oEnrollComment = new Enrollment_Comments__c(EnrollmentApplication__c = oEnrollmentApp.ID);
        }

    }

    public pageReference saveComments(){
      System.Debug(logginglevel.error,'Saving');
        if(oEnrollComment.Reason_Codes__c == null){
            System.debug(logginglevel.error,'oEnrollComment.Reason_Codes__c ');
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,'You must choose a reason code before saving.'));
        }else{
            ID workFlowID = ECO_Utils_sObject.getRecordTypeId(EnrollmentPlan__c.sObjectType,'Workflow');
            System.Debug(logginglevel.error,'Workflowid ' + workFlowID);
            oEnrollmentApp.ApprovalRecentlyProcessed__c = false;
            
            if(workFlowID != null){
              oEnrollmentApp.RecordTypeID=workFlowID;
              System.savePoint sp = Database.setSavePoint();
              try{
                  system.debug(logginglevel.error,'Updating records');
                  update oEnrollmentApp;
                  return null;
              }catch(Exception e){
                  system.debug('Handling Exception:  '+e.getMessage() + ' ' + e.getStackTraceString());
                  system.debug(logginglevel.error, 'enrollmentPlan update error: ' + e);
                  Database.rollBack(sp);
              }
              try{
                  system.debug(logginglevel.error,'Updating records');
                  upsert oEnrollComment;
                  return null;
              }catch(Exception e){
                  system.debug('Handling Exception:  '+e.getMessage() + ' ' + e.getStackTraceString());
                  system.debug(logginglevel.error, 'comment creation error: ' + e);
                  Database.rollBack(sp);
              }  
     
            }
              
        }

        //pageReference pr = new PageReference('/apex/INC_EnrollmentApp?id='+oEnrollmentApp.id);
        //pr.setredirect(true);
        return null;
    }




















}