src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>OracleCustomerNumber__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Customer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Billing__c.object
<CustomObject>
    <description>Object used for tracking billing information from Oracle</description>
    <fields>
        <fullName>CustomerName__c</fullName>
        <label>CustomerName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerNumber__c</fullName>
        <label>Customer Number</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Billing</label>
    <nameField>
        <label>Billing Invoice #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_Billingtriggers.cls
public class ECO_Billingtriggers{


public static void updateCustomername(list<billing__c> billinglist){
    list<string> Accountnumlist = new list<string>();
    map<string,string> Accountmap = new map<string,string>();
    for(Billing__c b:billinglist){
        if(b.customernumber__c !=null)
        {
            Accountnumlist.add(b.customernumber__c);
        }
    }
    if(Accountnumlist.size()>0)
    {
        for(Account acc:[select id,name,OracleCustomerNumber__c from account where  OracleCustomerNumber__c IN:Accountnumlist]){
            Accountmap.put(acc.OracleCustomerNumber__c,acc.name);
        }
        for(Billing__c b:billinglist){
            if(accountmap.containskey(b.customernumber__c))
            {
                b.customername__c = accountmap.get(b.customernumber__c);
            }
        }
    
    }
}



}