src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <formula>IF (ISBLANK( State_Province_Emerate__c ), &quot;None&quot;, 
IF (CONTAINS(&quot;New Brunswick:Newfoundland:Ontario:Prince Edward Island&quot;, State_Province_Emerate__r.Name ), &quot;Canada&quot;, 
IF (CONTAINS(&quot;Nova Scotia:Quebec&quot;, State_Province_Emerate__r.Name ), &quot;Canada&quot;, 
IF (CONTAINS(&quot;Alberta:British Columbia:Manitoba:Northwest Territories:Nunavut:Saskatchewan:Yukon Territory&quot;, State_Province_Emerate__r.Name ), &quot;Canada&quot;, 
IF (CONTAINS(&quot;Arkansas:Illinois:Indiana:Iowa:Kansas:Kentucky:Michigan:Minnesota:Missouri:Nebraska:North Dakota:Ohio:South Dakota:Delaware:Wisconsin&quot;,State_Province_Emerate__r.Name ), &quot;US North&quot;, 
IF (CONTAINS(&quot;Connecticut:Maine:Massachusetts:New Hampshire:Pennsylvania:New Jersey:New York:Rhode Island:Vermont:West Virginia&quot;,State_Province_Emerate__r.Name ),&quot;US North&quot;, 
IF (CONTAINS(&quot;Alabama:Florida:Georgia:Mississippi:North Carolina:District of Columbia:Maryland:Virginia:Puerto Rico:South Carolina:Tennessee:U.S. Virgin Islands&quot;,State_Province_Emerate__r.Name ), &quot;US South&quot;, 
IF (CONTAINS(&quot;Texas :Louisiana:Oklahoma&quot;,State_Province_Emerate__r.Name ), &quot;US South&quot;, 
IF (CONTAINS(&quot;Alaska:American Samoa:Arizona:California:Colorado:Hawaii:Idaho:Montana:Nevada:New Mexico:Oregon:Utah:Washington:Wyoming:Guam: Midway Atoll:Wake Island:Mariana Islands&quot;, State_Province_Emerate__r.Name ), &quot;US West&quot;, 
IF (CONTAINS(&quot;United Arab Emirates&quot;, CountryLookup__r.Name) , BillingCity , 
CountryLookup__r.Name ))))))))))</formula>
        <inlineHelpText>autofilled based on address state</inlineHelpText>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BudgetAssignment__c.object
<CustomObject>
    <fields>
        <fullName>BudgetResource__c</fullName>
        <label>Budget Resource</label>
        <referenceTo>BudgetResource__c</referenceTo>
        <relationshipLabel>Budget Assignments</relationshipLabel>
        <relationshipName>BudgetAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BudgetTask__c</fullName>
        <label>Budget Task</label>
        <referenceTo>BudgetTask__c</referenceTo>
        <relationshipLabel>Budget Assignments</relationshipLabel>
        <relationshipName>BudgetAssignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OUID__c</fullName>
        <formula>ProjectTask__r.CarryingOutOrganization__r.OUID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OUID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverrideBillRate__c</fullName>
        <label>Override Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideRawCost__c</fullName>
        <label>Override Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(BudgetTask__r.BudgetHeader__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaskName__c</fullName>
        <label>Task Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Budget Assignment</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Budget Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>BudgetHeaders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclude</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work at Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetResource__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipLabel>Budget Resources</relationshipLabel>
        <relationshipName>BudgetResources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OverrideBillRate__c</fullName>
        <label>Override Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideRawCost__c</fullName>
        <label>Override Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ResourceName__c</fullName>
        <label>Resource Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Budget Resource</label>
    <nameField>
        <displayFormat>BR-{000000000}</displayFormat>
        <label>Budget Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetTask__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>BudgetTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TaskName__c</fullName>
        <label>Task Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Budget Task</label>
    <nameField>
        <displayFormat>BT-{000000000}</displayFormat>
        <label>Budget Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrganizationString__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLineName__c</fullName>
        <label>Business Line Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GeographyName__c</fullName>
        <label>Geography Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InactiveDate__c</fullName>
        <label>Inactive Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OUID__c</fullName>
        <externalId>true</externalId>
        <label>OUID</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgID__c</fullName>
        <description>This is the ID of the Operating Unit</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the ID of the Operating Unit</inlineHelpText>
        <label>OrgID</label>
        <length>240</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <externalId>true</externalId>
        <label>Organization Name</label>
        <length>240</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Organization String</label>
    <nameField>
        <label>Organization String Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization String</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>AECOM_Primary_Department__c</referenceTo>
        <relationshipLabel>Project Profiles</relationshipLabel>
        <relationshipName>Project_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectOrganization__c.object
<CustomObject>
    <fields>
        <fullName>OrganizationString__c</fullName>
        <label>Organization String</label>
        <referenceTo>OrganizationString__c</referenceTo>
        <relationshipLabel>Project Organizations</relationshipLabel>
        <relationshipName>ProjectOrganizations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>AECOM Organizations</relationshipLabel>
        <relationshipName>ProjectOrganizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Organization</label>
    <nameField>
        <displayFormat>ProjOrg-{000000000}</displayFormat>
        <label>Project Organization Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Organizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProjectSnapshot__c.object
<CustomObject>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Snapshots</relationshipLabel>
        <relationshipName>ProjectSnapshots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Snapshot</label>
    <nameField>
        <label>Project Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Revenue__c.object
<CustomObject>
    <description>Object used to track revenue information from Oracle</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GLDate__c</fullName>
        <label>GL Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Revenue</relationshipLabel>
        <relationshipName>Revenue</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TaskName__c</fullName>
        <formula>TaskNumber__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Task Name</label>
        <type>Text</type>
    </fields>
    <label>Revenue</label>
    <nameField>
        <label>Revenue Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_Service_ProjectSnapshotTest.cls
@isTest
private class ECO_Service_ProjectSnapshotTest {

   static testMethod void testSingleProject() {
       
        Account testAccount = new Account();
		testAccount.Name = 'test account';
		insert testAccount;
		
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.pse__Account__c = testAccount.Id;
		testProject.EscalationApplies__c = true;
		testProject.EscalationDate__c = Date.today();
		testProject.EscalationDescription__c = 'Test Desc';
		insert testProject;
		
		BudgetHeader__c testHeader = new BudgetHeader__c();
		testHeader.Project__c = testProject.Id;
		testHeader.Status__c = 'Approved';
		insert testHeader;
		
		BudgetResource__c testResource = new BudgetResource__c();
		testResource.BudgetHeader__c = testHeader.Id;
		testResource.ResourceName__c = 'test resource';
		insert testResource;
		
		BudgetTask__c testTask = new BudgetTask__c();
		testTask.BudgetHeader__c = testHeader.Id;
		testTask.TaskName__c = 'test task';
		insert testTask;
		
		BudgetAssignment__c testAssignment = new BudgetAssignment__c();
		testAssignment.BudgetTask__c = testTask.Id;
		testAssignment.BudgetResource__c = testResource.Id;
		testAssignment.Quantity__c = 1;
		testAssignment.OverrideRawCost__c = 1;
		testAssignment.OverrideBillRate__c = 1;
		insert testAssignment;
		
		list<Revenue__c> revenues = new list<Revenue__c>();
		Revenue__c revenue = new Revenue__c();
		revenue.ProjectNumber__c = testProject.Id;
		revenue.Amount__c = 2000;
		revenue.GLDate__c = Date.today();
		revenues.add(revenue);
		
		Revenue__c revenue2 = new Revenue__c();
		revenue2.ProjectNumber__c = testProject.Id;
		revenue2.Amount__c = 2000;
		revenue2.GLDate__c = Date.today().addDays(-91);
		revenues.add(revenue2);
		
		insert revenues;

		List<OrganizationString__c> lOrgStrings = new List<OrganizationString__c>();
		OrganizationString__c Org1 = INC_Utils_Testing.createTestOrg();
		lOrgStrings.add(Org1);
		OrganizationString__c Org2 = INC_Utils_Testing.createTestOrg();
		
		
		Org2.OrganizationName__c = 'Water Organization';
		Org2.Name = 'Water Organization';
		Org2.BusinessLineName__c = 'Water';
		Org2.Department__c = 'Water Department';
		Org2.District__c = 'Water District';
		Org2.Description__c = 'Water org string';
		Org2.GeographyName__c = 'Water Geo';
		Org2.Region__c = 'Water Region';
		Org2.OrgID__c = '227';
		Org2.OUID__c = '999';
		org2.InactiveDate__c = null;

		lOrgStrings.add(Org2);
		insert lOrgStrings;		
		
		list<ProjectOrganization__c> projectOrgs = new list<ProjectOrganization__c>();
		ProjectOrganization__c projectOrg1 = new ProjectOrganization__c();
		projectOrg1.Project__c = testProject.Id;
		projectOrg1.OrganizationString__c = lOrgStrings[0].Id;
		projectOrg1.Type__c = 'Primary';
		projectOrg1.ContributionPercent__c = 75;
		projectOrgs.add(projectOrg1);
		
		ProjectOrganization__c projectOrg2 = new ProjectOrganization__c();
		projectOrg2.Project__c = testProject.Id;
		projectOrg2.OrganizationString__c = lOrgStrings[1].Id;
		projectOrg2.Type__c = 'Secondary';
		projectOrg2.ContributionPercent__c = 25;
		projectOrgs.add(projectOrg2);
		insert projectOrgs;
		
		Id changeOrderRecordTypeId = ECO_Utils_Meta.getRecordTypeId(BudgetHeader__c.sObjectType, 'Change Order');
		BudgetHeader__c bheader = new BudgetHeader__c();
		bheader.BudgetName__c = 'Change Order 1';
		bheader.ChangeManagerApprovedForSynch__c = true;
		bheader.Project__c = testProject.Id;
		bheader.RecordTypeId = changeOrderRecordTypeId;
		insert bheader;

		BudgetHeader__c bheader2 = new BudgetHeader__c();
		bheader2.BudgetName__c = 'Change Order 2';
		bheader2.ChangeManagerApprovedForSynch__c = true;
		bheader2.Project__c = testProject.Id;
		bheader2.RecordTypeId = changeOrderRecordTypeId;
		insert bheader2;		
				
		ECO_Service_ProjectSnapshots projectService = new ECO_Service_ProjectSnapshots(testProject.Id);		
		ProjectSnapshot__c projectSnapshot = projectService.getProjectSnapshot();
       	System.AssertEquals(1, projectSnapshot.GrossRevenueBudget__c);
       	System.AssertEquals(4000, projectSnapshot.GrossRevenueYearToDate__c);
       	System.AssertEquals(2000, projectSnapshot.GrossRevenueMonthToDate__c);
       	System.AssertEquals(4000, projectSnapshot.GrossRevenueITD__c);
       	
       	System.AssertEquals('Change Order 1;;0.00;;0.00::Change Order 2;;0.00;;0.00', projectSnapshot.ChangeOrdersPending__c);
    }
    
    static testMethod void testMultipleProjects() {
       
        Account testAccount = new Account();
		testAccount.Name = 'test account';
		insert testAccount;
		
		list<pse__Proj__c> projects = new list<pse__Proj__c>();
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.pse__Account__c = testAccount.Id;
		testProject.EscalationApplies__c = true;
		testProject.EscalationDate__c = Date.today();
		testProject.EscalationDescription__c = 'Test Desc';
		projects.add(testProject);
		
		pse__Proj__c testProject2 = new pse__Proj__c();
		testProject2.pse__Account__c = testAccount.Id;
		testProject2.EscalationApplies__c = true;
		testProject2.EscalationDate__c = Date.today();
		testProject2.EscalationDescription__c = 'Test Desc 2';
		projects.add(testProject2);
		insert projects;		
		
		list<BudgetHeader__c> headers = new list<BudgetHeader__c>();	
		BudgetHeader__c testHeader = new BudgetHeader__c();
		testHeader.Project__c = testProject.Id;
		testHeader.Status__c = 'Approved';
		headers.add(testHeader);
		
		BudgetHeader__c testHeader2 = new BudgetHeader__c();
		testHeader2.Project__c = testProject2.Id;
		testHeader2.Status__c = 'Approved';
		headers.add(testHeader2);
		insert headers;		
			
		list<BudgetResource__c> resources = new list<BudgetResource__c>();
		BudgetResource__c testResource = new BudgetResource__c();
		testResource.BudgetHeader__c = testHeader.Id;
		testResource.ResourceName__c = 'test resource';
		resources.add(testResource);
		
		BudgetResource__c testResource2 = new BudgetResource__c();
		testResource2.BudgetHeader__c = testHeader.Id;
		testResource2.ResourceName__c = 'test resource';
		resources.add(testResource2);
		insert resources;		
		
		list<BudgetTask__c> tasks = new list<BudgetTask__c>();
		BudgetTask__c testTask = new BudgetTask__c();
		testTask.BudgetHeader__c = testHeader.Id;
		testTask.TaskName__c = 'test task';
		tasks.add(testTask);
		
		BudgetTask__c testTask2 = new BudgetTask__c();
		testTask2.BudgetHeader__c = testHeader2.Id;
		testTask2.TaskName__c = 'test task 2';
		tasks.add(testTask2);
		insert tasks;		
		
		BudgetAssignment__c testAssignment = new BudgetAssignment__c();
		testAssignment.BudgetTask__c = testTask.Id;
		testAssignment.BudgetResource__c = testResource.Id;
		testAssignment.Quantity__c = 1;
		testAssignment.OverrideRawCost__c = 1;
		testAssignment.OverrideBillRate__c = 1;
		insert testAssignment;
		
		BudgetAssignment__c testAssignment2 = new BudgetAssignment__c();
		testAssignment2.BudgetTask__c = testTask2.Id;
		testAssignment2.BudgetResource__c = testResource2.Id;
		testAssignment2.Quantity__c = 1;
		testAssignment2.OverrideRawCost__c = 1;
		testAssignment2.OverrideBillRate__c = 1;
		insert testAssignment2;		
		
		list<Revenue__c> revenues = new list<Revenue__c>();
		Revenue__c revenue = new Revenue__c();
		revenue.ProjectNumber__c = testProject.Id;
		revenue.Amount__c = 2000;
		revenue.GLDate__c = Date.today();
		revenues.add(revenue);
		
		Revenue__c revenue2 = new Revenue__c();
		revenue2.ProjectNumber__c = testProject.Id;
		revenue2.Amount__c = 2000;
		revenue2.GLDate__c = Date.today().addDays(-91);
		revenues.add(revenue2);

		Revenue__c revenue3 = new Revenue__c();
		revenue3.ProjectNumber__c = testProject2.Id;
		revenue3.Amount__c = 2000;
		revenue3.GLDate__c = Date.today();
		revenues.add(revenue3);
		
		Revenue__c revenue4 = new Revenue__c();
		revenue4.ProjectNumber__c = testProject2.Id;
		revenue4.Amount__c = 2000;
		revenue4.GLDate__c = Date.today().addDays(-91);
		revenues.add(revenue4);		
		insert revenues;

		List<OrganizationString__c> lOrgStrings = new List<OrganizationString__c>();
		OrganizationString__c Org1 = INC_Utils_Testing.createTestOrg();
		lOrgStrings.add(Org1);
		OrganizationString__c Org2 = INC_Utils_Testing.createTestOrg();
		
		
		Org2.OrganizationName__c = 'Water Organization';
		Org2.Name = 'Water Organization';
		Org2.BusinessLineName__c = 'Water';
		Org2.Department__c = 'Water Department';
		Org2.District__c = 'Water District';
		Org2.Description__c = 'Water org string';
		Org2.GeographyName__c = 'Water Geo';
		Org2.Region__c = 'Water Region';
		Org2.OrgID__c = '227';
		Org2.OUID__c = '999';
		org2.InactiveDate__c = null;

		lOrgStrings.add(Org2);
		insert lOrgStrings;		
		
		list<ProjectOrganization__c> projectOrgs = new list<ProjectOrganization__c>();
		ProjectOrganization__c projectOrg1 = new ProjectOrganization__c();
		projectOrg1.Project__c = testProject.Id;
		projectOrg1.OrganizationString__c = lOrgStrings[0].Id;
		projectOrg1.Type__c = 'Primary';
		projectOrg1.ContributionPercent__c = 75;
		projectOrgs.add(projectOrg1);
		
		ProjectOrganization__c projectOrg2 = new ProjectOrganization__c();
		projectOrg2.Project__c = testProject.Id;
		projectOrg2.OrganizationString__c = lOrgStrings[1].Id;
		projectOrg2.Type__c = 'Secondary';
		projectOrg2.ContributionPercent__c = 25;
		projectOrgs.add(projectOrg2);
		
		ProjectOrganization__c projectOrg3 = new ProjectOrganization__c();
		projectOrg3.Project__c = testProject2.Id;
		projectOrg3.OrganizationString__c = lOrgStrings[1].Id;
		projectOrg3.Type__c = 'Primary';
		projectOrg3.ContributionPercent__c = 100;
		projectOrgs.add(projectOrg3);
				
		insert projectOrgs;
		
		list<BudgetHeader__c> bheaders = new list<BudgetHeader__c>();
		Id changeOrderRecordTypeId = ECO_Utils_Meta.getRecordTypeId(BudgetHeader__c.sObjectType, 'Change Order');
		BudgetHeader__c bheader = new BudgetHeader__c();
		bheader.BudgetName__c = 'Change Order 1';
		bheader.ChangeManagerApprovedForSynch__c = true;
		bheader.Project__c = testProject.Id;
		bheader.RecordTypeId = changeOrderRecordTypeId;
		bheaders.add(bheader);

		BudgetHeader__c bheader2 = new BudgetHeader__c();
		bheader2.BudgetName__c = 'Change Order 2';
		bheader2.ChangeManagerApprovedForSynch__c = true;
		bheader2.Project__c = testProject.Id;
		bheader2.RecordTypeId = changeOrderRecordTypeId;
		bheaders.add(bheader2);
		insert bheaders;		
		
		list<Id> projectIds = new list<Id>();
		projectIds.add(testProject.Id);
		projectIds.add(testProject2.Id);
		Test.startTest();		
		
		ECO_Service_ProjectSnapshots projectService = new ECO_Service_ProjectSnapshots(projectIds);		
		ProjectSnapshot__c projectSnapshot = projectService.getProjectSnapshot();
		Test.stopTest();
       	System.AssertEquals(2, projectSnapshot.GrossRevenueBudget__c);
       	System.AssertEquals(8000, projectSnapshot.GrossRevenueYearToDate__c);
       	System.AssertEquals(4000, projectSnapshot.GrossRevenueMonthToDate__c);
       	System.AssertEquals(8000, projectSnapshot.GrossRevenueITD__c);
       	
       	System.AssertEquals(null, projectSnapshot.ChangeOrdersPending__c);
    }    
}