src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Group__c</fullName>
        <label>Client Group</label>
        <picklist>
            <picklistValues>
                <fullName>Industrial/Commercial</fullName>
                <color>#33FFFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Municipal</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>National Government</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>State/Province Agencies</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Intercompany</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Subgroup__c</fullName>
        <description>Subset of Client Group, name changed to Market Sector for a time to match GDP, name restored as part of BD ROI workstream implemented for beginning of FY14.</description>
        <label>Client Subgroup</label>
        <picklist>
            <controllingField>Client_Group__c</controllingField>
            <picklistValues>
                <fullName>Aerospace/Defense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airports/Aviation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect/Engineers/Consultants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arts/Museum/Galleries/Cultural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemical/Fertiliser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemical/Pharmaceutical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction Company - Buildings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction Company - Infrastructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data/Technology/Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defense - Air Force</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defense - Army</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defense - Marines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defense - Navy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defense - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education Agency / Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education Services (Private)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Agency / Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental/Climate Agency/Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food/Beverages/Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forestry/Pulp/Paper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freight Transportation (except rail) and Warehousing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare &amp; Life Sciences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare Services (Private)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial/Commercial Developers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Justice/Prisons/Security Agency / Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal/Banking/Finance/Insurance</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legacy_AccountID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy AccountID</label>
        <length>75</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Describes relationship with AECOM - Choose all that might apply</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Client/Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subcontractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime/Teaming Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concessionaire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AECOM_Primary_Dept_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Read Only. To change, click Opportunity Departments at the top of the page, then click the &apos;New/Edit Opportunity Departments&apos; button.</inlineHelpText>
        <label>Primary Department</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>AECOM_Primary_Department__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>$Source.StageName</field>
                <operation>startsWith</operation>
                <value>6,7,8,9</value>
            </filterItems>
            <filterItems>
                <field>AECOM_Primary_Department__c.Status__c</field>
                <operation>equals</operation>
                <value>Active, Inactive</value>
            </filterItems>
            <filterItems>
                <field>$User.CommunityNickname</field>
                <operation>equals</operation>
                <value>SystemNA</value>
            </filterItems>
            <infoMessage>Department must be active. Use asterisks in searching, e.g. *PDD*</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AECOM_Primary_Department__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Group__c</fullName>
        <formula>TEXT(Account.Client_Group__c)</formula>
        <inlineHelpText>Inherited from Account record for reference only - to change, edit the Account.</inlineHelpText>
        <label>Client Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Subgroup__c</fullName>
        <description>Originally called Client Subgroup, then Market Sector, then reverted to Client Subgroup for FY14.
Displays the Client Subgroup (aka Market Sector) from the Account.</description>
        <formula>TEXT(Account.Client_Subgroup__c)</formula>
        <inlineHelpText>Inherited from Account record for reference only - to change, edit the Account.</inlineHelpText>
        <label>Client Subgroup</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_OpportunityID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy OpportunityID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Business_Line__c</fullName>
        <label>Primary Business Line_Old</label>
        <picklist>
            <picklistValues>
                <fullName>Building Engineering</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Construction Services</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Energy</fullName>
                <color>#BBBBBB</color>
            </picklistValues>
            <picklistValues>
                <fullName>Environment</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Geotechnical</fullName>
                <color>#003300</color>
            </picklistValues>
            <picklistValues>
                <fullName>Government Services</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>PCC</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>PDD</fullName>
                <color>#660000</color>
            </picklistValues>
            <picklistValues>
                <fullName>PM/CM</fullName>
                <color>#000099</color>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Water</fullName>
                <color>#00CCCC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Water &amp; Urban Development</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_State_Province__c</fullName>
        <inlineHelpText>Enter state or province of project (not of the office where work will be done)</inlineHelpText>
        <label>Project State/Province</label>
        <picklist>
            <picklistValues>
                <fullName>Abu Dhabi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aguascalientes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ajman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alberta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baja California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baja California Sur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>British Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>British Virgin Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campeche</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiapas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chihuahua</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coahuila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colima</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distrito Federal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distrito Federal MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dubai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durango</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eastern Cape</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free State</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

BreakFix/src/classes/TestProjectOpportunityExtension.cls
@istest
public with sharing class TestProjectOpportunityExtension {
    public static Opportunity opp;

    @isTest (seeAllData=true)
    static void testProjectOpportunityExtension() {
        createTestData();
        
        ApexPages.Standardcontroller ctl = new ApexPages.Standardcontroller(opp);
        ProjectOpportunityExtension ext = new ProjectOpportunityExtension(ctl);
        ext.saveProject();
    }
    
    private static void createTestData() {
Map<String,Id> recordTypes = new Map<String,Id>();
        List<Opportunity> opportunities = new List<Opportunity>(); 
        for(RecordType  recType :[Select Name, Id From RecordType where SobjectType ='Opportunity']){
            recordTypes.put(recType.Name,recType.Id);
        }
        
        Id aecomId;
        for(AECOM_Primary_Department__c aecom :[select id from AECOM_Primary_Department__c limit 1]){
            aecomId = aecom.id;
        }
       // Account
        Account acc1=new Account();
        acc1.Name='Test Account1';
        acc1.Type__c='Client';
        acc1.Client_Group__c='Industrial/Commercial';
        acc1.Client_Subgroup__c='Small - population under 500K';
        acc1.Legacy_AccountID__c='1221234';
        acc1.City__c='testCity';
        insert acc1;
        
        // Master Contract
        opp=new Opportunity();
        opp.AccountId=acc1.id;
        opp.Name='Test';
        opp.Primary_Business_Line__c='Water';
        opp.AECOM_Primary_Dept_Lookup__c=aecomId;
        opp.CloseDate=Date.today();
        opp.StageName='5B Test';
        opp.RecordTypeId=recordTypes.get('Program - APAC');
        
        opp.Legacy_OpportunityID__c='test' + System.now();
        opp.Project_State_Province__c = 'This is text DEscription';   
        opp.CM_Type__c='Test';     
        opp.Contract_Est_Months__c = 5;
        opp.WinDate__c = system.today();
        opp.Project_State_Province__c='WI';
        opp.AECOM_Job_Number__c='01010101';
        opp.Services__c = 'Test 1';
        opp.Energy_Service_Type__c = 'Test 2';
        insert opp;
        
        // Account
        Account part=new Account();
        part.Name='Test Account1';
        part.Type__c='Subcontractor';
        part.Client_Group__c='Industrial/Commercial';
        part.Client_Subgroup__c='Small - population under 500K';
        part.Legacy_AccountID__c='01101101';
        part.City__c='testCity';
        insert part;
        
        Partner op = new Partner();
        op.OpportunityId = opp.id;
        op.AccountToId=part.ID;
        op.Role = 'Alliance Partner';
        insert op;
        
            // Account
        Account prime=new Account();
        prime.Name='Test Account1';
        prime.Type__c='Subcontractor';
        prime.Client_Group__c='Industrial/Commercial';
        prime.Client_Subgroup__c='Small - population under 500K';
        prime.Legacy_AccountID__c='011011301';
        prime.City__c='testCity';
        insert prime;
        
        Partner op2 = new Partner();
        op2.OpportunityId = opp.id;
        op2.AccountToId=prime.ID;
        op2.Role = 'Prime';
        insert op2;
       
    }
    
    
     
}