src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>AECOM employee with primary responsibility for this account, or lead contact if no account manager</inlineHelpText>
        <label>Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AECOM_Employee__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AECOM_Employee__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Group__c</fullName>
        <label>Client Group</label>
        <picklist>
            <picklistValues>
                <fullName>Industrial/Commercial</fullName>
                <color>#33FFFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Municipal</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>National Government</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>State/Province Agencies</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Intercompany</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>If multiple, use country of headquarters address. If country is not in the list, send email to Salesforce_Help@aecom.com.</inlineHelpText>
        <label>Country - OLD</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>British Indian Ocean Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei Darussalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burkina Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cameroon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legacy_AccountID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy AccountID</label>
        <length>75</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province - OLD</label>
        <picklist>
            <picklistValues>
                <fullName>Aguascalientes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alberta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baja California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baja California Sur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>British Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campeche</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiapas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chihuahua</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coahuila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colima</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distrito Federal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durango</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guanajuato</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guerrero</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hidalgo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street address for account</description>
        <inlineHelpText>Multiple lines may be entered</inlineHelpText>
        <label>Street/PO Box</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Describes relationship with AECOM - Choose all that might apply</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Client/Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subcontractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime/Teaming Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concessionaire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <inlineHelpText>ZIP or other postal code</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AECOM_Employee__c.object
<CustomObject>
    <description>(HR Data) Design 2 - use custom object for employee data from HR.</description>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <description>Employee id from HR data source. Used for external lookup to HR database.</description>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>HR Data</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HR Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AECOM_team__c.object
<CustomObject>
    <description>The AECOM employees who are associated with a client, contact, opportunity, or community event.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client with which the employee is associated.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AECOM Team</relationshipLabel>
        <relationshipName>AECOM_Team1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AECOM employee who owns the relationship.</description>
        <label>Employee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AECOM_Employee__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AECOM_Employee__c</referenceTo>
        <relationshipLabel>AECOM Team</relationshipLabel>
        <relationshipName>AECOM_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AECOM Team</label>
    <nameField>
        <displayFormat>TEAM-{0}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AECOM Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BreakFix/src/classes/AccountManager_Test.cls
/*******************************************************************
  Name        :   AccountManager_Test
  Author      :   Sumit(Appirio Off)
  Version     :   1.0 
  Purpose     :   Test Class for AccountManager related Trigger
  Date        :   11-March-2011
********************************************************************/
@isTest
private class AccountManager_Test 
{ 
    static testMethod void myUnitTest() 
    {
        AECOM_Employee__c emp1 = new AECOM_Employee__c(Employee_ID__c='111',    First_Name__c='a1',Last_Name__c='a1',Name='a1 a1');
        AECOM_Employee__c emp2 = new AECOM_Employee__c(Employee_ID__c='112',    First_Name__c='a1',Last_Name__c='a1',Name='a1 a1');
        insert emp1;
        insert emp2;

        Integer iCount;
        List<Account> accList = new List<Account>();
        Account ac = new Account();

        ac.Name = 'name1';
        ac.Type__c = 'Prospect';
        ac.Legacy_AccountID__c = '1100' + system.now();
        ac.Client_Group__c = 'Industrial/Commercial';
        //ac.Client__c = 'Aerospace/Defense';
        ac.City__c = 'BillingCity';
        ac.Street__c = 'Street_1';
        ac.Country__c = 'India';
        ac.State__c = 'BillingState';
        ac.Zip__c = 'BillingPostalCode';
        ac.Account_Manager__c = emp1.id;
        insert ac;
        ac.Account_Manager__c = emp2.id;
        update ac;
        AECOM_team__c  atm =[Select id,Account__c,Employee__c,Role__c from AECOM_team__c where Account__c = :ac.Id];
        atm.Employee__c  = emp1.id;
        update atm;
        AECOM_team__c  atm1=new AECOM_team__c(Account__c=ac.Id,Employee__c=emp2.id,Role__c='Account Manager');
        try
        {
            insert atm1;
        }
        catch(exception ex)
        {
        }
        try
        {
            delete atm;
        }
        catch(exception ex)
        {
        }
        
    }
}