src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Describes relationship with AECOM - Choose all that might apply</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Client/Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subcontractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime/Teaming Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concessionaire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrollment_Comments__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <fields>
        <fullName>ApplicationType__c</fullName>
        <label>Application Type</label>
        <picklist>
            <picklistValues>
                <fullName>FP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T&amp;M</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will be filled in for the person who created the approver comments.</description>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Enrollment_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EnrollmentApplication__c</fullName>
        <label>Enrollment Application</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Enrollment Comments</relationshipLabel>
        <relationshipName>Enrollment_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Final_Rejection__c</fullName>
        <formula>if(and(ispickval(IsRejection__c,&quot;Yes&quot;),

and(
not(ispickval(Reason_Codes__c,&quot;More Suitable for T&amp;M Plan&quot;)),
not(ispickval(Reason_Codes__c,&quot;More Suitable for FP Plan&quot;)),
not(ispickval(Reason_Codes__c,&quot;Other&quot;)),
not(ispickval(Reason_Codes__c,&quot;Rejected For Corrections (explain in comments)&quot;)))),True,False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Final Rejection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRejection__c</fullName>
        <description>Hidden system field set by code to Yes if record created by rejection process</description>
        <inlineHelpText>This field must be displayed for the purposes of the workflow.  No entry required.</inlineHelpText>
        <label>IsRejection</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_Codes__c</fullName>
        <description>When rejection is required, use the dropdown list to select from the most commonly noted reasons. Comments must be logged with each rejection for the reference of the original submitter, prior approvers, and DTW Admin. If corrections to the application</description>
        <inlineHelpText>When rejection is required, use the dropdown list to select from the most commonly noted reasons. Comments must be logged with each rejection for the reference of the original submitter, prior approvers, and DTW Admin. If corrections to the application</inlineHelpText>
        <label>Reason Codes</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Poor Project Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project on Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project in Litigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Nearing Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More Suitable for T&amp;M Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More Suitable for FP Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project is Intercompany – Client is AECOM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected For Corrections (explain in comments)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Comment Type</label>
        <picklist>
            <controllingField>IsRejection__c</controllingField>
            <picklistValues>
                <fullName>General</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Exception</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejection for Corrections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interim Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Enrollment Comment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>EC-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EnrollmentPlan__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW Enrollment Plans under review by Approvers</description>
    <fields>
        <fullName>ApplicationType__c</fullName>
        <inlineHelpText>ENR: Initial Application
CCR: Combined Request for both Participant and Metrics Changes
MOD: Modeling Application that allows performance projections
PAY: Payment Request Application, the final stage in an active app lifecycle</inlineHelpText>
        <label>Form Type</label>
        <picklist>
            <picklistValues>
                <fullName>ENR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>CCR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ApprovalRecentlyProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Recently Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending PM Action</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 1 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 2 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 3 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending DTW Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected for Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unenrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Corp Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - No Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt-Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Enrollment Application</label>
    <nameField>
        <label>Enrollment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Applications</pluralLabel>
    <recordTypes>
        <fullName>Exception</fullName>
        <active>true</active>
        <label>Exception</label>
    </recordTypes>
    <recordTypes>
        <fullName>Workflow</fullName>
        <active>true</active>
        <label>Workflow</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/INC_EnrollmentCommentController.cls
public without sharing class INC_EnrollmentCommentController {

	public EnrollmentPlan__c oEnrollmentApp{get;set;}
    public Enrollment_Comments__c oEnrollComment{get;set;}
    public boolean isRejectedRecType{get;set;}
    public String sMessage{get;set;}
    public boolean bCommentFound{get;set;}
    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public INC_EnrollmentCommentController() {
        oEnrollmentApp = INC_Service_EnrollmentPlan.getEnrollmentPlan(new set<id>{Apexpages.currentpage().getParameters().get('id')})[0];
         ID rejectedRecTypeID = Schema.SObjectType.EnrollmentPlan__c.getRecordTypeInfosByName().get('Rejected Application').getRecordTypeId();
            
           
            if(rejectedRecTypeID == oEnrollmentApp.RecordTypeID){
                isRejectedRecType = true;
                bCommentFound = getLatestRejectionComment();

            }else{
                isRejectedRecType = false;
            }

    }

    private boolean getLatestRejectionComment(){
        boolean bReturn = false;
        
        list<Enrollment_Comments__c> lComments;
        if(oEnrollmentApp.ApplicationType__c !='OPT'){
                                        lComments = [Select ID
                                                          , Comments__c
                                                          , Type__c
                                                          , Reason_Codes__c
                                                          , Approver__c
                                                          , Approver__r.Name
                                                          , IsRejection__c
                                                          , Final_Rejection__c
                                                 From Enrollment_Comments__c
                                                 Where EnrollmentApplication__c =: oEnrollmentApp.ID
                                                 and (Type__c = 'Rejection' or Type__c ='Rejection for Corrections')
                                                 and (Reason_Codes__c = null)
                                                 Order by CreatedDate];
        }else{
                                        lComments = [Select ID
                                                          , Comments__c
                                                          , Type__c
                                                          , Reason_Codes__c
                                                          , Approver__c
                                                          , Approver__r.Name
                                                          , IsRejection__c
                                                          , Final_Rejection__c
                                                 From Enrollment_Comments__c
                                                 Where EnrollmentApplication__c =: oEnrollmentApp.ID
                                                 and (Type__c = 'Rejection')
                                                 and (Reason_Codes__c = null)
                                                 Order by CreatedDate];
        }
        //find the latest one, hopefully the query should only return one.  But I have to account for bad data
        System.Debug(logginglevel.error,'lcomments: 2 ' + lComments);
        if(lComments != Null && lComments.size() > 0){
                bReturn = true;
                oEnrollComment = lComments[0];
                if(oEnrollmentApp.ApplicationType__c != 'OPT'){
                  sMessage = lComments[0].Approver__r.Name + ' rejected the application.  A rejection code must be selected before any changes to the';
                  sMessage += ' application are possible.';
                }else{
                  sMessage = lComments[0].Approver__r.Name + ' approved opting out of the application.  A rejection code must be selected.';
                }
        }else{
          oEnrollComment = new Enrollment_Comments__c(EnrollmentApplication__c = oEnrollmentApp.ID);
        }

        return bReturn;
    }


    public pageReference saveComments(){
      System.Debug(logginglevel.error,'Saving');
        if(oEnrollComment.Reason_Codes__c == null){
            System.debug(logginglevel.error,'oEnrollComment.Reason_Codes__c ');
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,'You must choose a reason code before saving.'));
        }else{
          if(oEnrollComment.Comments__c != null && oEnrollComment.Comments__c != 'Please enter a comment.'
             && oEnrollComment.Comments__c != ''){
            ID workFlowID = ECO_Utils_sObject.getRecordTypeId(EnrollmentPlan__c.sObjectType,'Workflow');
            ID paymentID = ECO_Utils_sObject.getRecordTypeId(EnrollmentPlan__c.sObjectType,'Payment Request');
            System.Debug(logginglevel.error,'Workflowid ' + workFlowID);
            System.Debug(logginglevel.error,'paymentID ' + workFlowID);
            oEnrollmentApp.ApprovalRecentlyProcessed__c = false;
           // oEnrollmentApp.EnrollmentStatus__c = 'Rejected for Correction';
            if(workFlowID != null && paymentID != null){

              if(oEnrollmentApp.ApplicationType__c == 'PAY'){
                  oEnrollmentApp.RecordTypeID=paymentID;
              } else {
                  oEnrollmentApp.RecordTypeID=workFlowID;
              }

              System.savePoint sp = Database.setSavePoint();
              try{
                  system.debug(logginglevel.error,'Updating records');
                  update oEnrollmentApp;
              }catch(Exception e){
                  system.debug('Handling Exception:  '+e.getMessage() + ' ' + e.getStackTraceString());
                  system.debug(logginglevel.error, 'enrollmentPlan update error: ' + e);
                  Database.rollBack(sp);
              }
              try{
                  system.debug(logginglevel.error,'Updating Comments');
                  upsert oEnrollComment;
              }catch(Exception e){
                  system.debug('Handling Exception:  '+e.getMessage() + ' ' + e.getStackTraceString());
                  system.debug(logginglevel.error, 'comment creation error: ' + e);
                  Database.rollBack(sp);
              }  
              
              System.Debug(logginglevel.error,'oEnrollmentApp.Reason_Codes__c: ' + oEnrollComment.Reason_Codes__c);

              String sReason = oEnrollComment.Reason_Codes__c;

              /*if(sReason == 'Project in Litigation' ||
                 sReason.contains('Project is Intercompany') ||
                 sReason == 'Project on Hold' ||
                 sReason == 'Project Nearing Completion' ||
                 sReason == 'Poor Project Performance'){
                if(oEnrollmentApp.ApplicationType__c != 'OPT'){
                  System.Debug(logginglevel.error,'rejecting all');
                  rejectAll();
                }
              } */
              if(oEnrollComment.Final_Rejection__c && oEnrollmentApp.ApplicationType__c != 'OPT'){
                 System.Debug(logginglevel.error,'rejecting all');
                  rejectAll();
              }
            }
          }else{
                System.Debug(logginglevel.error,'Not saving comments');
                  ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,'You must enter a valid comment.'));
            
          }
              
        }

        //pageReference pr = new PageReference('/apex/INC_EnrollmentApp?id='+oEnrollmentApp.id);
        //pr.setredirect(true);
        return null;
    }

    public static Id getWorkItemId(Id targetObjectId)
    {
      Id retVal = null;
      for(ProcessInstanceWorkitem workItem  : [Select p.Id from ProcessInstanceWorkitem p
          where p.ProcessInstance.TargetObjectId =: targetObjectId])
      {
          retVal =  workItem.Id;
      }
      return retVal;
    }

    public pageReference rejectAll(){
      /*ID workItem = getWorkItemId(oEnrollmentApp.ID);
      while(workItem != null){
          //req.setNextApproverIds(new Id[] {UserInfo.getUserId()});
          req.setWorkitemId(workItem);
              // Submit the request for approval
          workItem = getWorkItemId(oEnrollmentApp.id);
       
      }
      return new pageReference('/apex/INC_EnrollmentApp?id=' + oEnrollmentApp.id);*/

      ID workItem = getWorkItemId(oEnrollmentApp.ID);
      While(workItem != null){
        Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
          req.setComments('System generated final rejection.');
          req.setAction('Reject');
          //req.setNextApproverIds(new Id[] {UserInfo.getUserId()});
          req.setWorkitemId(workItem);
              // Submit the request for approval
          Approval.ProcessResult result =  Approval.process(req);
          workItem = getWorkItemId(oEnrollmentApp.id);
      }

      oEnrollmentApp = INC_Service_EnrollmentPlan.getEnrollmentPlan(new set<id>{oEnrollmentApp.ID})[0];
      oEnrollmentApp.ApprovalRecentlyProcessed__c = false;
      //oEnrollmentApp.EnrollmentStatus__c = 'Rejected';
      update oEnrollmentApp;

      /*If(workItem != null){
            List<ProcessInstanceWorkitem> workitems = new List<ProcessInstanceWorkitem>([select Id from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId =:oEnrollmentApp.id]);

            list<Approval.ProcessWorkitemRequest> itemsToUpdate = new list<Approval.ProcessWorkitemRequest>();

            for(ProcessInstanceWorkitem w: workitems){
                Approval.ProcessWorkitemRequest PWR = new Approval.ProcessWorkitemRequest();
                PWR.setComments('Recalled due to final Rejection');
                PWR.setAction('Removed');
                PWR.setWorkItemId(w.Id);
                itemsToUpdate.add(PWR);
            }                
            System.Debug(logginglevel.error,'itemsToUpdate: ' + itemsToUpdate);
            if(itemsToUpdate.size() > 0){
                list<Approval.ProcessResult> results =  Approval.process(itemsToUpdate);
                System.debug(logginglevel.error,'results: ' + results);
            }
      }
      */

      return new pageReference('/apex/INC_EnrollmentApp?id=' + oEnrollmentApp.id);


    }

}