src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Used in reporting, to determine number of contacts associated with an account.</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CustomerAccountSiteID__c</fullName>
        <label>Customer Account Site ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationString__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization String</label>
        <referenceTo>OrganizationString__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the Contact to the User object.  This is for the representation of Employees.  Specifically, this is for the Shared Services Case Management.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VendorSiteID__c</fullName>
        <label>Vendor Site ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pse__Is_Resource_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resource Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse__Is_Resource__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resource</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Delegate__c.object
<CustomObject>
    <description>This object stores the delegate records.</description>
    <fields>
        <fullName>Active__c</fullName>
        <formula>AND ( 
     End_Date__c &gt; TODAY(),  
     ISPICKVAL (Approval_Status__c, &quot;APPROVED&quot;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Delegated to contact. Contact to whom a role has been delegated.</description>
        <label>Delegate</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Is_Resource__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Delegates</relationshipLabel>
        <relationshipName>Delegates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegator__c</fullName>
        <description>The contact who delegates to another contact</description>
        <label>Delegator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Delegates</relationshipLabel>
        <relationshipName>Delegates1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date on which the delegation would end</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key_Member_Role__c</fullName>
        <description>The role for which delegation is done</description>
        <label>Key Member Role</label>
        <picklist>
            <picklistValues>
                <fullName>Project Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Accountant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date at which the delegation would begin</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Delegate</label>
    <nameField>
        <displayFormat>DLGT-{0000000000}</displayFormat>
        <label>Delegate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrganizationString__c.object
<CustomObject>
    <fields>
        <fullName>PLManagerContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Approver 2 on stakeholders screen.</inlineHelpText>
        <label>Project Approver 2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>PSA Resource</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Salesforce_User__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization String</relationshipLabel>
        <relationshipName>Organization_String</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectAccountant2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Accountant 2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>PSA Resource</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Salesforce_User__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization String (Project Accountant 2)</relationshipLabel>
        <relationshipName>OrganizationStringProjectAccountant2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Organization String</label>
    <nameField>
        <label>Organization String Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization String</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <formula>Site__r.City__c</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipName>ProjectSites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Site</label>
    <nameField>
        <displayFormat>ProjectSite-{0000000000}</displayFormat>
        <label>Project Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProjectRole__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays only PSA resouces</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>PSA Resource</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Role</label>
        <referenceTo>ProjectRole__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersRole</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User must be active</description>
        <inlineHelpText>User must be active</inlineHelpText>
        <label>Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>User must be active</errorMessage>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>User must be active</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectTeamMemberUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000000}</displayFormat>
        <label>Project Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <recordTypes>
        <fullName>TeamMember</fullName>
        <active>true</active>
        <label>Team Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <description>Represents a customer/vendor site (address/location).</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Represents the account which is bound to the customer/vendor site (address/location).</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerAccountSiteID__c</fullName>
        <externalId>true</externalId>
        <label>Customer Account Site ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Site</label>
    <nameField>
        <displayFormat>Site-{0000000000}</displayFormat>
        <label>Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SurveySchedule__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Schedules</relationshipLabel>
        <relationshipName>SurveySchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Survey Schedules</relationshipLabel>
        <relationshipName>Survey_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Schedule</label>
    <nameField>
        <displayFormat>SS-{00000000}</displayFormat>
        <label>Survey Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_StakeholdersControllerTest.cls
/*
	Purpose: - Test class for the ECO_StakeholdersController Controller

	Created By: Aaron Pettitt (NTT Data)

	Revision Log: 
		v1.0 - (AP 10/12/2015) -- created 
*/
@isTest
private class ECO_StakeholdersControllerTest {
	Static User testUser;
	Static Contact testContact;
	Static Id recordTypeId;
	Static pse__Proj__c project;
	Static Site__c testSite;
	Static Account testAccount;
	Static List<ProjectTeamMember__c> projectMembers;
	Static List<ProjectRole__c> projectRoles;
	
	@isTest static void testConstructor() {
		setupTestData();
		PageReference pg = Page.ECO_Stakeholders;
		pg.getParameters().put('Id', project.id);
		Test.setCurrentPage(pg);
		ApexPages.StandardController standardController = new ApexPages.StandardController(project);
		ECO_StakeholdersController stakeHolderController = new ECO_StakeholdersController(standardController);
		system.assertEquals('/apex/eco_stakeholders?Id=' + project.Id, stakeHolderController.returnURL);
		system.assertEquals(5, stakeHolderController.lActiveMembersKey.size());
		testContact.pse__Is_Resource_Active__c = false;
		update testContact;
		stakeHolderController.initStakeHolders(project);
		system.assertEquals(1, stakeHolderController.lInactiveMembersTeam.size());
		system.assertEquals(new PageReference('/' + project.Id).getUrl(), stakeHolderController.ReturnToProject().getUrl());
	}
	
	@isTest static void testAddSaveData() {
		setupTestData();
		PageReference pg = Page.ECO_Stakeholders;
		pg.getParameters().put('Id', project.id);
		Test.setCurrentPage(pg);
		ApexPages.StandardController standardController = new ApexPages.StandardController(project);
		ECO_StakeholdersController stakeHolderController = new ECO_StakeholdersController(standardController);
		stakeHolderController.recordObjectType = 'MembersTeam';
		stakeHolderController.addRecord();
		system.assertEquals(5, stakeHolderController.lActiveMembersKey.size());
		stakeHolderController.recordObjectType = 'Stakeholder__c';
		stakeHolderController.addRecord();
		system.assertEquals(2, stakeHolderController.lStakeholders.size());
		stakeHolderController.recordObjectType = 'CommunicationPlan__c';
		stakeHolderController.addRecord();
		system.assertEquals(1, stakeHolderController.lCommPlans.size());
		stakeHolderController.recordObjectType = 'SurveySchedule__c';
		system.assertEquals(1, stakeHolderController.lSurveySchedules.size());
		stakeHolderController.addRecord();
		//stakeHolderController.lInactiveMembersKey.add(new ECO_StakeholdersController.TeamMember(project, projectRoles));
		//stakeHolderController.lInactiveMembersKey[0].oPTM = projectMembers[0];
		stakeHolderController.SaveAll();
		system.assertEquals(5, stakeHolderController.lActiveMembersKey.size());
		system.assertEquals(1, stakeHolderController.lStakeholders.size());
		system.assertEquals(0, stakeHolderController.lCommPlans.size());
		system.assertEquals(1, stakeHolderController.lSurveySchedules.size());
		stakeHolderController.resetQueryTable();
	}

	@isTest static void testSearchForKeyMembers() {
		setupTestData();
		PageReference pg = Page.ECO_Stakeholders;
		Test.setCurrentPage(pg);
		pg.getParameters().put('Id', project.id);
		pg.getParameters().put('contactName', testUser.FirstName + ' ' + testUser.LastName);
		pg.getParameters().put('selectedRole', 'Project Manager');
		pg.getParameters().put('startDate', Date.today().format());
		ApexPages.StandardController standardController = new ApexPages.StandardController(project);
		ECO_StakeholdersController stakeHolderController = new ECO_StakeholdersController(standardController);
		stakeHolderController.searchForKeyMembers();
		system.assertEquals(1, stakeHolderController.queryDelegates.size());

		/*
		User testUser2 = ECO_Utils_Testing.createTestUser('Standard User');
		Contact testContact2 = new Contact();
		testContact2.Email = testUser2.Email;
		testContact2.FirstName = testUser2.FirstName;
		testContact2.LastName =  testUser2.LastName;
		testContact2.Phone = '55555555555';
		testContact2.pse__Salesforce_User__c = testUser2.Id;
		testContact2.RecordTypeId = recordTypeId;
		testContact2.User__c = testUser2.Id;
		testContact2.OwnerId = testUser.Id;
		testContact2.Site__c = testSite.Id;
		testContact2.AccountId = testAccount.Id;
		testContact2.pse__Is_Resource_Active__c = true;
		testContact2.pse__Is_Resource__c = true;
		insert testContact2;
		system.runAs(testUser){
			Delegate__c delegate = new Delegate__c(Delegate__c = testContact2.Id, Delegator__c = testContact.Id, End_Date__c = Date.today().addDays(30), Key_Member_Role__c = 'Project Manager', Start_Date__c = Date.today());
			insert delegate;
		}*/

		
		pg.getParameters().put('queryType', 'Delegate');
		stakeHolderController.searchForKeyMembers();
		system.assertEquals(0, stakeHolderController.queryDelegates.size());

	}

	@isTest static void testSelectReplaceKeyMember() {
		setupTestData();
		PageReference pg = Page.ECO_Stakeholders;
		Test.setCurrentPage(pg);
		pg.getParameters().put('Id', project.id);
		pg.getParameters().put('selectedContactId', testContact.Id);
		pg.getParameters().put('selectedRole', 'Project Manager');
		pg.getParameters().put('queryType', 'Unfiltered');
		ApexPages.StandardController standardController = new ApexPages.StandardController(project);
		ECO_StakeholdersController stakeHolderController = new ECO_StakeholdersController(standardController);
		stakeHolderController.selectReplaceKeyMember();
		pg.getParameters().put('startDate', Date.today().addDays(1).format());
		stakeHolderController.selectReplaceKeyMember();
		pg.getParameters().put('startDate', Date.today().addDays(3).format());
		stakeHolderController.selectReplaceKeyMember();
		pg.getParameters().put('startDate', Date.today().addDays(12).format());
		stakeHolderController.selectReplaceKeyMember();
		system.assertEquals(5, stakeHolderController.lActiveMembersKey.size());
	}

	@isTest static void testMisc() {
		setupTestData();
		PageReference pg = Page.ECO_Stakeholders;
		Test.setCurrentPage(pg);
		pg.getParameters().put('Id', project.id);
		ApexPages.StandardController standardController = new ApexPages.StandardController(project);
		ECO_StakeholdersController stakeHolderController = new ECO_StakeholdersController(standardController);
		stakeHolderController.queryDelegates = new List<Contact>();
		stakeHolderController.queryDelegates.add(testContact);
		stakeHolderController.sendApprovalProcess(projectMembers[0], 'Project Manager');
		stakeHolderController.defaultDates();
		system.assertEquals('2015-09-05', stakeHolderController.convertStringSOQLString('9/5/2015'));
	}

	@isTest static void testSetOptions() {
		setupTestData();
		PageReference pg = Page.ECO_Stakeholders;
		Test.setCurrentPage(pg);
		pg.getParameters().put('Id', project.id);
		ApexPages.StandardController standardController = new ApexPages.StandardController(project);
		ECO_StakeholdersController stakeHolderController = new ECO_StakeholdersController(standardController);
		stakeHolderController.recordObjectType = 'SurveySchedule__c';
		system.assertEquals(1, stakeHolderController.lSurveySchedules.size());
		stakeHolderController.addRecord();
		stakeHolderController.lstSSW[0].ss.Client__c = testSite.Id;
		pg.getParameters().put('surveyToRefresh', '0');
		stakeHolderController.setOptions();
		system.assertEquals(2, stakeHolderController.lstSSW[0].cOptions.size());
	}

	@isTest static void testRemoveData() {
		setupTestData();
		PageReference pg = Page.ECO_Stakeholders;
		pg.getParameters().put('Id', project.id);
		Test.setCurrentPage(pg);
		ApexPages.StandardController standardController = new ApexPages.StandardController(project);
		ECO_StakeholdersController stakeHolderController = new ECO_StakeholdersController(standardController);
		stakeHolderController.recordObjectType = 'MembersTeam';
		stakeHolderController.addRecord();
		pg.getParameters().put('teamMemberToRemove', '0');
		stakeHolderController.removeRecord();
		system.assertEquals(5, stakeHolderController.lActiveMembersKey.size());
		stakeHolderController.recordObjectType = 'Stakeholder__c';
		stakeHolderController.addRecord();
		pg.getParameters().put('otherToRemove', '0');
		stakeHolderController.removeRecord();
		system.assertEquals(1, stakeHolderController.lStakeholders.size());
		stakeHolderController.recordObjectType = 'CommunicationPlan__c';
		stakeHolderController.addRecord();
		pg.getParameters().put('planToRemove', '0');
		stakeHolderController.removeRecord();
		system.assertEquals(0, stakeHolderController.lCommPlans.size());
		stakeHolderController.recordObjectType = 'SurveySchedule__c';
		stakeHolderController.addRecord();
		pg.getParameters().put('surveyToRemove', '0');
		stakeHolderController.removeRecord();
		system.assertEquals(1, stakeHolderController.lSurveySchedules.size());
	}

	static void setupTestData(){

		Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
		recordTypeId = ECO_Utils_sObject.getRecordTypeId(Contact.sObjectType, 'PSA Resource');

		testAccount = new Account();
		testAccount.Name = 'test account';
		insert testAccount;

		testUser = ECO_Utils_Testing.createTestUser('Standard User');
		insert testUser;

	    //project sites
		testSite = new Site__c();
		testSite.Account__c = testAccount.Id;
		testSite.CurrencyIsoCode = 'USD';
		testSite.City__c = 'Winnipeg';		
		testSite.VendorSiteID__c = '654321';
		testSite.CustomerAccountSiteID__c = '666666';

		insert testSite;

		testContact = new Contact();
		testContact.Email = testUser.Email;
		testContact.FirstName = testUser.FirstName;
		testContact.LastName =  testUser.LastName;
		testContact.Phone = '55555555555';
		testContact.pse__Salesforce_User__c = testUser.Id;
		testContact.RecordTypeId = recordTypeId;
		testContact.User__c = testUser.Id;
		testContact.OwnerId = testUser.Id;
		testContact.Site__c = testSite.Id;
		testContact.AccountId = testAccount.Id;
		testContact.pse__Is_Resource_Active__c = true;
		testContact.pse__Is_Resource__c = true;
		insert testContact;

		OrganizationString__c organizationString = new OrganizationString__c(Name = 'Test Organization', ProjectAccountant2__c = testContact.Id, PLManagerContact__c = testContact.Id);
		insert organizationString;

		projectRoles = new List<ProjectRole__c>();
		projectRoles.add(new ProjectRole__c(Name = 'Project Manager', Type__c = 'Key Member', Active__c = true));
		projectRoles.add(new ProjectRole__c(Name = 'Project Approver 2', Type__c = 'Key Member', Active__c = true));
		projectRoles.add(new ProjectRole__c(Name = 'Project Approver', Type__c = 'Key Member', Active__c = true));
		projectRoles.add(new ProjectRole__c(Name = 'Resilience Director', Type__c = 'Key Member', Active__c = true));
		projectRoles.add(new ProjectRole__c(Name = 'Project Worker', Active__c = true));
		projectRoles.add(new ProjectRole__c(Name = 'Finance Lead', Type__c = 'Key Member', Active__c = true));
		insert projectRoles;

		List<pse__Proj__c> projects = new List<pse__Proj__c>();
		projects.add(new pse__Proj__c(CarryingOutOrganization__c = organizationString.Id, pse__Account__c = testAccount.Id, pse__Start_Date__c = Date.today().addDays(30), pse__End_Date__c = Date.today().addDays(60)));
		projects.add(new pse__Proj__c(CarryingOutOrganization__c = organizationString.Id, pse__Account__c = testAccount.Id, pse__Start_Date__c = Date.today().addDays(-30), pse__End_Date__c = Date.today().addDays(-1)));
		insert projects;
		project = projects[0];

		Project_Site__c testProjectSite = new Project_Site__c();
		
		testProjectSite.BillingContactID__c	= '1234';
		//testProjectSite.OracleProjectSiteId__c = '1111';
		testProjectSite.Project__c = project.Id;
		testProjectSite.Site__c = testSite.Id;
		testProjectSite.Contribution__c = 100;

		insert testProjectSite;


		projectMembers = new List<ProjectTeamMember__c>();
		projectMembers.add(new ProjectTeamMember__c(Project__c = project.Id, CurrencyIsoCode = 'USD', ProjectRole__c = projectRoles[0].Id, Contact__c = testContact.Id, StartDate__c = Date.today(), EndDate__c = Date.today().addDays(1)));
		projectMembers.add(new ProjectTeamMember__c(Project__c = project.Id, CurrencyIsoCode = 'USD', ProjectRole__c = projectRoles[1].Id, Contact__c = testContact.Id, StartDate__c = Date.today().addDays(2), EndDate__c = Date.today().addDays(3)));
		projectMembers.add(new ProjectTeamMember__c(Project__c = project.Id, CurrencyIsoCode = 'USD', ProjectRole__c = projectRoles[3].Id, Contact__c = testContact.Id, StartDate__c = Date.today().addDays(4), EndDate__c = Date.today().addDays(5)));
		projectMembers.add(new ProjectTeamMember__c(Project__c = project.Id, CurrencyIsoCode = 'USD', ProjectRole__c = projectRoles[5].Id, Contact__c = testContact.Id, StartDate__c = Date.today().addDays(5), EndDate__c = Date.today().addDays(6)));
		projectMembers.add(new ProjectTeamMember__c(Project__c = project.Id, CurrencyIsoCode = 'USD', ProjectRole__c = projectRoles[4].Id, Contact__c = testContact.Id, StartDate__c = Date.today(), Is_Active__c = true));
		projectMembers.add(new ProjectTeamMember__c(Project__c = projects[1].Id, CurrencyIsoCode = 'USD', ProjectRole__c = projectRoles[1].Id, Contact__c = testContact.Id, StartDate__c = Date.today().addDays(-30)));
		insert projectMembers;

		SurveySchedule__c surveySchedule = new SurveySchedule__c(Account__c = testAccount.Id, Client__c = testSite.Id, Contact__c = testContact.Id, Project__c = project.Id, ScheduledDate__c = Date.today().addDays(10));
		insert surveySchedule;

	}
	
}