src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>If multiple, use country of headquarters address. If country is not in the list, send email to Salesforce_Help@aecom.com.</inlineHelpText>
        <label>Country - OLD</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>British Indian Ocean Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei Darussalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burkina Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cameroon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OracleCustomerID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Customer ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>IF (ISBLANK( State_Province_Emerate__c ), &quot;None&quot;, 
IF (CONTAINS(&quot;New Brunswick:Newfoundland:Ontario:Prince Edward Island&quot;, State_Province_Emerate__r.Name ), &quot;Canada&quot;, 
IF (CONTAINS(&quot;Nova Scotia:Quebec&quot;, State_Province_Emerate__r.Name ), &quot;Canada&quot;, 
IF (CONTAINS(&quot;Alberta:British Columbia:Manitoba:Northwest Territories:Nunavut:Saskatchewan:Yukon Territory&quot;, State_Province_Emerate__r.Name ), &quot;Canada&quot;, 
IF (CONTAINS(&quot;Arkansas:Illinois:Indiana:Iowa:Kansas:Kentucky:Michigan:Minnesota:Missouri:Nebraska:North Dakota:Ohio:South Dakota:Delaware:Wisconsin&quot;,State_Province_Emerate__r.Name ), &quot;US North&quot;, 
IF (CONTAINS(&quot;Connecticut:Maine:Massachusetts:New Hampshire:Pennsylvania:New Jersey:New York:Rhode Island:Vermont:West Virginia&quot;,State_Province_Emerate__r.Name ),&quot;US North&quot;, 
IF (CONTAINS(&quot;Alabama:Florida:Georgia:Mississippi:North Carolina:District of Columbia:Maryland:Virginia:Puerto Rico:South Carolina:Tennessee:U.S. Virgin Islands&quot;,State_Province_Emerate__r.Name ), &quot;US South&quot;, 
IF (CONTAINS(&quot;Texas :Louisiana:Oklahoma&quot;,State_Province_Emerate__r.Name ), &quot;US South&quot;, 
IF (CONTAINS(&quot;Alaska:American Samoa:Arizona:California:Colorado:Hawaii:Idaho:Montana:Nevada:New Mexico:Oregon:Utah:Washington:Wyoming:Guam: Midway Atoll:Wake Island:Mariana Islands&quot;, State_Province_Emerate__r.Name ), &quot;US West&quot;, 
IF (CONTAINS(&quot;United Arab Emirates&quot;, CountryLookup__r.Name) , BillingCity , 
CountryLookup__r.Name ))))))))))</formula>
        <inlineHelpText>autofilled based on address state</inlineHelpText>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province - OLD</label>
        <picklist>
            <picklistValues>
                <fullName>Aguascalientes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alberta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baja California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baja California Sur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>British Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campeche</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiapas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chihuahua</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coahuila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colima</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distrito Federal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durango</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guanajuato</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guerrero</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hidalgo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ontario</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Country and Region</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>TO_Procurement_Method__c</fullName>
        <inlineHelpText>Indicate whether task orders will be Noncompetitive (they will be assigned without another bid) or Competitive (we will have to submit a bid and compete with other firms)</inlineHelpText>
        <label>Task Order Procurement Method</label>
        <picklist>
            <picklistValues>
                <fullName>Competitive Task Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noncompetitive Task Orders</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OrganizationString__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLineName__c</fullName>
        <label>Business Line Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GeographyName__c</fullName>
        <label>Geography Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InactiveDate__c</fullName>
        <label>Inactive Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OUID__c</fullName>
        <externalId>true</externalId>
        <label>OUID</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgID__c</fullName>
        <description>This is the ID of the Operating Unit</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the ID of the Operating Unit</inlineHelpText>
        <label>OrgID</label>
        <length>240</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <externalId>true</externalId>
        <label>Organization Name</label>
        <length>240</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Organization String</label>
    <nameField>
        <label>Organization String Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization String</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFDC_Acct_Plan__c.object
<CustomObject>
    <description>Overall goals, objectives, and challenges for penetrating an account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <description>Represents a customer/vendor site (address/location).</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Represents the account which is bound to the customer/vendor site (address/location).</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerSiteUseCode__c</fullName>
        <externalId>true</externalId>
        <label>Customer Site Use Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OracleCustomerID__c</fullName>
        <formula>Account__r.OracleCustomerID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Oracle Customer ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgID__c</fullName>
        <label>Org ID</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province/Emirate</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <displayFormat>Site-{0000000000}</displayFormat>
        <label>Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_ProjectSetupControllerTest.cls
@isTest
private class ECO_ProjectSetupControllerTest
{

	static void initializeSites(){

		list<account> testAccounts = new list<account>();

		// Insert Test Account
		Account testAccount = new Account();
		testAccount.Name = 'test account';
		testAccount.OracleCustomerID__c = '1111';
		testAccounts.add(testAccount);

		Account testAccount2 = new Account();
		testAccount2.Name = 'another account';
		testAccount2.OracleCustomerID__c = '2222';
		testAccounts.add(testAccount2);

		insert testAccounts;		

		Opportunity testOpp = new Opportunity();
		testOpp.accountid = testAccount.id;
        testOpp.name = 'test opp';
        testOpp.closeDate = date.today();
        testOpp.Stagename = '1 Lead';
        testOpp.probability = 100;
        testOpp.TO_Procurement_Method__c = 'Competitive Task Orders';		

        insert testOpp;

		// Insert Test Site Data
		list<site__c> testSites = new list<site__c>();

		Site__c s1 = new Site__c();
		s1.Account__c = testAccount.id;
		s1.City__c = 'Toronto';
		s1.Country__c = 'Canada';
		s1.State__c = 'Ontario';
		s1.CustomerSiteUseCode__c = 'BILL_TO';

		testSites.add(s1);

		Site__c s2 = new Site__c();
		s2.Account__c = testAccount.id;
		s2.City__c = 'Toronto2';
		s2.Country__c = 'Canada2';
		s2.State__c = 'Ontario2';
		s2.CustomerSiteUseCode__c = 'SHIP_TO';

		testSites.add(s2);

		Site__c s3 = new Site__c();
		s3.Account__c = testAccount.id;
		s3.City__c = 'Toronto3';
		s3.Country__c = 'Canada3';
		s3.State__c = 'Ontario3';
		s3.CustomerSiteUseCode__c = 'SHIP_TO';

		testSites.add(s3);		

		Site__c s4 = new Site__c();
		s4.Account__c = testAccount2.id;
		s4.City__c = 'Vanc';
		s4.Country__c = 'Canada';
		s4.State__c = 'BC';
		s4.CustomerSiteUseCode__c = 'BILL_TO';

		testSites.add(s4);	


		insert testSites;

		/*
		List<OrganizationString__c> lOrgStrings = new List<OrganizationString__c>();
		OrganizationString__c Org1 = INC_Utils_Testing.createTestOrg();
		OrganizationString__c Org2 = INC_Utils_Testing.createTestOrg();

		Org2.OrganizationName__c = 'Water Organization';
		Org2.Name = 'Water Organization';
		Org2.BusinessLineName__c = 'Water';
		Org2.Department__c = 'Water Department';
		Org2.District__c = 'Water District';
		Org2.Description__c = 'Water org string';
		Org2.GeographyName__c = 'Water Geo';
		Org2.Region__c = 'Water Region';
		Org2.OrgID__c = '227';
		Org2.OUID__c = '999';
		org2.InactiveDate__c = null;

		lOrgStrings.add(Org2);
		insert lOrgStrings;		
		*/
	}


	// Test duplicate filtering functionality of site searching
	@isTest
	static void DupeTest()
	{

		initializeSites();


		// Create standard controller for a new project and pass to the ext. Start the real test.
		ApexPages.StandardController sc = new ApexPages.StandardController(new pse__Proj__c());
		ECO_ProjectSetupController ext = new ECO_ProjectSetupController(sc);

		ext.SearchSites();
		system.assertEquals(ext.lstSitesSearchResults.size(), 2); 
	}

	// Test No Results for Sites
	@isTest
	static void NoSiteResult()
	{

		initializeSites();


		// Create standard controller for a new project and pass to the ext. Start the real test.
		ApexPages.StandardController sc = new ApexPages.StandardController(new pse__Proj__c());
		ECO_ProjectSetupController ext = new ECO_ProjectSetupController(sc);

		ext.oSite.Account__r.name = 'BLAHBLAHBLAH';
		ext.SearchSites();
		system.assertEquals(ext.lstSitesSearchResults.size(), 0); 
	}

	// Test No Results for Sites with Successful Search
	@isTest
	static void WithSiteFilterResult()
	{

		initializeSites();

		// Create standard controller for a new project and pass to the ext. Start the real test.
		ApexPages.StandardController sc = new ApexPages.StandardController(new pse__Proj__c());
		ECO_ProjectSetupController ext = new ECO_ProjectSetupController(sc);

		ext.oSite.Account__r.name = 'test';
		ext.oSite.City__c = 'Toronto2';
		ext.oSite.Country__c = 'Canada';
		ext.oSite.State__c = 'Ontario';
		ext.SearchSites();
		system.assertEquals(ext.lstSitesSearchResults.size(), 1); 
		system.assertEquals(ext.lstSitesSearchResults[0].City__c, 'Toronto2'); 
		system.assertEquals(ext.lstSitesSearchResults[0].Country__c, 'Canada2'); 
		system.assertEquals(ext.lstSitesSearchResults[0].State__c, 'Ontario2'); 
	}

	// Test the selection of a searched Site with no opp + creation of project
	@isTest
	static void NoOppSelect()
	{

		initializeSites();


		// Create standard controller for a new project and pass to the ext. Start the real test.
		ApexPages.StandardController sc = new ApexPages.StandardController(new pse__Proj__c());
		ECO_ProjectSetupController ext = new ECO_ProjectSetupController(sc);

		ext.oSite.Account__r.name = 'another';
		ext.SearchSites();
		system.assertEquals(ext.lstSitesSearchResults.size(), 1); 

		// Select Target Site
		ext.idSiteID = ext.lstSitesSearchResults[0].id;
		ext.SelectSite();

		system.assertEquals(ext.lstSites.size(), 1); 
		system.assertEquals(ext.lstSites[0].booIsPrimaryEnd, true); 
		system.assertEquals(ext.lstSites[0].booIsBilling, true); 
		system.assertEquals(ext.lstSites[0].booIsEnd, true); 		
		system.assertEquals(ext.lstSites[0].booIsDefaultTopTask, true);
		system.assertEquals(ext.lstSites[0].oSite.City__c, 'Vanc');
		system.assertEquals(ext.lstSites[0].oSite.Country__c, 'Canada');
		system.assertEquals(ext.lstSites[0].oSite.State__c, 'BC');


		system.assertEquals(ext.lstSearchOpportunities.size(), 0); 

		ext.oProject.name = 'test project';
		ext.oProject.EstimatedContractValue__c = 1;
		ext.oProject.ownerid = UserInfo.getUserId();
		ext.oproject.EstimatedStartDate__c = date.today();

		ext.ProjectDetailNext();

		ext.sOrganizationName = 'Water Organization';
		ext.SearchOrganizations();
		ext.sSelectedOrganizationId = ext.lOrganizations[0].id;
		ext.SelectPrimary();

		ext.CreateProject();

		pse__Proj__c oProject = [select id, pse__Opportunity__c from pse__Proj__c];

		system.assertNotEquals(oProject.pse__Opportunity__c, null);		

		opportunity checkOpp = [select id, name from opportunity];

		system.assertEquals(checkOpp.name, ext.oProject.name);	

	}	

	// Test the selection of a searched Site with Opp + creation of project
	@isTest
	static void OppSelect()
	{

		initializeSites();


		// Create standard controller for a new project and pass to the ext. Start the real test.
		ApexPages.StandardController sc = new ApexPages.StandardController(new pse__Proj__c());
		ECO_ProjectSetupController ext = new ECO_ProjectSetupController(sc);

		ext.oSite.Account__r.name = 'test';
		ext.SearchSites();
		system.assertEquals(ext.lstSitesSearchResults.size(), 1); 

		// Select Target Site
		ext.idSiteID = ext.lstSitesSearchResults[0].id;
		ext.SelectSite();

		system.assertEquals(ext.lstSites.size(), 1); 
		system.assertEquals(ext.lstSites[0].booIsPrimaryEnd, true); 
		system.assertEquals(ext.lstSites[0].booIsBilling, true); 
		system.assertEquals(ext.lstSites[0].booIsEnd, true); 		
		system.assertEquals(ext.lstSites[0].booIsDefaultTopTask, true);
		system.assertEquals(ext.lstSites[0].oSite.City__c, 'Toronto');
		system.assertEquals(ext.lstSites[0].oSite.Country__c, 'Canada');
		system.assertEquals(ext.lstSites[0].oSite.State__c, 'Ontario');

		system.assertEquals(ext.lstSearchOpportunities.size(), 1); 

		// Select available opportunity
		ext.sSelectedOpportunityId = ext.lstSearchOpportunities[0].id;

		// Check to see if the project is populated with the opportunity id
		ext.SelectOpportunity();
		system.assertEquals(ext.oProject.pse__Opportunity__c, ext.lstSearchOpportunities[0].id);

		ext.oProject.name = 'test project';
		ext.oProject.EstimatedContractValue__c = 1;
		ext.oProject.ownerid = UserInfo.getUserId();
		ext.oproject.EstimatedStartDate__c = date.today();

		ext.ProjectDetailNext();

		ext.sOrganizationName = 'Water Organization';
		ext.SearchOrganizations();
		ext.sSelectedOrganizationId = ext.lOrganizations[0].id;
		ext.SelectPrimary();

		ext.CreateProject();

		pse__Proj__c oProject = [select id, pse__Opportunity__c from pse__Proj__c];

		system.assertEquals(oProject.pse__Opportunity__c, ext.lstSearchOpportunities[0].id);

	}	


}