src/objects/AECOM_Primary_Department__c.object
<CustomObject>
    <description>AECOM Primary Department</description>
    <fields>
        <fullName>Business_Line_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Line\SBU</label>
        <referenceTo>Business_Line__c</referenceTo>
        <relationshipLabel>AECOM  Departments</relationshipLabel>
        <relationshipName>AECOM_Departments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_District__c</fullName>
        <description>Lead District</description>
        <label>Lead District</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <description>Subset of Group used for enterprise-wide reporting</description>
        <inlineHelpText>Subset of Group used for enterprise-wide reporting</inlineHelpText>
        <label>Operating Group</label>
        <picklist>
            <picklistValues>
                <fullName>CS-BC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CS-EIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCS AME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCS APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCS EMEA+I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>AECOM Department</label>
    <nameField>
        <label>AECOM Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AECOM  Departments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Business_Line__c.object
<CustomObject>
    <description>Use by taxonomy to supply the Business Line.</description>
    <label>Business Line</label>
    <nameField>
        <label>Business Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CFM_Survey_Case_Hierarchy__c.object
<CustomObject>
    <description>CFM: Identifies based on certain attributes the Survey Case Follow-up Owner, Escalation Owner, and Client Care owner</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Line</label>
        <referenceTo>Business_Line__c</referenceTo>
        <relationshipName>Survey_Case_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Default_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if this is the default survey case rule for the system.</inlineHelpText>
        <label>Is Default Rule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_District__c</fullName>
        <label>Lead District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <label>Operating Group</label>
        <picklist>
            <picklistValues>
                <fullName>CS-BC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CS-EIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCS AME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCS APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCS EMEA+I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Step_1_Email__c</fullName>
        <description>This is the e-mail template that will be sent for this step.</description>
        <inlineHelpText>Email Template Unique Name for email sent for Step 1</inlineHelpText>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Survey Case Hierarchy</label>
    <nameField>
        <displayFormat>SCH-{0000}</displayFormat>
        <label>Survey Case Hierarchy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Case Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <description>The AECOM business line(s) involved in the project work. Multiple business lines can be selected, if appropriate. Can be edited using replace after the conversion.</description>
        <inlineHelpText>The AECOM business line(s) involved in the project work. Multiple business lines can be selected, if appropriate.</inlineHelpText>
        <label>Business Line</label>
        <picklist>
            <picklistValues>
                <fullName>Architecture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DP&amp;E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mining and Metals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning, Design and Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>OracleDepartment__c</fullName>
        <description>From Oracle Feed</description>
        <inlineHelpText>From Oracle Feed</inlineHelpText>
        <label>Oracle Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CFM_SurveyCaseHierarchy.cls
public class CFM_SurveyCaseHierarchy extends CFM_BaseModel {

	public static Finder find = new Finder('CFM_Survey_Case_Hierarchy__c');

	public static final String DEFAULT_KEY = 'DEFAULT';
 
	public CFM_Survey_Case_Hierarchy__c obj { get { return (CFM_Survey_Case_Hierarchy__c)mObj; } }

	public CFM_SurveyCaseHierarchy(CFM_Survey_Case_Hierarchy__c caseHierarchy) {
		super(caseHierarchy);
	}

	public String getKey() {
		String key = obj.Operating_Group__c + '|';
		if (obj.Lead_District__c != null) key += obj.Lead_District__c;
		key += '|';
		if (obj.Business_Line__c != null) key += obj.Business_Line__c;
		return key;
	}

	public String getStep1EmailTemplate() {
		return obj.Step_1_Email__c;
	}

	public static CFM_SurveyCaseHierarchy findRoutingForProject(Map<String, CFM_SurveyCaseHierarchy> routings, Map<String, AECOM_Primary_Department__c> departments, Project__c project) {

		if (project.OracleDepartment__c != null && departments.containsKey(project.OracleDepartment__c)) {
			AECOM_Primary_Department__c department = departments.get(project.OracleDepartment__c);
			String operatingGroup = department.Operating_Group__c;
			String leadDistrict = department.Lead_District__c;
			String businessLine = department.Business_Line_Lookup__c;

			String olb = operatingGroup + '|' + leadDistrict + '|' + businessLine;
			String ol = operatingGroup + '|' + leadDistrict + '|';
			String o = operatingGroup + '||';

			List<String> keyCombinations = new List<String> { olb, ol, o};

			for (String keyCombination : keyCombinations) {
				if (routings.containsKey(keyCombination)) {
					return routings.get(keyCombination);
				}
			}
		}
		

		if (routings.containsKey(DEFAULT_KEY)) {
			return routings.get(DEFAULT_KEY);
		}


		return null;
	}

	public static List<CFM_SurveyCaseHierarchy> decorate(List<CFM_Survey_Case_Hierarchy__c> sList) {
		List<CFM_SurveyCaseHierarchy> mList = new List<CFM_SurveyCaseHierarchy>();
		for (CFM_Survey_Case_Hierarchy__c sRow : sList) mList.add(new CFM_SurveyCaseHierarchy(sRow));
		return mList;
	}


	public class Finder extends CFM_BaseFinder {
		public Finder(String sObjectName) {
			super(sObjectName); 
		}


		public Map<String, CFM_SurveyCaseHierarchy> forDepartments(List<AECOM_Primary_Department__c> departments) {
			Map<String, CFM_SurveyCaseHierarchy> keyToHierarchyMap = new Map<String, CFM_SurveyCaseHierarchy>();
			
			Set<String> operatingGroups = new Set<String>();
			Set<String> leadDistricts = new Set<String>();
			Set<String> businessLines = new Set<String>();

			for (AECOM_Primary_Department__c department : departments) {
				if (department.Operating_Group__c != null) operatingGroups.add(department.Operating_Group__c);
				if (department.Lead_District__c != null) leadDistricts.add(department.Lead_District__c);
				if (department.Business_Line_Lookup__c != null) businessLines.add(department.Business_Line_Lookup__c);
			}

			List<CFM_SurveyCaseHierarchy> searchResults = CFM_SurveyCaseHierarchy.decorate(Database.query(getSelect() + ' WHERE Is_Default_Rule__c = true OR Operating_Group__c in :operatingGroups OR Lead_District__c in :leadDistricts OR Business_Line__c in :businessLines'));

			for (CFM_SurveyCaseHierarchy row : searchResults) {
				if (row.obj.Is_Default_Rule__c) {
					keyToHierarchyMap.put(CFM_SurveyCaseHierarchy.DEFAULT_KEY, row);
				}
				else {
					keyToHierarchyMap.put(row.getKey(), row);
				}
			}

			return keyToHierarchyMap;
		}
	}
}