src/objects/AECOM_Primary_Department__c.object
<CustomObject>
    <description>AECOM Primary Department</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>AECOM Department</label>
    <nameField>
        <label>AECOM Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AECOM  Departments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contract_Review__c.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <formula>Country__r.Country_Code__c</formula>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Country where the project is managed.</inlineHelpText>
        <label>Country</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Country not available for selection</errorMessage>
            <filterItems>
                <field>Country__c.Country_Code__c</field>
                <operation>equals</operation>
                <value>CA,US,AU,NZ,BR,VE,MX,SP,ES,RO,GR,CZ,HU,AL,BA,BG,HR,CS,MK,ME,SI,IT,FR,PL,DE,AT,CH,BE,NL,LU,EE,LV,LT,DK,NO,SE,RU,AZ,TR,KZ,GE,UA,GB,IE,ZA,AE,BH,OM,IQ,QW,QA,IN</value>
            </filterItems>
            <filterItems>
                <field>Country__c.Country_Code__c</field>
                <operation>equals</operation>
                <value>DZ,AO,SH,KW,BW,SA,BI,CM,CV,CF,TD,KM,CG,AR,EG,GQ,ER,ET,GA,GM,GH,GW,GN,CI,KE,LS,LR,LY,MG,MW,ML,MR,MU,YT,MA,MZ,NA,NE,NG,ST,RE,RW,ST,SN,SC,SL,SO,SH,SD,SZ,TZ,TN,UG,CD,ZM,TZ,ZW,SS,CD,CN,TW,SG,ID,MY,TH,PH,MM,VN,LK</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contract Reviews</relationshipLabel>
        <relationshipName>Contract_Reviews</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Required__c</fullName>
        <defaultValue>Today() + 7</defaultValue>
        <description>Allow at least 7 days for your request to be reviewed. More time is needed should DOA approvals be required</description>
        <inlineHelpText>Allow at least 7 days for your request to be reviewed. More time is needed should DOA approvals be required</inlineHelpText>
        <label>Date Review is Required</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_GNG__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If an opportunity exists within Salesforce, please identify it and the following pages will be pre-filled for you.  If there is no Salesforce Opportunity created please leave blank.</inlineHelpText>
        <label>Opportunity (Go/No Go)</label>
        <referenceTo>Go_No_Go_Conversation__c</referenceTo>
        <relationshipLabel>Contract Reviews</relationshipLabel>
        <relationshipName>Contract_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <formula>Opportunity_GNG__r.Opportunity_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The real opportunity, used for referancing</description>
        <inlineHelpText>Only accessible by full CRM users</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contract Reviews</relationshipLabel>
        <relationshipName>Contract_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Review Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Contract Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Country and Region</description>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Go_No_Go_Conversation__c.object
<CustomObject>
    <description>Discussions and decisions related to the Go / No-Go process</description>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <formula>Opportunity__r.Name</formula>
        <inlineHelpText>Opportunity Name visible to non-CRM users</inlineHelpText>
        <label>Opportunity Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Opportunity for which the Go - No-Go decision is being made</description>
        <inlineHelpText>Opportunity for which the Go - No-Go decision is being made</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Go/No Go Conversation</relationshipLabel>
        <relationshipName>G_NG_Conversations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Go/No Go Conversation</label>
    <nameField>
        <displayFormat>GNG-{0000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go/No Go Conversation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_Department__c.object
<CustomObject>
    <description>Related list used by Opportunities to support multiple department &amp; percent.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Departments</relationshipLabel>
        <relationshipName>Opportunity_Departments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Department</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Legal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Legal Member</description>
        <inlineHelpText>Legal Member - currently used in Middle East on Approval process for go/no go</inlineHelpText>
        <label>Legal</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ContractReviewTest.cls
@isTest
public with sharing class ContractReviewTest {

  @isTest 
  private static void TestContractReviewTrigger() 
    {
        // ctry = [SELECT Id, name FROM Country__c WHERE name = 'Australia'];
        Country__c ctry = new Country__c(Name='Someplace', Country_Code__c='SP');
        insert ctry;
        
        Opportunity mockOpp = TestCoverageSmokeMocks.mockOpp(true);

        AECOM_Primary_Department__c dept = [select id from AECOM_Primary_Department__c limit 1];

        List<Opportunity_Department__c> mockOppDepList = TestCoverageSmokeMocks.mockOppDepList(true, 1, mockOpp, dept,null, null );

        Go_No_Go_Conversation__c a = new Go_No_Go_Conversation__c();
        a.Opportunity__c = mockOpp.id;
        insert a;   

        Go_No_Go_Conversation__c gng;

        gng = [SELECT id,Opportunity__c FROM Go_No_Go_Conversation__c limit 1 ];
     

        // Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];

        Contract_Review__c cr = new Contract_Review__c();
        cr.Country__c = ctry.Id;
        cr.Date_Required__c = Date.today();
        cr.Opportunity_GNG__c = gng.Id; 

        insert cr; 

        System.assert(cr.Opportunity_GNG__c != null);

        cr.Opportunity_GNG__c = null;

        update cr;

        System.assert(cr.Opportunity_GNG__c == null);
        
    }    
  
     
    @isTest 
    private static void TestContractReviewSharing() 
    {
      User user = [SELECT id, Legal__c  FROM user WHERE profile.UserLicense.Name = 'Force.com - App Subscription' and Legal__c = false and isactive = true limit 1 ];


      Country__c ctry = new Country__c(Name='Someplace', Country_Code__c='SP');
      insert ctry;


      Contract_Review__c cr = new Contract_Review__c();
      cr.Country__c = ctry.Id;
      cr.Date_Required__c = Date.today(); 

      insert cr; 

      boolean wassuccess = ContractReviewSharing.manualShareRead(cr.id,  user.id,  'Read');

      System.assert(wassuccess);
        
    }    
    
    
    
    @isTest 
    private static void TestLegalFlagTrigger() 
    {
    	
      StaticHelper.excludeIt = false;
        
        
        // Test a 'Salesforce' licence user 
      User user = [SELECT id, Legal__c  FROM user WHERE profile.UserLicense.Name = 'salesforce' and Legal__c = false and isactive = true limit 1 ];
      user.Legal__c = true;  
      update user ;

      Integer i = [SELECT COUNT()  From PermissionSetAssignment p
      where p.PermissionSet.Name = 'Contract_Reviewer_SF' and p.AssigneeId  = :user.Id];
      //There should be a Contract_Reviewer_SF PermissionSet for the user
      System.assert(i == 1);

      user.Legal__c = false; 
      update user ;

      i = [SELECT COUNT()  From PermissionSetAssignment p
      where p.PermissionSet.Name = 'Contract_Reviewer_SF' and p.AssigneeId  = :user.Id];
      //There should NOT be a Contract_Reviewer_SF PermissionSet for the user
      System.assert(i == 0);

      //Test a 'Force.com - App Subscription' licence user 
      user = [SELECT id, Legal__c  FROM user WHERE profile.UserLicense.Name = 'Force.com - App Subscription' and Legal__c = false and isactive = true limit 1 ];
      user.Legal__c = true; 
      update user ;

      i = [SELECT COUNT()  From PermissionSetAssignment p
      where p.PermissionSet.Name = 'Contract_Reviewer' and p.AssigneeId  = :user.Id];

      //There should be a Contract_Reviewer_SF PermissionSet for the user
      System.assert(i == 1);
      user.Legal__c = false; 
      update user ;

      i = [SELECT COUNT()  From PermissionSetAssignment p
      where p.PermissionSet.Name = 'Contract_Reviewer' and p.AssigneeId  = :user.Id];
      //There should NOT be a Contract_Reviewer_SF PermissionSet for the user
      System.assert(i == 0);

    }
    
    
    @isTest 
    private static void TestInvocableMethodContractReviewAssign() 
    {
  
      Country__c ctry = new Country__c(Name='Someplace', Country_Code__c='SP');
      insert ctry;

      Opportunity mockOpp = TestCoverageSmokeMocks.mockOpp(true);

      AECOM_Primary_Department__c dept = [select id from AECOM_Primary_Department__c limit 1];

      List<Opportunity_Department__c> mockOppDepList = TestCoverageSmokeMocks.mockOppDepList(true, 1, mockOpp, dept,null, null );

      Go_No_Go_Conversation__c a = new Go_No_Go_Conversation__c();
      a.Opportunity__c = mockOpp.id;
      insert a;   

      Go_No_Go_Conversation__c gng;

      gng = [SELECT id,Opportunity__c FROM Go_No_Go_Conversation__c limit 1 ];

          
      Contract_Review__c cr = new Contract_Review__c();
      cr.Country__c = ctry.Id;
      cr.Date_Required__c = Date.today();
      cr.Opportunity_GNG__c = gng.Id; 
        		
      insert cr; 

      ContractReviewVariable crv = new ContractReviewVariable();
      crv.crId = cr.Id;
      crv.queueName = 'Legal ANZ VSA';

      List<ContractReviewVariable> crvl = new List<ContractReviewVariable>{};

      crvl.add(crv);

      ContractReview.Assign(crvl);
		
		
    }
    
    
    @isTest
    public static  void testBatchUpdateOpportunityNameSearchable() {
    

      Country__c ctry = new Country__c(Name='Someplace', Country_Code__c='SP');
      insert ctry;
      
      Opportunity mockOpp = TestCoverageSmokeMocks.mockOpp(true);

      AECOM_Primary_Department__c dept = [select id from AECOM_Primary_Department__c limit 1];

      List<Opportunity_Department__c> mockOppDepList = TestCoverageSmokeMocks.mockOppDepList(true, 1, mockOpp, dept,null, null );

      Go_No_Go_Conversation__c a = new Go_No_Go_Conversation__c();
      a.Opportunity__c = mockOpp.id;
      insert a;   


  		Test.StartTest();   
  		BatchUpdateOpportunityNameSearchable batchprocess = new BatchUpdateOpportunityNameSearchable();
  		ID batchprocessid = Database.executeBatch(batchprocess);
  		
  		Test.StopTest();    		 	
  		Go_No_Go_Conversation__c gng = [select Opportunity_Name__c, Opportunity_Name_Searchable__c 
  		    		 						from Go_No_Go_Conversation__c limit 1];						 						
  		System.assert(gng.Opportunity_Name__c == gng.Opportunity_Name_Searchable__c);
		
   }
   
   
   //a once off trigger
   @isTest
    public static  void testBatchUpdateUserCRSPermissionSets() {

      User user = TestCoverageSmokeMocks.mockUser(true);

  		Test.StartTest();   
  		
      BatchUpdateUserCRSPermissionSets batchprocess = new BatchUpdateUserCRSPermissionSets();
  		ID batchprocessid = Database.executeBatch(batchprocess);
  		
  		Test.StopTest();   

      integer cnt = [select count() from PermissionSetAssignment where PermissionSet.Name like '%Contract_Reviewer%' and AssigneeId = :user.Id];

      System.assert(cnt == 1, cnt);
 
		
   }

    
}