src/objects/AECOM_Delegation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom setting for delegation audit. When a new record gets created or approver is changed for an existing record, a trigger looks to this custom setting and creates audit records in delegation object.</description>
    <fields>
        <fullName>Escalation__c</fullName>
        <label>Escalation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <description>API Name of the field that is being tracked</description>
        <label>Field API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Role assigned to the user</description>
        <label>Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Eco Delegation</label>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <fields>
        <fullName>ChangeManagerIsChanged__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Change Manager Is Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PnLManager__c</fullName>
        <formula>Project__r.PnLManager__c</formula>
        <label>PnL Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>AgreementsProject</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Prime</fullName>
        <active>true</active>
        <description>Any type of single use contract for general consulting services between AECOM and the client.  This type of agreement will be interfaced to Oracle to provide the contract value and approved funding for the project.</description>
        <label>Prime</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ChangeManager__c.object
<CustomObject>
    <fields>
        <fullName>ProjectApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ChangeManagerProjectApprover</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectLongName__c</fullName>
        <formula>Project__r.ProjectLongName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Long Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Change Requests</relationshipLabel>
        <relationshipName>ChangeManager</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change</label>
    <nameField>
        <displayFormat>CM-{0}</displayFormat>
        <label>Change Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>If this person moves to another account: (a) change this field to &quot;No Longer with Client,&quot; (b) enter a note in the &quot;Need to Know&quot; field below, and (c) create a new Contact record under the new account.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No longer with client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the Contact to the User object.  This is for the representation of Employees.  Specifically, this is for the Shared Services Case Management.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Is_Resource__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resource</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Delegate__c.object
<CustomObject>
    <description>This object stores the delegate records.</description>
    <fields>
        <fullName>Agreement_Amount_estimated__c</fullName>
        <label>Agreement Amount (estimated) &gt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Backlog_Value__c</fullName>
        <label>Backlog Value &gt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Backlog_Value_lt__c</fullName>
        <label>Backlog Value &lt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Delegate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Delegated to contact. Contact to whom a role has been delegated.</description>
        <label>Delegate</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Is_Resource__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Delegates</relationshipLabel>
        <relationshipName>Delegates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegator__c</fullName>
        <description>The contact who delegates to another contact</description>
        <label>Delegator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Delegates</relationshipLabel>
        <relationshipName>Delegates1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Key_Member_Role__c</fullName>
        <description>The role for which delegation is done</description>
        <label>Key Member Role</label>
        <picklist>
            <picklistValues>
                <fullName>Project Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Accountant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Net_Margin_Value__c</fullName>
        <label>Project Approved Net Margin (Value) &gt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Net_Margin_Value_lt__c</fullName>
        <label>Project Approved Net Margin (Value) &lt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Net_Margin_age_of_NSR__c</fullName>
        <label>Project Approved Net Margin (% of NSR) &gt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Project_Net_Margin_age_of_NSR_lt__c</fullName>
        <label>Project Approved Net Margin (% of NSR) &lt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Project_Revenue_Budget__c</fullName>
        <label>Project Approved Revenue Budget &gt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Revenue_Budget_lt__c</fullName>
        <label>Project Approved Revenue Budget &lt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Review_Category_C_4_Bypass__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Review Category C-4 Bypass</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Review_Category_C_4__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Project Review Category C-4</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date at which the delegation would begin</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Value_change_in_Forecast_Net_Margin__c</fullName>
        <label>Value change in Forecast Net Margin &gt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value_change_in_Forecast_Net_Margin_lt__c</fullName>
        <label>Value change in Forecast Net Margin &lt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>age_Change_in_Forecast_Net_Margin__c</fullName>
        <label>%age Change in Forecast Net Margin &gt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>age_Change_in_Forecast_Net_Margin_lt__c</fullName>
        <label>%age Change in Forecast Net Margin &lt;</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Delegate</label>
    <nameField>
        <displayFormat>DLGT-{0000000000}</displayFormat>
        <label>Delegate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegates</pluralLabel>
    <recordTypes>
        <fullName>Vacation</fullName>
        <active>true</active>
        <label>Vacation</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Delegation__c.object
<CustomObject>
    <description>This object is for Audit purpose of all the delegations. Each time a record is submitted for approval to a delegated user, this object records that event.</description>
    <fields>
        <fullName>Delegate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Related Delegate to which record is submitted for approval</description>
        <label>Delegate Rule Reference</label>
        <referenceTo>Delegate__c</referenceTo>
        <relationshipLabel>Delegations Audit</relationshipLabel>
        <relationshipName>Delegations_Audit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <description>It captures the value of the Process, the record is submitted for approval</description>
        <label>Process</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Delegations</relationshipLabel>
        <relationshipName>Delegations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Delegation</label>
    <nameField>
        <displayFormat>DLGN-{0000000000}</displayFormat>
        <label>Delegation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/POHeader__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>PurchaseOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PurchaseOrdersProjectManager</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>POHeadersProject</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_Service_Delegation_Test.cls
@isTest
private class ECO_Service_Delegation_Test
{
	Static List<User> users;
	Static List<Contact> contacts;

	@isTest
	static void testvacationadmin(){

		Test.startTest();
		ECO_Utils_Testing.createTestDataForProjectSync(3, 3);
		Test.stopTest();

		setupTestData();
		
		AECOM_Delegation__c ad = new AECOM_Delegation__c();
		ad.name = 'EcoPurchase Order';
		ad.Escalation__c = 'PNL';
		ad.Field_API_Name__c = 'ProjectManager__c';
		ad.Object_Name__c = 'POHeader__c';
		ad.Process__c = 'EcoPurchase Order';
		ad.Role__c = 'Project Manager';

		insert ad;

		Id recordTypeId = ECO_Utils_sObject.getRecordTypeId(Delegate__c.sObjectType, 'Vacation');
		Id recordTypeId2 = ECO_Utils_sObject.getRecordTypeId(Delegate__c.sObjectType, 'Key Roles');
		
		Delegate__c delegate = new Delegate__c();
		delegate.Delegate__c = contacts[1].Id;
		delegate.RecordTypeId = recordTypeId;
		delegate.Delegator__c = contacts[2].Id;
		delegate.Start_Date__c = Date.today();

		Delegate__c delegate2 = new Delegate__c(
												Key_Member_Role__c = 'Project Manager', 
												age_Change_in_Forecast_Net_Margin_lt__c = 1, 
												age_Change_in_Forecast_Net_Margin__c = 5,
												Agreement_Amount_estimated__c = 5000,
												Backlog_Value_lt__c = 1000,
												Backlog_Value__c = 5000,
												Project_Net_Margin_age_of_NSR_lt__c = 1,
												Project_Net_Margin_age_of_NSR__c = 5,
												Project_Net_Margin_Value_lt__c = 1000,
												Project_Net_Margin_Value__c = 5000,
												Project_Revenue_Budget_lt__c = 1000,
												Project_Revenue_Budget__c = 5000,
												Value_change_in_Forecast_Net_Margin_lt__c = 1000,
												Value_change_in_Forecast_Net_Margin__c = 5000,
												Project_Review_Category_C_4_Bypass__c = true,
												Project_Review_Category_C_4__c = false
												);
		delegate2.Delegate__c = contacts[0].Id;
		delegate2.RecordTypeId = recordTypeId2;
		delegate2.Delegator__c = contacts[2].Id;



		list<Delegate__c> lstdelToInsert = new list<Delegate__c> ();
		lstdelToInsert.add(delegate);
		lstdelToInsert.add(delegate2);

		insert lstdelToInsert;



		pse__Proj__c testProject = [SELECT Id, Name FROM pse__Proj__c LIMIT 1];
		testProject.ProjectLongName__c = null;
		testProject.PnLManager__c = contacts[2].id;
		testProject.clAECOMProjectReviewCategory__c = 'C-4';
		update testProject;

		POHeader__c po = new POHeader__c();
		po.Project__c = testProject.id;
		po.ProjectManager__c = users[0].id;

		insert po;

		po = [select id, ProjectManager__c from POHeader__c];
		list<delegation__c> lstDelegations = [select id from delegation__c];

		system.assertEquals(po.ProjectManager__c, contacts[1].pse__Salesforce_User__c);
		system.assertEquals(lstDelegations.size(), 3);

		po.ProjectManager__c = users[0].id;
		ad.Escalation__c = 'FA';



		update ad;
		update po;
	}

	@isTest
	static void testChangeManagement(){

		Test.startTest();
		ECO_Utils_Testing.createTestDataForProjectSync(3, 3);
		Test.stopTest();

		setupTestData();
		
		AECOM_Delegation__c ad = new AECOM_Delegation__c();
		ad.name = 'EcoPurchase Order';
		ad.Escalation__c = 'PNL';
		ad.Field_API_Name__c = 'ProjectApprover__c';
		ad.Object_Name__c = 'ChangeManager__c';
		ad.Process__c = 'EcoPurchase Order';
		ad.Role__c = 'Project Manager';

		insert ad;

		Id recordTypeId = ECO_Utils_sObject.getRecordTypeId(Delegate__c.sObjectType, 'Vacation');
		Id recordTypeId2 = ECO_Utils_sObject.getRecordTypeId(Delegate__c.sObjectType, 'Key Roles');
		
		Delegate__c delegate = new Delegate__c();
		delegate.Delegate__c = contacts[1].Id;
		delegate.RecordTypeId = recordTypeId;
		delegate.Delegator__c = contacts[2].Id;
		delegate.Start_Date__c = Date.today();

		Delegate__c delegate2 = new Delegate__c(
												Key_Member_Role__c = 'Project Manager', 
												age_Change_in_Forecast_Net_Margin_lt__c = 1, 
												age_Change_in_Forecast_Net_Margin__c = 5,
												Agreement_Amount_estimated__c = 5000,
												Backlog_Value_lt__c = 1000,
												Backlog_Value__c = 5000,
												Project_Net_Margin_age_of_NSR_lt__c = 1,
												Project_Net_Margin_age_of_NSR__c = 5,
												Project_Net_Margin_Value_lt__c = 1000,
												Project_Net_Margin_Value__c = 5000,
												Project_Revenue_Budget_lt__c = 1000,
												Project_Revenue_Budget__c = 5000,
												Value_change_in_Forecast_Net_Margin_lt__c = 1000,
												Value_change_in_Forecast_Net_Margin__c = 5000,
												Project_Review_Category_C_4_Bypass__c = true,
												Project_Review_Category_C_4__c = false
												);
		delegate2.Delegate__c = contacts[0].Id;
		delegate2.RecordTypeId = recordTypeId2;
		delegate2.Delegator__c = contacts[2].Id;



		list<Delegate__c> lstdelToInsert = new list<Delegate__c> ();
		lstdelToInsert.add(delegate);
		lstdelToInsert.add(delegate2);

		insert lstdelToInsert;



		pse__Proj__c testProject = [SELECT Id, Name FROM pse__Proj__c LIMIT 1];
		testProject.ProjectLongName__c = null;
		testProject.PnLManager__c = contacts[2].id;
		testProject.clAECOMProjectReviewCategory__c = 'C-4';
		update testProject;

		Id agreementRecordTypeId = ECO_Utils_Meta.getRecordTypeId(Agreement__c.sObjectType, 'Prime');
		Agreement__c agreement = new Agreement__c(RecordTypeId = agreementRecordTypeId, Project__c = testProject.Id, ChangeManagerIsChanged__c = true);
		insert agreement;		

		Id changeManagerRecordTypeId = ECO_Utils_Meta.getRecordTypeId(ChangeManager__c.sObjectType, 'Internal Change');
		ChangeManager__c changeManager = new ChangeManager__c(Project__c = testProject.Id, RecordTypeId = changeManagerRecordTypeId, ProjectApprover__c = contacts[0].pse__Salesforce_User__c);
		insert changeManager;


	}

	static void setupTestData(){

		Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
		Id recordTypeId = ECO_Utils_sObject.getRecordTypeId(Contact.sObjectType, 'PSA Resource');

		Account testAccount = [select id from Account];

		users = new List<User>();
		users.add(ECO_Utils_Testing.createTestUser('Standard User'));
		users.add(ECO_Utils_Testing.createTestUser('Standard User'));
		users.add(ECO_Utils_Testing.createTestUser('Standard User'));
		insert users;

		contacts = new List<Contact>();
		contacts.add(new Contact(pse__Is_Resource__c = true, Status__c = 'Active', Email = users[0].Email, FirstName = users[0].FirstName, LastName = users[0].LastName, pse__Salesforce_User__c = users[0].Id, recordTypeId = recordTypeId, User__c = users[0].Id, OwnerId = users[0].Id));
		contacts.add(new Contact(pse__Is_Resource__c = true, Status__c = 'Active', Email = users[1].Email, FirstName = users[1].FirstName, LastName = users[1].LastName, pse__Salesforce_User__c = users[1].Id, recordTypeId = recordTypeId, User__c = users[1].Id, OwnerId = users[1].Id));
		contacts.add(new Contact(pse__Is_Resource__c = true, Status__c = 'Active', Email = users[2].Email, FirstName = users[2].FirstName, LastName = users[2].LastName, pse__Salesforce_User__c = users[2].Id, recordTypeId = recordTypeId, User__c = users[2].Id, OwnerId = users[2].Id));
		insert contacts;
	}
}