src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The prime client on the contract.</inlineHelpText>
        <label>Billing Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements (Billing Client)</relationshipLabel>
        <relationshipName>AgreementsEndClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Once executed, populate the current total confirmed agreement amount</description>
        <inlineHelpText>Once executed, populate the current total confirmed agreement amount</inlineHelpText>
        <label>Agreement Amount (Confirmed)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Provide a one or two sentence description of the contract.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BillRate__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Bill Rates</relationshipLabel>
        <relationshipName>BillRatesAgreement</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BillRateEnd__c</fullName>
        <label>BillRateEnd</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BillRatePeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill Rate Period</label>
        <referenceTo>BillRatePeriod__c</referenceTo>
        <relationshipLabel>Bill Rates</relationshipLabel>
        <relationshipName>BillRates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillRateStart__c</fullName>
        <label>BillRateStart</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BillRate__c</fullName>
        <label>Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LaborCategory__c</fullName>
        <label>Labor Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Bill Rate</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Bill Rate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BillRatePeriod__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Bill Rate Periods</relationshipLabel>
        <relationshipName>BillRatePeriods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillRateEnd__c</fullName>
        <label>BillRateEnd</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BillRateStart__c</fullName>
        <label>BillRateStart</label>
        <type>Date</type>
    </fields>
    <label>Bill Rate Period</label>
    <nameField>
        <displayFormat>BRP-{0000}</displayFormat>
        <label>BillRatePeriod Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Rate Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_BIllRateManagementTest.cls
@isTest
private class ECO_BIllRateManagementTest {

    static testMethod void controllerTest1() {
    	Account testAccount = new Account();
		testAccount.Name = 'test Account';
		insert testAccount;

		//create create source project 
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.Name = 'test project 1';
		testProject.pse__Account__c = testAccount.Id;
		testProject.pse__Project_Type__c = 'Customer Project';
		testProject.pse__Billing_Type__c = 'Fixed Price';
		testProject.CurrencyIsoCode = 'USD';
		testProject.pse__Is_Active__c = true;
		insert testProject;
		
		Agreement__c agreement = new Agreement__c();
		agreement.Account__c = testAccount.Id;
		agreement.Description__c = 'Test Agreement';
		agreement.CurrencyIsoCode = 'USD';
		agreement.Amount__c = 1000000;
		insert agreement;
		
		ApexPages.currentPage().getParameters().put('AgreementId',agreement.Id);
		ECO_BillRateManagement controller = new ECO_BillRateManagement();
		System.AssertEquals(0, controller.getLaborCategories().size());
		System.AssertEquals(0, controller.getPeriods().size());
		System.AssertNotEquals(null, controller.returnToAgreement());
		controller.createNewBillRatePeriod();
		controller.newBillRatePeriod.BillRateStart__c = Date.today();
		controller.newBillRatePeriod.BillRateEnd__c = Date.today().addDays(1);
		controller.saveNewBillRatePeriod();
		System.AssertEquals(1, [select Id from BillRatePeriod__c].size());
		controller.createNewBillRate();
		controller.newBillRate.LaborCategory__c = 'Test Category';
		controller.saveNewBillRate();
		System.AssertEquals(1, [select Id from BillRate__c].size());
		//System.AssertEquals(1, controller.getLaborCategories().size());
		controller.createNewBillRatePeriod();
		controller.newBillRatePeriod.BillRateStart__c = Date.today().addDays(5);
		controller.newBillRatePeriod.BillRateEnd__c = Date.today().addDays(10);
		controller.saveNewBillRatePeriod();
		System.AssertEquals(2, controller.getPeriods().size());
							
    }

    static testMethod void controllerTest2() {
    	Account testAccount = new Account();
		testAccount.Name = 'test Account';
		insert testAccount;

		//create create source project 
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.Name = 'test project 1';
		testProject.pse__Account__c = testAccount.Id;
		testProject.pse__Project_Type__c = 'Customer Project';
		testProject.pse__Billing_Type__c = 'Fixed Price';
		testProject.CurrencyIsoCode = 'USD';
		testProject.pse__Is_Active__c = true;
		insert testProject;
		
		Agreement__c agreement = new Agreement__c();
		agreement.Account__c = testAccount.Id;
		agreement.Description__c = 'Test Agreement';
		agreement.CurrencyIsoCode = 'USD';
		agreement.Amount__c = 1000000;
		insert agreement;
		
		BillRatePeriod__c billRatePeriod = new BillRatePeriod__c();
		billRatePeriod.BillRateStart__c = Date.today().addDays(-100);
		billRatePeriod.BillRateEnd__c = Date.today().addDays(-95);
		billRatePeriod.Agreement__c = agreement.Id;
		insert billRatePeriod;
		
		BillRate__c billRate = new BillRate__c();
		billRate.Agreement__c = agreement.Id;
		billRate.BillRatePeriod__c = billRatePeriod.Id;
		billRate.LaborCategory__c = 'Test 1';
		insert billRate;
		
		ApexPages.currentPage().getParameters().put('AgreementId',agreement.Id);
		ECO_BillRateManagement controller = new ECO_BillRateManagement();
		System.AssertEquals(1, controller.getLaborCategories().size());
		controller.createNewBillRatePeriod();
		controller.newBillRatePeriod.BillRateStart__c = Date.today();
		controller.newBillRatePeriod.BillRateEnd__c = Date.today().addDays(1);
		controller.saveNewBillRatePeriod();
		System.AssertEquals(2, [select Id from BillRatePeriod__c].size());
		controller.createNewBillRate();
		controller.newBillRate.LaborCategory__c = 'Test Category';
		controller.saveNewBillRate();
		System.AssertEquals(4, [select Id from BillRate__c].size());
		//System.AssertEquals(1, controller.getLaborCategories().size());
		controller.createNewBillRatePeriod();
		controller.newBillRatePeriod.BillRateStart__c = Date.today().addDays(5);
		controller.newBillRatePeriod.BillRateEnd__c = Date.today().addDays(10);
		controller.saveNewBillRatePeriod();
							
    }    
    
}