src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <fields>
        <fullName>AgreementNumber__c</fullName>
        <description>This is a unique identifier assigned to all Agreement Records in Ecosystem.  Use this reference for Contract Reviews.</description>
        <label>Contract Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Once executed, populate the current total confirmed agreement amount</description>
        <inlineHelpText>Once executed, populate the current total confirmed agreement amount</inlineHelpText>
        <label>Agreement Amount (Confirmed)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChangeManagerApprovedForSynch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Change Manager Approved For Synch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FundingCurrencyCode__c</fullName>
        <description>Select the currency of the agreement</description>
        <inlineHelpText>Select the currency of the agreement</inlineHelpText>
        <label>Agreement Currency</label>
        <picklist>
            <picklistValues>
                <fullName>AED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BGN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CZK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DJF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DKK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EGP</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsMSA__c</fullName>
        <formula>IF( RecordType.Name == &quot;Prime (MSA)&quot;, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is MSA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTaskOrder__c</fullName>
        <formula>IF( RecordType.Name == &quot;Prime Task Order&quot;, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Task Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MSAReference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Search and select the MSA that applies to the contract.  If no MSA, then leave blank</description>
        <inlineHelpText>Search and select the MSA that applies to the contract.  If no MSA, then leave blank</inlineHelpText>
        <label>MSA Reference</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Agreement__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Prime (MSA)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Agreements (MSA Reference)</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectAgreementRecordCount__c</fullName>
        <label>ProjectAgreementRecordCount</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>AgreementsProject</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SegApprovalStatus__c</fullName>
        <label>Segmentation Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotalTaskOrdersValue__c</fullName>
        <inlineHelpText>The sum of all Ecosystem task orders linked to the master agreement (automatic calculation).</inlineHelpText>
        <label>Total Task Orders Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>segAdherence__c</fullName>
        <label>Adherence</label>
        <picklist>
            <picklistValues>
                <fullName>Y</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>segOptionDoesNotQualify__c</fullName>
        <label>Option Does Not Qualify</label>
        <picklist>
            <picklistValues>
                <fullName>Y</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectAgreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>ProjectAgreementsAgreement</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>ProjectAgreementsProject</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Agreement</label>
    <nameField>
        <displayFormat>PA-{0}</displayFormat>
        <label>Project Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_AgreementTriggerHandler.cls
public class ECO_AgreementTriggerHandler {
	
	public static void handleSegmentationApproval(map<Id, Agreement__c> oldAgreementMap, map<Id, Agreement__c> newAgreementMap)
	{
		if (!ECO_TriggerSettings.getIsTriggerEnabled('AGREEMENT_segmentationApproval')) {
			return;
		}
		
		map<Id, Agreement__c> msaAgreements = new map<Id, Agreement__c>();
		map<Id, Agreement__c> nonMSAAgreements = new map<Id, Agreement__c>();
		list<pse__Proj__c> updatedProjects =  new list<pse__Proj__c>();
		
		for(Agreement__c agreement:newAgreementMap.values())
		{
			if(oldAgreementMap.get(agreement.Id).SegApprovalStatus__c != 'Approved' && agreement.SegApprovalStatus__c == 'Approved')
			{
				if(agreement.IsMSA__c)
					msaAgreements.put(agreement.Id, agreement);	
				else
					nonMSAAgreements.put(agreement.Id, agreement);
			}
		}
		
		if(msaAgreements.values().size() > 0)
		{
			map<Id, list<Agreement__c>> msaTaskOrderMap = new map<Id, list<Agreement__c>>();
			list<Agreement__c> taskOrders = [select Id, MSAReference__c from Agreement__c where MSAReference__c in :msaAgreements.keyset()];
			for(Agreement__c taskOrder:taskOrders)
			{
				if(msaTaskOrderMap.get(taskOrder.MSAReference__c) == null)
					msaTaskOrderMap.put(taskOrder.MSAReference__c, new list<Agreement__c>());
				msaTaskOrderMap.get(taskOrder.MSAReference__c).add(taskOrder);
			}
			
			map<Id, list<Id>> agreementProjectIdMap = new map<Id, list<Id>>();
			set<Id> projectIds = new set<Id>();		
			for(ProjectAgreement__c projectAgreement: [select Id, Project__c, Agreement__c from ProjectAgreement__c where Agreement__c in :taskOrders])
			{
				projectIds.add(projectAgreement.Project__c);
				if(agreementProjectIdMap.get(projectAgreement.Agreement__c) == null)
					agreementProjectIdMap.put(projectAgreement.Agreement__c, new list<Id>());
				agreementProjectIdMap.get(projectAgreement.Agreement__c).add(projectAgreement.Project__c);
			}
			map<Id, pse__Proj__c> projectMap = new map<Id, pse__Proj__c>([select Id, isSegmented__c from pse__Proj__c where Id in :projectIds]);
			
			//final processing for the msa agreement
			pse__Proj__c updatedProject;
			for(Agreement__c msaAgreement:msaAgreements.values())
			{
				for(Agreement__c taskOrder:msaTaskOrderMap.get(msaAgreement.Id))
				{
					for(Id projectId:agreementProjectIdMap.get(taskOrder.Id))
					{
						updatedProject = projectMap.get(projectId);
						if(msaAgreement.segAdherence__c == 'Yes')
						{
							updatedProject.isSegmented__c = true;
							updatedProject.SegmentationStatus__c = 'Segmented';
						}
						else if(msaAgreement.segOptionDoesNotQualify__c == 'Yes')
						{
							updatedProject.isSegmented__c = true;
							updatedProject.SegmentationStatus__c = 'Segmented for Mangement Purposes';
						}
						else
						{
							updatedProject.isSegmented__c = false;
							updatedProject.SegmentationStatus__c = 'Not Segmented';
						}
						updatedProjects.add(updatedProject);											
					}
				}				
			}
		}
		else if(nonMSAAgreements.size() > 0)
		{
			map<Id, list<Id>> agreementProjectIdMap = new map<Id, list<Id>>();
			set<Id> projectIds = new set<Id>();		
			
			for(ProjectAgreement__c projectAgreement:[select Id, Project__c, Agreement__c from ProjectAgreement__c where Agreement__c in :nonMSAAgreements.keyset()])
			{
				projectIds.add(projectAgreement.Project__c);
				if(agreementProjectIdMap.get(projectAgreement.Agreement__c) == null)
					agreementProjectIdMap.put(projectAgreement.Agreement__c, new list<Id>());
				agreementProjectIdMap.get(projectAgreement.Agreement__c).add(projectAgreement.Project__c);				
			}
			map<Id, pse__Proj__c> projectMap = new map<Id, pse__Proj__c>([select Id, isSegmented__c from pse__Proj__c where Id in :projectIds]);

			//final processing for the msa agreement
			pse__Proj__c updatedProject;
			for(Agreement__c agreement:nonMSAAgreements.values())
			{
				for(Id projectId:agreementProjectIdMap.get(agreement.Id))
				{
					updatedProject = projectMap.get(projectId);
					if(agreement.segAdherence__c == 'Yes')
					{
						updatedProject.isSegmented__c = true;
						updatedProject.SegmentationStatus__c = 'Segmented';
					}
					else if(agreement.segOptionDoesNotQualify__c == 'Yes')
					{
						updatedProject.isSegmented__c = true;
						updatedProject.SegmentationStatus__c = 'Segmented for Mangement Purposes';						
					}
					else
					{
						updatedProject.isSegmented__c = false;
						updatedProject.SegmentationStatus__c = 'Not Segmented';
					}
					updatedProjects.add(updatedProject);											
				}
			}				
		}
		if(updatedProjects.size() > 0)
			update updatedProjects;		
	}
	
	public static void handleAgreementBeforeUpdate(map<Id, Agreement__c> oldAgreementMap, map<Id, Agreement__c> newAgreementMap)
	{
		if (!ECO_TriggerSettings.getIsTriggerEnabled('AGREEMENT_populateAgreementNumber')) {
			return;
		}
		
		list<Id> projectIds = new list<Id>();
		list<Agreement__c> agreementsWithNoProjectNumber = new list<Agreement__c>();
		for(Agreement__c agreement:newAgreementMap.values())
		{		
			if(agreement.ChangeManagerApprovedForSynch__c == true && oldAgreementMap.get(agreement.Id).ChangeManagerApprovedForSynch__c == false)
			{
				if(agreement.AgreementNumber__c == null)
				{
					projectIds.add(agreement.Project__c);
					agreementsWithNoProjectNumber.add(agreement);
				}
			}	
		}
		
		if(!agreementsWithNoProjectNumber.isEmpty())
		{
			map<Id, pse__Proj__c> projectMap = new map<Id, pse__Proj__c>([select Id, OracleProjectNumber__c from pse__Proj__c where Id in :projectIds]);
			for(Agreement__c agreement:agreementsWithNoProjectNumber)
			{
				if(projectMap.get(agreement.Project__c).OracleProjectNumber__c == null)
				{
					agreement.addError('This agreement is associated to Project that does not have an Oracle Project Number.  Please get an Oracle Project Number before proceeding with Synch!');
				}
				else
				{
					agreement.AgreementNumber__c = projectMap.get(agreement.Project__c).OracleProjectNumber__c + '-' + String.ValueOf(agreement.ProjectAgreementRecordCount__c);
				}
			}	
		}					
	}
	
	public static void calculateTaskOrderValueForMSA(list<Agreement__c> agreements)
	{
		if (!ECO_TriggerSettings.getIsTriggerEnabled('AGREEMENT_CalcMSAValue')) {
			return;
		}
		
		set<Id> msaAgreementIds = new set<Id>();
		
		for(Agreement__c agreement:agreements)
		{
			if(agreement.IsTaskOrder__c && agreement.MSAReference__c != null)
				msaAgreementIds.add(agreement.MSAReference__c);				
		}
		
		if(msaAgreementIds.size() > 0)
		{		
			map<Id, list<Agreement__c>> msaTaskOrderMap = new map<Id, list<Agreement__c>>();
			for(Agreement__c taskOrder:[select Id, Amount__c, MSAReference__c, FundingCurrencyCode__c from Agreement__c where MSAReference__c in :msaAgreementIds and IsTaskOrder__c = true])
			{
				if(msaTaskOrderMap.get(taskOrder.MSAReference__c) == null)
					msaTaskOrderMap.put(taskOrder.MSAReference__c, new list<Agreement__c>());
				msaTaskOrderMap.get(taskOrder.MSAReference__c).add(taskOrder);		
			}

			Decimal totalMSAValue = 0;
			list<Agreement__c> msaAgreements = [select Id, FundingCurrencyCode__c, TotalTaskOrdersValue__c from Agreement__c where Id in :msaAgreementIds];
			for(Agreement__c msaAgreement:msaAgreements)
			{
				for(Agreement__c taskOrder:msaTaskOrderMap.get(msaAgreement.Id))
				{
					if(msaAgreement.FundingCurrencyCode__c != taskOrder.FundingCurrencyCode__c)
						totalMSAValue += taskOrder.Amount__c * ECO_Service_ExchangeRate.getExchangeRate(taskOrder.FundingCurrencyCode__c, msaAgreement.FundingCurrencyCode__c, Date.today());
					else
						totalMSAValue += taskOrder.Amount__c;
				}
				msaAgreement.TotalTaskOrdersValue__c =	totalMSAValue;	
			}
			if(msaAgreements.size() > 0)
				update msaAgreements;
		} 		
	}
}
//					agreement.addError('This agreement is associated to Project that does not have an Oracle Project Number.  Please get an Oracle Project Number before proceeding with Synch');