src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Approved_Sub__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipName>Approved_Subs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Approved or Preferred Subs/Vendors</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Approved Sub Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approved or Preferred Subs/Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_ApprovedSubController.cls
public class ECO_ApprovedSubController {
	
	public Approved_Sub__c approvedSub {get; set;}

	public ECO_ApprovedSubController(ApexPages.standardController controller)
	{
		approvedSub = (Approved_Sub__c)controller.getRecord();	
	}
	
	public void init()
	{
		if(Apexpages.currentPage().getParameters().get('Agreement__c') != null)
		{
			approvedSub.Agreement__c = Apexpages.currentPage().getParameters().get('Agreement__c'); 		
		}
	}
	
	public PageReference save()
	{
		insert approvedSub;
		
		PageReference pageRef = new PageReference('/' + approvedSub.Agreement__c);
		return pageRef;
	}
	
}