src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The prime client on the contract.</inlineHelpText>
        <label>Billing Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements (Billing Client)</relationshipLabel>
        <relationshipName>AgreementsEndClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentTerms__c</fullName>
        <label>Payment Terms</label>
        <picklist>
            <picklistValues>
                <fullName>IMMEDIATE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>35 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>38 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>45 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>75 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30 NET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20th Next Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pay on Receipt</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>AgreementsProject</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VendorName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Name</label>
        <referenceTo>VendorSub__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>AgreementsVendorName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VendorSite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>VendorSite__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>VendorSite__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>Any other contract\agreement type that does not meet the contract types described herein (e.g., Confidentiality Agreement, Non-Disclosure Agreement, Memorandum of Understanding, Teaming etc).</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>OracleContactID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Contact ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Record Type for External Vendor Contact</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ECO_IntegrationEndpoints__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>rest endpoint used with oracle integrations</description>
    <fields>
        <fullName>EndPointUrl__c</fullName>
        <label>EndPoint Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ECO_IntegrationEndpoints</label>
</CustomObject>

src/objects/POHeader__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>PurchaseOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CancelFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancel Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OraclePurchaseOrderId__c</fullName>
        <description>Oracle Id for purchase order obtained after initial sync with oracle</description>
        <externalId>true</externalId>
        <label>Oracle Purchase Order Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaymentTerm__c</fullName>
        <label>Payment Term</label>
        <picklist>
            <picklistValues>
                <fullName>NET 30 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pay When Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pay When Paid Partial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET 10 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET 15 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET 5 YEARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET 90 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET 120 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET 45 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET 60 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET 7 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET 14 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET 20 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET 55 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extended Terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 FOL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET 85 DAYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5/14 NET 30 DAYS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>POHeadersProject</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VendorName__c</fullName>
        <formula>VendorSite__r.AccountName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VendorSite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>VendorSite__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/POLineItem__c.object
<CustomObject>
    <fields>
        <fullName>CancelFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancel Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LineNumber__c</fullName>
        <label>Line Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LineType__c</fullName>
        <label>Line Type</label>
        <picklist>
            <picklistValues>
                <fullName>Unit Rate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Fee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>POHeader__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>POHeader__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>POLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Purchase Order Line Items</relationshipLabel>
        <relationshipName>POLineItemsProjectTask</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO Line Item</label>
    <nameField>
        <displayFormat>POLI-{0000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project that the Task is a part of.</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <description>Represents a customer/vendor site (address/location).</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Represents the account which is bound to the customer/vendor site (address/location).</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Site</label>
    <nameField>
        <displayFormat>Site-{0000000000}</displayFormat>
        <label>Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/VendorSite__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Vendors and Subs</relationshipLabel>
        <relationshipName>VendorSitesProject</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Vendor Sites</relationshipLabel>
        <relationshipName>VendorSitesSite</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Vendor Site</label>
    <nameField>
        <displayFormat>VS-{0}</displayFormat>
        <label>Vendor Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_PurchaseOrderSummaryControllerTest.cls
@isTest
private class ECO_PurchaseOrderSummaryControllerTest{

    private static final Integer numTestProjectTasks = 10;	
	private static final Integer numTeamMembers = 1;

	static testMethod void testMissingUrlParams(){
		PageReference pageRef = new PageReference('/apex/ECO_PurchaseOrderSummary');
		test.setCurrentPage(pageRef);
		ECO_PurchaseOrderSummaryController con = new ECO_PurchaseOrderSummaryController(new ApexPages.StandardController(new POHeader__c()));
		system.assertEquals(true, con.hideEverything);	//flag to not display any of the form
        
        PageReference pageRefAfterSave = con.updatePurchaseOrder();
	}
    
    static testMethod void testDeletePurchaseOrder() {
        createTestData();
    	
		pse__Proj__c testProject = [SELECT Id, Name, pse__Account__c, pse__Project_Manager__c FROM pse__Proj__c LIMIT 1];
		testProject.pse__Project_Manager__r = null;
		update testProject;
		
        Test.startTest();
		Agreement__c agreement = [SELECT Id, VendorName__c, Project__c FROM Agreement__c WHERE Project__c = :testProject.Id];
        agreement.Project__c = null;
        update agreement;

        PageReference pageRef = new PageReference('/apex/ECO_PurchaseOrderSummary');   	
		pageRef.getParameters().put('agreementId', agreement.Id); 
        test.setCurrentPage(pageRef);
        
        ECO_PurchaseOrderSummaryController con = new ECO_PurchaseOrderSummaryController(new ApexPages.StandardController(new POHeader__c()));
        
        agreement.Project__c = testProject.Id;
        update agreement;
        
		VendorSite__c vendor = [SELECT Id, Site__c, Site__r.PaymentTerms__c FROM VendorSite__c WHERE Project__c = :testProject.Id];

		List<pse__Project_Task__c> tasks = [SELECT Id FROM pse__Project_Task__c WHERE pse__Project__c = :testProject.Id];

    	pageRef = new PageReference('/apex/ECO_PurchaseOrderSummary');
		pageRef.getParameters().put('projectId', testProject.Id);    	
		pageRef.getParameters().put('agreementId', agreement.Id); 

    	test.setCurrentPage(pageRef);

    	con = new ECO_PurchaseOrderSummaryController(new ApexPages.StandardController(new POHeader__c()));

    	//check params were processed and objects retrieved
    	system.assertEquals(true, con.showCreateAndSubmitForApproval);	//new purchase order 
    	system.assertEquals(false, con.allowRequestSubmit);	//flag that allow line items to be added
    	system.assertEquals(testProject.Id, con.poHeader.Project__c );
    	system.assertEquals(agreement.Id, con.poHeader.Agreement__c);

    	system.debug('project pm = ' + testProject.pse__Project_Manager__c);

    	//test vendor is available
    	system.assertEquals(2, con.optSelectProjectSites.size());	

    	//json should be empty
    	system.assertEquals(true, String.isEmpty(con.sJSON));
    	
    	//verify other 
		system.assertEquals(true, con.validPOLineItems.isEmpty()); 
		system.assertEquals(true, con.invalidPOLineItems.isEmpty()); 

		system.assertEquals(false, con.hasBeenApproved);
		system.assertEquals(false, con.hasSyncHistory);

		//test set vendor
		SelectOption vendorOpt = con.optSelectProjectSites.get(1);

		con.selProjectSiteId = vendorOpt.getValue();
		con.getDefaultPaymentTermsForVendor();
		system.assertEquals(vendor.Site__r.PaymentTerms__c, con.poHeader.PaymentTerm__c);
		System.debug('con.selProjectSiteId: ' + con.selProjectSiteId);
        
        Contact pm = [SELECT Id, OracleContactID__c FROM Contact WHERE Id = :con.poHeader.Requestor__c];
        pm.OracleContactID__c = '123456789';
        update pm;
        
		PageReference pageRefAfterSave = con.updatePurchaseOrder();
        agreement.VendorSite__c = vendor.Id;
        update agreement;
        
        POHeader__c poHeader = [SELECT Id FROM POHeader__c WHERE Project__c = :testProject.Id];
        poHeader.CancelFlag__c = true;
        poHeader.OraclePurchaseOrderId__c = '123456789';
        update poHeader;
        
        con = new ECO_PurchaseOrderSummaryController(new ApexPages.StandardController(poHeader));
        
        con.deletePurchaseOrder();
        Test.stopTest();
    }
    
    static testMethod void testexecuteOracleSyncRequest() {
        createTestData();
    	
		pse__Proj__c testProject = [SELECT Id, Name, pse__Account__c, pse__Project_Manager__c FROM pse__Proj__c LIMIT 1];
		testProject.pse__Project_Manager__r = null;
		update testProject;
		
		Agreement__c agreement = [SELECT Id, VendorName__c FROM Agreement__c WHERE Project__c = :testProject.Id];

		VendorSite__c vendor = [SELECT Id, Site__c, Site__r.PaymentTerms__c FROM VendorSite__c WHERE Project__c = :testProject.Id];

		List<pse__Project_Task__c> tasks = [SELECT Id FROM pse__Project_Task__c WHERE pse__Project__c = :testProject.Id];
        Test.startTest();

    	PageReference pageRef = new PageReference('/apex/ECO_PurchaseOrderSummary');
		pageRef.getParameters().put('projectId', testProject.Id);    	
		pageRef.getParameters().put('agreementId', agreement.Id); 

    	test.setCurrentPage(pageRef);

    	ECO_PurchaseOrderSummaryController con = new ECO_PurchaseOrderSummaryController(new ApexPages.StandardController(new POHeader__c()));
		con.selectedVendorId = vendor.Id;
    	//check params were processed and objects retrieved
    	system.assertEquals(true, con.showCreateAndSubmitForApproval);	//new purchase order 
    	system.assertEquals(false, con.allowRequestSubmit);	//flag that allow line items to be added
    	system.assertEquals(testProject.Id, con.poHeader.Project__c );
    	system.assertEquals(agreement.Id, con.poHeader.Agreement__c);

    	system.debug('project pm = ' + testProject.pse__Project_Manager__c);

    	//test vendor is available
    	system.assertEquals(2, con.optSelectProjectSites.size());	

    	//json should be empty
    	system.assertEquals(true, String.isEmpty(con.sJSON));
    	
    	//verify other 
		system.assertEquals(true, con.validPOLineItems.isEmpty()); 
		system.assertEquals(true, con.invalidPOLineItems.isEmpty()); 

		system.assertEquals(false, con.hasBeenApproved);
		system.assertEquals(false, con.hasSyncHistory);

		//test set vendor
		SelectOption vendorOpt = con.optSelectProjectSites.get(1);

		con.selProjectSiteId = vendorOpt.getValue();
		con.getDefaultPaymentTermsForVendor();
		system.assertEquals(vendor.Site__r.PaymentTerms__c, con.poHeader.PaymentTerm__c);
		System.debug('con.selProjectSiteId: ' + con.selProjectSiteId);
        
        Contact pm = [SELECT Id, OracleContactID__c FROM Contact WHERE Id = :con.poHeader.Requestor__c];
        pm.OracleContactID__c = '123456789';
        update pm;
        
		PageReference pageRefAfterSave = con.updatePurchaseOrder();
        
        ECO_IntegrationEndpoints__c integrationEndPoint2 = new ECO_IntegrationEndpoints__c();
        integrationEndPoint2.Name = 'Project Sync 2';
        integrationEndPoint2.EndPointUrl__c = 'https://ecodev.aecom.com/OA_HTML/jsp/fnd/PicDisconnSF.jsp';
        insert integrationEndPoint2;
        
        pageRef = new PageReference('/apex/ECO_PurchaseOrderSummary');
		pageRef.getParameters().put('username', 'username');    	
		pageRef.getParameters().put('password', 'password'); 

    	test.setCurrentPage(pageRef);
        
        pageRef = con.authenticateCredentials();
        pageRef = con.closeAuthenticationWindow();
        

		test.setCurrentPage(pageRefAfterSave);	

		POHeader__c poHeader = [SELECT Id FROM POHeader__c WHERE Project__c = :testProject.Id];

		POLineItem__c poLineItem = new POLineItem__c();
		//poLineItem.ProjectTask__c = tasks.get(0).Id;
		poLineItem.POHeader__c = poHeader.Id;
		poLineItem.LineNumber__c = 1;
		poLineItem.LineType__c = 'Fixed Fee';
		poLineItem.UnitofMeasure__c = 'Lump SUm';

		insert poLineItem;

		ECO_PurchaseOrderSummaryController con2 = new ECO_PurchaseOrderSummaryController(new ApexPages.StandardController(poHeader));

        poLineItem.ProjectTask__c = tasks.get(0).Id;
		update poLineItem;

		con2.validatePOLineItems();

		//test add po line item
		PageReference poLineItemPageRef = con2.gotoPOLineItemPage();

		con2.initiateOracleSyncRequest();
        
        ECO_IntegrationEndpoints__c integrationEndPoint = new ECO_IntegrationEndpoints__c();
        integrationEndPoint.Name = 'Purchase Order Sync';
        integrationEndPoint.EndPointUrl__c = 'https://ecodev.aecom.com/services/api/PurchaseOrder';
        insert integrationEndPoint;
		
        con2.executeOracleSyncRequest();
        
        Test.stopTest();
    }

    static testMethod void testCreateNewPurchaseOrder() {
        createTestData();
    	
		pse__Proj__c testProject = [SELECT Id, Name, pse__Account__c, pse__Project_Manager__c FROM pse__Proj__c LIMIT 1];
		testProject.pse__Project_Manager__r = null;
		update testProject;
		
		Agreement__c agreement = [SELECT Id, VendorName__c FROM Agreement__c WHERE Project__c = :testProject.Id];

		VendorSite__c vendor = [SELECT Id, Site__c, Site__r.PaymentTerms__c FROM VendorSite__c WHERE Project__c = :testProject.Id];

		List<pse__Project_Task__c> tasks = [SELECT Id FROM pse__Project_Task__c WHERE pse__Project__c = :testProject.Id];
        Test.startTest();

    	PageReference pageRef = new PageReference('/apex/ECO_PurchaseOrderSummary');
		pageRef.getParameters().put('projectId', testProject.Id);    	
		pageRef.getParameters().put('agreementId', agreement.Id); 

    	test.setCurrentPage(pageRef);

    	ECO_PurchaseOrderSummaryController con = new ECO_PurchaseOrderSummaryController(new ApexPages.StandardController(new POHeader__c()));
		con.selectedVendorId = vendor.Id;
    	//check params were processed and objects retrieved
    	system.assertEquals(true, con.showCreateAndSubmitForApproval);	//new purchase order 
    	system.assertEquals(false, con.allowRequestSubmit);	//flag that allow line items to be added
    	system.assertEquals(testProject.Id, con.poHeader.Project__c );
    	system.assertEquals(agreement.Id, con.poHeader.Agreement__c);

    	system.debug('project pm = ' + testProject.pse__Project_Manager__c);

    	//test vendor is available
    	system.assertEquals(2, con.optSelectProjectSites.size());	

    	//json should be empty
    	system.assertEquals(true, String.isEmpty(con.sJSON));
    	
    	//verify other 
		system.assertEquals(true, con.validPOLineItems.isEmpty()); 
		system.assertEquals(true, con.invalidPOLineItems.isEmpty()); 

		system.assertEquals(false, con.hasBeenApproved);
		system.assertEquals(false, con.hasSyncHistory);

		//test set vendor
		SelectOption vendorOpt = con.optSelectProjectSites.get(1);

		con.selProjectSiteId = vendorOpt.getValue();
		con.getDefaultPaymentTermsForVendor();
		system.assertEquals(vendor.Site__r.PaymentTerms__c, con.poHeader.PaymentTerm__c);
		System.debug('con.selProjectSiteId: ' + con.selProjectSiteId);
        
        Contact pm = [SELECT Id, OracleContactID__c FROM Contact WHERE Id = :con.poHeader.Requestor__c];
        pm.OracleContactID__c = '123456789';
        update pm;
        
		PageReference pageRefAfterSave = con.updatePurchaseOrder();

		test.setCurrentPage(pageRefAfterSave);	

		POHeader__c poHeader = [SELECT Id FROM POHeader__c WHERE Project__c = :testProject.Id];

		POLineItem__c poLineItem = new POLineItem__c();
		//poLineItem.ProjectTask__c = tasks.get(0).Id;
		poLineItem.POHeader__c = poHeader.Id;
		poLineItem.LineNumber__c = 1;
		poLineItem.LineType__c = 'Fixed Fee';
		poLineItem.UnitofMeasure__c = 'Lump SUm';

		insert poLineItem;

		ECO_PurchaseOrderSummaryController con2 = new ECO_PurchaseOrderSummaryController(new ApexPages.StandardController(poHeader));

/*
		//test save - should get set to approval appending since current user is not pm

	    PageReference savePageRef =	con.saveAndSubmitForApproval();

	    system.assertNotEquals(null, savePageRef);

	    POHeader__c poHeaderAfterSave = [SELECT Id, Status__c, PaymentTerm__c, Requestor__c, VendorSite__c, Project__c, Agreement__c
	    									FROM POHeader__c
	    									WHERE Project__c = :testProject.Id];

	    system.assertEquals('Pending', poHeaderAfterSave.Status__c);
*/
        
        
        

		poLineItem.ProjectTask__c = tasks.get(0).Id;
		update poLineItem;

		con2.validatePOLineItems();

		//test add po line item
		PageReference poLineItemPageRef = con2.gotoPOLineItemPage();

		con2.initiateOracleSyncRequest();

		con2.executeOracleSyncRequest();
        
        con2.cancelPurchaseOrder();

		con2.closeOutPurchaseOrder();

		PageReference projectPageRef = con2.returnToProject();

		con2.createMessageQueueRecord_start();

		con2.createMessageQueueRecord_complete();

		con2.sendPOSyncRequest_start();

		con2.sendPOSyncRequest_complete();

		con2.sendPOSyncRequest_Finish();

		con2.checkIfSyncHasBeenProcessed();
        
        con2.SimulateInvoicedByOracle();
        con2.SimulateProcessedByOracle();
        con2.refreshJSON();
        
        Test.stopTest();
    }

    static void createTestData(){
    	//create account and project
		ECO_Utils_Testing.createTestDataForProjectSync(numTestProjectTasks, numTeamMembers);
		pse__Proj__c testProject = [SELECT Id, pse__Account__c FROM pse__Proj__c];

    	//create a vendor
    	Account vendor = new Account();
		vendor.Name = 'test vendor';

		insert vendor;

		Site__c site = new Site__c();
		site.Account__c = vendor.Id;
		site.PaymentTerms__c = 'Immediate';
		site.VendorSiteID__c  = '123456';
		insert site;

		VendorSite__c vendorSite = new VendorSite__c();
		vendorSite.Site__c = site.Id;
		vendorSite.Project__c = testProject.Id;

		insert vendorSite;

		//create an agreement
		Agreement__c agreement = new Agreement__c();		
		agreement.Project__c = testProject.Id;
		agreement.Account__c = testProject.pse__Account__c;
		insert agreement;
    }
}