src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OtherDirectCost__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Other Direct Costs</relationshipLabel>
        <relationshipName>Other_Direct_Costs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Other Direct Cost</label>
    <nameField>
        <displayFormat>DC-{0000}</displayFormat>
        <label>Other Direct Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Direct Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_OtherDirectCostController.cls
public class ECO_OtherDirectCostController {
	
	public OtherDirectCost__c otherDirectCost {get; set;}
	
	public ECO_OtherDirectCostController(ApexPages.StandardController standardController)
	{
		otherDirectCost = (OtherDirectCost__c)standardController.getRecord();
	}

	public void init()
	{
		if(Apexpages.currentPage().getParameters().get('Agreement__c') != null)
		{
			otherDirectCost.Agreement__c = Apexpages.currentPage().getParameters().get('Agreement__c'); 		
		}
	}
	
	public PageReference save()
	{
		insert otherDirectCost;
		
		PageReference pageRef = new PageReference('/' + otherDirectCost.Agreement__c);
		return pageRef;
	}	
}