src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <fields>
        <fullName>AgreementType__c</fullName>
        <description>Select the contract type from a master list of contract types available in the drop down list.</description>
        <inlineHelpText>Select the contract type from a master list of contract types available in the drop down list.</inlineHelpText>
        <label>Contract Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agreement for the Transfer of Digital Model Files</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ Industry Standard (AS4122, IPENZ/ACENZ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architectural Design Services Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architectural Design Services Agreement (Transnational)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD Conditions of Use Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash on Delivery Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client (Day1) Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Authorization to Proceed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Data Confidentiality Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditions of Engagement for Accredited Design Verification Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confidentiality Agreement/Deed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction / EPC Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting Services Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting Services Agreement (Transnational)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting Services Subcontract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting Services Subcontract (Transnational)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Confidentiatlity Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deed Poll</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Engineering Services Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Information Consent and Acknowledgement Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economics Services Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economics Services Agreement (Transnational)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Data Licence Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering Design Services (Transnational)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expert Services Consultant Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FIDIC 2006 Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FIDIC Sub Consultancy Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indefinite Deliverable/Indefinite Quantity (ID/IQ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Contractor Agreement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FundingCurrencyCode__c</fullName>
        <description>Select the currency of the agreement</description>
        <inlineHelpText>Select the currency of the agreement</inlineHelpText>
        <label>Agreement Currency</label>
        <picklist>
            <picklistValues>
                <fullName>AED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BGN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CZK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DJF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DKK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EGP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfIndemnityLiabilityAmt__c</fullName>
        <inlineHelpText>Enter the total value of Professional Indemnity/Liability nominated in the contract</inlineHelpText>
        <label>Prof Indemnity/Liability Amt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>AgreementsProject</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PublicGeneralLiabilityAmt__c</fullName>
        <inlineHelpText>Enter the total value of Public/General Liability nominated in the contract</inlineHelpText>
        <label>Public/General Liability Amt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ScopeOfServices__c</fullName>
        <description>Provide a detailed description of the scope of services available under the agreement.</description>
        <inlineHelpText>Provide a detailed description of the scope of services available under the agreement.</inlineHelpText>
        <label>Scope of Services</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Prime</fullName>
        <active>true</active>
        <description>Any type of single use contract for general consulting services between AECOM and the client.  This type of agreement will be interfaced to Oracle to provide the contract value and approved funding for the project.</description>
        <label>Prime</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectAgreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>ProjectAgreementsAgreement</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>ProjectAgreementsProject</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Agreement</label>
    <nameField>
        <displayFormat>PA-{0}</displayFormat>
        <label>Project Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_ServiceContractReviewTest.cls
@isTest
private class ECO_ServiceContractReviewTest {

    static testMethod void myUnitTest() {
        ECO_Utils_Testing.createTestDataForProjectSync(1, 2);
        
       	pse__Proj__c testProject = [SELECT Id, Name FROM pse__Proj__c LIMIT 1];
       	
       	Id recordTypeId = ECO_Utils_sObject.getRecordTypeId(Agreement__c.sObjectType, 'Prime Task Order');
       	Agreement__c testAgreement = new Agreement__c();
       	testAgreement.FundingCurrencyCode__c = 'USD';
       	testAgreement.ScopeOfServices__c = 'Test Services';
       	testAgreement.RecordTypeId = recordTypeId;
       	testAgreement.ProfIndemnityLiabilityAmt__c = 1000;
       	testAgreement.PublicGeneralLiabilityAmt__c = 1000;
       	testAgreement.AgreementType__c = 'Test Agreement Type';
       	insert testAgreement;
       	
       	ProjectAgreement__c projectAgreement = new ProjectAgreement__c(Agreement__c = testAgreement.Id, Project__c = testProject.Id);
       	insert projectAgreement;
       	
       	list<ECO_ContractReviewDTO> contractReviewDTOs = ECO_Service_ContractReview.getContractReivewDTOs(testAgreement.Id);
       	System.AssertEquals(1, contractReviewDTOs.size());
        
    }
    
    static testMethod void myUnitTest2() {
        ECO_Utils_Testing.createTestDataForProjectSync(1, 2);
        //ECO_Utils_Testing.createTestDataForProjectSync(1, 2);
        
       	pse__Proj__c testProject = [SELECT Id, Name FROM pse__Proj__c];
       	
       	Id recordTypeId = ECO_Utils_sObject.getRecordTypeId(Agreement__c.sObjectType, 'Prime Task Order');
       	Agreement__c testAgreement = new Agreement__c();
       	testAgreement.FundingCurrencyCode__c = 'USD';
       	testAgreement.ScopeOfServices__c = 'Test Services';
       	testAgreement.RecordTypeId = recordTypeId;
       	testAgreement.ProfIndemnityLiabilityAmt__c = 1000;
       	testAgreement.PublicGeneralLiabilityAmt__c = 1000;
       	testAgreement.AgreementType__c = 'Test Agreement Type';
       	insert testAgreement;
       	
       	Account testAccount = new Account();
		testAccount.Name = 'test Account';
		insert testAccount;
		
		//create create source project 
		pse__Proj__c testProject2 = new pse__Proj__c();
		testProject2.Name = 'test project 2';
		testProject2.pse__Account__c = testAccount.Id;
		testProject2.pse__Project_Type__c = 'Customer Project';
		testProject2.pse__Billing_Type__c = 'Fixed Price';
		testProject2.CurrencyIsoCode = 'USD';
		testProject2.pse__Is_Active__c = true;
		testProject2.pse__End_Date__c = Date.today().addDays(5);
		insert testProject2;		
       	
       	ProjectAgreement__c projectAgreement1 = new ProjectAgreement__c(Agreement__c = testAgreement.Id, Project__c = testProject.Id);
       	ProjectAgreement__c projectAgreement2 = new ProjectAgreement__c(Agreement__c = testAgreement.Id, Project__c = testProject2.Id);
       	insert projectAgreement1;
       	insert projectAgreement2;
       	   	
       	list<ECO_ContractReviewDTO> contractReviewDTOs = ECO_Service_ContractReview.getContractReivewDTOs(testAgreement.Id);
       	System.AssertEquals(2, contractReviewDTOs.size());
        
    }    
    
}