src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>AgreementsProject</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>BudgetHeaders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_AttachmentTriggerHandlerTest.cls
@isTest
private class ECO_AttachmentTriggerHandlerTest {

    static testMethod void testDeleteAgreementAttachment() {
    	
    	Agreement__c agreement = new Agreement__c();
    	insert agreement;
    	
    	Blob attachmentBody = Blob.valueOf('This is a test');
    	Attachment attachment = new Attachment();
    	attachment.Body = attachmentBody;
    	attachment.ParentId = agreement.Id;
    	attachment.Name = 'Test Attachment';
    	insert attachment;
    	
    	try
    	{
    		delete attachment;
    	}
    	catch(Exception e)
		{
			Boolean expectedExceptionThrown =  e.getMessage().contains('Users are not allowed to delete Agreement Attachments') ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
		} 
    
        // TO DO: implement unit test
    }
    
    static testMethod void testDeleteBudgetAttachment() {
    	
    	pse__Proj__c project = new pse__Proj__c();
    	insert project;
    	
    	BudgetHeader__c budgetHeader = new BudgetHeader__c(Project__c = project.Id);
    	insert budgetHeader;
    	
    	Blob attachmentBody = Blob.valueOf('This is a test');
    	Attachment attachment = new Attachment();
    	attachment.Body = attachmentBody;
    	attachment.ParentId = budgetHeader.Id;
    	attachment.Name = 'Test Attachment';
    	insert attachment;
    	
    	try
    	{
    		delete attachment;
    	}
    	catch(Exception e)
		{
			Boolean expectedExceptionThrown =  e.getMessage().contains('Users are not allowed to delete Budget Attachments') ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
		} 
    
        // TO DO: implement unit test
    }    
}