src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <fields>
        <fullName>AgreementNumber__c</fullName>
        <description>This is a unique identifier assigned to all Agreement Records in Ecosystem.  Use this reference for Contract Reviews.</description>
        <label>Contract Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FundingCurrencyCode__c</fullName>
        <description>Select the currency of the agreement</description>
        <inlineHelpText>Select the currency of the agreement</inlineHelpText>
        <label>Agreement Currency</label>
        <picklist>
            <picklistValues>
                <fullName>AED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BGN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CZK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DJF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DKK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EGP</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BillRate__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Bill Rates</relationshipLabel>
        <relationshipName>BillRatesAgreement</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BillRateEnd__c</fullName>
        <label>BillRateEnd</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BillRatePeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill Rate Period</label>
        <referenceTo>BillRatePeriod__c</referenceTo>
        <relationshipLabel>Bill Rates</relationshipLabel>
        <relationshipName>BillRates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillRateStart__c</fullName>
        <label>BillRateStart</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BillRate__c</fullName>
        <label>Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LaborCategory__c</fullName>
        <label>Labor Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Bill Rate</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Bill Rate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BillRatePeriod__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Bill Rate Periods</relationshipLabel>
        <relationshipName>BillRatePeriods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillRateEnd__c</fullName>
        <label>BillRateEnd</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BillRateStart__c</fullName>
        <label>BillRateStart</label>
        <type>Date</type>
    </fields>
    <label>Bill Rate Period</label>
    <nameField>
        <displayFormat>BRP-{0000}</displayFormat>
        <label>BillRatePeriod Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Rate Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_BillRateManagement.cls
public class ECO_BillRateManagement {
	
	String agreementId = '';
	public list<BillRate__c> billRates {get;set;}
	public BillRate__c newBillRate {get; set;}
	public BillRatePeriod__c newBillRatePeriod {get; set;}
	public Boolean creatingNewBillRatePeriod {get; set;}
	public Boolean creatingNewBillRate {get; set;}
	public Agreement__c agreement {get;set;}
	public map<String, list<BillRatePeriod__c>> laborCategoryToBillRatePeriodMap;
	public map<Id,BillRatePeriod__c> billRatePeriodMap;
	//public map<String, list<BillRate__c>> laborCategoryBillRateMap {get; set;}
	public map<String, BillRate__c> billRatePeriodCategoryRateMap {get; set;}
	public String updatedKey {get; set;}
	public Decimal updatedValue {get; set;}
	
	public ECO_BillRateManagement()
	{
		laborCategoryToBillRatePeriodMap = new map<String, list<BillRatePeriod__c>>();
		
		agreementId = ApexPages.currentPage().getParameters().get('AgreementId');
		agreement = [select Id, Name, FundingCurrencyCode__c, AgreementNumber__c from Agreement__c where Id = :agreementId];
		billRates = [select Id, Name, BillRatePeriod__c, LaborCategory__c, BillRate__c from BillRate__c where Agreement__c = :agreementId];
		billRatePeriodMap = new map<Id,BillRatePeriod__c>([select Id, BillRateStart__c, BillRateEnd__c from BillRatePeriod__c where Agreement__c = :agreementId]);
		//laborCategoryBillRateMap = new map<String, list<BillRate__c>>();
		billRatePeriodCategoryRateMap = new map<String, BillRate__c>();
		for(BillRate__c billRate:billRates)
		{
			if(billRatePeriodCategoryRateMap.get(billRate.BillRatePeriod__c + '-' + billRate.LaborCategory__c) == null)
				billRatePeriodCategoryRateMap.put(billRate.BillRatePeriod__c + '-' + billRate.LaborCategory__c, billRate);
			
			if(laborCategoryToBillRatePeriodMap.get(billRate.LaborCategory__c) == null)
				laborCategoryToBillRatePeriodMap.put(billRate.LaborCategory__c, new list<BillRatePeriod__c>());	
			if(billRate.BillRatePeriod__c != null)
				laborCategoryToBillRatePeriodMap.get(billRate.LaborCategory__c).add(billRatePeriodMap.get(billRate.BillRatePeriod__c));				
		}
	}

	public void createNewBillRate()
	{
		creatingNewBillRate = true;
		newBillRate = new BillRate__c(Agreement__c = agreementId);		
	}
	
	public void createNewBillRatePeriod()
	{
		creatingNewBillRatePeriod = true;
		newBillRatePeriod = new BillRatePeriod__c(Agreement__c = agreementId);	
	}	
	
	public PageReference returnToAgreement()
	{
		return new PageReference('/apex/ECO_AgreementView?Id=' + agreement.Id);
	}
	
	public void updateBillRateApex()
	{
		if(billRatePeriodCategoryRateMap.get(updatedKey) != null)
			billRatePeriodCategoryRateMap.get(updatedKey).BillRate__c = updatedValue;
	}
	
	public void cancelNewBillRate()
	{
		creatingNewBillRate = false;
	}
	
	public void saveNewBillRate()
	{
		if(billRatePeriodMap.values().size() == 0)
			insert newBillRate;
		else
		{
			string laborCategory = newBillRate.LaborCategory__c;
			list<BillRate__c> lBillRates = new list<BillRate__c>();
			for(BillRatePeriod__c lbillRatePeriod:billRatePeriodMap.values())
			{
				newBillRate.BillRate__c = 0;
				newBillRate.BillRatePeriod__c = lbillRatePeriod.Id;
				lBillRates.add(newBillRate);
				if(laborCategoryToBillRatePeriodMap.get(newBillRate.LaborCategory__c)==null)
					laborCategoryToBillRatePeriodMap.put(newBillRate.LaborCategory__c, new list<BillRatePeriod__c>());
				laborCategoryToBillRatePeriodMap.get(newBillRate.LaborCategory__c).add(lbillRatePeriod);

				//if(laborCategoryBillRateMap.get(newBillRate.LaborCategory__c)==null)
				//	laborCategoryBillRateMap.put(newBillRate.LaborCategory__c, new list<BillRate__c>());
				//laborCategoryBillRateMap.get(newBillRate.LaborCategory__c).add(newBillRate);
				billRatePeriodCategoryRateMap.put(lbillRatePeriod.Id +'-' + laborCategory, newBillRate);	
				newBillRate = new BillRate__c(Agreement__c = agreementId, LaborCategory__c = laborCategory);					
			}
			if(lBillRates.size() > 0)
				insert lBillRates;
		}				
		creatingNewBillRate = false;
	}
	
	public set<String> getLaborCategories()
	{
		set<String> keysetValues = new set<String>();
		if(laborCategoryToBillRatePeriodMap.keyset() != null)
			return laborCategoryToBillRatePeriodMap.keyset();
		return keysetValues;
	}
	
	public list<BillRatePeriod__c> getPeriods()
	{
		if(billRatePeriodMap.values() != null)
			return billRatePeriodMap.values();
		return new list<BillRatePeriod__c>();
	}
	
	public void saveBillRates()
	{
		update billRatePeriodCategoryRateMap.values();
	}
	
	public void cancelNewBillRatePeriod()
	{
		creatingNewBillRatePeriod = false;
	}
	
	public void saveNewBillRatePeriod()
	{
		if(laborCategoryToBillRatePeriodMap.keyset().size() == 0)
		{	
			insert newBillRatePeriod;
			billRatePeriodMap.put(newBillRatePeriod.Id, newBillRatePeriod);
		}
		else
		{
			insert newBillRatePeriod;
			list<BillRate__c> lBillRates = new list<BillRate__c>();
			if(billRatePeriodMap.keyset().size() == 0)
			{
				
			}
			else
			{
				for(String laborCategory:laborCategoryToBillRatePeriodMap.keyset())
				{
					newBillRate = new BillRate__c(Agreement__c = agreementId, BillRatePeriod__c = newBillRatePeriod.Id, LaborCategory__c = laborCategory, BillRate__c = 0);
					lBillRates.add(newBillRate);
					laborCategoryToBillRatePeriodMap.get(laborCategory).add(newBillRatePeriod);
					billRatePeriodMap.put(newBillRatePeriod.Id, newBillRatePeriod);
					billRatePeriodCategoryRateMap.put(newBillRatePeriod.Id +'-' + laborCategory, newBillRate);				
				}
			}
			if(lBillRates.size() > 0)
				insert lBillRates;
		}		
				
		creatingNewBillRatePeriod = false;
		
	}	
}