src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Once executed, populate the current total confirmed agreement amount</description>
        <inlineHelpText>Once executed, populate the current total confirmed agreement amount</inlineHelpText>
        <label>Agreement Amount (Confirmed)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>AgreementsProject</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Billing__c.object
<CustomObject>
    <description>Object used for tracking billing information from Oracle</description>
    <fields>
        <fullName>InvoiceAmount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InvoiceDate__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Billing</label>
    <nameField>
        <label>Billing Invoice #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PortalMessage__c.object
<CustomObject>
    <description>Used by the ECO_Portal pages to display User Alerts, News Feed Items, and News Ticker.</description>
    <label>Portal Message</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Portal Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectAgreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>ProjectAgreementsAgreement</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>ProjectAgreementsProject</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Agreement</label>
    <nameField>
        <displayFormat>PA-{0}</displayFormat>
        <label>Project Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_ProjectClosureRecommendationTest.cls
@isTest
public class ECO_ProjectClosureRecommendationTest {
	
	static testMethod void testBatchOne()
	{ 	
		Account testAccount = new Account();
		testAccount.Name = 'test Account';
		insert testAccount;

		//create create source project 
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.Name = 'test project 1';
		testProject.pse__Account__c = testAccount.Id;
		testProject.pse__Project_Type__c = 'Customer Project';
		testProject.pse__Billing_Type__c = 'Fixed Price';
		testProject.CurrencyIsoCode = 'USD';
		testProject.pse__Is_Active__c = true;
		testProject.pse__End_Date__c = Date.today().addDays(-1);
		insert testProject;
		
		Billing__c billing = new Billing__c();
		billing.ProjectNumber__c = testProject.Id;
		billing.InvoiceAmount__c = 10000;
		billing.InvoiceDate__c = Date.today();
		insert billing;
		
		Test.StartTest();                
        ECO_ProjectClosureRecommendationBatch recommendationBatch = new ECO_ProjectClosureRecommendationBatch();
        Id batchprocessid = Database.executeBatch(recommendationBatch);    
        Test.StopTest(); 
        
        list<PortalMessage__c> messages = [select Id from PortalMessage__c];
        System.AssertEquals(0, messages.size());
	}

	static testMethod void testBatchTwo()
	{ 	
		Account testAccount = new Account();
		testAccount.Name = 'test Account';
		insert testAccount;

		//create create source project 
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.Name = 'test project 1';
		testProject.pse__Account__c = testAccount.Id;
		testProject.pse__Project_Type__c = 'Customer Project';
		testProject.pse__Billing_Type__c = 'Fixed Price';
		testProject.CurrencyIsoCode = 'USD';
		testProject.pse__Is_Active__c = true;
		testProject.pse__End_Date__c = Date.today().addDays(-1);
		insert testProject;
		
		Billing__c billing = new Billing__c();
		billing.ProjectNumber__c = testProject.Id;
		billing.InvoiceAmount__c = 10000;
		billing.InvoiceDate__c = Date.today().addDays(-100);
		insert billing;
		
		Agreement__c agreement = new Agreement__c();
		agreement.Amount__c = 10000;
		insert agreement;
		
		ProjectAgreement__c projectAgreement = new ProjectAgreement__c(Agreement__c = agreement.Id,
																	   Project__c = testProject.Id);
		insert projectAgreement;
																	  		
		Test.StartTest();                
        ECO_ProjectClosureRecommendationBatch recommendationBatch = new ECO_ProjectClosureRecommendationBatch();
        Id batchprocessid = Database.executeBatch(recommendationBatch);    
        Test.StopTest(); 
        
        list<PortalMessage__c> messages = [select Id from PortalMessage__c];
        System.AssertEquals(1, messages.size());
	}

}