src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The prime client on the contract.</inlineHelpText>
        <label>Billing Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements (Billing Client)</relationshipLabel>
        <relationshipName>AgreementsEndClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ManagementTeam__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Management Team</relationshipLabel>
        <relationshipName>ManagementTeam</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Management Team</relationshipLabel>
        <relationshipName>ManagementTeamContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Management Team</label>
    <nameField>
        <displayFormat>MT-{0}</displayFormat>
        <label>Management Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Management Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_CreateMSAContact.cls
public class ECO_CreateMSAContact {
	
	public ManagementTeam__c managementTeam {get; set;}
	public boolean creatingNewContact {get; set;}
	public Contact contact {get; set;}
	private Agreement__c agreement {get; set;}
	
	public ECO_CreateMSAContact(ApexPages.standardController sc)
	{
		managementTeam = (ManagementTeam__c)sc.getRecord();
//		managementTeam.Agreement__c = 'a4Ye00000009lshEAA';
	}

	public PageReference createNewContact()
	{
		agreement = [select Id, Account__c from Agreement__c where Id = :managementTeam.Agreement__c limit 1];

		creatingNewContact = true;
		contact = new Contact(AccountId = agreement.Account__c);
		
		return null;
	}
	
	public PageReference save()
	{
		update managementTeam;
		
		PageReference pageRef = new PageReference('/apex/ECO_AgreementView');
		pageRef.getParameters().put('Id', managementTeam.Agreement__c);
		return pageRef;
	}
	
	public PageReference saveNewContact()
	{
		creatingNewContact = false;
		
		insert contact;
		managementTeam.TeamMember__c = contact.Id;
		
		return null;
	}
	
	public PageReference cancelNewContact()
	{
		creatingNewContact = false;
		
		return null;
	}	

}