src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The prime client on the contract.</inlineHelpText>
        <label>Billing Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements (Billing Client)</relationshipLabel>
        <relationshipName>AgreementsEndClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Once executed, populate the current total confirmed agreement amount</description>
        <inlineHelpText>Once executed, populate the current total confirmed agreement amount</inlineHelpText>
        <label>Agreement Amount (Confirmed)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Provide a one or two sentence description of the contract.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FundingCurrencyCode__c</fullName>
        <description>Select the currency of the agreement</description>
        <inlineHelpText>Select the currency of the agreement</inlineHelpText>
        <label>Agreement Currency</label>
        <picklist>
            <picklistValues>
                <fullName>AED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BGN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CZK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DJF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DKK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EGP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>AgreementsProject</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Funding__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <description>The agreement related to funding</description>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Funding</relationshipLabel>
        <relationshipName>Funding</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AllocatedAmount__c</fullName>
        <label>Allocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DateAllocatedDate__c</fullName>
        <label>Date Allocated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The project task as it relates to funding</description>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Funding</relationshipLabel>
        <relationshipName>Funding</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The funding as it relates to projects</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Funding</relationshipLabel>
        <relationshipName>Funding</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding</label>
    <nameField>
        <displayFormat>Fund-{0000000000}</displayFormat>
        <label>Funding Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>FinancialTask__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This box should be checked if this project task is a financial task. Unchecked means the task represents a non-financial task.</description>
        <inlineHelpText>This box should be checked if this project task is a financial task. Unchecked means the task represents a non-financial task.</inlineHelpText>
        <label>Financial Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse__End_Date_Time__c</fullName>
        <description>The date &amp; time on which work for this Task is supposed to end.  Timecards may still be entered for a Task after this date as long as it is not closed for time entry.</description>
        <inlineHelpText>The date &amp; time on which work for this Task is supposed to end.  Timecards may still be entered for a Task after this date as long as it is not closed for time entry.</inlineHelpText>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project that the Task is a part of.</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Start_Date_Time__c</fullName>
        <description>The date &amp; time on which work for this Task is supposed to start.  Timecards may still be entered for a Task before this date as long as it is not closed for time entry.</description>
        <inlineHelpText>The date &amp; time on which work for this Task is supposed to start.  Timecards may still be entered for a Task before this date as long as it is not closed for time entry.</inlineHelpText>
        <label>Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>pse__Status__c</fullName>
        <description>Pick list for Project Task status that may be customized as needed for possible Task status values</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_ProjectFundingControllerTest.cls
@isTest
private class ECO_ProjectFundingControllerTest {

    static testMethod void controllerUnitTest() {
    	
    	Account testAccount = new Account();
		testAccount.Name = 'test Account';
		insert testAccount;

		//create create source project 
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.Name = 'test project 1';
		testProject.pse__Account__c = testAccount.Id;
		testProject.pse__Project_Type__c = 'Customer Project';
		testProject.pse__Billing_Type__c = 'Fixed Price';
		testProject.CurrencyIsoCode = 'USD';
		testProject.pse__Is_Active__c = true;
		insert testProject;
		
		Agreement__c agreement = new Agreement__c();
		agreement.Account__c = testAccount.Id;
		agreement.Description__c = 'Test Agreement';
		agreement.CurrencyIsoCode = 'USD';
		agreement.Amount__c = 1000000;
		insert agreement;
		
		pse__Project_Task__c task = new pse__Project_Task__c();
		task.Name = 'top task';
		task.pse__Project__c = testProject.Id;
		task.pse__Start_Date_Time__c = DateTime.now();
		task.pse__End_Date_Time__c = DateTime.now().addDays(1);
		task.pse__Status__c = 'Draft';
		task.FinancialTask__c = false;
		insert task;	
		
		Funding__c funding = new Funding__c();
		funding.AllocatedAmount__c = 10000;
		funding.Agreement__c = agreement.Id;
		funding.Project__c = testproject.Id;
		funding.DateAllocatedDate__c = Date.today();
		funding.ProjectTask__c = task.Id;
		insert funding;	
		
		ApexPages.currentPage().getParameters().put('ProjectId',testProject.Id);
		ApexPages.currentPage().getParameters().put('AgreementId',agreement.Id);
		
		ECO_ProjectFundingController controller = new ECO_ProjectFundingController(); 
		controller.createFunding();
		controller.newFunding.AllocatedAmount__c = 1000;
		controller.newFunding.ProjectTask__c = task.Id;
		controller.saveNewFunding();
		system.assertequals(2, [select Id from funding__c].size());
		system.assertnotequals(null, controller.returnToAgreement());
    }
    
    static testMethod void controllerUnitTest2() {
    	
    	Account testAccount = new Account();
		testAccount.Name = 'test Account';
		insert testAccount;

		//create create source project 
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.Name = 'test project 1';
		testProject.pse__Account__c = testAccount.Id;
		testProject.pse__Project_Type__c = 'Customer Project';
		testProject.pse__Billing_Type__c = 'Fixed Price';
		testProject.CurrencyIsoCode = 'USD';
		testProject.ProjectCurrencyCode__c = 'USD';
		testProject.pse__Is_Active__c = true;
		insert testProject;
		
		Agreement__c agreement = new Agreement__c();
		agreement.Account__c = testAccount.Id;
		agreement.Description__c = 'Test Agreement';
		agreement.CurrencyIsoCode = 'EUR';
		agreement.Amount__c = 1000000;
		agreement.FundingCurrencyCode__c = 'EUR';
		insert agreement;
		
		pse__Project_Task__c task = new pse__Project_Task__c();
		task.Name = 'top task';
		task.pse__Project__c = testProject.Id;
		task.pse__Start_Date_Time__c = DateTime.now();
		task.pse__End_Date_Time__c = DateTime.now().addDays(1);
		task.pse__Status__c = 'Draft';
		task.FinancialTask__c = false;
		insert task;	
		
		Funding__c funding = new Funding__c();
		funding.AllocatedAmount__c = 10000;
		funding.Agreement__c = agreement.Id;
		funding.Project__c = testproject.Id;
		funding.DateAllocatedDate__c = Date.today();
		funding.ProjectTask__c = task.Id;
		insert funding;	
		
		ApexPages.currentPage().getParameters().put('ProjectId',testProject.Id);
		ApexPages.currentPage().getParameters().put('AgreementId',agreement.Id);
		
		ECO_ProjectFundingController controller = new ECO_ProjectFundingController(); 
		controller.createFunding();
		controller.newFunding.AllocatedAmount__c = 1000;
		controller.newFunding.ProjectTask__c = task.Id;
		controller.saveNewFunding();
		system.assertequals(2, [select Id from funding__c].size());
		system.assertnotequals(null, controller.returnToProject());		
    }    
    
	static testMethod void controllerUnitTest3() {
    	
    	Account testAccount = new Account();
		testAccount.Name = 'test Account';
		insert testAccount;

		//create create source project 
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.Name = 'test project 1';
		testProject.pse__Account__c = testAccount.Id;
		testProject.pse__Project_Type__c = 'Customer Project';
		testProject.pse__Billing_Type__c = 'Fixed Price';
		testProject.CurrencyIsoCode = 'USD';
		testProject.ProjectCurrencyCode__c = 'USD';
		testProject.pse__Is_Active__c = true;
		insert testProject;
		
		Agreement__c agreement = new Agreement__c();
		agreement.Account__c = testAccount.Id;
		//agreement.Description__c = 'Test Agreement';
		agreement.CurrencyIsoCode = 'EUR';
		agreement.Amount__c = 1000000;
		agreement.FundingCurrencyCode__c = 'EUR';
		insert agreement;
		
		pse__Project_Task__c task = new pse__Project_Task__c();
		task.Name = 'top task';
		task.pse__Project__c = testProject.Id;
		task.pse__Start_Date_Time__c = DateTime.now();
		task.pse__End_Date_Time__c = DateTime.now().addDays(1);
		task.pse__Status__c = 'Draft';
		task.FinancialTask__c = false;
		insert task;	
		
		Funding__c funding = new Funding__c();
		funding.AllocatedAmount__c = 10000;
		funding.Agreement__c = agreement.Id;
		funding.Project__c = testproject.Id;
		funding.DateAllocatedDate__c = Date.today();
		funding.ProjectTask__c = task.Id;
		insert funding;	
		
		ApexPages.currentPage().getParameters().put('ProjectId',testProject.Id);
		ApexPages.currentPage().getParameters().put('AgreementId',agreement.Id);
		
		ECO_ProjectFundingController controller = new ECO_ProjectFundingController(); 
		controller.createFunding();
		controller.newFunding.AllocatedAmount__c = 1000;
		controller.newFunding.ProjectTask__c = task.Id;
		controller.cancelNewFunding();
		system.assertEquals(null, controller.newFunding);
    }    
}