src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The prime client on the contract.</inlineHelpText>
        <label>Billing Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements (Billing Client)</relationshipLabel>
        <relationshipName>AgreementsEndClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AgreementsMSA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreements MSA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements (MSA)</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Prime</fullName>
        <active>true</active>
        <description>Any type of single use contract for general consulting services between AECOM and the client.  This type of agreement will be interfaced to Oracle to provide the contract value and approved funding for the project.</description>
        <label>Prime</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_MSAAgreementController.cls
public class ECO_MSAAgreementController {
	
	public Agreement__c agreement {get; set;}
	public String mode {get; set;}
	public String clientId {get; set;}
	public String contractType {get; set;}
	
	public ECO_MSAAgreementController()
	{
		clientId = ApexPages.currentPage().getParameters().get('clientId'); 
        contractType = ApexPages.currentPage().getParameters().get('contractType');		
	}
	
	public PageReference init()
	{
		RecordType recordType = [select Id from RecordType where name = 'Prime (MSA)'];
		Agreement__c agreement = new Agreement__c(Account__c = clientId, RecordTypeId = recordType.Id, AgreementsMSA__c = clientId);
		insert agreement;
		
		PageReference ref = new PageReference('/apex/ECO_AgreementView');
		ref.getParameters().put('Id', agreement.Id);
		ref.getParameters().put('Mode', 'Edit');
		return ref;
		
		
	}

	

}