src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Once executed, populate the current total confirmed agreement amount</description>
        <inlineHelpText>Once executed, populate the current total confirmed agreement amount</inlineHelpText>
        <label>Agreement Amount (Confirmed)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>AgreementsProject</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Enter the date the contract is effective from (or the date of execution)</description>
        <inlineHelpText>Enter the date the contract is effective from (or the date of execution)</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Billing__c.object
<CustomObject>
    <description>Object used for tracking billing information from Oracle</description>
    <fields>
        <fullName>BalanceDue__c</fullName>
        <label>Balance Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InvoiceAmount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InvoiceDate__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Billing</label>
    <nameField>
        <label>Billing Invoice #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CostDistLine__c.object
<CustomObject>
    <fields>
        <fullName>ExpenditureItem__c</fullName>
        <label>Expenditure Item</label>
        <referenceTo>ExpendItem__c</referenceTo>
        <relationshipLabel>Cost Distribution Lines (Expenditure Items)</relationshipLabel>
        <relationshipName>CostDistributionLinesExpenditureItem</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GLDate__c</fullName>
        <label>GL Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <formula>CASESAFEID(ExpenditureItem__r.ProjectTask__r.pse__Project__r.Id)</formula>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <label>Cost Distribution Line</label>
    <nameField>
        <displayFormat>Dist-{0}</displayFormat>
        <label>Cost Distribution Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Distribution Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ExpendItem__c.object
<CustomObject>
    <fields>
        <fullName>OracleProjectNumber__c</fullName>
        <formula>Project__r.OracleProjectnumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Oracle Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Cost Transactions</relationshipLabel>
        <relationshipName>ExpenditureItemsProject</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expenditure Item</label>
    <nameField>
        <displayFormat>Exp-{0}</displayFormat>
        <label>Expenditure Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenditure Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PortalMessage__c.object
<CustomObject>
    <description>Used by the ECO_Portal pages to display User Alerts, News Feed Items, and News Ticker.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LinkToRecord__c</fullName>
        <label>Link to Record</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LongDescriptionMaxLength__c</fullName>
        <label>Long Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PortalMessages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portal Message</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Portal Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectAgreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>ProjectAgreementsAgreement</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>ProjectAgreementsProject</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Agreement</label>
    <nameField>
        <displayFormat>PA-{0}</displayFormat>
        <label>Project Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Revenue__c.object
<CustomObject>
    <description>Object used to track revenue information from Oracle</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GLDate__c</fullName>
        <label>GL Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Revenue</relationshipLabel>
        <relationshipName>Revenue</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Revenue</label>
    <nameField>
        <label>Revenue Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_ProjectClosureRecommendationBatch.cls
global class ECO_ProjectClosureRecommendationBatch implements Database.Batchable<sObject>{

	private String query = 'select Id, Name, OracleProjectNumber__c, pse__Project_Manager__c, pse__Project_Manager__r.Name, CMProjectClosureIsApproved__c, Project_Manager_User__c from pse__Proj__c where pse__Stage__c != \'Closed\' and pse__End_Date__c <= TODAY';
	
    global Database.QueryLocator start(Database.BatchableContext projectClosureBatchContext)
    {   
    	System.Debug(LoggingLevel.Info, 'Query ' + query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext projectClosureBatchContext, List<pse__Proj__c> projects)
    {  	
    	map<Id, Boolean> projectFinanceMap = new map<Id, Boolean>();
    	map<Id, pse__Proj__c> projectMap = new map<Id, pse__Proj__c>();
    	map<Id, Decimal> projectAgreementTotalsMap = new map<Id, Decimal>();
    	map<Id, Decimal> projectBillingTotalsMap = new map<Id, Decimal>();
    	map<Id, Decimal> projectUnPaidTotalsMap = new map<Id, Decimal>();
    	
    	for(pse__Proj__c project:projects)
    	{
    		projectFinanceMap.put(project.Id, false);	
    		projectMap.put(project.Id, project);
    		projectBillingTotalsMap.put(project.Id, 0);
    		projectUnPaidTotalsMap.put(project.Id, 0);
    		projectAgreementTotalsMap.put(project.Id, 0);	
    	}
    	
    	Date asOfDate = Date.today().addDays(-90);
		//recent revenue    
   		for(AggregateResult ar:[select ProjectNumber__c Project from Revenue__c where ProjectNumber__c in :projects and GLDate__c > :asOfDate group by ProjectNumber__c])
   			projectFinanceMap.put((Id)ar.get('Project'), true);
   		
   		//recent billings	
   		for(AggregateResult ar:[select ProjectNumber__c Project, sum(InvoiceAmount__c) total  from Billing__c where ProjectNumber__c in :projects and InvoiceDate__c > :asOfDate group by ProjectNumber__c])
   		{
   			projectFinanceMap.put((Id)ar.get('Project'), true);	
   		}	
   		
   		//billings total
   		for(AggregateResult ar:[select ProjectNumber__c Project, sum(InvoiceAmount__c) total, sum(BalanceDue__c) totalUnpaid  from Billing__c where ProjectNumber__c in :projects group by ProjectNumber__c])
   		{
   			if(ar.get('total') != null)
   				projectBillingTotalsMap.put((Id)ar.get('Project'), (Decimal)ar.get('total'));
   			
   			if(ar.get('totalUnpaid') != null)
   				projectUnPaidTotalsMap.put((Id)ar.get('Project'), (Decimal)ar.get('totalUnpaid'));
   		}   		
   		
   		//recent costs	
   		for(AggregateResult ar:[select ExpenditureItem__r.Project__c Project from CostDistLine__c where ExpenditureItem__r.Project__c in :projects and GLDate__c > :asOfDate group by ExpenditureItem__r.Project__c])
   			projectFinanceMap.put((Id)ar.get('Project'), true);	
   			
   		map<Id, list<Id>> projectAgreementIdsMap = new map<Id, list<Id>>();
   		set<Id> agreementIds = new set<Id>();
   		for(ProjectAgreement__c projectAgreement:[select Id, Project__c, Agreement__c from ProjectAgreement__c where Project__c in :projects])
   		{
   			if(projectAgreementIdsMap.get(projectAgreement.Project__c) == null)
   				projectAgreementIdsMap.put(projectAgreement.Project__c, new list<Id>());
   			projectAgreementIdsMap.get(projectAgreement.Project__c).add(projectAgreement.Agreement__c);
   			agreementIds.add(projectAgreement.Agreement__c);
   		}
   		   			   		
		Decimal projectTotal;
   		map<Id, Agreement__c> agreementMap = new map<Id, Agreement__c>([select Id, Amount__c from Agreement__c where Id in :agreementIds]);		
 		for(pse__Proj__c project:projectMap.values())
 		{
 			projectTotal = projectAgreementTotalsMap.get(project.Id);
 			if(projectAgreementIdsMap.get(project.Id) != null)
 			{
 				for(Id agreementId:projectAgreementIdsMap.get(project.Id))
 				{
 					projectTotal += agreementMap.get(agreementId).Amount__c; 
 				}
 				projectAgreementTotalsMap.put(project.Id, projectTotal);
 			}
 		}
 		  		   			   			
		Id alertRecordTypeId = ECO_Utils_Meta.getRecordTypeId(PortalMessage__c.sObjectType, ECO_Constants.PortalMessage_AlertRecordTypeName);
		list<PortalMessage__c> alerts = new list<PortalMessage__c>();
		for(pse__Proj__c project:projectMap.values())
		{
			System.Debug('----Brent-----' + projectFinanceMap.get(project.Id));
			System.Debug('----Brent-----' + projectAgreementTotalsMap.get(project.Id));		
			System.Debug('----Brent-----' + projectBillingTotalsMap.get(project.Id));			
				
			if((!projectFinanceMap.get(project.Id)) && (projectAgreementTotalsMap.get(project.Id) == projectBillingTotalsMap.get(project.Id) && projectUnPaidTotalsMap.get(project.Id)  <= 0))
			{
   				alerts.add(new PortalMessage__c(RecordTypeId = alertRecordTypeId
   											, User__c = project.Project_Manager_User__c
   											, StartDate__c = Date.today()
   											, EndDate__c = Date.today().addDays(1)
   											, LongDescriptionMaxLength__c = 'Please considering closing this project.'
   											, Subject__c = project.Name
   											, LinkToRecord__c = '/' + project.Id
   											));    
			} 				
   		}													

		if(!alerts.isEmpty()) {
			insert alerts;
		}  
    }	
    
    global void finish(Database.BatchableContext projectClosureBatchContext)
    {   	   	
        system.debug('Batch completed');
    }  
}