src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MSATeamingPartner__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>MSA Teaming Partners</relationshipLabel>
        <relationshipName>MSA_Teaming_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MSA Teaming Partner</label>
    <nameField>
        <displayFormat>TP-{0000}</displayFormat>
        <label>MSA Teaming Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MSA Teaming Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_MSATeamingPartnerController.cls
public class ECO_MSATeamingPartnerController {
	
	public MSATeamingPartner__c msaTeamingPartner {get; set;}
	
	public ECO_MSATeamingPartnerController(ApexPages.StandardController standardController)
	{
		msaTeamingPartner = (MSATeamingPartner__c)standardController.getRecord();
	}

	public void init()
	{
		if(Apexpages.currentPage().getParameters().get('Agreement__c') != null)
		{
			msaTeamingPartner.Agreement__c = Apexpages.currentPage().getParameters().get('Agreement__c'); 		
		}
	}
	
	public PageReference save()
	{
		insert msaTeamingPartner;
		
		PageReference pageRef = new PageReference('/' + msaTeamingPartner.Agreement__c);
		return pageRef;
	}	
}