src/objects/Agreement__c.object
<CustomObject>
    <description>MSA&apos;s agreement terms</description>
    <fields>
        <fullName>AgreementNumber__c</fullName>
        <description>This is a unique identifier assigned to all Agreement Records in Ecosystem.  Use this reference for Contract Reviews.</description>
        <label>Contract Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ContractTitle__c</fullName>
        <description>Enter a Title or Name of the Contract</description>
        <inlineHelpText>Enter a Title or Name of the Contract</inlineHelpText>
        <label>Contract Title/Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>AgreementsProject</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Ecosystem Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DOAApprovalRequest__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>DOA Approval Requests</relationshipLabel>
        <relationshipName>DOAApprovalRequestsProject</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DOA Approval Request</label>
    <nameField>
        <displayFormat>DOA-{0}</displayFormat>
        <label>DOA Request For Approval Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DOA Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DOAConditions__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>DOA Conditions</relationshipLabel>
        <relationshipName>DOAConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOAApprovalRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOA Approval Request</label>
        <referenceTo>DOAApprovalRequest__c</referenceTo>
        <relationshipLabel>DOA Conditions (DOA Approval Request)</relationshipLabel>
        <relationshipName>DOAConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>DOA Conditions</relationshipLabel>
        <relationshipName>DOAConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DOA Condition</label>
    <nameField>
        <label>Condition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DOA Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_DOAConditionsOfApprovalController.cls
public with sharing class ECO_DOAConditionsOfApprovalController {
  
  public DOAConditions__c doaConditions {get; set;}
    public DOAApprovalRequest__c doaApproval {get;set;}
  public Agreement__c agreement {get; set;}
    public Id DoaApprovalId {get;set;}
    public String retVFP {get;set;}
    public Id projectId {get;set;}
  public ECO_DOAConditionsOfApprovalController(ApexPages.StandardController standardController)
  {
    doaConditions = (DOAConditions__c)standardController.getRecord();
        DoaApprovalId = ApexPages.currentPage().getParameters().get('doaId');
        retVFP = ApexPages.currentPage().getParameters().get('retvfp');
        doaApproval = new DOAApprovalRequest__c();
        System.debug('doaConditions:  '+doaConditions.Id);
        System.debug('retVFP:   '+retVFP);
  }

  public void init()
  {
    if(Apexpages.currentPage().getParameters().get('Agreement__c') != null)
    {
      doaConditions.Agreement__c = Apexpages.currentPage().getParameters().get('Agreement__c'); 
      agreement = [select Id, AgreementNumber__c, ContractTitle__c from Agreement__c where Id = :doaConditions.Agreement__c];    
    }
    //else
            //agreement = [select Id, AgreementNumber__c, ContractTitle__c from Agreement__c where Id = :doaConditions.Agreement__c];
        /*if(ApexPages.currentPage().getParameters().get('doaId') != null)
            doaConditions.DOAApprovalRequest__c = ApexPages.currentPage().getParameters().get('doaId');*/
        if(DoaApprovalId != null){
            doaApproval = [Select Id, Project__c From DOAApprovalRequest__c Where Id = :DoaApprovalId];
            doaConditions.Project__c = doaApproval.Project__c;
            doaConditions.DOAApprovalRequest__c = DoaApprovalId;
        }
            
  }
  
  public PageReference save()
  {
        try{
            PageReference pageRef;
            if(doaConditions.Id == null)
                
                insert doaConditions;
            else
                update doaConditions;
            System.debug('doaConditions id is = '+doaConditions.Id);
            System.debug('doaConditions agreement is = '+doaConditions.Agreement__c);
            if(doaConditions.DOAApprovalRequest__c != null || doaConditions.DOAApprovalRequest__c != '')
                pageRef = new PageReference('/' + doaConditions.DOAApprovalRequest__c);
            else
                pageRef = new PageReference('/'+doaConditions.Agreement__c);
            System.debug('pageRef    = '+pageRef);
            return pageRef;
        } catch (Exception e) {
              ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attempting to creating DOA Condition. Please contact your administrator with the following error: ' + e);
              ApexPages.addMessage(oMsg);
              return null;
    }
  }
    
    public PageReference returnToDOA(){
        Pagereference Pgref;
        if(doaConditions.DOAApprovalRequest__c != null || doaConditions.DOAApprovalRequest__c !=''){
            if(retVFP != null || retVFP != '')
                Pgref = new PageReference('/apex/ECO_DOAApprovals?Id=' + doaConditions.DOAApprovalRequest__c);
            else
              Pgref = new PageReference('/'+doaConditions.DOAApprovalRequest__c);
            System.debug('Pgref:   '+Pgref);
            System.debug('doaConditions.DOAApprovalRequest__c:   '+doaConditions.DOAApprovalRequest__c);
           return Pgref; 
        }
        else if((doaConditions.Agreement__c != null || doaConditions.Agreement__c != '')){
            Pgref = new PageReference('/' + doaConditions.Agreement__c);
            System.debug('Pgref:   '+Pgref);
            System.debug('doaConditions.Agreement__c:   '+doaConditions.Agreement__c);
            return Pgref; 
        }
        else 
            return null;
    }
}