src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>Questionnaire__c</fullName>
        <label>Questionnaire</label>
        <referenceTo>Questionnaire__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TemplateQuestion__c</fullName>
        <label>Template Question</label>
        <referenceTo>TemplateQuestion__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>Answer-{0000000000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ExportControl__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Export Controls</relationshipLabel>
        <relationshipName>ExportControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionnaireSet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questionnaire Set</label>
        <referenceTo>QuestionnaireSet__c</referenceTo>
        <relationshipLabel>Export Controls</relationshipLabel>
        <relationshipName>ExportControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Export Control</label>
    <nameField>
        <displayFormat>EC-{000000000}</displayFormat>
        <label>Export Control Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Export Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>DoATriggers__c</fullName>
        <label>DoA Triggers</label>
        <summaryFilterItems>
            <field>Answer__c.DoATrigger__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Answer__c.Questionnaire__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PercentComplete__c</fullName>
        <formula>CompletedAnswers__c / TotalAnswers__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percent Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProjectRisk__c</fullName>
        <label>Project Risk</label>
        <summaryFilterItems>
            <field>Answer__c.IsRisk__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Answer__c.Questionnaire__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>QuestionnaireSet__c</fullName>
        <label>QuestionnaireSet</label>
        <referenceTo>QuestionnaireSet__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QuestionnaireTemplate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>QuestionnaireTemplate</label>
        <referenceTo>QuestionnaireTemplate__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionnaireSet__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Risk and Market Assessments</relationshipLabel>
        <relationshipName>QuestionnaireSet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk and Market Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk and Market Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionnaireTemplate__c.object
<CustomObject>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Questionnaire Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TemplateQuestion__c.object
<CustomObject>
    <fields>
        <fullName>DCSSubDOA__c</fullName>
        <label>DCS Sub-DOA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnterpriseDOA__c</fullName>
        <label>Enterprise DOA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HelpText__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Help_Icon_Text__c</fullName>
        <label>Help Icon Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Indented__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Indented</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsDoATrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is DoA Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuestionSet__c</fullName>
        <label>Question Set</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>QuestionnaireTemplate__c</fullName>
        <label>Questionnaire Template</label>
        <referenceTo>QuestionnaireTemplate__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>RiskTitle__c</fullName>
        <label>Risk Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SectionPrefix__c</fullName>
        <label>Section Pre-fix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>Sort Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isDOAmaster__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDOAmaster</label>
        <type>Checkbox</type>
    </fields>
    <label>Template Question</label>
    <nameField>
        <displayFormat>TQ-{0000000000}</displayFormat>
        <label>Template Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Template Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_Utils_Questionnaire.cls
public with sharing class ECO_Utils_Questionnaire {
	public class EcoServiceException extends Exception {}

	public static list<Questionnaire__c> GetQuestionnaires(Id sQuestionnaireSetId){
		list<Questionnaire__c> lQuestionnaires = new list<Questionnaire__c>([SELECT Id, Name, ProjectRisk__c, DoATriggers__c, PercentComplete__c, QuestionnaireTemplate__c, QuestionnaireTemplate__r.Id FROM Questionnaire__c WHERE QuestionnaireSet__c = :sQuestionnaireSetId]);

		return lQuestionnaires;
	}

	public static list<QuestionnaireSet__c> GetRelatedQuestionnaireSets(Id sProjectId){
		list<QuestionnaireSet__c> lQuestionnaireSets = new list<QuestionnaireSet__c>([SELECT Id
																						   , Name
																						   , ApprovalStatus__c
																					  FROM QuestionnaireSet__c WHERE Project__c = :sProjectId]);

		return lQuestionnaireSets;
	}

	public static integer FindQuestionnaireIndex(list<Questionnaire__c> lQuestionnaires, Questionnaire__c oQuestionnaireToValidate){
		integer iIndex = 0;

		for(Questionnaire__c oQuestionnaire : lQuestionnaires){
			system.debug(oQuestionnaire.QuestionnaireTemplate__c);
			system.debug(oQuestionnaireToValidate.QuestionnaireTemplate__c);

			if(oQuestionnaireToValidate.QuestionnaireTemplate__c == oQuestionnaire.QuestionnaireTemplate__c){
				return iIndex;
			}

			iIndex++;
		}

		throw new EcoServiceException('Record Not Found');

		return iIndex;
	}

	public static list<Answer__c> GetAnswers(Id sQuestionnaireId){
		list<Answer__c> lAnswers = new list<Answer__c>([SELECT  Id
															  , Value__c
															  , TemplateQuestion__c
															  , TemplateQuestion__r.Indented__c
															  , TemplateQuestion__r.IsDoATrigger__c
															  , TemplateQuestion__r.Question__c
															  , TemplateQuestion__r.QuestionSet__c
															  , TemplateQuestion__r.SectionPrefix__c
															  , TemplateQuestion__r.SortOrder__c
															  , TemplateQuestion__r.Region__c
															  , TemplateQuestion__r.HelpText__c
															  , TemplateQuestion__r.Help_Icon_Text__c
															  , TemplateQuestion__r.RiskTitle__c
															  , TemplateQuestion__r.DCSSubDOA__c
															  , TemplateQuestion__r.EnterpriseDOA__c
															  , TemplateQuestion__r.isDOAmaster__c
														FROM Answer__c
														WHERE Questionnaire__c = :sQuestionnaireId
														ORDER BY TemplateQuestion__r.SortOrder__c]);
		return lAnswers;
	}

	public static Boolean ExportControlExists(Id sQuestionnaireSetId) 
	{
		list<ExportControl__c> lExportControls = new list<ExportControl__c>([Select Id
															, Name
															, Status__c 
													From ExportControl__c 
													WHERE QuestionnaireSet__c = :sQuestionnaireSetId]);
		if(!lExportControls.isEmpty())
		{
			return true;
		}
		return false;
	}
}