src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>DoATrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DoA Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Questionnaire__c</fullName>
        <label>Questionnaire</label>
        <referenceTo>Questionnaire__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TemplateQuestion__c</fullName>
        <label>Template Question</label>
        <referenceTo>TemplateQuestion__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>Answer-{0000000000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DOARegister__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Answer</label>
        <referenceTo>Answer__c</referenceTo>
        <relationshipLabel>DOA Register</relationshipLabel>
        <relationshipName>DOARegisterAnswer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DCSsubDOA__c</fullName>
        <label>DCS sub-DOA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOATrigger__c</fullName>
        <label>DOA Trigger</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EnterpriseDOA__c</fullName>
        <label>Enterprise DOA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>DOA Register</relationshipLabel>
        <relationshipName>DOARegister</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Questionnaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questionnaire</label>
        <referenceTo>Questionnaire__c</referenceTo>
        <relationshipLabel>DOA Register</relationshipLabel>
        <relationshipName>DOARegisterQuestionnaire</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskTitle__c</fullName>
        <label>Risk Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TemplateQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template Question</label>
        <referenceTo>TemplateQuestion__c</referenceTo>
        <relationshipLabel>DOA Register</relationshipLabel>
        <relationshipName>DOARegister</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DOA Register</label>
    <nameField>
        <displayFormat>DOA-{0}</displayFormat>
        <label>DOA Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DOA Register</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ExportControl__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Export Controls</relationshipLabel>
        <relationshipName>ExportControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionnaireSet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questionnaire Set</label>
        <referenceTo>QuestionnaireSet__c</referenceTo>
        <relationshipLabel>Export Controls</relationshipLabel>
        <relationshipName>ExportControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Export Control</label>
    <nameField>
        <displayFormat>EC-{000000000}</displayFormat>
        <label>Export Control Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Export Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MarketAssessment__c.object
<CustomObject>
    <fields>
        <fullName>QuestionnaireSet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questionnaire Set</label>
        <referenceTo>QuestionnaireSet__c</referenceTo>
        <relationshipLabel>Market Assessments</relationshipLabel>
        <relationshipName>MarketAssessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Market Assessment</label>
    <nameField>
        <label>Market Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>QuestionnaireSet__c</fullName>
        <label>QuestionnaireSet</label>
        <referenceTo>QuestionnaireSet__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QuestionnaireTemplate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>QuestionnaireTemplate</label>
        <referenceTo>QuestionnaireTemplate__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionnaireSet__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Risk and Market Assessments</relationshipLabel>
        <relationshipName>QuestionnaireSet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk and Market Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk and Market Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionnaireTemplate__c.object
<CustomObject>
    <label>Questionnaire Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Answer</label>
        <referenceTo>Answer__c</referenceTo>
        <relationshipLabel>Risks</relationshipLabel>
        <relationshipName>Risks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DoATrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Automatically ticked if the risk is a DoA trigger transferred from the Risk &amp; Market Assessment.</inlineHelpText>
        <label>DoA Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PlanElement__c</fullName>
        <inlineHelpText>Which element of the project plan of the project does this affect? Select from the drop down list.</inlineHelpText>
        <label>Plan Element</label>
        <picklist>
            <picklistValues>
                <fullName>Agreements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closeout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deliverables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resilience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scope</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SH&amp;E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stakeholders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subs/Vendors</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Risk Register</relationshipLabel>
        <relationshipName>Risks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Questionnaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questionnaire</label>
        <referenceTo>Questionnaire__c</referenceTo>
        <relationshipLabel>Risks</relationshipLabel>
        <relationshipName>Risks_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskMitigation__c</fullName>
        <inlineHelpText>Outline which measures you will employ to manage or mitigate the risk.</inlineHelpText>
        <label>Mitigation Strategy</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Risk</label>
    <nameField>
        <label>Risk Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TemplateQuestion__c.object
<CustomObject>
    <fields>
        <fullName>DCSSubDOA__c</fullName>
        <label>DCS Sub-DOA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnterpriseDOA__c</fullName>
        <label>Enterprise DOA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDoATrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is DoA Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuestionSet__c</fullName>
        <label>Question Set</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>QuestionnaireTemplate__c</fullName>
        <label>Questionnaire Template</label>
        <referenceTo>QuestionnaireTemplate__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RiskTitle__c</fullName>
        <label>Risk Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isDOAmaster__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDOAmaster</label>
        <type>Checkbox</type>
    </fields>
    <label>Template Question</label>
    <nameField>
        <displayFormat>TQ-{0000000000}</displayFormat>
        <label>Template Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Template Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_RMAQuestionnaireController.cls
public with sharing class ECO_RMAQuestionnaireController extends ECO_PageControllerBase 
{

	public Questionnaire__c oQuestionnaire {get; set;}
	public list<Questionnaire__c> lQuestionnaires {get; set;}
	public ApexPages.StandardController oStandardController {get; set;}
	public Boolean showDOASection {get; set;}
    public Boolean showDOASubSection {get; set;}
    public Answer__c DOA_SectionAnswer {get;set;}

	private integer iIndex {get; set;}

	public class EcoControllerException extends Exception {}

	public map<string, list<Answer__c>> mDoAAnswers {get; set;}
	public map<string, list<Answer__c>> mNotDoAAnswers {get; set;}
	public list<Answer__c> lAnswers {get; set;}
	public Map<Id, Risk__c> questionToRiskMap { get; set; }  // Key is TemplateQuestion__c id
    public Map<Id, DOARegister__c> questionToDOAMap { get; set; }  // Key is TemplateQuestion__c id
    public list<TemplateQuestion__c> lTemplateQuestion {get; set;}
    public list<SelectOption> lAnswerValues {get; set;}
    public list<SelectOption> lAnswerValuesBoolean {get; set;}
    public list<Answer__c> deleteAnswer {get;set;}
    public Id selectedQuestionId {get; set;}
    public Id navTargetQuestionnaireId {get;set;}

    public ECO_RMAQuestionnaireController(ApexPages.StandardController oStandardController) {
    	showDOASection = false;
    	showDOASubSection = false;
        list<string> lFields = new list<string>();
        lFields.add('QuestionnaireSet__c');
        lFields.add('QuestionnaireSet__r.Project__c');
        lFields.add('QuestionnaireTemplate__c');
        oStandardController.addFields(lFields);

        DOA_SectionAnswer = null;


        lAnswerValues = new list<SelectOption>{
            new SelectOption('Yes', 'Yes'),
            new SelectOption('No', 'No'),
            new SelectOption('Unknown', 'Unknown')
        };
        
        lAnswerValuesBoolean = new list<SelectOption>{
            new SelectOption('True', 'True'),
            new SelectOption('False', 'False')
        };

        this.oQuestionnaire = (Questionnaire__c)oStandardController.getRecord();
        this.oStandardController = oStandardController;

        if(ECO_Utils_String.NullCheck(oQuestionnaire.QuestionnaireSet__c) == ''){
			ApexPages.Message oPageMessage = new ApexPages.Message(ApexPages.Severity.WARNING,'You have reached this page improperly, please access it from the Project screen.');
            ApexPages.addMessage(oPageMessage);

            return;
		}
		//lTemplateQuestion = new list<TemplateQuestion__c>([Select id From TemplateQuestion__c where Question__c = 'Does this project trigger any DoA Items?']);
        refreshData();
    }
    
    public PageReference goToSpecificQuestionnaire () {
    	
    	doSaveAction();
    	
    	refreshData();
    	
    	PageReference oPageReference = Page.ECO_RMAQuestionnaire;

    	oPageReference.getParameters().put('Id', navTargetQuestionnaireId);
    	oPageReference.setRedirect(true);
    	
    	return oPageReference;
    }
    
    public PageReference doShowDOASection () {
    	showDOASection = true;
        showDOASubSection = true;
    	return null;
    }
    
    public PageReference doHideDOASection () {
    	showDOASection = false;
        showDOASubSection = false;
    	return null;
    }
	
    public void refreshData(){
        
    	lQuestionnaires = ECO_Utils_Questionnaire.GetQuestionnaires(oQuestionnaire.QuestionnaireSet__c);
        iIndex = ECO_Utils_Questionnaire.FindQuestionnaireIndex(lQuestionnaires, oQuestionnaire);

        lAnswers = ECO_Utils_Questionnaire.GetAnswers(oQuestionnaire.Id);

        mDoAAnswers = new map<string, list<Answer__c>>();
        mNotDoAAnswers = new map<string, list<Answer__c>>();
        questionToRiskMap = new Map<Id, Risk__c>();
        questionToDOAMap = new Map<Id, DOARegister__c>();

        for(Answer__c oAnswer : lAnswers)
        {
        	if(oAnswer.TemplateQuestion__r.IsDoATrigger__c)
            {
        		if(!mDoAAnswers.containsKey(oAnswer.TemplateQuestion__r.QuestionSet__c))
                {
                    mDoAAnswers.put(oAnswer.TemplateQuestion__r.QuestionSet__c, new list<Answer__c>());
                }

                mDoAAnswers.get(oAnswer.TemplateQuestion__r.QuestionSet__c).add(oAnswer);
                
                // Show the answers section if the section header is 'yes'
                if(oAnswer.TemplateQuestion__r.isDOAmaster__c && 'Yes'.equalsIgnoreCase(oAnswer.Value__c)) 
                {
                	doShowDOASection();
                }
				
                //Preload the DOA map
                DOARegister__c newDOA = new DOARegister__c();
                newDOA.Questionnaire__c = oQuestionnaire.Id;
                newDOA.DCSsubDOA__c = oAnswer.TemplateQuestion__r.DCSSubDOA__c;
                newDOA.EnterpriseDOA__c = oAnswer.TemplateQuestion__r.EnterpriseDOA__c;
                newDOA.DOATrigger__c = oAnswer.TemplateQuestion__r.Question__c;
                newDOA.RiskTitle__c = oAnswer.TemplateQuestion__r.RiskTitle__c;
                newDOA.TemplateQuestion__c = oAnswer.TemplateQuestion__c;
                
                //newDOA.MitigationStrategy__c = '';
                
                questionToDOAMap.put(oAnswer.TemplateQuestion__c, newDOA);
    		}
            else
            {
                if(!oAnswer.TemplateQuestion__r.isDOAmaster__c){
                    if(!mNotDoAAnswers.containsKey(oAnswer.TemplateQuestion__r.QuestionSet__c))
                    {
                        mNotDoAAnswers.put(oAnswer.TemplateQuestion__r.QuestionSet__c, new list<Answer__c>());
                    }

                    mNotDoAAnswers.get(oAnswer.TemplateQuestion__r.QuestionSet__c).add(oAnswer);
                } else {
                    DOA_SectionAnswer = oAnswer;
                    /*if(DOA_SectionAnswer.Value__c == 'True' || DOA_SectionAnswer.Value__c == 'Unknown' || DOA_SectionAnswer.Value__c == 'Yes'){
                        showDOASection = true;
                    }*/
                    DOA_SectionAnswer.Value__c = 'True';
                    
                    showDOASection = true;
                    System.debug('setting showDOASection:   '+showDOASection);
                    System.debug('oAnswer:   '+oAnswer);
                }
    		}
            // Preload the risk map
            questionToRiskMap.put(oAnswer.TemplateQuestion__c, new Risk__c());
        }
        if(mDoAAnswers.size()>0)
            showDOASubSection = true;
        System.debug('mDoAAnswers.size:   '+mDoAAnswers.size());
        System.debug('mNotDoAAnswers.size:  '+ mNotDoAAnswers.size());
        System.debug('showDOASection:   '+showDOASection);
        System.debug('showDOASubSection:   '+showDOASubSection);
        for (Risk__c r : ECO_Service_Risks.getRisksForAnswers(lAnswers)) {
        	questionToRiskMap.put(r.Answer__r.TemplateQuestion__c, r);
        }

        for (DOARegister__c d : ECO_Service_Risks.getDOAForAnswers(lAnswers)) {
            questionToDOAMap.put(d.TemplateQuestion__c, d);
        }
		
  		return;
    }
    
    public PageReference addRiskToAnswer () {
    	Risk__c newRisk = new Risk__c();
    	newRisk.Questionnaire__c = oQuestionnaire.Id;
    	newRisk.Project__c = oQuestionnaire.QuestionnaireSet__r.Project__c;
    	newRisk.PlanElement__c = oQuestionnaire.Name;
    	questionToRiskMap.put(selectedQuestionId, newRisk);
    	
    	return null;
    }
    
    public PageReference removeRiskFromAnswer () {
    	questionToRiskMap.put(selectedQuestionId, new Risk__c());
    	
    	return null;
    }

    public PageReference addDOARiskToAnswer () 
    {
        if(questionToDOAMap.containsKey(selectedQuestionId))
        {
            System.debug('addDOARiskToAnswer');
            DOARegister__c doa = questionToDOAMap.get(selectedQuestionId);
            doa.Project__c = oQuestionnaire.QuestionnaireSet__r.Project__c;
            questionToDOAMap.put(selectedQuestionId, doa);

            //add a risk for each DOA as well
            Risk__c newRisk = new Risk__c();
            newRisk.Questionnaire__c = oQuestionnaire.Id;
            newRisk.Project__c = oQuestionnaire.QuestionnaireSet__r.Project__c;
            newRisk.PlanElement__c = oQuestionnaire.Name;
            newRisk.DoATrigger__c = true;
            questionToRiskMap.put(selectedQuestionId, newRisk);

        }
        
        return null;
    }
    
    public PageReference removeDOARiskFromAnswer () 
    {
        /*
        if(questionToDOAMap.containsKey(selectedQuestionId))
        {
            DOARegister__c doa = questionToDOAMap.get(selectedQuestionId);
            doa.Project__c = '';
            
        }
        */
        questionToDOAMap.put(selectedQuestionId, new DOARegister__c());

        //remove risk for DOA as well
        questionToRiskMap.put(selectedQuestionId, new Risk__c());
        
        return null;
    }
    
    private void doSaveAction () 
    {
    	try
        {
    		markDOAAnswersAsNoIfParentIsNo();
    		
    		//oStandardController.save();
    		upsert lAnswers;
    		
    		// Create our map so we can set the answer field properly on the risks
    		Map<Id, Id> questionTemplateToAnswerMap = new Map<Id, Id>();
            Boolean ExportControlExists = ECO_Utils_Questionnaire.ExportControlExists(oQuestionnaire.QuestionnaireSet__c);
    		for (Answer__c a : lAnswers) 
            {
    			questionTemplateToAnswerMap.put(a.TemplateQuestion__c, a.Id);

                if(a.TemplateQuestion__r.RiskTitle__c == 'Export Controls' && !ExportControlExists && (a.Value__c == 'Yes' || a.Value__c == 'Unknown'))
                {
                    //create Export Control record
                    ExportControl__c oEC = new ExportControl__c(Status__c='Open', QuestionnaireSet__c=oQuestionnaire.QuestionnaireSet__c, Project__c = oQuestionnaire.QuestionnaireSet__r.Project__c);
                    insert oEC;
                    ExportControlExists = true;
                }
    		}
    		
    		cleanEmptyRisks();
    		
    		for (Id i : questionToRiskMap.keySet()) {
    			questionToRiskMap.get(i).Answer__c = questionTemplateToAnswerMap.get(i);
    		}

            for (Id i : questionToDOAMap.keySet()) {
                questionToDOAMap.get(i).Answer__c = questionTemplateToAnswerMap.get(i);
            }
            System.debug('questionToDOAMap size: ' + questionToDOAMap.size());
    		
    		upsert questionToRiskMap.values();
            upsert questionToDOAMap.values();
    	} 
        catch (Exception e) 
        {
            System.debug('doSaveAction error: ' + e.getMessage());
    		ApexPages.addMessages(e);  // TODO:  Make this pretty
    	}
    }
    
    private void markDOAAnswersAsNoIfParentIsNo () {
    	Boolean isSectionHeaderNo = false;
    	for (Answer__c a : lAnswers) 
        {
    		// Check if this is the header question for the DOA section, and if it's 'No'
    		//if (a.TemplateQuestion__r.IsDoATrigger__c 
    		if(a.TemplateQuestion__r.isDOAmaster__c
    			&& 'No'.equalsIgnoreCase(a.Value__c)) {
    				isSectionHeaderNo = true;
    				break;
    		}
    	}
    	
    	// If it is equal to 'no', our boolean is true, so let's loop over them again and set the kids to no
    	if (isSectionHeaderNo) {
    		for (Answer__c a : lAnswers) {
    			// Only set to 'no' if the type matches DOA trigger
	    	if (questionToDOAMAP.containsKey(a.TemplateQuestion__c)) {
    			a.Value__c = 'No';
    			}
    		}
    	}
    }
    
    private void cleanEmptyRisks () {
    	for (Id questionId : questionToRiskMap.keySet()) {
    		Risk__c thisRisk = questionToRiskMap.get(questionId);
    		Boolean keepThisRisk = false;
    		
    		keepThisRisk = (thisRisk.Project__c != null) ? true : false;
    		
    		if (!keepThisRisk) {
                System.debug('questionId:   '+questionId);
    			questionToRiskMap.remove(questionId);
    		}
    	}

        for (Id questionId : questionToDOAMap.keySet()) {
            DOARegister__c thisDOA = questionToDOAMap.get(questionId);
            Boolean keepThisDOA = false;
            
            keepThisDOA = (thisDOA.Project__c != null) ? true : false;
            
            if (!keepThisDOA) {
                questionToDOAMap.remove(questionId);
            }
        }
    }

    private boolean checkMitigation(){
        for(string RMKey: questionToRiskMap.keySet()){

            Risk__c risk = questionToRiskMap.get(RMKey);

            if(risk.Project__c != null && risk.DoATrigger__c==false){
                if(risk.RiskMitigation__c == '' || risk.RiskMitigation__c == null){
                    return true;
                }
            }

        }  

        return false;
    }

    public PageReference SaveNext(){


        if(checkMitigation()){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Mitigation Strategy: Validation Error: Value is required.'));
            return null;
        }

    	if(iIndex + 1 < 0){
    		throw new EcoControllerException('Error Cannot Go Next');
    	}
    	
    	iIndex++;
    	
    	system.debug('lQuestionnaires.size():  '+lQuestionnaires.size());
		
		if (lQuestionnaires.size() <= iIndex) {
			
			List<MarketAssessment__c> lMarketAssessment = [SELECT Id 
															FROM MarketAssessment__c 
															WHERE QuestionnaireSet__c = :oQuestionnaire.QuestionnaireSet__c];
			system.debug('lMarketAssessment:  '+lMarketAssessment);
			if (!lMarketAssessment.isEmpty()) {

                doSaveAction();
                refreshData();
				return new PageReference('/'+lMarketAssessment[0].Id);
			} else {
				PageReference oPageReference = Page.ECO_RMASummary;

		    	oPageReference.getParameters().put('Id', oQuestionnaire.QuestionnaireSet__c);
		    	oPageReference.setRedirect(true);
		    	
                doSaveAction();
                refreshData();
		    	return oPageReference;
			}
			
		}
    	
    	Questionnaire__c oPreviousQuestionnaire = lQuestionnaires.get(iIndex);

    	doSaveAction();

    	PageReference oPageReference = Page.ECO_RMAQuestionnaire;

    	oPageReference.getParameters().put('Id', oPreviousQuestionnaire.Id);
    	oPageReference.setRedirect(true);

    	refreshData();

    	return oPageReference;
    }

    public PageReference SavePrevious(){

        if(checkMitigation()){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Mitigation Strategy: Validation Error: Value is required.'));
            return null;
        }

    	if(iIndex - 1 < 0){
    		throw new EcoControllerException('Error Cannot Go Previous');
    	}

    	Questionnaire__c oPreviousQuestionnaire = lQuestionnaires.get(iIndex - 1);

    	doSaveAction();

    	PageReference oPageReference = Page.ECO_RMAQuestionnaire;

    	oPageReference.getParameters().put('Id', oPreviousQuestionnaire.Id);
    	oPageReference.setRedirect(true);

    	refreshData();

    	return oPageReference;
    }

    public PageReference SaveRecord(){

        if(checkMitigation()){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Mitigation Strategy: Validation Error: Value is required.'));
            return null;
        }

    	doSaveAction();

    	refreshData();

    	return null;
    }

    public PageReference ReturnToSummary(){
    	PageReference oPageReference = Page.ECO_RMASummary;

    	oPageReference.getParameters().put('Id', oQuestionnaire.QuestionnaireSet__c);
    	oPageReference.setRedirect(true);

    	refreshData();

    	return oPageReference;
    }
    public PageReference SetDefaultNo(){
        for(Answer__c oAnswer : lAnswers){
            
            if(oAnswer.TemplateQuestion__r.IsDoATrigger__c == true && (oAnswer.Value__c == '' || oAnswer.Value__c == null)){
                oAnswer.Value__c = 'No';
            }
        }
        return null;
    }
    
    
    
}