src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>BudgetName__c</fullName>
        <label>Budget Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GMNSR__c</fullName>
        <formula>IF(NetServicesRevenue__c = 0, 0,GrossMargin__c / NetServicesRevenue__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GM/NSR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>GrossMargin__c</fullName>
        <formula>TotalRevenue__c - TotalOverhead__c -  TotalFeeAmount__c -  TotalSubAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NMNSR__c</fullName>
        <formula>IF(NetServicesRevenue__c = 0, 0, NetMargin__c / NetServicesRevenue__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NM/NSR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>NetMargin__c</fullName>
        <formula>TotalRevenue__c - TotalCost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NetServicesRevenue__c</fullName>
        <formula>TotalRevenue__c -  TotalSubAmount__c -  TotalFeeAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Services Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>BudgetHeaders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclude</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work at Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotalContingencyAmount__c</fullName>
        <label>Total Contingency Amount</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>Contingency</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalFeeAmount__c</fullName>
        <label>Total Fee Amount</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>ODC/FEE</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalFringe__c</fullName>
        <label>Total Fringe</label>
        <summarizedField>BudgetResource__c.TotalFringe__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalLaborAmount__c</fullName>
        <label>Total Labor Amount</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalOverhead__c</fullName>
        <label>Total Overhead</label>
        <summarizedField>BudgetResource__c.TotalOverhead__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalRawCost__c</fullName>
        <label>Total Raw Cost</label>
        <summarizedField>BudgetResource__c.TotalRawCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalResourceAmount__c</fullName>
        <formula>TotalSubAmount__c +  TotalLaborAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Resource Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalRevenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>BudgetResource__c.TotalRevenue__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalSubAmount__c</fullName>
        <label>Total Sub Amount</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>Subcontractor</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DTO_BudgetHeaderWrapper.cls
public class DTO_BudgetHeaderWrapper {
	public List<DTO_BudgetHeader> dtoBudgetHeaders{get; set;}
    
    public Decimal getBudgetTotalRawLabour {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED, 'TotalRawCost__c');}
    }
    
    public Decimal getForecastTotalRawLabour {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST, 'TotalRawCost__c');}
    }
    
    public Decimal getWorkAtRiskTotalRawLabour {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalRawCost__c');}
    }
    
    public Decimal getBudgetTotalFringe {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED, 'TotalFringe__c');}
    }

    public Decimal getForecastTotalFringe {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST, 'TotalFringe__c');}
    }

    public Decimal getWorkAtRiskTotalFringe {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalFringe__c');}
    } 
    
    public Decimal getBudgetTotalOverhead {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED, 'TotalOverhead__c');}
    }

    public Decimal getForecastTotalOverhead {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST, 'TotalOverhead__c');}
    }

    public Decimal getWorkAtRiskTotalOverhead {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalOverhead__c');}
    }
    
    public Decimal getBudgetTotalSubAmount {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED, 'TotalSubAmount__c');}
    }

    public Decimal getForecastTotalSubAmount {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST, 'TotalSubAmount__c');}
    }

    public Decimal getWorkAtRiskTotalSubAmount {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalSubAmount__c');}
    }
    
    public Decimal getBudgetTotalFeeAmount {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED, 'TotalFeeAmount__c');}
    }

    public Decimal getForecastTotalFeeAmount {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST, 'TotalFeeAmount__c');}
    }

    public Decimal getWorkAtRiskTotalFeeAmount {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalFeeAmount__c');}
    }
    
    public Decimal getBudgetTotalCost {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED, 'TotalCost__c');}
    }

    public Decimal getForecastTotalCost {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST, 'TotalCost__c');}
    }

    public Decimal getWorkAtRiskTotalCost {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalCost__c');}
    }
    
    public Decimal getBudgetTotalRevenue {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED, 'TotalRevenue__c');}
    }

    public Decimal getForecastTotalRevenue {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST, 'TotalRevenue__c');}
    }

    public Decimal getWorkAtRiskTotalRevenue {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalRevenue__c');}
    }
    
    public Decimal getBudgetTotalNetServiceRevenue {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED, 'NetServicesRevenue__c');}
    }

    public Decimal getForecastTotalNetServiceRevenue {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST, 'NetServicesRevenue__c');}
    }

    public Decimal getWorkAtRiskTotalNetServiceRevenue {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_WORKATRISK, 'NetServicesRevenue__c');}
    }
    
    public Decimal getBudgetTotalGrossMargin {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED, 'GrossMargin__c');}
    }

    public Decimal getForecastTotalGrossMargin {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST, 'GrossMargin__c');}
    }

    public Decimal getWorkAtRiskTotalGrossMargin {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_WORKATRISK, 'GrossMargin__c');}
    }
    
    public Decimal getBudgetTotalNetMargin {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED, 'NetMargin__c');}
    }

    public Decimal getForecastTotalNetMargin {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST, 'NetMargin__c');}
    }

    public Decimal getWorkAtRiskTotalNetMargin {
        get{return calculateTotal(DTO_BudgetHeader.STATUS_WORKATRISK, 'NetMargin__c');}
    }
    
    public Decimal getBudgetTotalGMNSR {
        get{
            Integer recCount = calculateRecordsWithStatus(DTO_BudgetHeader.STATUS_APPROVED);
            if(recCount > 0)
                return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED, 'GMNSR__c')/recCount;
        	return 0.0;
        }
    }

    public Decimal getForecastTotalGMNSR {
        get{
            Integer recCount = calculateRecordsWithStatus(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST);
            if(recCount > 0)
                return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST, 'GMNSR__c')/recCount;
        	return 0.0;
        }
    }

    public Decimal getWorkAtRiskTotalGMNSR {
        get{
            Integer recCount = calculateRecordsWithStatus(DTO_BudgetHeader.STATUS_WORKATRISK);
            if(recCount > 0)
            	return calculateTotal(DTO_BudgetHeader.STATUS_WORKATRISK, 'GMNSR__c')/recCount;
        	return 0.0;
        }
    }
    
    public Decimal getBudgetTotalNMNSR {
        get{
            Integer recCount = calculateRecordsWithStatus(DTO_BudgetHeader.STATUS_APPROVED);
            if(recCount > 0)
                return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED, 'NMNSR__c')/recCount;
        	return 0.0;
        }
    }

    public Decimal getForecastTotalNMNSR {
        get{
            Integer recCount = calculateRecordsWithStatus(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST);
            if(recCount > 0)
                return calculateTotal(DTO_BudgetHeader.STATUS_APPROVED + ', ' + DTO_BudgetHeader.STATUS_FORECAST, 'NMNSR__c')/recCount;
        	return 0.0;
        }
    }

    public Decimal getWorkAtRiskTotalNMNSR {
        get{
            Integer recCount = calculateRecordsWithStatus(DTO_BudgetHeader.STATUS_WORKATRISK);
            if(recCount > 0)
            	return calculateTotal(DTO_BudgetHeader.STATUS_WORKATRISK, 'NMNSR__c')/recCount;
        	return 0.0;
        }
    }
    
    public Decimal calculateTotal(String Statuses, String field) {
        Set<String> statusList = new Set<String>(Statuses.split(','));
        
        Decimal total = 0.0;
        for(DTO_BudgetHeader budgetHeader : dtoBudgetHeaders) {
            if(statusList.contains(budgetHeader.status)) {
                total = total + (Decimal)budgetHeader.oBudgetHeader.get(field);
            }
        }
        
        return total;
    }
    
    public Integer calculateRecordsWithStatus(String Statuses) {
        Set<String> statusList = new Set<String>(Statuses.split(','));
        Integer total = 0;
        for(DTO_BudgetHeader budgetHeader : dtoBudgetHeaders) {
            if(statusList.contains(budgetHeader.status)) {
                total = total + 1;
            }
        }
        
        return total;
    }
    
    public DTO_BudgetHeaderWrapper(Id projectId) {
        dtoBudgetHeaders = new List<DTO_BudgetHeader>();
        
        List<BudgetHeader__c> budgetHeaders = [SELECT 
                                               		Id, 
                                               		BudgetName__c, 
                                               		TotalCost__c, 
                                               		TotalRevenue__c, 
                                               		TotalFeeAmount__c, 
                                               		TotalLaborAmount__c, 
                                               		TotalSubAmount__c, 
                                               		TotalContingencyAmount__c, 
                                               		TotalResourceAmount__c,
                                               		TotalRawCost__c,
                                               		TotalFringe__c,
                                               		TotalOverhead__c,
                                               	    NetServicesRevenue__c,
                                               	    GrossMargin__c,
                                               		NetMargin__c,
                                               		GMNSR__c,
                                               		NMNSR__c,
                                               		Status__c, 
                                               		CreatedDate
												FROM 
                                               		BudgetHeader__c
												WHERE 
                                               		Project__c = :projectId
												ORDER BY 
                                               		CreatedDate ASC];
        for(BudgetHeader__c budgetHeader : budgetHeaders) {
            DTO_BudgetHeader dtoBudgetHeader = new DTO_BudgetHeader(budgetHeader);
            dtoBudgetHeaders.add(dtoBudgetHeader);
        }
    }
}