src/objects/BudgetAssignment__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BudgetResource__c</fullName>
        <label>Budget Resource</label>
        <referenceTo>BudgetResource__c</referenceTo>
        <relationshipLabel>Budget Assignments</relationshipLabel>
        <relationshipName>BudgetAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BudgetTask__c</fullName>
        <label>Budget Task</label>
        <referenceTo>BudgetTask__c</referenceTo>
        <relationshipLabel>Budget Assignments</relationshipLabel>
        <relationshipName>BudgetAssignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MarginType__c</fullName>
        <label>Margin Type</label>
        <picklist>
            <picklistValues>
                <fullName>Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OverrideBillRate__c</fullName>
        <label>Override Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideFringeMultiplier__c</fullName>
        <label>Override Fringe Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OverrideOverheadMultiplier__c</fullName>
        <label>Override Overhead Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OverrideRawCost__c</fullName>
        <label>Override Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideUplift__c</fullName>
        <label>Override Uplift</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipName>BudgetLineProjectTask</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(BudgetTask__r.BudgetHeader__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Budget Assignment</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Budget Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>BudgetHeaders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclude</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work at Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetResource__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipLabel>Budget Resources</relationshipLabel>
        <relationshipName>BudgetResources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MarginType__c</fullName>
        <label>Margin Type</label>
        <picklist>
            <picklistValues>
                <fullName>Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OverrideBillRate__c</fullName>
        <label>Override Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideFringeMultiplierField__c</fullName>
        <label>Override Fringe Multiplier (Field)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OverrideFringeMultiplier__c</fullName>
        <label>Override Fringe Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OverrideOverheadMultiplierField__c</fullName>
        <label>Override Overhead Multiplier (Field)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OverrideOverheadMultiplier__c</fullName>
        <label>Override Overhead Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OverrideRatesOnLines__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Override Rates On Lines</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OverrideRawCost__c</fullName>
        <label>Override Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideUplift__c</fullName>
        <label>Override Uplift</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Budget Resources</relationshipLabel>
        <relationshipName>BudgetResources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget Resource</label>
    <nameField>
        <displayFormat>BR-{000000000}</displayFormat>
        <label>Budget Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetTask__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>BudgetTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>BudgetTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget Task</label>
    <nameField>
        <displayFormat>BT-{000000000}</displayFormat>
        <label>Budget Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BurdenSchedule__c.object
<CustomObject>
    <fields>
        <fullName>OrgID__c</fullName>
        <label>OrgID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Burden Schedule</label>
    <nameField>
        <displayFormat>BS-{0000000000}</displayFormat>
        <label>Burden Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Burden Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>If this person moves to another account: (a) change this field to &quot;No Longer with Client,&quot; (b) enter a note in the &quot;Need to Know&quot; field below, and (c) create a new Contact record under the new account.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No longer with client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the Contact to the User object.  This is for the representation of Employees.  Specifically, this is for the Shared Services Case Management.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>Burden_Reference_Schedule_Name__c</fullName>
        <label>Burden Reference Schedule Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgID__c</fullName>
        <formula>pse__Project__r.OrgId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OrgID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkTypeName__c</fullName>
        <label>Work Type Name</label>
        <picklist>
            <picklistValues>
                <fullName>Home Office</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Field Office</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_BudgetAssignmentTriggers.cls
public without sharing class ECO_BudgetAssignmentTriggers {
    public static Boolean run = true;
    
    public static void setCurrency(List<BudgetAssignment__c> baNew) {
        if (!run) {
            return;
        }

        Set<Id> btIds = new Set<Id>();
        Map<Id, BudgetTask__c> mapTasks = new Map<Id, BudgetTask__c>();

        for (BudgetAssignment__c ba : baNew) {
            btIds.add(ba.budgetTask__c);
        }   
            
        // Get project currency
        for (BudgetTask__c budgetTask : [Select Id, ProjectTask__r.WorkTypeName__c, BudgetHeader__r.Project__r.ProjectFunctionalCurrencyCode__c 
                                            From BudgetTask__c 
                                            Where Id IN :btIds]) {
            mapTasks.put(budgetTask.Id, budgetTask);
        }

         for (BudgetAssignment__c ba : baNew) {
            ba.CurrencyIsoCode = mapTasks.get(ba.BudgetTask__c).BudgetHeader__r.Project__r.ProjectFunctionalCurrencyCode__c;
            ba.WorkTypeName__c = mapTasks.get(ba.BudgetTask__c).ProjectTask__r.WorkTypeName__c;
        }
    }

    public static void setRateDefaults(List<BudgetAssignment__c> baNew) {
        if (!run) {
            return;
        }

        Set<Id> budgetResourceIds = new Set<Id>();
        for (BudgetAssignment__c ba : baNew) {
            budgetResourceIds.add(ba.BudgetResource__c);
        }
        
        Map<Id, BudgetResource__c> mapBudgetResourceById = new Map<Id, BudgetResource__c> (
                                                            [SELECT Id, 
                                                                OverrideRatesOnLines__c, 
                                                                OverrideRawCost__c, 
                                                                OverrideFringeMultiplier__c,
                                                                OverrideOverheadMultiplier__c,
                                                                OverrideFringeMultiplierField__c,
                                                                OverrideOverheadMultiplierField__c,
                                                                MarginType__c,
                                                                OverrideBillRate__c,
                                                                OverrideUplift__c  
                                                            FROM BudgetResource__c 
                                                            WHERE Id IN :budgetResourceIds]);
        

        for (BudgetAssignment__c ba : baNew) {
            BudgetResource__c br = mapBudgetResourceById.get(ba.BudgetResource__c);

            ECO_BudgetResourceTriggers.setRatesEqual(br, ba);
        }
    }

    public static void setDefaults (List<BudgetAssignment__c> baNew) {
        if (!run || !ECO_TriggerSettings.getIsTriggerEnabled('BA_setDefaults')) {
            return;
        }
        
        Set<Id> budgetResourceIds = new Set<Id>();
        for (BudgetAssignment__c ba : baNew) {
            budgetResourceIds.add(ba.BudgetResource__c);
        }
        
        Map<Id, String> budgetResourceIdToApprovalStatusMap = new Map<Id, String>();
        for (BudgetResource__c br : [SELECT Id 
                                        , BudgetHeader__r.Status__c
                                    FROM BudgetResource__c 
                                    WHERE Id IN :budgetResourceIds]) {
            budgetResourceIdToApprovalStatusMap.put(br.Id, br.BudgetHeader__r.Status__c);
        }
        
        for (BudgetAssignment__c ba : baNew) {
            ba.ApprovalStatus__c = budgetResourceIdToApprovalStatusMap.get(ba.BudgetResource__c);
        }
    }

    public static void calculateMultiplier(List<BudgetAssignment__c> baNew) {
        if (!run) {
            return;
        }

        Set<Id> baIds = new Set<Id>();

        for (BudgetAssignment__c ba : baNew) {
            baIds.add(ba.id);
        }

        List<BudgetAssignment__c> budgetAssignments = [select id, ProjectTask__r.OrgID__c, BudgetTask__r.ProjectTask__r.Burden_Reference_Schedule_Name__c, BudgetResource__r.Resource__r.User__r.ExpenditureType__c from BudgetAssignment__c where id in :baIds];

        Set<String> scheduleNames = new Set<String>();

        for (BudgetAssignment__c budgetAssignment : budgetAssignments) {
            scheduleNames.add(budgetAssignment.BudgetTask__r.ProjectTask__r.Burden_Reference_Schedule_Name__c);
        }

        List<BurdenSchedule__c> burdenSchedules = [select id, CostCode__c, CostPlusStructure__c, OracleRateScheduleName__c from BurdenSchedule__c where OracleRateScheduleName__c in :scheduleNames];

        Set<String> costPlusStructures = new Set<String>();
        Map<String, Set<String>> scheduleNameToCostPlusStructures = new Map<String, Set<String>>();

        for (BurdenSchedule__c burdenSchedule : burdenSchedules) {
            costPlusStructures.add(burdenSchedule.CostPlusStructure__c);
            
            Set<String> costPlusStructureSet = scheduleNameToCostPlusStructures.get(burdenSchedule.CostPlusStructure__c);

            if (costPlusStructureSet == null) {
                costPlusStructureSet = new Set<String>();

                scheduleNameToCostPlusStructures.put(burdenSchedule.CostPlusStructure__c, costPlusStructureSet);
            }

            costPlusStructureSet.add(burdenSchedule.OracleRateScheduleName__c);
        }

        List<BurdenStructure__c> burdenStructures = [select id, ExpenditureType__c, CostCode__c, CostPlusStructure__c from BurdenStructure__c where CostPlusStructure__c in :costPlusStructures];

        Map<String, Set<String>> costCodeMap = new Map<String, Set<String>>();

        for (BurdenStructure__c burdenStructure : burdenStructures) {
            String key = burdenStructure.CostPlusStructure__c + '~' + burdenStructure.ExpenditureType__c;

            Set<String> costCodes = costCodeMap.get(key);

            if (costCodes == null) {
                costCodes = new Set<String>();

                costCodeMap.put(key, costCodes);
            }

            costCodes.add(burdenStructure.CostCode__c);
        }

        Set<String> allCostCodes = new Set<String>();

        for (BudgetAssignment__c budgetAssignment : budgetAssignments) {
            String scheduleName = budgetAssignment.BudgetTask__r.ProjectTask__r.Burden_Reference_Schedule_Name__c;
            String expenditureType = budgetAssignment.BudgetResource__r.Resource__r.User__r.ExpenditureType__c;
            
            Set<String> costPlusStructures2 = scheduleNameToCostPlusStructures.get(scheduleName);

            for (String costPlusStructure : costPlusStructures2) {
                String key = costPlusStructure + '~' + expenditureType;

                Set<String> costCodes = costCodeMap.get(key);

                allCostCodes.addAll(costCodes);
            }
        }


        List<BurdenSchedule__c> burdenSchedules2 = [select id, CostCode__c, OrgID__c from BurdenSchedule__c where CostCode__c in :allCostCodes];

        Map<String, Set<String>> orgMap = new Map<String, Set<String>>();

        for (BurdenSchedule__c burdenSchedule : burdenSchedules2) {
            Set<String> orgIds = orgMap.get(burdenSchedule.CostCode__c);

            if (orgIds == null) {
                orgIds = new Set<String>();

                orgMap.put(burdenSchedule.CostCode__c, orgIds);
            }

            orgIds.add(burdenSchedule.OrgID__c);
        }

        for (BudgetAssignment__c budgetAssignment : budgetAssignments) {
            String scheduleName = budgetAssignment.BudgetTask__r.ProjectTask__r.Burden_Reference_Schedule_Name__c;
            String expenditureType = budgetAssignment.BudgetResource__r.Resource__r.User__r.ExpenditureType__c;
            
            Set<String> costPlusStructures2 = scheduleNameToCostPlusStructures.get(scheduleName);

            for (String costPlusStructure : costPlusStructures2) {
                String key = costPlusStructure + '~' + expenditureType;

                Set<String> costCodes = costCodeMap.get(key);

                for (String costCode : costCodes) {
                    Set<String> orgIds = orgMap.get(costCode);

                    for (String orgId : orgIds) {
                        if (orgId == budgetAssignment.ProjectTask__r.OrgID__c) {
                            System.debug('hey - ' + orgId + ' - ' + costCode + ' - ' + budgetAssignment.id);
                        }
                    }
                }
            }
        }

    }

    public static void calculateFiscalMonths(list<BudgetAssignment__c> budgetAssignments)
    {
        
        list<date> enddatelist = new list<date>();
        for (BudgetAssignment__c ba : budgetAssignments){
             if (ba.EndDate__c != null){ 
                 
                 enddatelist.add((ba.EndDate__c).addmonths(2));
                 enddatelist.add((ba.EndDate__c).addmonths(-3));
             }
        }
        system.debug('enddatelist----'+enddatelist);
         List<pse__Time_Period__c> timePeriods  = new  List<pse__Time_Period__c>();
        if(enddatelist.size()>0)
        {
            // Time period
          timePeriods = ECO_Utils_Date.calcTimePeriods(enddatelist,'Month');
          //  List<pse__Time_Period__c> timePeriods = new list<pse__Time_Period__c>([select id,TimePeriodCode__c,pse__End_Date__c,pse__Start_Date__c from pse__Time_Period__c where pse__Type__c = 'Month' and pse__Start_Date__c <=:enddatelist and pse__End_Date__c  >=:enddatelist]);
          system.debug('timePeriods ----'+timePeriods );
            pse__Time_Period__c fm = null;
            for (BudgetAssignment__c ba : budgetAssignments){
                if (ba.EndDate__c != null){ 
                    fm = ECO_Utils_Date.getFiscalPeriod(ba.EndDate__c, 0, timePeriods);  
                    system.debug('207-----'+fm);
                    if (fm != null){
                        ba.EndDateFiscalMonth__c = fm.TimePeriodCode__c;
                    }
                    
                    fm = ECO_Utils_Date.getFiscalPeriod(ba.EndDate__c, 1, timePeriods);
                     system.debug('213-----'+fm);
                    if (fm != null){
                        ba.EndDatePreviousFiscalMonth__c = fm.TimePeriodCode__c; 
                    }
                }
            }
        }
    }
}