src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>AppliedTotalRevenue__c</fullName>
        <formula>IF( OverrideTotalRevenue__c == 0,  TotalRevenue__c , OverrideTotalRevenue__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Applied Total Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetName__c</fullName>
        <label>Budget Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GMNSR__c</fullName>
        <formula>IF(NetServicesRevenue__c = 0, 0,GrossMargin__c / NetServicesRevenue__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GM/NSR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>GrossMargin__c</fullName>
        <formula>TotalRevenue__c - TotalOverhead__c -  TotalFeeAmount__c -  TotalSubAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NMNSR__c</fullName>
        <formula>IF(NetServicesRevenue__c = 0, 0, NetMargin__c / NetServicesRevenue__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NM/NSR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>NetMargin__c</fullName>
        <formula>TotalRevenue__c - TotalCost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NetServicesRevenue__c</fullName>
        <formula>TotalRevenue__c -  TotalSubAmount__c -  TotalFeeAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Services Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>BudgetHeaders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclude</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work at Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotalContingencyAmount__c</fullName>
        <label>Total Contingency Amount</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>Contingency</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalFeeAmount__c</fullName>
        <label>Total Fee Amount</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>ODC/FEE</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalFringe__c</fullName>
        <label>Total Fringe</label>
        <summarizedField>BudgetResource__c.TotalFringe__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalLaborAmount__c</fullName>
        <label>Total Labor Amount</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalOverhead__c</fullName>
        <label>Total Overhead</label>
        <summarizedField>BudgetResource__c.TotalOverhead__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalRawCost__c</fullName>
        <label>Total Raw Cost</label>
        <summarizedField>BudgetResource__c.TotalRawCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalResourceAmount__c</fullName>
        <formula>TotalSubAmount__c +  TotalLaborAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Resource Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalRevenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>BudgetResource__c.TotalRevenue__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalSubAmount__c</fullName>
        <label>Total Sub Amount</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetResource__c.ResourceType__c</field>
            <operation>equals</operation>
            <value>Subcontractor</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ChangeManager__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipName>Change_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Change Requests</relationshipLabel>
        <relationshipName>ChangeManager</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change</label>
    <nameField>
        <displayFormat>CM-{0}</displayFormat>
        <label>Change Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_DTO_BudgetHeaderWrapper.cls
public class ECO_DTO_BudgetHeaderWrapper {
	public List<ECO_DTO_BudgetHeader> dtoBudgetHeaders{get; set;}
    
    public Decimal getBudgetTotalRawLabour {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'TotalRawCost__c');}
    }
    
    public Decimal getForecastTotalRawLabour {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'TotalRawCost__c');}
    }
    
    public Decimal getWorkAtRiskTotalRawLabour {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalRawCost__c');}
    }
    
    public Decimal getBudgetTotalFringe {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'TotalFringe__c');}
    }

    public Decimal getForecastTotalFringe {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'TotalFringe__c');}
    }

    public Decimal getWorkAtRiskTotalFringe {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalFringe__c');}
    } 
    
    public Decimal getBudgetTotalOverhead {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'TotalOverhead__c');}
    }

    public Decimal getForecastTotalOverhead {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'TotalOverhead__c');}
    }

    public Decimal getWorkAtRiskTotalOverhead {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalOverhead__c');}
    }
    
    public Decimal getBudgetTotalSubAmount {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'TotalSubAmount__c');}
    }

    public Decimal getForecastTotalSubAmount {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'TotalSubAmount__c');}
    }

    public Decimal getWorkAtRiskTotalSubAmount {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalSubAmount__c');}
    }
    
    public Decimal getBudgetTotalFeeAmount {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'TotalFeeAmount__c');}
    }

    public Decimal getForecastTotalFeeAmount {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'TotalFeeAmount__c');}
    }

    public Decimal getWorkAtRiskTotalFeeAmount {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalFeeAmount__c');}
    }
    
    public Decimal getBudgetTotalContingencyAmount {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'TotalContingencyAmount__c');}
    }

    public Decimal getForecastTotalContingencyAmount {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'TotalContingencyAmount__c');}
    }

    public Decimal getWorkAtRiskTotalContingencyAmount {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalContingencyAmount__c');}
    }

    public Decimal getBudgetTotalCost {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'TotalCost__c');}
    }

    public Decimal getForecastTotalCost {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'TotalCost__c');}
    }

    public Decimal getWorkAtRiskTotalCost {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'TotalCost__c');}
    }
    
    public Decimal getBudgetTotalRevenue {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'AppliedTotalRevenue__c');}
    }

    public Decimal getForecastTotalRevenue {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'AppliedTotalRevenue__c');}
    }

    public Decimal getWorkAtRiskTotalRevenue {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'AppliedTotalRevenue__c');}
    }
    
    public Decimal getBudgetTotalNetServiceRevenue {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'NetServicesRevenue__c');}
    }

    public Decimal getForecastTotalNetServiceRevenue {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'NetServicesRevenue__c');}
    }

    public Decimal getWorkAtRiskTotalNetServiceRevenue {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'NetServicesRevenue__c');}
    }
    
    public Decimal getBudgetTotalGrossMargin {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'GrossMargin__c');}
    }

    public Decimal getForecastTotalGrossMargin {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'GrossMargin__c');}
    }

    public Decimal getWorkAtRiskTotalGrossMargin {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'GrossMargin__c');}
    }
    
    public Decimal getBudgetTotalNetMargin {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'NetMargin__c');}
    }

    public Decimal getForecastTotalNetMargin {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'NetMargin__c');}
    }

    public Decimal getWorkAtRiskTotalNetMargin {
        get{return calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'NetMargin__c');}
    }
    
    public Decimal getBudgetTotalGMNSR {
        get{
            Decimal NSR = calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'NetServicesRevenue__c');
            
            if(NSR != 0) {
                Decimal GM = calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'GrossMargin__c');    
                return (100*GM/NSR).setScale(2);
            }
        	return 0.0;
        }
    }

    public Decimal getForecastTotalGMNSR {
        get{
            Decimal NSR = calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'NetServicesRevenue__c');
            
            if(NSR != 0) {
                Decimal GM = calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'GrossMargin__c');    
                return (100*GM/NSR).setScale(2);
            }
        	return 0.0;
        }
    }

    public Decimal getWorkAtRiskTotalGMNSR {
        get{
            Decimal NSR = calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'NetServicesRevenue__c');
            
            if(NSR != 0) {
                Decimal GM = calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'GrossMargin__c');    
                return (100*GM/NSR).setScale(2);
            }            
        	return 0.0;
        }
    }
    
    public Decimal getBudgetTotalNMNSR {
        get{
            Decimal NSR = calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'NetServicesRevenue__c');
            
            if(NSR != 0) {
                Decimal NM = calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'NetMargin__c');    
                return (100*NM/NSR).setScale(2);
            }
        	return 0.0;
        }
    }

    public Decimal getForecastTotalNMNSR {
        get{
            Decimal NSR = calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'NetServicesRevenue__c');
            
            if(NSR != 0) {
                Decimal NM = calculateTotal(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'NetMargin__c');    
                return (100*NM/NSR).setScale(2);
            }
        	return 0.0;
        }
    }

    public Decimal getWorkAtRiskTotalNMNSR {
        get{
            Decimal NSR = calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'NetServicesRevenue__c');
            
            if(NSR != 0) {
                Decimal NM = calculateTotal(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'NetMargin__c');    
                return (100*NM/NSR).setScale(2);
            }

        	return 0.0;
        }
    }
    
    public Decimal getBudgetTotalsalaryCostMultiplier {
        get{
            return calculateTotalDTOproperty(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'salaryCostMultiplier').setScale(1);
        }
    }
    
    public Decimal getForecastTotalsalaryCostMultiplier {
        get{
            return calculateTotalDTOproperty(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'salaryCostMultiplier').setScale(1);
        }
    }
    
    public Decimal getWorkAtRiskTotalsalaryCostMultiplier {
        get{
            return calculateTotalDTOproperty(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'salaryCostMultiplier').setScale(1);
        }
    }
    
    public Decimal getBudgetTotalaverageLabourRatePerHour {
        get{
            return calculateTotalDTOproperty(ECO_DTO_BudgetHeader.STATUS_APPROVED, 'averageLabourRatePerHour').setScale(1);
        }
    }
    
    public Decimal getForecastTotalaverageLabourRatePerHour {
        get{
            return calculateTotalDTOproperty(ECO_DTO_BudgetHeader.STATUS_APPROVED + ',' + ECO_DTO_BudgetHeader.STATUS_FORECAST, 'averageLabourRatePerHour').setScale(1);
        }
    }
    
    public Decimal getWorkAtRiskTotalaverageLabourRatePerHour {
        get{
            return calculateTotalDTOproperty(ECO_DTO_BudgetHeader.STATUS_WORKATRISK, 'averageLabourRatePerHour').setScale(1);
        }
    }
    
    public Decimal calculateTotal(String Statuses, String field) {
        Set<String> statusList = new Set<String>(Statuses.split(','));
        
        Decimal total = 0.0;
        for(ECO_DTO_BudgetHeader budgetHeader : dtoBudgetHeaders) {
            if(statusList.contains(budgetHeader.status)) {
                total = total + (Decimal)budgetHeader.oBudgetHeader.get(field);
            }
        }
        
        return total;
    }
    
    public Decimal calculateTotalDTOproperty(String Statuses, String property) {
		Set<String> statusList = new Set<String>(Statuses.split(','));
        
        Decimal totalNum = 0.0;
        Decimal totalDen = 0.0;

        for(ECO_DTO_BudgetHeader budgetHeader : dtoBudgetHeaders) {
            if(statusList.contains(budgetHeader.status)) {
                totalNum = totalNum + budgetHeader.oBudgetHeader.NetServicesRevenue__c;
                if(property == 'salaryCostMultiplier'){
                    totalDen = totalDen + budgetHeader.directPersonnelExpenses;
                }
                else if(property == 'averageLabourRatePerHour') {
                    totalDen = totalDen + budgetHeader.oBudgetHeader.TotalLaborHours__c;
                }                
            }
        }
        
        if (totalDen != 0.0) {
            return totalNum/totalDen;
        }
        return 0.0;        
    }
    
    public Integer calculateRecordsWithStatus(String Statuses) {
        Set<String> statusList = new Set<String>(Statuses.split(','));
        Integer total = 0;
        for(ECO_DTO_BudgetHeader budgetHeader : dtoBudgetHeaders) {
            if(statusList.contains(budgetHeader.status)) {
                total = total + 1;
            }
        }
        
        return total;
    }
    
    public ECO_DTO_BudgetHeaderWrapper(Id projectId) {
        dtoBudgetHeaders = new List<ECO_DTO_BudgetHeader>();
        
        List<BudgetHeader__c> budgetHeaders = [SELECT 
                                               		Id, 
                                               		BudgetName__c, 
                                               		TotalCost__c, 
                                               		TotalRevenue__c,
                                                    AppliedTotalRevenue__c, 
                                                    TotalLaborHours__c,
                                               		TotalFeeAmount__c, 
                                               		TotalLaborAmount__c, 
                                               		TotalSubAmount__c, 
                                               		TotalContingencyAmount__c, 
                                               		TotalResourceAmount__c,
                                               		TotalRawCost__c,
                                               		TotalFringe__c,
                                               		TotalOverhead__c,
                                               	    NetServicesRevenue__c,
                                               	    GrossMargin__c,
                                               		NetMargin__c,
                                               		GMNSR__c,
                                               		NMNSR__c,
                                               		Status__c, 
                                               		CreatedDate,
                                               		(SELECT Id, RecordType.Name FROM Change_Manager__r)
												FROM 
                                               		BudgetHeader__c
												WHERE 
                                               		Project__c = :projectId
												ORDER BY 
                                               		CreatedDate ASC];
        for(BudgetHeader__c budgetHeader : budgetHeaders) {
            ECO_DTO_BudgetHeader dtoBudgetHeader = new ECO_DTO_BudgetHeader(budgetHeader);
            dtoBudgetHeaders.add(dtoBudgetHeader);
        }
    }
    
    public ECO_DTO_BudgetHeader findBudgetHeaderDTOById(Id budgetHeaderId) {
        
        for(ECO_DTO_BudgetHeader dtoBudgetHeader : dtoBudgetHeaders) {
            if(dtoBudgetHeader.oBudgetHeader.Id == budgetHeaderId) {
        		return dtoBudgetHeader;        
            }
        }
        
        return null;
    }
}