src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>BudgetName__c</fullName>
        <label>Budget Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclude</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work at Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalRevenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>BudgetResource__c.TotalRevenue__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DTO_BudgetHeader.cls
// Git Demo for DTW team - just a test
public class DTO_BudgetHeader {
	public BudgetHeader__c oBudgetHeader {get; set;}
    
    public static final String STATUS_APPROVED = 'Approved';
    public static final String STATUS_FORECAST = 'Forecast';
    public static final String STATUS_WORKATRISK = 'Work at Risk';
    
    public String budgetName{
        get {return oBudgetHeader.BudgetName__c;}
        private set;
    }
    
    public DateTime createdDate {
        get {return oBudgetHeader.CreatedDate;}
        private set;
    }
    
    public String status {
        get {return oBudgetHeader.Status__c;}
        private set;
    }
    
    public decimal dTotalCost {
        get {return oBudgetHeader.TotalCost__c;}
        private set;
    }
    
    public decimal dTotalRevenue {
        get {return oBudgetHeader.TotalRevenue__c;}
        private set;
    }
    
    public decimal dTotalApprovedCost {
        get{
            if(oBudgetHeader.Status__c == STATUS_APPROVED)
                return oBudgetHeader.TotalCost__c;
            
            return 0.0;
        }
        
        private set;
    }
    
    public decimal dTotalApprovedRevenue {
        get{
            if(oBudgetHeader.Status__c == STATUS_APPROVED)
                return oBudgetHeader.TotalRevenue__c;
            
            return 0.0;
        }
        
        private set;
    }
    
    public decimal dTotalForecastCost {
        get{
            if(oBudgetHeader.Status__c == STATUS_APPROVED || oBudgetHeader.Status__c == STATUS_FORECAST)
                return oBudgetHeader.TotalCost__c;
            
            return 0.0;
        }
        
        private set;
    }
    
    public decimal dTotalForecastRevenue {
        get{
            if(oBudgetHeader.Status__c == STATUS_APPROVED || oBudgetHeader.Status__c == STATUS_FORECAST)
                return oBudgetHeader.TotalRevenue__c;
            
            return 0.0;
        }
        
        private set;
    }
    
    public decimal dTotalWorkAtRiskCost {
        get{
            if(oBudgetHeader.Status__c == STATUS_WORKATRISK)
                return oBudgetHeader.TotalCost__c;
            
            return 0.0;
        }
        
        private set;
    }
    
    public decimal dTotalWorkAtRiskRevenue {
        get{
            if(oBudgetHeader.Status__c == STATUS_WORKATRISK)
                return oBudgetHeader.TotalRevenue__c;
            
            return 0.0;
        }
        
        private set;
    }
    
    public DTO_BudgetHeader(BudgetHeader__c o_BudgetHeader){
        oBudgetHeader = o_BudgetHeader;
    }
}