src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>BudgetName__c</fullName>
        <label>Budget Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclude</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work at Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalRevenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>BudgetResource__c.TotalRevenue__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ChangeManager__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipName>Change_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change</label>
    <nameField>
        <displayFormat>CM-{0}</displayFormat>
        <label>Change Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_DTO_BudgetHeader.cls
public class ECO_DTO_BudgetHeader {
	public BudgetHeader__c oBudgetHeader {get; set;}
    
    public Map<String, String> budgetHeaderChangeManagerMap {get; set;}
        
    public static final String STATUS_APPROVED = 'Approved';
    public static final String STATUS_FORECAST = 'Forecast';
    public static final String STATUS_WORKATRISK = 'Work at Risk';
    public static final String STATUS_ESTIMATE = 'Estimate';
    public static final String STATUS_ARCHIVE = 'Archive';

    public String budgetName{
        get {return oBudgetHeader.BudgetName__c;}
        private set;
    }
    
    public DateTime createdDate {
        get {return oBudgetHeader.CreatedDate;}
        private set;
    }
    
    public String status {
        get {return oBudgetHeader.Status__c;}
        private set;
    }
    
    public decimal dTotalCost {
        get {return oBudgetHeader.TotalCost__c;}
        private set;
    }
    
    public decimal dTotalRevenue {
        get {return oBudgetHeader.TotalRevenue__c;}
        private set;
    }
    
    public decimal dTotalApprovedCost {
        get{
            if(oBudgetHeader.Status__c == STATUS_APPROVED)
                return oBudgetHeader.TotalCost__c;
            
            return 0.0;
        }
        
        private set;
    }
    
    public decimal dTotalApprovedRevenue {
        get{
            if(oBudgetHeader.Status__c == STATUS_APPROVED)
                return oBudgetHeader.TotalRevenue__c;
            
            return 0.0;
        }
        
        private set;
    }
    
    public decimal dTotalForecastCost {
        get{
            if(oBudgetHeader.Status__c == STATUS_APPROVED || oBudgetHeader.Status__c == STATUS_FORECAST)
                return oBudgetHeader.TotalCost__c;
            
            return 0.0;
        }
        
        private set;
    }
    
    public decimal dTotalForecastRevenue {
        get{
            if(oBudgetHeader.Status__c == STATUS_APPROVED || oBudgetHeader.Status__c == STATUS_FORECAST)
                return oBudgetHeader.TotalRevenue__c;
            
            return 0.0;
        }
        
        private set;
    }
    
    public decimal dTotalWorkAtRiskCost {
        get{
            if(oBudgetHeader.Status__c == STATUS_WORKATRISK)
                return oBudgetHeader.TotalCost__c;
            
            return 0.0;
        }
        
        private set;
    }
    
    public decimal dTotalWorkAtRiskRevenue {
        get{
            if(oBudgetHeader.Status__c == STATUS_WORKATRISK)
                return oBudgetHeader.TotalRevenue__c;
            
            return 0.0;
        }
        
        private set;
    }
    
    public List<SelectOption> lstActions {
        get {
            List<SelectOption> listOptions = new List<SelectOption>();
            listOptions.add(new SelectOption('','Select Action'));
            if(oBudgetHeader.Status__c == STATUS_ESTIMATE && String.IsEmpty(budgetHeaderChangeManagerMap.get('Internal Change'))&& String.IsEmpty(budgetHeaderChangeManagerMap.get('External Change'))) {
                listOptions.add(new SelectOption('SubmitInternalChange','Submit Forecasted Change'));
            }
            
            if((oBudgetHeader.Status__c == STATUS_ESTIMATE || oBudgetHeader.Status__c == STATUS_FORECAST) && String.IsEmpty(budgetHeaderChangeManagerMap.get('External Change'))){
                listOptions.add(new SelectOption('SubmitExternalChange','Submit Approved Change'));
            }
            
            if(oBudgetHeader.Status__c != STATUS_APPROVED && oBudgetHeader.Status__c != STATUS_FORECAST 
                && oBudgetHeader.Status__c != STATUS_ARCHIVE) {
                listOptions.add(new SelectOption('ArchiveBudget','Archive Budget'));
            }

            if(oBudgetHeader.Status__c == STATUS_ARCHIVE) {
                listOptions.add(new SelectOption('UnArchiveBudget','UnArchive Budget'));
            }
           
            if(!String.IsEmpty(budgetHeaderChangeManagerMap.get('Internal Change'))) {
                listOptions.add(new SelectOption('ViewInternalChange','View Forecasted Change'));
            }
            
            if(!String.IsEmpty(budgetHeaderChangeManagerMap.get('External Change'))) {
                listOptions.add(new SelectOption('ViewExternalChange','View Approved Change'));
            }
            
            return listOptions;
        }
        
        private set;
    }
    
    public String strSelectedAction { get; set;}
    
    public ECO_DTO_BudgetHeader(BudgetHeader__c o_BudgetHeader){
        oBudgetHeader = o_BudgetHeader;
        
        budgetHeaderChangeManagerMap = new Map<String, String>();
        budgetHeaderChangeManagerMap.put('Internal Change', '');
        budgetHeaderChangeManagerMap.put('External Change', '');
        
        for(ChangeManager__c changeManager : oBudgetHeader.Change_Manager__r) {
            budgetHeaderChangeManagerMap.put(changeManager.RecordType.Name, changeManager.Id);
        }
        
    }
}