src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>BudgetName__c</fullName>
        <label>Budget Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>BudgetHeaders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclude</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work at Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <recordTypes>
        <fullName>EAC</fullName>
        <active>true</active>
        <label>EAC</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetTask__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>BudgetTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>BudgetTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskName__c</fullName>
        <label>Task Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Budget Task</label>
    <nameField>
        <displayFormat>BT-{000000000}</displayFormat>
        <label>Budget Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>pse__Parent_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup captures Task hierarchies:  sub-Tasks have a Parent Task lookup value for the next higher-level Task in the Task hierarchy.  Note that this is separate and distinct from temporal (dependent/predecessor) relationships between Tasks.</description>
        <inlineHelpText>This lookup captures Task hierarchies:  sub-Tasks have a Parent Task lookup value for the next higher-level Task in the Task hierarchy.  Note that this is separate and distinct from temporal (dependent/predecessor) relationships between Tasks.</inlineHelpText>
        <label>Parent Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Project Tasks (Child Task)</relationshipLabel>
        <relationshipName>Immediate_Sub_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project that the Task is a part of.</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_BudgetFrameController.cls
public class ECO_BudgetFrameController {
    public Id sProjectId {get; set;}
    public Id sBudgetHeaderId {get; set;}

    public String recordTypeName {get; set;}
    
    public boolean bAllowHeaderNavigation {
        get{
            if(sBudgetHeaderId == null){
                return false;
            }
            
            return true;
        }
        
        private set;
    }
    
    public boolean bHasBudgetHeader {
        get{ 
            if(sBudgetHeaderId == null){
                return false;
            }

            return true;
        }

        private set;
    }
    
    public ECO_BudgetFrameController(){
        Id sRecordId = (Id)ApexPages.currentPage().getParameters().get('Id');
        
        if(sRecordId == null){
            //Handle
            
            return;
        }
        
        String sObjName = sRecordId.getSObjectType().getDescribe().getName();

        if(sObjName == 'pse__Proj__c'){
            sProjectId = sRecordId;
            sBudgetHeaderId = null;
        }else if(sObjName == 'BudgetHeader__c'){
            sProjectId = ECO_Service_Projects.getProjectIdByBudgetHeader(sRecordId);
            sBudgetHeaderId = sRecordId;
            recordTypeName = [SELECT Id, RecordType.DeveloperName FROM BudgetHeader__c Where Id = :sBudgetHeaderId].RecordType.DeveloperName;
        }
    }
	
    public PageReference createEAC() {
        System.savePoint oSavePoint = Database.setSavepoint();

       	try {
            Id budgetHeaderId = ECO_BudgetEACService.createInitECO(sProjectId);
            
            PageReference oPageReference = Page.ECO_BudgetHeader;
            
            oPageReference.getParameters().put('Id', budgetHeaderId);
            return oPageReference;
            
        } catch (Exception e) {
            system.debug(Logginglevel.ERROR, 'Handled Exception:  ' + e.getMessage());
            system.debug(Logginglevel.ERROR, 'Handled Exception.getLineNumber:  ' + e.getLineNumber());
            Database.rollback(oSavePoint);
            ApexPages.addMessages(e);
        }
        
        return null;
    }
    
    public PageReference createChangeOrder(){
        System.savePoint oSavePoint = Database.setSavepoint();

        BudgetHeader__c oBudgetHeader = new BudgetHeader__c();

        try {
            oBudgetHeader.RecordTypeId = ECO_Utils_Meta.getRecordTypeId(BudgetHeader__c.sObjectType, 'Change Order');
            oBudgetHeader.Project__c = sProjectId;
            oBudgetHeader.Status__c = 'Estimate';

            list<BudgetHeader__c> lBudgetHeader = new list<BudgetHeader__c>([SELECT Id FROM BudgetHeader__c WHERE Project__c = :sProjectId]);

            oBudgetHeader.BudgetName__c = 'Change Order ' + lBudgetHeader.size();

            insert oBudgetHeader;
        } catch (Exception e) {
            system.debug('Handled Exception:  '+e.getMessage());
            system.debug('Handled Exception.getLineNumber:  '+e.getLineNumber());
            Database.rollback(oSavePoint);
            ApexPages.addMessages(e);
        }

        try {
            map<Id, BudgetTask__c> mBudgetTask = new map<Id, BudgetTask__c>();
            
            for (pse__Project_Task__c oProjectTask : [SELECT Id
                                                    , Name 
                                                    , (SELECT Id FROM pse__Immediate_Sub_Tasks__r)
                                            FROM pse__Project_Task__c 
                                            WHERE pse__Project__c = :sProjectId]) {

                BudgetTask__c oBudgetTask = new BudgetTask__c();
                oBudgetTask.ProjectTask__c = oProjectTask.Id;
                oBudgetTask.BudgetHeader__c = oBudgetHeader.Id;
                oBudgetTask.TaskName__c = oProjectTask.Name;
                mBudgetTask.put(oProjectTask.Id, oBudgetTask);
            }
            
            if (!mBudgetTask.isEmpty()) {
                insert mBudgetTask.values();
            }

        } catch (Exception e) {
            system.debug('Handled Exception:  '+e.getMessage());
            system.debug('Handled Exception.getLineNumber:  '+e.getLineNumber());
            Database.rollback(oSavePoint);
            ApexPages.addMessages(e);
        }


        PageReference oPageReference = Page.ECO_BudgetHeader;

        oPageReference.getParameters().put('Id', oBudgetHeader.Id);
        
        return oPageReference;
    }

    public PageReference returnToProject(){
        PageReference oPageReference = new PageReference('/' + sProjectId);
        
        return oPageReference;
    }

    public PageReference gotoSetup(){
        PageReference oPageReference = Page.ECO_BudgetQuestionnaire;
		oPageReference.getParameters().put('retURL', '/apex/ECO_BudgetHeaderSummary?id=' + sProjectId);
        oPageReference.getParameters().put('id', sProjectId);
        
        return oPageReference;
    }

    public PageReference showBudgetList(){
        PageReference oPageReference = Page.ECO_BudgetHeaderSummary;

        oPageReference.getParameters().put('id', sProjectId);
        
        return oPageReference;
    }

    public PageReference showBudgetSummary(){
        PageReference oPageReference = Page.ECO_BudgetHeader;

        oPageReference.getParameters().put('id', sBudgetHeaderId);
        
        return oPageReference;
    }

    public PageReference showTaskTab(){
        PageReference oPageReference = Page.ECO_TaskDetail;

        oPageReference.getParameters().put('id', sProjectId);
        
        return oPageReference;
    }

    public PageReference showLaborTab(){
        PageReference oPageReference;
        
        if (recordTypeName != 'EAC')
            oPageReference = Page.ECO_BudgetLabourDetail;
        else {
            oPageReference = Page.ECO_BudgetLabourEAC;
        }
        
        oPageReference.getParameters().put('id', sBudgetHeaderId);
        
        return oPageReference;
    }

    public PageReference showSubTab(){
        PageReference oPageReference = Page.ECO_BudgetSubDetail;
		
        if (recordTypeName == 'EAC') {
            oPageReference = Page.ECO_BudgetSubDetailEAC;
    	}
        oPageReference.getParameters().put('id', sBudgetHeaderId);
        
        return oPageReference;
    }

    public PageReference showODCTab(){
        PageReference oPageReference = Page.ECO_BudgetODCDetail;

        if (recordTypeName == 'EAC') {
            oPageReference = Page.ECO_BudgetODCDetailEAC;
    	}
        oPageReference.getParameters().put('id', sBudgetHeaderId);
        
        return oPageReference;
    }

    public PageReference showContTab(){
        PageReference oPageReference = Page.ECO_BudgetContingency;
        
        if (recordTypeName == 'EAC') {
            oPageReference = Page.ECO_BudgetContingencyEAC;
        }

        oPageReference.getParameters().put('id', sBudgetHeaderId);
        
        return oPageReference;
    }
}