src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>BudgetName__c</fullName>
        <label>Budget Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>BudgetHeaders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclude</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work at Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <recordTypes>
        <fullName>Baseline</fullName>
        <active>true</active>
        <label>Baseline</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetTask__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>BudgetTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>BudgetTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskName__c</fullName>
        <label>Task Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Budget Task</label>
    <nameField>
        <displayFormat>BT-{000000000}</displayFormat>
        <label>Budget Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project that the Task is a part of.</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_BudgetHeaderSummaryController.cls
public with sharing class ECO_BudgetHeaderSummaryController {
	public pse__Proj__c theProject{ get; set; }
    
    public ECO_DTO_BudgetHeaderWrapper budgetWrapper {get; set;}
    
    private Boolean isThisFirstBudget;
    
    public String selectedBudgetHeader {get; set;}
    public String selectedAction {get; set;}
    
   	public ECO_BudgetHeaderSummaryController (ApexPages.StandardController con) {
		theProject = ECO_Service_Projects.getProjectById(con.getId());
        
        if (theProject.BudgetHeaders__r.isEmpty()) {
			isThisFirstBudget = true;
		} else {
			isThisFirstBudget = false;
		}
        
        if(!isThisFirstBudget) {
        	budgetWrapper = new ECO_DTO_BudgetHeaderWrapper(theProject.Id);    
        }
    }
    
    public PageReference goToQuestionnaire () {
		PageReference pageReference = Page.ECO_BudgetQuestionnaire;
		pageReference.getParameters().put('retURL', '/apex/ECO_BudgetHeaderSummary?id='+theProject.Id);
		pageReference.getParameters().put('id', theProject.Id);
		return pageReference;
	}
    
    public PageReference onAction() {
        String bhId = Apexpages.currentPage().getParameters().get('budgetHeaderId');
        String actionSelected = Apexpages.currentPage().getParameters().get('actionSelected');
        
        system.debug('budgetHeaderId:' + bhId);
        system.debug('selectionAction:' + actionSelected);
        
        if(actionSelected == 'SubmitInternalChange') {
			Id newChangeManagerId = ECO_Service_ChangeManager.createNewInternalChangeManagerFromBudget(bhId, theProject.Id);
            PageReference changeManagerPage = new PageReference('/apex/ECO_ChangeManagerDetail?Id=' + newChangeManagerId + '&mode=Edit');
			changeManagerPage.setRedirect(true);
            return changeManagerPage;
        }
        else if (actionSelected == 'SubmitExternalChange') {
            Id newChangeManagerId = ECO_Service_ChangeManager.createNewExternalChangeManagerFromBudget(bhId, theProject.Id);
            PageReference changeManagerPage = new PageReference('/apex/ECO_ChangeManagerDetail?Id=' + newChangeManagerId + '&mode=Edit');
			changeManagerPage.setRedirect(true);
            return changeManagerPage;
        }
        else if (actionSelected == 'ViewInternalChange') {
            ECO_DTO_BudgetHeader dtoBudgetHeader = budgetWrapper.findBudgetHeaderDTOById(Id.valueOf(bhId));
            PageReference changeManagerPage = new PageReference('/apex/ECO_ChangeManagerDetail?Id=' + dtoBudgetHeader.budgetHeaderChangeManagerMap.get('Internal Change') + '&mode=Edit');
			changeManagerPage.setRedirect(true);
            return changeManagerPage;
        }
        else if(actionSelected == 'ViewExternalChange') {
            ECO_DTO_BudgetHeader dtoBudgetHeader = budgetWrapper.findBudgetHeaderDTOById(Id.valueOf(bhId));
            PageReference changeManagerPage = new PageReference('/apex/ECO_ChangeManagerDetail?Id=' + dtoBudgetHeader.budgetHeaderChangeManagerMap.get('External Change') + '&mode=Edit');
			changeManagerPage.setRedirect(true);
            return changeManagerPage;
        }
        
        PageReference pageReference = new PageReference('/apex/ECO_BudgetHeaderSummary?Id=' + theProject.Id);
        pageReference.setRedirect(true);
		return pageReference;
    }
    
    public PageReference onLoad () {
		if (theProject.DateLastCompletedBudgetQuestionnaire__c == null) {
			return goToQuestionnaire();
		}
		
		if (isThisFirstBudget) {
            System.savePoint oSavePoint = Database.setSavepoint();
            
            BudgetHeader__c oBudgetHeader = new BudgetHeader__c();
            
            try {
                oBudgetHeader.Project__c = theProject.Id;
                oBudgetHeader.BudgetName__c = 'Estimate 1';
                oBudgetHeader.RecordTypeId = ECO_Utils_Meta.getRecordTypeId(BudgetHeader__c.sObjectType, 'Baseline');
                oBudgetHeader.Status__c = 'Estimate';
                
                insert oBudgetHeader; 
            } catch (Exception e) {
                system.debug('Handled Exception:  '+e.getMessage());
                system.debug('Handled Exception.getLineNumber:  '+e.getLineNumber());
                Database.rollback(oSavePoint);
                ApexPages.addMessages(e);
            }
            
            try {
                List<BudgetTask__c> lBudgetTask = new List<BudgetTask__c>();
                
                for (pse__Project_Task__c oProjectTask : [SELECT Id, Name 
                                                		  FROM pse__Project_Task__c 
                                                		  WHERE pse__Project__c = :theProject.Id]) {
    
                    BudgetTask__c oBudgetTask = new BudgetTask__c();
                    oBudgetTask.ProjectTask__c = oProjectTask.Id;
                    oBudgetTask.BudgetHeader__c = oBudgetHeader.Id;
                    oBudgetTask.TaskName__c = oProjectTask.Name;
                    lBudgetTask.add(oBudgetTask);
                }
                
                if (!lBudgetTask.isEmpty()) {
                    insert lBudgetTask;
                }
    
            } catch (Exception e) {
                system.debug('Handled Exception:  '+e.getMessage());
                system.debug('Handled Exception.getLineNumber:  '+e.getLineNumber());
                Database.rollback(oSavePoint);
                ApexPages.addMessages(e);
            }
            
            budgetWrapper = new ECO_DTO_BudgetHeaderWrapper(theProject.Id);
		}
		
		return null;
	}
}