src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>OriginalBudget__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Original Budget</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StatusAsOfDate__c</fullName>
        <label>Status As Of Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclude</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work at Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalRevenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>BudgetResource__c.TotalRevenue__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetTask__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>BudgetTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>BudgetTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalApprovedCost__c</fullName>
        <label>Total Approved Cost</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ApprovalStatus__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalForecastCost__c</fullName>
        <label>Total Forecast Cost</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ApprovalStatus__c</field>
            <operation>equals</operation>
            <value>Forecast, Approved</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalRevenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>BudgetAssignment__c.CalculatedRevenue__c</summarizedField>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget Task</label>
    <nameField>
        <displayFormat>BT-{000000000}</displayFormat>
        <label>Budget Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EarnedValueSnapshot__c.object
<CustomObject>
    <fields>
        <fullName>AcctBurdenedCost__c</fullName>
        <label>Acct Burdened Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectFunctionalBurdenedCost__c</fullName>
        <label>Project Functional Burdened Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Earned Value Snapshots</relationshipLabel>
        <relationshipName>EarnedValueSnapshots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ThisWeekAmount__c</fullName>
        <label>This Week Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WeekStartDate__c</fullName>
        <label>Week Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WeeklyRollupEntry__c</fullName>
        <label>Weekly Rollup Entry</label>
        <referenceTo>WeeklyRollupEntry__c</referenceTo>
        <relationshipLabel>Earned Value Snapshots</relationshipLabel>
        <relationshipName>Earned_Value_Snapshots</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Earned Value Snapshot</label>
    <nameField>
        <displayFormat>EVS-{00000000}</displayFormat>
        <label>Earned Value Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Earned Value Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EarnedValueTask__c.object
<CustomObject>
    <fields>
        <fullName>EarnedValueSnapshot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Earned Value Snapshot</label>
        <referenceTo>EarnedValueSnapshot__c</referenceTo>
        <relationshipLabel>Earned Value Tasks</relationshipLabel>
        <relationshipName>EarnedValueTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EarnedValue__c</fullName>
        <formula>if (and(not(isblank(TaskTotalApprovedCostSnapshot__c)),PercentComplete__c&gt;0),
   TaskTotalApprovedCostSnapshot__c * (PercentComplete__c / 100),
   0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Earned Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Earned Value Tasks</relationshipLabel>
        <relationshipName>Earned_Value_Tasks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SnapshotDate__c</fullName>
        <label>Snapshot Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TaskTotalApprovedCostSnapshot__c</fullName>
        <label>Task Total Approved Cost Snapshot</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Earned Value Task</label>
    <nameField>
        <displayFormat>EVT-{0000000}</displayFormat>
        <label>Earned Value Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Earned Value Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExpendItem__c.object
<CustomObject>
    <fields>
        <fullName>ExpenditureItemDate__c</fullName>
        <label>Expenditure Item Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectFunctionalBurdenedCost__c</fullName>
        <label>Project Functional Burdened Cost</label>
        <summarizedField>CostDistLine__c.ProjectFunctionalBurdenedCost__c</summarizedField>
        <summaryForeignKey>CostDistLine__c.ExpenditureItem__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Expenditure Items (Project Task)</relationshipLabel>
        <relationshipName>ExpenditureItemsProjectTask</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expenditure Item</label>
    <nameField>
        <displayFormat>Exp-{0}</displayFormat>
        <label>Expenditure Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenditure Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>TotalApprovedCost__c</fullName>
        <label>Total Approved Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pse__End_Date__c</fullName>
        <formula>DATEVALUE(pse__End_Date_Time__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project that the Task is a part of.</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Time_Period__c.object
<CustomObject>
    <customHelpPage>pse__TimePeriodHelp</customHelpPage>
    <description>The divisions of time that your services organization is concerned with. Time periods have types such as Month (e.g. November 2014), Quarter (e.g. Q4 2014), Year (e.g. 2014), or Perpetual (‘All Time’). Time periods drive how actuals are categorized, how forecasting is done, how billing events are generated, and most other time-specific functions within FinancialForce PSA. Always create one perpetual time period with an end date well into the future.</description>
    <fields>
        <fullName>pse__End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Time Period</label>
    <nameField>
        <label>Time Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WeeklyRollupEntry__c.object
<CustomObject>
    <fields>
        <fullName>AcctBurdenedCost__c</fullName>
        <label>Acct Burdened Cost</label>
        <summarizedField>EarnedValueSnapshot__c.AcctBurdenedCost__c</summarizedField>
        <summaryForeignKey>EarnedValueSnapshot__c.WeeklyRollupEntry__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CPI__c</fullName>
        <formula>IF( AppliedAcctBurdenedCost__c != 0, EarnedValue__c / AppliedAcctBurdenedCost__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CPI</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EarnedValue__c</fullName>
        <label>Earned Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FiscalMonth__c</fullName>
        <description>The name of the fiscal month, following the naming convention: FY2015-01, FY2015-02, ..., FY2015-12, etc.</description>
        <inlineHelpText>The name of the fiscal month, following the naming convention: FY2015-01, FY2015-02, ..., FY2015-12, etc.</inlineHelpText>
        <label>Fiscal Month</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectFunctionalBurdenedCost__c</fullName>
        <label>Project Functional Burdened Cost</label>
        <summarizedField>EarnedValueSnapshot__c.ProjectFunctionalBurdenedCost__c</summarizedField>
        <summaryForeignKey>EarnedValueSnapshot__c.WeeklyRollupEntry__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Weekly Rollup Entry</label>
    <nameField>
        <displayFormat>WRE-{0000000}</displayFormat>
        <label>Weekly Rollup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weekly Rollup Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_Service_ProjectTask.cls
public class ECO_Service_ProjectTask{
    
    private list<Id> projectTaskIds;
    public map<string,EarnedValueSnapshot__c> earnedvaluemap{get;set;}
    public map<string,EarnedValueTask__c> earnedvaluetaskmap{get;set;}
    public ECO_Service_ProjectTask(list<Id> snapshotProjectTaskIds)
    {
        projectTaskIds = snapshotProjectTaskIds;    
        earnedvaluemap = new map<string,EarnedValueSnapshot__c>();
        earnedvaluetaskmap = new map<string,EarnedValueTask__c>();
        for(EarnedValueTask__c e: [select id,TaskTotalApprovedCostSnapshot__C,EarnedValue__c,ProjectTask__c from EarnedValueTask__c where ProjectTask__c IN :projectTaskIds and  SnapshotDate__c <= today order by SnapshotDate__c,createddate desc] ){
            if(earnedvaluetaskmap.containskey(e.ProjectTask__c))
            earnedvaluetaskmap.put(e.ProjectTask__c,e);
        }
        for(EarnedValueSnapshot__c e:[select id,ThisWeekAmount__c,ProjectTask__c,ProjectTask__r.EarnedValue__c,ProjectTask__r.TotalApprovedCost__c,WeekStartDate__c from EarnedValueSnapshot__c where   ProjectTask__c IN :projectTaskIds and WeekStartDate__c <=today order by WeekStartDate__c,createddate desc ]){
            if(earnedvaluemap.containskey(e.ProjectTask__c))
                earnedvaluemap.put(e.ProjectTask__c,e);
        }
    }
    
    public ECO_Service_ProjectTask(Id snapshotProjectTaskId)
    {
        projectTaskIds = new list<Id>();
        projectTaskIds.add(snapshotProjectTaskId);
        earnedvaluemap = new    map<string,EarnedValueSnapshot__c>();
         earnedvaluetaskmap = new map<string,EarnedValueTask__c>();
        for(EarnedValueTask__c e: [select id,TaskTotalApprovedCostSnapshot__C,ProjectTask__c,EarnedValue__c from EarnedValueTask__c where ProjectTask__c = :snapshotProjectTaskId and  SnapshotDate__c <= today order by SnapshotDate__c,createddate desc] ){
            if(earnedvaluetaskmap.containskey(e.ProjectTask__c))
            earnedvaluetaskmap.put(e.ProjectTask__c,e);
        }
        for(EarnedValueSnapshot__c e:[select id,ThisWeekAmount__c,ProjectTask__c,ProjectTask__r.EarnedValue__c,ProjectTask__r.TotalApprovedCost__c,WeekStartDate__c from EarnedValueSnapshot__c where   ProjectTask__c = :snapshotProjectTaskId and WeekStartDate__c <=today order by WeekStartDate__c,createddate desc ]){
            if(earnedvaluemap.containskey(e.ProjectTask__c))
                earnedvaluemap.put(e.ProjectTask__c,e);
        }
    }
        
    public List<pse__Project_Task__c> getProjectTasks()
    {
        
        List<pse__Project_Task__c> tasks = null;

        try {
            
            List<pse__Time_Period__c> timePeriods = ECO_ProjectTaskService.calcTimePeriods;
            
            Map<String,AggregateResult> originalBudget = getOriginalBudgetInformation();
            Map<String,AggregateResult> currentBudget = getCurrentBudgetInformation();
            Map<String,AggregateResult> forecastBudget = getForecastBudgetInformation(timePeriods);
            
            Date threeMonthsAgoFiscalEndDate = getMonthEndDate3FiscalMonthsAgo(timePeriods);
            Map<String,AggregateResult> ITD3Months = getITD3Months(threeMonthsAgoFiscalEndDate);
            
            tasks = [select Id,MetricsDate__c,
                            RevenueBudgetOriginal__c,  // ok
                            RevenueBudgetCurrent__c,  // select TotalRevenue__c from BudgetTask where and BudgetHeader__r.status=approved   
                            CostBudgetOriginal__c,   // ok
                            CostPrevMTD__c,         // ok 
                            CostMTD__c,             //ok
                            TotalForecastCostPrevME__c,         //Select TotalForecastCost__c from BudgetTask where BudgetHeader.Status=forecast and BudgetHeader.date is in previous fiscal month or earlier
                            EarnedValue__c,                     // ???
   							CPI__c,
                            MonthEndDate3FiscalMonthsAgo__c,
                            CostITD3FiscalMonthEndsAgo__c,
                            EndDateFiscalMonth__c,
                            EndDatePreviousFiscalMonth__c
                        from pse__Project_Task__c 
                        where Id = : projectTaskIds];
                        
            List<String> months = new List<String>();
            for (pse__Project_Task__c pt : tasks){
                if (!String.isBlank(pt.EndDateFiscalMonth__c)){
                    months.add(pt.EndDateFiscalMonth__c);
                }
                if (!String.isBlank(pt.EndDatePreviousFiscalMonth__c)){
                    months.add(pt.EndDatePreviousFiscalMonth__c);
                }
            } 
                
            Map<String, AggregateResult> costMTD = getCostMTDInformation(months);
           
            for (pse__Project_Task__c pt : tasks){
                if(originalBudget.containskey(pt.Id))
                pt.RevenueBudgetOriginal__c = (Decimal) originalBudget.get(pt.Id).get('totalRevenue');
                if(currentBudget.containskey(pt.Id))
                pt.RevenueBudgetCurrent__c = (Decimal) currentBudget.get(pt.Id).get('totalRevenue');
                if(originalBudget.containskey(pt.Id))
                pt.CostBudgetOriginal__c = (Decimal) originalBudget.get(pt.Id).get('totalCost');
                if(costMTD.containskey(pt.Id + pt.EndDatePreviousFiscalMonth__c))
                {
                    pt.CostPrevMTD__c = (Decimal) costMTD.get(pt.Id + pt.EndDatePreviousFiscalMonth__c).get('totalCost');                
                    pt.CostMTD__c = (Decimal) costMTD.get(pt.Id + pt.EndDateFiscalMonth__c).get('totalCost');
                }
                if(forecastBudget.containskey(pt.Id))
                pt.TotalForecastCostPrevME__c = (Decimal) forecastBudget.get(pt.Id).get('totalCost');
                pt.EarnedValue__c = null;
                pt.MonthEndDate3FiscalMonthsAgo__c = threeMonthsAgoFiscalEndDate;
                 if(ITD3Months.containskey(pt.Id))
                pt.CostITD3FiscalMonthEndsAgo__c =  (Decimal) ITD3Months.get(pt.Id).get('totalCost');
                if(earnedvaluemap.containskey(pt.id))
                    pt.PlannedCost__c = earnedvaluetaskmap.get(pt.id).TaskTotalApprovedCostSnapshot__C;
                if(earnedvaluemap.containskey(pt.id))
                    pt.PlannedValue__c = earnedvaluemap.get(pt.id).ThisWeekAmount__c;
                if(earnedvaluemap.containskey(pt.id))
                   pt.EarnedValue__c = earnedvaluetaskmap.get(pt.id).EarnedValue__c;
                pt.MetricsDate__c = date.today();
                 
            } 
            
        } catch (Exception e) {
            system.debug('e---------'+e);
            System.debug(e.getStackTraceString());
        }
        return tasks;
    }
    
    private Map<String, AggregateResult> getOriginalBudgetInformation() {
    
        try {
            List<AggregateResult> results = [SELECT     ProjectTask__c, 
                                                        SUM(TotalRevenue__c)totalRevenue, 
                                                        SUM(TotalCost__c)totalCost 
                                                        FROM BudgetTask__c 
                                                        WHERE BudgetHeader__r.OriginalBudget__c = true 
                                                        AND ProjectTask__c IN :projectTaskIds
                                                        GROUP BY ProjectTask__c]; 
           
            Map<String, AggregateResult> out = new Map<String, AggregateResult>();
            for (AggregateResult ar : results){
                out.put((String)ar.get('ProjectTask__c'), ar);
            }
            return out;
           
        } catch(Exception e) {
            System.Debug(e.getStackTraceString());
        }   
        return null;
    }
    
    private Map<String,AggregateResult> getCurrentBudgetInformation() {
        try {
            List<AggregateResult> results = [SELECT     ProjectTask__c, 
                                                        SUM(TotalRevenue__c)totalRevenue
                                                        FROM BudgetTask__c 
                                                        WHERE BudgetHeader__r.Status__c = 'Approved' 
                                                        AND ProjectTask__c IN :projectTaskIds
                                                        GROUP BY ProjectTask__c]; 
           
            Map<String, AggregateResult> out = new Map<String, AggregateResult>();
            for (AggregateResult ar : results){
                out.put((String)ar.get('ProjectTask__c'), ar);
            }
            return out;
           
        } catch(Exception e) {
            System.Debug(e.getStackTraceString());
        }   
        return null;
    }
    
    private Map<String, AggregateResult> getCostMTDInformation(List<String> months) {
        
        try {
            
            List<AggregateResult> results = [SELECT     ProjectTask__c,
                                                        WeeklyRollupEntry__r.FiscalMonth__c,
                                                        SUM(AcctBurdenedCost__c)totalCost
                                                        FROM EarnedValueSnapshot__c
                                                        WHERE ProjectTask__c IN :projectTaskIds
                                                        AND WeeklyRollupEntry__r.FiscalMonth__c IN :months
                                                        GROUP BY ProjectTask__c, WeeklyRollupEntry__r.FiscalMonth__c]; 
           
            Map<String, AggregateResult> out = new Map<String, AggregateResult>();
            for (AggregateResult ar : results){
                out.put((String)ar.get('ProjectTask__c')  + (String)ar.get('FiscalMonth__c'), ar);
            }
            return out;
           
        } catch(Exception e) {
            System.Debug(e.getStackTraceString());
        }   
        return null;
    }
    
    private Map<String, AggregateResult> getEarnedValueInformation(List<String> months) {
        
        try {
            /*
            if(evHeaders.size() > 0){
                
                if(snapshots.size() > 0)
                {
                    //earnedValueController = new ECO_EarnedValueReportController(evHeaders[0].Id);
                
                    list<AggregateResult> earnedValueTasks = [SELECT    ProjectTask__c,
                                                                        MAX(SnapshotDate__c)snapshotDate
                                                                 FROM EarnedValueTask__c
                                                                 WHERE ProjectTask__c = : projectTaskIds
                                                                 GROUP BY ProjectTask__c];
                    //list<EarnedValueSnapshot__c> snapshots = [SELECT Id, WeekStartDate__c FROM EarnedValueSnapshot__c WHERE WeekStartDate__c <= TODAY AND ProjectTask__r.pse__Project__c = :snapshotProjectId order by WeekStartDate__c desc];
                    if(earnedValueTasks.size() > 0)
                    {
                        EarnedValueSnapshotDate = earnedValueTasks[0].SnapshotDate__c;
                        EarnedValueLastModifiedDate = earnedValueTasks[0].LastModifiedDate;
                    }
                }
            }*/
            
            List<AggregateResult> results = [SELECT     ProjectTask__c,
                                                        WeeklyRollupEntry__r.FiscalMonth__c,
                                                        SUM(AcctBurdenedCost__c)totalCost
                                                        FROM EarnedValueSnapshot__c
                                                        WHERE ProjectTask__c IN :projectTaskIds
                                                        AND WeeklyRollupEntry__r.FiscalMonth__c IN :months
                                                        GROUP BY ProjectTask__c, WeeklyRollupEntry__r.FiscalMonth__c]; 
           
            Map<String, AggregateResult> out = new Map<String, AggregateResult>();
            for (AggregateResult ar : results){
                out.put((String)ar.get('ProjectTask__c')  + (String)ar.get('FiscalMonth__c'), ar);
            }
            return out;
           
        } catch(Exception e) {
            System.Debug(e.getStackTraceString());
        }   
        return null;
    }
    
    private Map<String, AggregateResult> getForecastBudgetInformation(List<pse__Time_Period__c> timePeriods) {
    
        try {
            Date now = Date.Today();
            Date previousFMEndDate = null;
            
            pse__Time_Period__c previousFM = ECO_Utils_Date.getFiscalPeriod(now, 1, timePeriods); 
            if (previousFM != null){
                previousFMEndDate = previousFM.pse__End_Date__c;  
            }
                                                    
            List<AggregateResult> results = [SELECT     ProjectTask__c, 
                                                        SUM(TotalForecastCost__c)totalCost 
                                                        FROM BudgetTask__c 
                                                        WHERE ProjectTask__c IN :projectTaskIds
                                                        AND BudgetHeader__r.Status__c = 'Forecast'
                                                        AND BudgetHeader__r.StatusAsOfDate__c <=: previousFMEndDate
                                                        GROUP BY ProjectTask__c]; 
           
            Map<String, AggregateResult> out = new Map<String, AggregateResult>();
            for (AggregateResult ar : results){
                out.put((String)ar.get('ProjectTask__c'), ar);
            }
            return out;
           
        } catch(Exception e) {
            System.Debug(e.getStackTraceString());
        }   
        return null;
    }
    
    private Date getMonthEndDate3FiscalMonthsAgo(List<pse__Time_Period__c> timePeriods) {
    
        try {
            Date now = Date.Today();
            Date returnDate = null;
            
            pse__Time_Period__c threeMonthsAgoFM = ECO_Utils_Date.getFiscalPeriod(now, 3, timePeriods); 
            if (threeMonthsAgoFM != null){
                returnDate = threeMonthsAgoFM.pse__End_Date__c;
            }
            
            return returnDate;
       } catch(Exception e) {
            System.Debug(e.getStackTraceString());
       }   
       return null;
    }
    
     
     private Map<String, AggregateResult> getITD3Months(Date threeMonthsAgoFiscalEndDate) {
    
        try {
                                                    
            List<AggregateResult> results = [SELECT     ProjectTask__c, 
                                                        SUM(ProjectFunctionalBurdenedCost__c)totalCost 
                                                        FROM ExpendItem__c 
                                                        WHERE ProjectTask__c IN :projectTaskIds
                                                        AND ExpenditureItemDate__c <= : threeMonthsAgoFiscalEndDate
                                                        GROUP BY ProjectTask__c]; 
           
            Map<String, AggregateResult> out = new Map<String, AggregateResult>();
            for (AggregateResult ar : results){
                out.put((String)ar.get('ProjectTask__c'), ar);
            }
            return out;
           
        } catch(Exception e) {
            System.Debug(e.getStackTraceString());
        }   
        return null;
    }
    
}