src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>BudgetHeaders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetResource__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipLabel>Budget Resources</relationshipLabel>
        <relationshipName>BudgetResources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <summarizedField>BudgetAssignment__c.EndDate__c</summarizedField>
        <summaryForeignKey>BudgetAssignment__c.BudgetResource__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>JobName__c</fullName>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverrideBillRate__c</fullName>
        <label>Override Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideRatesOnLines__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Override Rates On Lines</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OverrideRawCost__c</fullName>
        <label>Override Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideUplift__c</fullName>
        <label>Override Uplift</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProjectTeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Team Member</label>
        <referenceTo>ProjectTeamMember__c</referenceTo>
        <relationshipName>BudgetColumns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResourceName__c</fullName>
        <label>Resource Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResourceType__c</fullName>
        <label>Resource Type</label>
        <picklist>
            <picklistValues>
                <fullName>Labor/Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subcontractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODC/FEE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingency</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Budget Resources</relationshipLabel>
        <relationshipName>BudgetResources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget Resource</label>
    <nameField>
        <displayFormat>BR-{000000000}</displayFormat>
        <label>Budget Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Used in reporting, to determine number of contacts associated with an account.</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JobName__c</fullName>
        <label>Job Name</label>
        <picklist>
            <picklistValues>
                <fullName>Queen Bee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Accountant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foreman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Designer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OrganizationBusinessLine__c</fullName>
        <formula>OrganizationString__r.BusinessLineName__c</formula>
        <label>Organization Business Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationRegion__c</fullName>
        <formula>OrganizationString__r.Region__c</formula>
        <label>Organization Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationString__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization String</label>
        <referenceTo>OrganizationString__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Default_Cost_Rate__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Default Cost Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ECO_Job_Name__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ECO Job Name</label>
</CustomObject>

src/objects/OrganizationString__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLineName__c</fullName>
        <label>Business Line Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Organization String</label>
    <nameField>
        <label>Organization String Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization String</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectRole__c.object
<CustomObject>
    <label>Project Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays only PSA resouces</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>PSA Resource</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Contact__r.pse__Salesforce_User__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <formula>Contact__r.pse__Salesforce_User__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Role</label>
        <referenceTo>ProjectRole__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersRole</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Project Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Director 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Accountant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Accountant Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Lead 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFO or Delegate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discipline Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HS&amp;E Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000000}</displayFormat>
        <label>Project Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_AddResourceController2.cls
public with sharing class ECO_AddResourceController2 {
	public String budgetHeaderId {
		get;

		set {
			if (budgetHeaderId == null) {
				budgetHeaderId = value;

				init();
			}
		}
	}

	public BudgetHeader__c budgetHeader {get; set;}
	public pse__Proj__c theProject {get; set;}

	public List<SelectOption> allProjectTeamMembers {get; set;}

	public String selectedProjectTeamMember {get; set;}

	public List<ECO_DTO_ProjectTeamMember> members {get; set;}

	public String jobNameSelections {get; set;}
	public String jobNameJSON {get; set;}

	public List<SelectOption> businessLineChoices {get; set;}
	public List<SelectOption> regionChoices {get; set;}

	public String businessLineSelection {get; set;}
	public String regionSelection {get; set;}

	public String searchFirstName {get; set;}
	public String searchLastName {get; set;}
	public String searchRole {get; set;}
	public String searchPhone {get; set;}
	public String searchEmail {get; set;}

	public String thesoql {get; set;}

	public String memberids {get; set;}

	public List<ProjectTeamMember__c> memberList {get; set;}

	public List<Contact> contacts {get; set;}

	public ECO_AddResourceController2() {
	}

	public void init() {
		budgetHeader = [select id, Project__c from BudgetHeader__c where id = :budgetHeaderId];

		System.debug(LoggingLevel.ERROR, 'budget header id - ' + budgetHeader.id);

		if (budgetHeader.id == null)
			return;

		theProject = [select id, DefaultBillRate__c, DefaultUpliftLabor__c from pse__Proj__c where id = :budgetHeader.Project__c];

		populateProjectTeam();
		populateOrganizationStrings();
		populateJobNameChoices();

		contacts = new List<Contact>();
	}

	private String notNull(String value1, String value2, String value3) {
		if (value1 != null)
			return value1;

		if (value2 != null)
			return value2;

		return value3;
	}

	public void populateProjectTeam () {
		Id projid = theProject.id;

		memberList = [select id, role__c, projectrole__r.name, name__c, name, startdate__c, enddate__c, Phone__c, Email__c from projectteammember__c where project__c = :projid order by name, projectrole__r.name];
	}

	public void findResource() {
		String soql = 'select id, firstname, lastname, phone, email from Contact';

		Boolean added = false;

		if ((searchFirstName != null) && (!searchFirstName.trim().equals(''))) {
			soql += ' where firstname like \'%' + searchFirstName.trim() + '%\'';
			added = true;
		}

		if ((searchLastName != null) && (!searchLastName.trim().equals(''))) {
			if (added)
				soql += ' and';
			else
				soql += ' where';

			soql += ' lastname like \'%' + searchLastName.trim() + '%\'';

			added = true;
		}

		if ((searchPhone != null) && (!searchPhone.trim().equals(''))) {
			if (added)
				soql += ' and';
			else
				soql += ' where';

			soql += ' Phone like \'%' + searchPhone.trim() + '%\'';

			added = true;
		}

		if ((searchEmail != null) && (!searchEmail.trim().equals(''))) {
			if (added)
				soql += ' and';
			else
				soql += ' where';

			soql += ' Email like \'%' + searchEmail.trim() + '%\'';

			added = true;
		}

		soql += ' order by lastname, firstname';

		System.debug(LoggingLevel.ERROR, 'the soql - ' + soql);

		if (added)
			contacts = Database.query(soql);
		else
			contacts = new List<Contact>();
	}

/*
	public void populateProjectTeam () {
		members = new List<ECO_DTO_ProjectTeamMember>();

		allProjectTeamMembers = new List<SelectOption>();

		allProjectTeamMembers.add(new SelectOption('', '--- Choose a Team Member ---'));

		List<String> names = new List<String>();
		Map<String, Id> nameMap = new Map<String, Id>();

		Id projid = theProject.id;

		String soql = 'select id, role__c, projectrole__r.name, name__c, name, startdate__c, enddate__c, Phone__c, Email__c from projectteammember__c where project__c = :projid';

		if ((searchName != null) && (!searchName.trim().equals(''))) {
			soql += ' and name like \'%' + searchName.trim() + '%\'';
		}

		if ((searchRole != null) && (!searchRole.trim().equals(''))) {
			soql += ' and ProjectRole__r.name like \'%' + searchRole.trim() + '%\'';
		}

		if ((searchPhone != null) && (!searchPhone.trim().equals(''))) {
			soql += ' and Phone__c like \'%' + searchPhone.trim() + '%\'';
		}

		if ((searchEmail != null) && (!searchEmail.trim().equals(''))) {
			soql += ' and Email__c like \'%' + searchEmail.trim() + '%\'';
		}

		soql += ' order by name, projectrole__r.name';

		System.debug(LoggingLevel.ERROR, 'the soql - ' + soql);

		thesoql = soql;

		List<ProjectTeamMember__c> memberList = Database.query(soql);
		
		for (ProjectTeamMember__c ptm : memberList) {
			String roleName = notNull(ptm.ProjectRole__r.name, ptm.Role__c, 'no role');

			String name = notNull(ptm.name__c, ptm.name, 'no name');

			name += ' (' + roleName + ')';

			names.add(name);
			nameMap.put(name, ptm.Id);

			members.add(new ECO_DTO_ProjectTeamMember(ptm));
		}

		names.sort();

		for (String name : names) {
			allProjectTeamMembers.add(new SelectOption(nameMap.get(name), name));
		}
	}
*/	

	public void populateOrganizationStrings() {
		Map<String, String> businessLineMap = new Map<String, String>();
		Map<String, String> regionMap = new Map<String, String>();

		if ((jobNameSelections == null) || (jobNameSelections.trim().equals(''))) {
			List<OrganizationString__c> orgStrings = [select id, BusinessLineName__c, Region__c from OrganizationString__c where (BusinessLineName__c != null) or (Region__c != null)];

			for (OrganizationString__c orgString : orgStrings) {
				if (orgString.BusinessLineName__c != null)
					businessLineMap.put(orgString.BusinessLineName__c, orgString.id);

				if (orgString.Region__c != null)
					regionMap.put(orgString.Region__c, orgString.id);	
			}
		} else {
			List<Contact> contacts = [select id, OrganizationBusinessLine__c, OrganizationRegion__c from Contact where JobName__c = :jobNameSelections and ((OrganizationBusinessLine__c != null) or (OrganizationRegion__c != null))];

			for (Contact con : contacts) {
				if (con.OrganizationBusinessLine__c != null)
					businessLineMap.put(con.OrganizationBusinessLine__c, con.OrganizationBusinessLine__c);

				if (con.OrganizationRegion__c != null)
					regionMap.put(con.OrganizationRegion__c, con.OrganizationRegion__c);	
			}
		}

		List<String> businessLineList = new List<String>(businessLineMap.keySet());
		List<String> regionList = new List<String>(regionMap.keySet());

		businessLineList.sort();
		regionList.sort();

		businessLineChoices = new List<SelectOption>();

		businessLineChoices.add(new SelectOption('', 'Select Business Line (optional)'));

		for (String s : businessLineList) {
			businessLineChoices.add(new SelectOption(businessLineMap.get(s), s));
		}

		regionChoices = new List<SelectOption>();

		regionChoices.add(new SelectOption('', 'Select Region (optional)'));

		for (String s : regionList) {
			regionChoices.add(new SelectOption(regionMap.get(s), s));
		}
	}

	private void populateJobNameChoices() {
		Map<String, ECO_Job_Name__c> jobNames = ECO_Job_Name__c.getAll();

		List<String> listt = new List<String>();

		for (ECO_Job_Name__c jobName : jobNames.values()) {
			listt.add(jobName.name__c);
		}

		listt.sort();

		jobNameJSON = '[';

		Boolean first = true;

		for (String s : listt) {
			if (s.indexOf('"') != -1)
				continue;  // TODO - probably shouldn't skip, maybe escape is a better option

			if (!first)
				jobNameJSON += ',';

			jobNameJSON += '"' + s + '"';

			first = false;

			//jobNameChoices.add(new SelectOption(s, s));
		}

		jobNameJSON += ']';
   	}

	public PageReference addExistingResource() {
		List<String> memberidsList = memberids.split(',');

		List<ProjectTeamMember__c> membersTemp = [select id, Contact__c from ProjectTeamMember__c where id in :memberidsList];

		Map<Id, Id> membersMap = new Map<Id, Id>();

		for (ProjectTeamMember__c member : membersTemp) {
			membersMap.put(member.id, member.Contact__c);
		}

		List<BudgetResource__c> toAdd = new List<BudgetResource__c>();

		System.debug(LoggingLevel.ERROR, 'here 1');

/*
		for (ECO_DTO_ProjectTeamMember member : members) {
			if (!member.selected)
				continue;
*/

		for (String memberid : memberidsList) {
//			System.debug(LoggingLevel.ERROR, 'here 2 - ' + member.member.id);	

			BudgetResource__c newBudgetColumn = new BudgetResource__c();

			newBudgetColumn.BudgetHeader__c = budgetHeader.id;
			newBudgetColumn.OverrideRatesOnLines__c = true;
			newBudgetColumn.ResourceType__c = 'Labor/Person';

			newBudgetColumn.OverrideBillRate__c = theProject.DefaultBillRate__c;
			newBudgetColumn.OverrideUplift__c = theProject.DefaultUpliftLabor__c;
			newBudgetColumn.JobName__c = null;
			newBudgetColumn.Resource__c = membersMap.get(memberid);

//			newBudgetColumn.ProjectTeamMember__c = member.member.id;
			newBudgetColumn.ProjectTeamMember__c = memberid;

			toAdd.add(newBudgetColumn);
		}

//		insert newBudgetColumn;
		insert toAdd;

		System.debug(LoggingLevel.ERROR, 'here 3 - ' + toAdd.size());

		PageReference pr = new PageReference('/apex/ECO_BudgetLabourDetail?id=' + budgetHeader.id);
		pr.setRedirect(true);

		return pr;
	}

	public PageReference addFoundResource() {
		return null;
	}

	public Double computeAverageCostRate() {
		populateOrganizationStrings();

		String soql = 'select id, pse__Default_Cost_Rate__c from Contact where JobName__c = :jobNameSelections';

		if ((businessLineSelection != null) && (businessLineSelection != '')) {
			soql += ' and OrganizationBusinessLine__c = :businessLineSelection';
		}

		if ((regionSelection != null) && (regionSelection != '')) {
			soql += ' and OrganizationRegion__c = :regionSelection';
		}

		List<Contact> contacts = null;

		try {
			contacts = Database.query(soql);
		} catch (Exception ex) {

		}

		Double acc = 0;
		Double ct = 0;

		for (Contact con : contacts) {
			if (con.pse__Default_Cost_Rate__c > 0) {
				acc += con.pse__Default_Cost_Rate__c;
				ct++;
			}
		}

		if (ct > 0)
			return acc / ct;

		return 0.0;	
	}

	public PageReference addGenericResource() {
		BudgetResource__c newBudgetColumn = new BudgetResource__c();

		newBudgetColumn.BudgetHeader__c = budgetHeader.id;
		newBudgetColumn.OverrideRatesOnLines__c = true;
		newBudgetColumn.ResourceType__c = 'Labor/Person';

		newBudgetColumn.ResourceName__c = null;
		newBudgetColumn.ProjectTeamMember__c = null;
		newBudgetColumn.OverrideRawCost__c = computeAverageCostRate();
		newBudgetColumn.JobName__c = jobNameSelections;
		newBudgetColumn.OverrideUplift__c = theProject.DefaultUpliftLabor__c;

		insert newBudgetColumn;

		PageReference pr = new PageReference('/apex/ECO_BudgetLabourDetail?id=' + budgetHeader.id);
		pr.setRedirect(true);

		return pr;
	}
}