src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>BudgetHeaders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <recordTypes>
        <fullName>EAC</fullName>
        <active>true</active>
        <label>EAC</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetTask__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>BudgetTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Budget Task</label>
    <nameField>
        <displayFormat>BT-{000000000}</displayFormat>
        <label>Budget Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_BudgetHeaderController.cls
public with sharing class ECO_BudgetHeaderController {
	public ApexPages.StandardController stdController {get; set;}

	public Id headerId {get; set;}

	public List<ECO_DTO_BudgetTask> tasks {get; set;}

	public ECO_DTO_BudgetTask totalRow {get; set;}
    
    public String projectCurrency {get; set;}
    public String laborPage {get; set;}
    public String subPage {get; set;}
    public String odcPage {get; set;}
    public String contingencyPage {get; set;}
    
    public pse__Proj__c theProject { get; set; }

	public ECO_BudgetHeaderController(ApexPages.StandardController stdController) {
		this.stdController = stdController;

		List<String> fields = new List<String>();

		fields.add('Project__c');

		stdController.addFields(fields);

		headerId = stdController.getId();

		reload();
        
        BudgetHeader__c budgetHeader = [SELECT Id, Project__c, RecordType.DeveloperName FROM BudgetHeader__c WHERE Id =: headerId];
        String recordTypeName = budgetHeader.RecordType.DeveloperName;
        if (recordTypeName != 'EAC') {
            laborPage = 'ECO_BudgetLabourDetail';
            subPage = 'ECO_BudgetSubDetail';
            odcPage = 'ECO_BudgetODCDetail';
            contingencyPage = 'ECO_BudgetContingency';
        } else {
            laborPage = 'ECO_BudgetLabourEAC';
            subPage = 'ECO_BudgetSubDetailEAC';
            odcPage = 'ECO_BudgetODCDetailEAC';
            contingencyPage = 'ECO_BudgetContingencyEAC';
        }

        theProject = ECO_Service_Projects.getProjectById(budgetHeader.Project__c);
	}
	
    public PageReference saveBudget() {
        stdController.save();
        
        List<BudgetTask__c> budgetTasks = new List<BudgetTask__c>();
        
        for (ECO_DTO_BudgetTask task : tasks) {
            budgetTasks.add(task.obudgetTask);
        }
        
        update budgetTasks;
        
        return null;
    }
    
	public void reload() {
		tasks = ECO_BudgetTaskService.getBudgetTaskList(headerId);

		totalRow = ECO_BudgetTaskService.getTotalRow(tasks);
	}
}