src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>BudgetHeaders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetResource__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipLabel>Budget Resources</relationshipLabel>
        <relationshipName>BudgetResources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExpenditureType__c</fullName>
        <label>Expenditure Type</label>
        <picklist>
            <picklistValues>
                <fullName>LAB - Fringe Reversal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAB - Sick Leave Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAB - Other Fringe Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingency - Gen Cond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cont Adj - Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cont Adj - Gen Cond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingency - Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Dues &amp; Mems - Unallowed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Emp Relation Exp-Unallowed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Dues &amp; Mems - Allowed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Housing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Living Allowance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Medical Exp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Professional Licenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Relocation - Allowed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Relocation - Unallowed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-School Allowance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Union Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Dues &amp; Mems-Allowed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Commissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Completion Bonus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Deferred Compensation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Employee Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Seminars/Conferences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMP-Recruiting Costs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FRI-Applied Fringe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FRI - Billable Fringe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FRI - Actual Fringe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OverrideFringeMultiplier__c</fullName>
        <label>Override Fringe Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OverrideOverheadMultiplier__c</fullName>
        <label>Override Overhead Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OverrideRatesOnLines__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Override Rates On Lines</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OverrideRawCost__c</fullName>
        <label>Override Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideUplift__c</fullName>
        <label>Override Uplift</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProjectTeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Team Member</label>
        <referenceTo>ProjectTeamMember__c</referenceTo>
        <relationshipName>BudgetColumns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResourceType__c</fullName>
        <label>Resource Type</label>
        <picklist>
            <picklistValues>
                <fullName>Labor/Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subcontractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODC/FEE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingency</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Budget Resource</label>
    <nameField>
        <displayFormat>BR-{000000000}</displayFormat>
        <label>Budget Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Used in reporting, to determine number of contacts associated with an account.</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpenditureType__c</fullName>
        <label>Expenditure Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pse__Default_Cost_Rate__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Default Cost Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ExpenditureType__c.object
<CustomObject>
    <fields>
        <fullName>ResourceType__c</fullName>
        <label>Resource Type</label>
        <picklist>
            <picklistValues>
                <fullName>SUBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Expenditure Type</label>
    <nameField>
        <label>Expenditure Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenditure Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays only PSA resouces</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>PSA Resource</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000000}</displayFormat>
        <label>Project Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_BudgetResourceTriggers.cls
public without sharing class ECO_BudgetResourceTriggers {
	public static Boolean run = true;
	
	// runs before insert
	public static void defaultCostRevenueValuesOnHeader (List<BudgetResource__c> budResToDefault) {
		if (!run || !ECO_TriggerSettings.getIsTriggerEnabled('BR_setDefaults')) {
			return;
		}
		
		Set<Id> allBudgetHeaderIds = new Set<Id>();
		Set<Id> allResourceIds = new Set<Id>();
		Set<String> allExpenditureTypes = new Set<String>();
		
		
		for (BudgetResource__c br : budResToDefault) {
			allBudgetHeaderIds.add(br.BudgetHeader__c);
			allResourceIds.add(br.ProjectTeamMember__c);
			allExpenditureTypes.add(br.ExpenditureType__c);
		}
		
		Map<Id, BudgetHeader__c> headerMap = new Map<Id, BudgetHeader__c>([SELECT Id 
																					, Project__r.DefaultUpliftLabor__c
																					, Project__r.DefaultUpliftSubs__c
																					, Project__r.DefaultUpliftODCs__c
																			FROM BudgetHeader__c
																			WHERE Id IN :allBudgetHeaderIds]);
																			
		Map<Id, ProjectTeamMember__c> resourceMap = new Map<Id, ProjectTeamMember__c>([SELECT Id
																								, Contact__r.pse__Default_Cost_Rate__c
																								, Contact__r.ExpenditureType__c
																						FROM ProjectTeamMember__c
																						WHERE Id IN :allResourceIds]);
		
		
		
		
		
		
		for (BudgetResource__c br : budResToDefault) {
			BudgetHeader__c thisBH = headerMap.get(br.BudgetHeader__c);
			
			if (thisBH != null) {
				if ('Labor/Person'.equalsIgnoreCase(br.ResourceType__c)) {
					br.OverrideUplift__c = thisBH.Project__r.DefaultUpliftLabor__c;
				} else if ('Subcontractor'.equalsIgnoreCase(br.ResourceType__c)) {
					br.OverrideUplift__c = thisBH.Project__r.DefaultUpliftSubs__c;
				} else if ('ODC/FEE'.equalsIgnoreCase(br.ResourceType__c)) {
					br.OverrideUplift__c = thisBH.Project__r.DefaultUpliftODCs__c;
				}
				
				// Old style, we replaced this with the stuff above
				//br.OverrideUplift__c = thisBH.Project__r.DefaultUplift__c;
			}
			
			ProjectTeamMember__c thisResource = resourceMap.get(br.ProjectTeamMember__c);
			
			if (thisResource != null) {
				system.debug('thisResource:  '+thisResource);
				system.debug('thisResource.pse__Default_Cost_Rate__c:  '+thisResource.Contact__r.pse__Default_Cost_Rate__c);
				
				br.OverrideRawCost__c = thisResource.Contact__r.pse__Default_Cost_Rate__c;
				
				br.ExpenditureType__c = thisResource.Contact__r.ExpenditureType__c;
			}
			
			
			// TODO:  These are totally temporary and need to be replaced with the burden schedule complex logic
			br.OverrideFringeMultiplier__c = 50;
			br.OverrideOverheadMultiplier__c = 50;
			
			br.OverrideRatesOnLines__c = true;
			
		}
		
		
	}
}