src/objects/BudgetAssignment__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BudgetResource__c</fullName>
        <label>Budget Resource</label>
        <referenceTo>BudgetResource__c</referenceTo>
        <relationshipLabel>Budget Assignments</relationshipLabel>
        <relationshipName>BudgetAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(BudgetTask__r.BudgetHeader__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Budget Assignment</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Budget Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>BudgetHeaders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclude</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work at Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalRevenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>BudgetResource__c.TotalRevenue__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetResource__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipLabel>Budget Resources</relationshipLabel>
        <relationshipName>BudgetResources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryForeignKey>BudgetAssignment__c.BudgetResource__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalRevenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>BudgetAssignment__c.CalculatedRevenue__c</summarizedField>
        <summaryForeignKey>BudgetAssignment__c.BudgetResource__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget Resource</label>
    <nameField>
        <displayFormat>BR-{000000000}</displayFormat>
        <label>Budget Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_BudgetHeaderTriggers.cls
public without sharing class ECO_BudgetHeaderTriggers {
	public static Boolean run = true;
	
	public static void setCurrency(List<BudgetHeader__c> newBHList) {
    	if (!run) {
    		return;
    	}

    	Id projId = newBHList[0].Project__c;
    	// Get project currency
        pse__Proj__c proj = [Select Id, CurrencyIsoCode From pse__Proj__c Where Id = :projId];


        String projectCurrency = proj.CurrencyIsoCode;

        for (BudgetHeader__c bh : newBHList) {
        	bh.CurrencyIsoCode = projectCurrency;
            
        }
    }
	public static void cascadeApprovalStatus (Map<Id, BudgetHeader__c> bhNew, Map<Id, BudgetHeader__c> bhOld) {
		if (!run || !ECO_TriggerSettings.getIsTriggerEnabled('BH_cascadeApproval')) {
			return;
		}
		
		Set<Id> budgetHeaderIdsThatChangedStatus = new Set<Id>();
		
		for (BudgetHeader__c bh : bhNew.values()) {
			if (bh.Status__c != bhOld.get(bh.Id).Status__c) {  // Safe, since we always run after update.
				budgetHeaderIdsThatChangedStatus.add(bh.Id);
			}
		}
		
		List<BudgetAssignment__c> budgetAssignmentsToUpdate = new List<BudgetAssignment__c>();
		
		for (BudgetResource__c br : [SELECT Id 
											, (SELECT Id 
													, BudgetResource__r.BudgetHeader__r.Status__c
												FROM BudgetAssignments__r)
										FROM BudgetResource__c 
										WHERE BudgetHeader__c IN :budgetHeaderIdsThatChangedStatus]) {
			for (BudgetAssignment__c ba : br.BudgetAssignments__r) {
				ba.ApprovalStatus__c = ba.BudgetResource__r.BudgetHeader__r.Status__c;
				budgetAssignmentsToUpdate.add(ba);
			}
		}
		
		if (!budgetAssignmentsToUpdate.isEmpty()) {
			update budgetAssignmentsToUpdate;
		}
	}
	
	public static void rollUpValuesToProject (List<BudgetHeader__c> newBHList, List<BudgetHeader__c> oldBHList) {
		if (!run || !ECO_TriggerSettings.getIsTriggerEnabled('BH_rollUpToProject')) {
			return;
		}
		
		Map<Id, pse__Proj__c> projectsToUpdate = new Map<Id, pse__Proj__c>();
		
		for (BudgetHeader__c bh : newBHList) {
			projectsToUpdate.put(bh.Project__c, new pse__Proj__c(Id = bh.Project__c
																, TotalApprovedRevenue__c = 0
																, TotalApprovedCost__c = 0
																, TotalForecastRevenue__c = 0
																, TotalForecastCost__c = 0));
		}
		
		for (BudgetHeader__c bh : oldBHList) {
			projectsToUpdate.put(bh.Project__c, new pse__Proj__c(Id = bh.Project__c
																, TotalApprovedRevenue__c = 0
																, TotalApprovedCost__c = 0
																, TotalForecastRevenue__c = 0
																, TotalForecastCost__c = 0));
		}
		
		for (AggregateResult ar : [SELECT Project__c
											, SUM(TotalRevenue__c) totalRevenue
											, SUM(TotalCost__c) totalCost
									FROM BudgetHeader__c
									WHERE Project__c IN :projectsToUpdate.keySet()
										AND Status__c = 'Approved'
									GROUP BY Project__c]) {
			pse__Proj__c projToUpdate = projectsToUpdate.get((Id)ar.get('Project__c'));
			projToUpdate.TotalApprovedRevenue__c = (Decimal)ar.get('totalRevenue');
			projToUpdate.TotalApprovedCost__c = (Decimal)ar.get('totalCost');
		}
		
		for (AggregateResult ar : [SELECT Project__c
											, SUM(TotalRevenue__c) totalRevenue
											, SUM(TotalCost__c) totalCost
									FROM BudgetHeader__c
									WHERE Project__c IN :projectsToUpdate.keySet()
										AND Status__c = 'Forecast'
									GROUP BY Project__c]) {
			pse__Proj__c projToUpdate = projectsToUpdate.get((Id)ar.get('Project__c'));
			projToUpdate.TotalForecastRevenue__c = (Decimal)ar.get('totalRevenue') + projToUpdate.TotalApprovedRevenue__c;
			projToUpdate.TotalForecastCost__c = (Decimal)ar.get('totalCost') + projToUpdate.TotalApprovedCost__c;
		}
		

		update projectsToUpdate.values(); // This will always have values in it... no need to check for isempty
		
	}
}