src/objects/BudgetTask__c.object
<CustomObject>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>BudgetTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalContingencyRevenue__c</fullName>
        <label>Total Contingency Revenue</label>
        <summarizedField>BudgetAssignment__c.CalculatedRevenue__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ResourceTypeText__c</field>
            <operation>equals</operation>
            <value>Contingency</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalContingency__c</fullName>
        <label>Total Contingency</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ResourceTypeText__c</field>
            <operation>equals</operation>
            <value>Contingency</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalFringe__c</fullName>
        <label>Total Fringe</label>
        <summarizedField>BudgetAssignment__c.TotalFringe__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ResourceTypeText__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalFullyBurdenedLaborRate__c</fullName>
        <label>Total Fully Burdened Labor Rate</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ResourceTypeText__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalLaborCost__c</fullName>
        <label>Total Labor Cost</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ResourceTypeText__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalLaborHours__c</fullName>
        <label>Total Labor Hours</label>
        <summarizedField>BudgetAssignment__c.Quantity__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ResourceTypeText__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalLaborRevenue__c</fullName>
        <label>Total Labor Revenue</label>
        <summarizedField>BudgetAssignment__c.CalculatedRevenue__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ResourceTypeText__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalODCCost__c</fullName>
        <label>Total ODC Cost</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ResourceTypeText__c</field>
            <operation>equals</operation>
            <value>ODC/FEE</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalODCRevenue__c</fullName>
        <label>Total ODC Revenue</label>
        <summarizedField>BudgetAssignment__c.CalculatedRevenue__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ResourceTypeText__c</field>
            <operation>equals</operation>
            <value>ODC/FEE</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalOverhead__c</fullName>
        <label>Total Overhead</label>
        <summarizedField>BudgetAssignment__c.TotalOverhead__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ResourceTypeText__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalRawCost__c</fullName>
        <label>Total Raw Cost</label>
        <summarizedField>BudgetAssignment__c.TotalRawCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ResourceTypeText__c</field>
            <operation>equals</operation>
            <value>Labor/Person</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalRevenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>BudgetAssignment__c.CalculatedRevenue__c</summarizedField>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalSubCost__c</fullName>
        <label>Total Sub Cost</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ResourceTypeText__c</field>
            <operation>equals</operation>
            <value>Subcontractor</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalSubRevenue__c</fullName>
        <label>Total Sub Revenue</label>
        <summarizedField>BudgetAssignment__c.CalculatedRevenue__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ResourceTypeText__c</field>
            <operation>equals</operation>
            <value>Subcontractor</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget Task</label>
    <nameField>
        <displayFormat>BT-{000000000}</displayFormat>
        <label>Budget Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>ProjectTaskNumber__c</fullName>
        <label>Project Task Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pse__Parent_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup captures Task hierarchies:  sub-Tasks have a Parent Task lookup value for the next higher-level Task in the Task hierarchy.  Note that this is separate and distinct from temporal (dependent/predecessor) relationships between Tasks.</description>
        <inlineHelpText>This lookup captures Task hierarchies:  sub-Tasks have a Parent Task lookup value for the next higher-level Task in the Task hierarchy.  Note that this is separate and distinct from temporal (dependent/predecessor) relationships between Tasks.</inlineHelpText>
        <label>Parent Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Project Tasks (Child Task)</relationshipLabel>
        <relationshipName>Immediate_Sub_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project that the Task is a part of.</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_DTO_BudgetTask.cls
public class ECO_DTO_BudgetTask {
    public BudgetTask__c obudgetTask {get; set;}
    
    public Id id {
        get{return obudgetTask.ProjectTask__c;}
        private set;
    }
    
    public Id parentTaskId {
        get{return obudgetTask.ProjectTask__r.pse__Parent_Task__c;} 
        private set;
    }
    
    public String name {
        get{return obudgetTask.Name;} 
        private set;
    }
    
    public String taskNumber {
        get{return obudgetTask.ProjectTask__r.ProjectTaskNumber__c;} 
        private set;
    }
    
    public String taskName {
        get{return obudgetTask.ProjectTask__r.Name;} 
        private set;
    }

    public String budgetCostStrategy {
        get { 
            return obudgetTask.ProjectTask__r.pse__Project__r.BudgetStrategy__c; }
        private set;
    }
    private  Map<String, Decimal> values;

    public Decimal totalContingency {
    	get; 

    	set {
    		values.put('totalContingency', value);
    		totalContingency = value;
    	}
    }

    public Decimal totalContingencyRevenue {
    	get;

    	set {
    		values.put('totalContingencyRevenue', value);
    		totalContingencyRevenue = value;
    	}
    }

    public Decimal totalCost {
    	get;

    	set {
    		values.put('totalCost', value);
    		totalCost = value;
    	}
    }

    public Decimal totalComputedCost {
    	get;

    	set {
    		values.put('totalComputedCost', value);
    		totalComputedCost = value;
    	}
    }
    
    public Decimal totalFringe {
    	get;

    	set {
    		values.put('totalFringe', value);
    		totalFringe = value;
    	}
    }
    
    public Decimal totalFullyBurdenedLaborRate {
    	get;

    	set {
    		values.put('totalFullyBurdenedLaborRate', value);
    		totalFullyBurdenedLaborRate = value;
    	}
    }
    
    public Decimal totalLaborHours {
    	get { return isNull(totalLaborHours).setScale(1); }

    	set {
    		values.put('totalLaborHours', value);
    		totalLaborHours = value;
    	}
    }
    
    public Decimal totalODCCost {
    	get { return isNull(totalODCCost).setScale(2); }

    	set {
    		values.put('totalODCCost', value);
    		totalODCCost = value;
    	}
    }

    public Decimal totalODCRevenue {
    	get { return isNull(totalODCRevenue).setScale(2); }
    	
    	set {
    		values.put('totalODCRevenue', value);
    		totalODCRevenue = value;
    	}
    }

    public Decimal totalOverhead {
    	get { return isNull(totalOverhead).setScale(2); }

    	set {
    		values.put('totalOverhead', value);
    		totalOverhead = value;
    	}
    }
    
    public Decimal totalRawCost {
    	get { return isNull(totalRawCost).setScale(2); }

    	set {
    		values.put('totalRawCost', value);
    		totalRawCost = value;
    	}
    }
    
    public Decimal totalRevenue {
    	get { return isNull(totalRevenue).setScale(2); }

    	set {
    		values.put('totalRevenue', value);
    		totalRevenue = value;
    	}
    }
    
    public Decimal totalSubCost {
    	get { return isNull(totalSubCost).setScale(2); }

    	set {
    		values.put('totalSubCost', value);
    		totalSubCost = value;
    	}
    }

    public Decimal totalSubRevenue {
    	get { return isNull(totalSubRevenue).setScale(2); }

    	set {
    		values.put('totalSubRevenue', value);
    		totalSubRevenue = value;
    	}
    }
    
    public Decimal totalLabourCost {
    	get { return isNull(totalLabourCost).setScale(2); }
    
    	set {
    		values.put('totalLabourCost', value);
    		totalLabourCost = value;
    	}
    }

    public Decimal totalLabourRevenue {
        get { return isNull(totalLabourRevenue).setScale(2); }

        set {
            values.put('totalLabourRevenue', value);
            totalLabourRevenue = value;
        }   
    }

    public Decimal totalEACActualCost {
    	get { return isNull(totalEACActualCost).setScale(2); }

    	set {
    		values.put('totalEACActualCost', value);
    		totalEACActualCost = value;
    	}
    }


    public Decimal totalEACActualQuantity {
        get { return isNull(totalEACActualQuantity).setScale(2); }

        set {
            values.put('totalEACActualQuantity', value);
            totalEACActualQuantity = value;
        }
    }

    public Decimal totalEACApprovedQuantity {
        get { return isNull(totalEACApprovedQuantity).setScale(2); }

        set {
            values.put('totalEACApprovedQuantity', value);
            totalEACApprovedQuantity = value;
        }
    }

    public Decimal totalEACApprovedTotalCost {
        get { return isNull(totalEACApprovedTotalCost).setScale(2); }

        set {
            values.put('totalEACApprovedTotalCost', value);
            totalEACApprovedTotalCost = value;
        }
    }


    public Decimal totalEACForecastQuantity {
        get { return isNull(totalEACForecastQuantity).setScale(2); }

        set {
            values.put('totalEACForecastQuantity', value);
            totalEACForecastQuantity = value;
        }
    }

    public Decimal totalEACForecastRevenue {
        get { return isNull(totalEACForecastRevenue).setScale(2); }

        set {
            values.put('totalEACForecastRevenue', value);
            totalEACForecastRevenue = value;
        }
    }

    public Decimal totalEACForecastTotalCost {
        get { return isNull(totalEACForecastTotalCost).setScale(2); }

        set {
            values.put('totalEACForecastTotalCost', value);
            totalEACForecastTotalCost = value;
        }
    }

    public Decimal isNull(Decimal val) {
        Decimal retVal = val == null ? 0.00 : val;

        return retVal;
    }

    public Boolean hasChildren {
        get {
            return children.size() > 0 ? true: false;
        }
        private set;
    }

    public Boolean getIsEditable() {
        
        if (budgetCostStrategy == 'Project Level') 
            return false;

        if (!hasChildren && 
            budgetCostStrategy == 'Bottom Task') 
        {
            return true;
        }

        if (parentTaskId == null && 
            budgetCostStrategy == 'Top Task') 
        {
            return true;
        }

        return false;
    }

    public Boolean getIsVisible() {

        if (budgetCostStrategy == 'Project Level') 
            return false;

        if (hasChildren && 
            budgetCostStrategy == 'Bottom Task')
                return true;

        return false;
        /*
        if (parentTaskId == null &&
            obudgetTask.ProjectTask__r.pse__Project__r.BudgetStrategy__c == 'Top Task') 
        {
            return true;
        }

        return false;
        */
    }

    public Boolean showProject {
        get {
            return obudgetTask.ProjectTask__r.pse__Project__r.BudgetStrategy__c == 'Project Level';
        }
        private set;
    }
    public  ECO_DTO_BudgetTask parent {get; set;}
    public  List<ECO_DTO_BudgetTask> children {get; set;}
    public  Integer indentLevel {get; set;}

    public  String parentClasses {get; set;}

    public ECO_DTO_BudgetTask() {
    	values = new Map<String, Decimal>();
        children = new List<ECO_DTO_BudgetTask>();

        totalComputedCost = 0;
    }

    public ECO_DTO_BudgetTask(pse__Project_Task__c projectTask) {
        this();
        obudgetTask = new BudgetTask__c();
        obudgetTask.ProjectTask__c = projectTask.Id;
        obudgetTask.ProjectTask__r = projectTask;

        totalComputedCost = 0;
    }
    
    public ECO_DTO_BudgetTask(BudgetTask__c budgetTask) {
        obudgetTask = budgetTask;

    	values = new Map<String, Decimal>();

    	totalComputedCost = 0;
        
        totalContingency = obudgetTask.TotalContingency__c;
        totalContingencyRevenue = obudgetTask.TotalContingencyRevenue__c;
        totalCost = budgetTask.TotalCost__c;
        totalFringe = budgetTask.TotalFringe__c;
        totalFullyBurdenedLaborRate = budgetTask.TotalFullyBurdenedLaborRate__c;
        totalLaborHours = budgetTask.TotalLaborHours__c;
        totalODCCost = budgetTask.TotalODCCost__c;
        totalODCRevenue = budgetTask.TotalODCRevenue__c;

        totalOverhead = budgetTask.TotalOverhead__c;
        totalRawCost = budgetTask.TotalRawCost__c;
        totalRevenue = budgetTask.TotalRevenue__c;
        totalSubCost = budgetTask.TotalSubCost__c;
        totalSubRevenue = budgetTask.TotalSubRevenue__c;
        totalLabourCost = budgetTask.TotalLaborCost__c;
        totalLabourRevenue = budgetTask.TotalLaborRevenue__c;

        children = new List<ECO_DTO_BudgetTask>();
    }

    public Decimal getValueByName(String name) {
    	Decimal result = values.get(name);

    	if (result == null)
    		result = 0.0;

    	return result;
    }

    public void addChild(ECO_DTO_BudgetTask child) {
        children.add(child);
        child.parent = this;
    }

    public Decimal getSubtaskTotal(String fieldName) {
        return getSubtaskTotal(fieldName, true);
    }

    public Decimal getSubtaskTotal(String fieldName, boolean includeThis) {
        Decimal result = 0;

        if (includeThis && (children.size() == 0)) {
//            result += (Decimal) obudgetTask.get(fieldName);
			result += getValueByName(fieldName);
        }

        for (ECO_DTO_BudgetTask child : children) {
            result += child.getSubtaskTotal(fieldName);
        }

        return result;
    }
}