src/objects/BudgetAssignment__c.object
<CustomObject>
    <fields>
        <fullName>BudgetResource__c</fullName>
        <label>Budget Resource</label>
        <referenceTo>BudgetResource__c</referenceTo>
        <relationshipLabel>Budget Assignments</relationshipLabel>
        <relationshipName>BudgetAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FullyBurdenedCostRate__c</fullName>
        <description>OverrideRawCost__c *  OverrideFringeMultiplier__c *  OverrideOverheadMultiplier__c</description>
        <formula>OverrideRawCost__c + (OverrideRawCost__c *  OverrideFringeMultiplier__c )
+
 (OverrideRawCost__c *  OverrideOverheadMultiplier__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fully Burdened Cost Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MarginType__c</fullName>
        <label>Margin Type</label>
        <picklist>
            <picklistValues>
                <fullName>Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OverrideBillRate__c</fullName>
        <label>Override Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideFringeMultiplier__c</fullName>
        <label>Override Fringe Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OverrideOverheadMultiplier__c</fullName>
        <label>Override Overhead Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OverrideRawCost__c</fullName>
        <label>Override Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideUplift__c</fullName>
        <label>Override Uplift</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ResourceType__c</fullName>
        <formula>TEXT(BudgetResource__r.ResourceType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Resource Type</label>
        <type>Text</type>
    </fields>
    <label>Budget Assignment</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Budget Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetHeader__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>BudgetHeaders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>BudgetResource__c.TotalCost__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalRevenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>BudgetResource__c.TotalRevenue__c</summarizedField>
        <summaryForeignKey>BudgetResource__c.BudgetHeader__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget Header</label>
    <nameField>
        <displayFormat>BH-{00000000}</displayFormat>
        <label>Budget Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetResource__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipLabel>Budget Resources</relationshipLabel>
        <relationshipName>BudgetResources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ColumnHeader__c</fullName>
        <formula>BLANKVALUE(IF(ISBLANK(
   IF(ISBLANK( ProjectTeamMember__c )
   ,
   ResourceName__c
   ,
   ProjectTeamMember__r.Contact__r.FirstName + &apos; &apos; + ProjectTeamMember__r.Contact__r.LastName
   )
)
,
VendorSite__r.Site__r.AccountName__c
,
IF(ISBLANK( ProjectTeamMember__c )
   ,
   ResourceName__c
   ,
   ProjectTeamMember__r.Contact__r.FirstName + &apos; &apos; + ProjectTeamMember__r.Contact__r.LastName
   )
), &apos;Generic Resource&apos;)</formula>
        <label>Column Header</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CostRate__c</fullName>
        <formula>OverrideRawCost__c + (OverrideRawCost__c * OverrideFringeMultiplier__c ) 
+ 
(OverrideRawCost__c * OverrideOverheadMultiplier__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ForeignResource__c</fullName>
        <formula>IF(BudgetHeader__r.Project__r.CarryingOutOrganization__r.OUID__c ==  ProjectTeamMember__r.Contact__r.User__r.ECO_OUID__c, &apos;Local&apos;, &apos;Foreign&apos;)</formula>
        <label>Foreign Resource</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FullyBurdenedCostRate__c</fullName>
        <label>Fully Burdened Cost Rate</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCostRate__c</summarizedField>
        <summaryForeignKey>BudgetAssignment__c.BudgetResource__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>MarginType__c</fullName>
        <label>Margin Type</label>
        <picklist>
            <picklistValues>
                <fullName>Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OverrideBillRate__c</fullName>
        <label>Override Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideFringeMultiplier__c</fullName>
        <label>Override Fringe Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OverrideOverheadMultiplier__c</fullName>
        <label>Override Overhead Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OverrideRatesOnLines__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Override Rates On Lines</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OverrideRawCost__c</fullName>
        <label>Override Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideUplift__c</fullName>
        <label>Override Uplift</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProjectTeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Team Member</label>
        <referenceTo>ProjectTeamMember__c</referenceTo>
        <relationshipName>BudgetColumns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResourceName__c</fullName>
        <label>Resource Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResourceType__c</fullName>
        <label>Resource Type</label>
        <picklist>
            <picklistValues>
                <fullName>Labor/Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subcontractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODC/FEE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingency</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <formula>IF(  ISPICKVAL( ResourceType__c , &apos;Labor/Person&apos;) , 1
,
IF(  ISPICKVAL( ResourceType__c , &apos;Subcontractor&apos;) , 2
,
IF(  ISPICKVAL( ResourceType__c , &apos;ODC/FEE&apos;) , 3
,
4
)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sort_Order_Detail__c</fullName>
        <label>Sort Order Detail</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubsAndVendors__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subs and Vendors</label>
        <referenceTo>VendorSub__c</referenceTo>
        <relationshipName>BudgetColumns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryForeignKey>BudgetAssignment__c.BudgetResource__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalRevenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>BudgetAssignment__c.CalculatedRevenue__c</summarizedField>
        <summaryForeignKey>BudgetAssignment__c.BudgetResource__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget Resource</label>
    <nameField>
        <displayFormat>BR-{000000000}</displayFormat>
        <label>Budget Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetTask__c.object
<CustomObject>
    <fields>
        <fullName>BudgetHeader__c</fullName>
        <label>Budget Header</label>
        <referenceTo>BudgetHeader__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>BudgetTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalRevenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>BudgetAssignment__c.CalculatedRevenue__c</summarizedField>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget Task</label>
    <nameField>
        <displayFormat>BT-{000000000}</displayFormat>
        <label>Budget Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProjectTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays only PSA resouces</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>PSA Resource</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000000}</displayFormat>
        <label>Project Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_BudgetContingencyEACController.cls
public with sharing class ECO_BudgetContingencyEACController {

    public Id budgetHeaderId {get;set;}
    
    public ECO_DTO_BudgetLabourWrapper budgetLabourWrapper{get; set;}

    public String projectCurrency {get; set;}

    public Decimal totalRisk {get; set;}
    public Decimal totalBudgetContingencies {get; set;}

    public ECO_BudgetContingencyEACController(ApexPages.StandardController con) {
        budgetHeaderId = con.getId();
        System.debug('budgetHeaderId: ' + budgetHeaderId);
        System.debug('con: ' + con);
        
        budgetLabourWrapper = new ECO_DTO_BudgetLabourWrapper(budgetHeaderId, 'Contingency');

        BudgetHeader__c budgetHeader = [Select Id, Project__c, Project__r.ProjectFunctionalCurrencyCode__c From BudgetHeader__c Where Id = :budgetHeaderId];

        projectCurrency = budgetHeader.Project__r.ProjectFunctionalCurrencyCode__c;

        totalRisk = ECO_BudgetTaskService.sumRiskRegister(budgetHeader.Project__c);
        totalBudgetContingencies = ECO_BudgetTaskService.sumContingencies(budgetHeader.Project__c);
        
        totalRisk = totalRisk != null ? totalRisk : 0;
        totalBudgetContingencies = totalBudgetContingencies != null ? totalBudgetContingencies : 0;
        system.debug('totalRisk: ' + totalRisk);
        system.debug('totalBudgetContingencies: ' + totalBudgetContingencies);
    }

    public PageReference cloneResource() {
                System.savepoint sp = Database.setSavepoint();
        
        Id budgetSubId = System.currentPageReference().getParameters().get('budgetSubId');
        
        try {
            
            BudgetResource__c sourceResource = [SELECT Id
                                                    , Name 
                                                    , BudgetHeader__c
                                                    , ExternalId__c
                                                    , MarginType__c
                                                    , ProjectTeamMember__c
                                                    , ResourceType__c
                                                    , SubsAndVendors__c 
                                                    , TotalCost__c
                                                    , TotalRevenue__c
                                                    , OverrideBillRate__c
                                                    , OverrideFringeMultiplier__c
                                                    , OverrideOverheadMultiplier__c
                                                    , OverrideRawCost__c
                                                    , OverrideUplift__c 
                                                    , FullyBurdenedCostRate__c 
                                                    , CostRate__c
                                                    , OverrideRatesOnLines__c 
                                                    , ResourceName__c
                                                    , ColumnHeader__c
                                                    , ProjectTeamMember__r.Contact__c
                                                    , SortOrder__c
                                                    , Sort_Order_Detail__c
                                                    , ForeignResource__c
                                                    , JobName__c
                                                    , TotalHours__c
                                                    , IsQuoted__c
                                                    , IsEstimated__c
                                                    , IsBillable__c
                                                    , (SELECT Id 
                                                            , Name
                                                            , ApprovalStatus__c
                                                            , DefaultBillRate__c
                                                            , DefaultFringeMultiplier__c
                                                            , DefaultOverheadMultiplier__c
                                                            , DefaultRawCost__c
                                                            , DefaultUplift__c
                                                            , FullyBurdenedCost__c
                                                            , FullyBurdenedCostRate__c
                                                            , MarginType__c
                                                            , OverrideBillRate__c
                                                            , OverrideFringeMultiplier__c
                                                            , OverrideOverheadMultiplier__c
                                                            , OverrideRawCost__c
                                                            , OverrideUplift__c
                                                            , MarginAmountQtyTimesRate__c 
                                                            , MarginAmountCostTimesUplift__c
                                                            , Quantity__c 
                                                            , BudgetResource__c
                                                            , BudgetTask__c
                                                            , CalculatedRevenue__c 
                                                            , OverrideTotalCost__c 
                                                            , OverrideTotalRevenue__c 
                                                            , ProjectTaskAssignment__c
                                                        FROM BudgetAssignments__r)
                                            FROM BudgetResource__c 
                                            WHERE Id = :budgetSubId AND ResourceType__c =: 'Contingency'];
                                            
            BudgetResource__c clonedResource = sourceResource.clone(false, false, false, false);
            List<BudgetAssignment__c> clonedAssignments = new List<BudgetAssignment__c>();
            
            insert clonedResource;
            
            for (BudgetAssignment__c ba : sourceResource.BudgetAssignments__r) {
                BudgetAssignment__c clonedAssignment = ba.clone(false, false, false, false);
                clonedAssignment.BudgetResource__c = clonedResource.Id;
                clonedAssignments.add(clonedAssignment);
            }
            
            if (!clonedAssignments.isEmpty()) {
                insert clonedAssignments;
            }
            //budgetLabourWrapper = new ECO_DTO_BudgetLabourWrapper(budgetHeaderId, 'Subcontractor');
            //budgetLabourWrapper.dtoBudgetLabourDetails.add(new ECO_DTO_BudgetLabourDetail(clonedResource, clonedAssignments));
            
        } catch (Exception e) {
            system.debug('Cloning Exception:  '+e.getMessage());
            system.debug('Cloning Exception Trace:  '+e.getStackTraceString());
            Database.rollBack(sp);
            ApexPages.addMessages(e);
        }
        
        PageReference pageReference = ApexPages.currentPage();
        pageReference.getParameters().put('Id', budgetHeaderId );
        pageReference.setRedirect(True);
        
        return pageReference;
    }

    public PageReference removeEntireColumn () {
        Id budgetSubId = System.currentPageReference().getParameters().get('budgetSubId');
        delete new BudgetResource__c(Id = budgetSubId);
        
        //budgetLabourWrapper = new ECO_DTO_BudgetLabourWrapper(budgetHeaderId, 'Subcontractor');
        //budgetLabourWrapper.removeBudgetLabourDetail(budgetSubId);
        
        PageReference pageReference = ApexPages.currentPage();
        pageReference.getParameters().put('Id', budgetHeaderId );
        pageReference.setRedirect(True);
        
        return pageReference;
    }
    
    public PageReference save() {
        List<BudgetResource__c> budgetResourceToUpdate = new List<BudgetResource__c>();
        List<BudgetAssignment__c> budgetAssignmentsToUpdate = new List<BudgetAssignment__c>();
        
        for(ECO_DTO_BudgetLabourDetail dtoBudgetDetail : budgetLabourWrapper.dtoBudgetLabourDetails) {
            budgetResourceToUpdate.add(dtoBudgetDetail.oBudgetResource);
            budgetAssignmentsToUpdate.addAll(dtoBudgetDetail.mAssignmentMap.values());
        }
        
        system.debug('Resource: ' + budgetAssignmentsToUpdate[0].BudgetResource__c);
        system.debug('Task: ' + budgetAssignmentsToUpdate[0].BudgetTask__c);
        upsert budgetResourceToUpdate;
        upsert budgetAssignmentsToUpdate;
        
        PageReference pageReference = ApexPages.currentPage();
        pageReference.getParameters().put('Id', budgetHeaderId );
        pageReference.setRedirect(True);
        
        return pageReference;
    }
}