src/objects/BudgetTask__c.object
<CustomObject>
    <fields>
        <fullName>HasChildren__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Children</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HierarchyDepth__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Hierarchy Depth</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HierarchyIds__c</fullName>
        <label>Hierarchy Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsBottomLevelTask__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Bottom Level Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ParentTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Task</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Parent Budget Tasks must be under same Budget Header.</errorMessage>
            <filterItems>
                <field>BudgetTask__c.BudgetHeader__c</field>
                <operation>equals</operation>
                <valueField>$Source.BudgetHeader__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BudgetTask__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>ChildTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Budget Tasks</relationshipLabel>
        <relationshipName>BudgetTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalApprovedCost__c</fullName>
        <label>Total Approved Cost</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryFilterItems>
            <field>BudgetAssignment__c.ApprovalStatus__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalEstimateCost__c</fullName>
        <label>Total Estimate Cost</label>
        <summarizedField>BudgetAssignment__c.FullyBurdenedCost__c</summarizedField>
        <summaryForeignKey>BudgetAssignment__c.BudgetTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget Task</label>
    <nameField>
        <displayFormat>BT-{000000000}</displayFormat>
        <label>Budget Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>TotalApprovedCost__c</fullName>
        <label>Total Approved Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_BudgetTaskTriggers.cls
public without sharing class ECO_BudgetTaskTriggers {
	public static Boolean run = true;
	
	public static void rollUpBudgetTaskValues (Map<Id, BudgetTask__c> btOld, Map<Id, BudgetTask__c> btNew) {
		if (!run || !ECO_TriggerSettings.getIsTriggerEnabled('BT_rollup')) {
			return;
		}
		
		Set<Id> projectTaskIds = new Set<Id>();
		if (btOld != null) {
			for (BudgetTask__c bt : btOld.values()) {
				projectTaskIds.add(bt.ProjectTask__c);
			}
		}
		if (btNew != null) {
			for (BudgetTask__c bt : btNew.values()) {
				projectTaskIds.add(bt.ProjectTask__c);
			}
		}
												
		List<pse__Project_Task__c> projectTasksToUpdate = new List<pse__Project_Task__c>();
		
		for (AggregateResult ar : [SELECT ProjectTask__c
										, SUM(TotalApprovedCost__c) totalApprovedCostAmount
                                   		, SUM(TotalEstimateCost__c) totalEstimateCostAmount
									FROM BudgetTask__c
									WHERE ProjectTask__c IN :projectTaskIds
										AND ProjectTask__c != null
									GROUP BY ProjectTask__c]) {
										
			system.debug('ar:  '+ar);
			
			pse__Project_Task__c ptToUpdate = new pse__Project_Task__c();
			ptToUpdate.Id = (Id)ar.get('ProjectTask__c');
			ptToUpdate.TotalApprovedCost__c = (Decimal)ar.get('totalApprovedCostAmount');
            ptToUpdate.TotalEstimateCost__c = (Decimal)ar.get('totalEstimateCostAmount');
			projectTasksToUpdate.add(ptToUpdate);
		}
		
		if (!projectTasksToUpdate.isEmpty()) {
			update projectTasksToUpdate;
		}
	}
	
	public static void calculateDepth (List<BudgetTask__c> newBTasksList) {
		if (!run || !ECO_TriggerSettings.getIsTriggerEnabled('BT_hierarchy')) {
			return;
		}
		
		Map<Id, Integer> parentIdToNewDepthMap = new Map<Id, Integer>();
		
		for (BudgetTask__c bt : newBTasksList) {
			if (bt.ParentTask__c != null) {
				parentIdToNewDepthMap.put(bt.ParentTask__c, null);
			}
		}
		
		for (BudgetTask__c bt : [SELECT Id 
										, HierarchyDepth__c
								FROM BudgetTask__c 
								WHERE Id IN :parentIdToNewDepthMap.keySet()]) {
			
			parentIdToNewDepthMap.put(bt.Id, Integer.valueOf(bt.HierarchyDepth__c) + 1);
		}
		
		for (BudgetTask__c bt : newBTasksList) {
			if (bt.ParentTask__c == null) {
				// this is a parent task
				bt.HierarchyDepth__c = 0;
				bt.HierarchyIds__c = bt.Id;
			} else {
				bt.HierarchyDepth__c = parentIdToNewDepthMap.get(bt.ParentTask__c);
				bt.HierarchyIds__c = ''+bt.Id;
			}
		}
	}
	
	// Must run after everything, delete, undelete, etc
	public static void calculateBottomTaskFlag (List<BudgetTask__c> newBTaskList, List<BudgetTask__c> oldBTaskList) {
		if (!run || !ECO_TriggerSettings.getIsTriggerEnabled('BT_bottomFlag')) {
			return;
		}
		
		Set<Id> allTaskIds = new Set<Id>();
		
		if (newBTaskList != null) {
			for (BudgetTask__c bt : newBTaskList) {
				allTaskIds.add(bt.Id);
				allTaskIds.add(bt.ParentTask__c);
			}
		}
		
		if (oldBTaskList != null) {
			for (BudgetTask__c bt : oldBTaskList) {
				allTaskIds.add(bt.Id);
				allTaskIds.add(bt.ParentTask__c);
			}
		}
		
		List<BudgetTask__c> BTasksToUpdate = new List<BudgetTask__c>();
		
		for (BudgetTask__c bt : [SELECT Id
										, (SELECT Id FROM ChildTasks__r)
								FROM BudgetTask__c
								WHERE Id IN :allTaskIds]) {
			if (bt.ChildTasks__r.isEmpty()) {
				bt.IsBottomLevelTask__c = true;
				bt.HasChildren__c = false;
			} else {
				bt.IsBottomLevelTask__c = false;
				bt.HasChildren__c = true;
			}
			
			BTasksToUpdate.add(bt);
		}
		
		run = false;
		update BTasksToUpdate;
		run = true;
	}
}