src/objects/CFM_Survey_Batch_Project__c.object
<CustomObject>
    <description>CFM: Projects that are included in a Survey Batch</description>
    <fields>
        <fullName>PM_Reject_Other__c</fullName>
        <description>PM Comments to describe request to exclude project from survey due to &quot;Other reasons&quot;</description>
        <inlineHelpText>PM Comments to describe request to exclude project from survey due to &quot;Other reasons&quot;</inlineHelpText>
        <label>PM Reject Other</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PM_Reject_Reason__c</fullName>
        <description>PM Reason for request to exclude project from survey</description>
        <inlineHelpText>PM Reason for request to exclude project from survey</inlineHelpText>
        <label>PM Reject Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Client contact changed recently</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client has formal feedback process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current proposal/bid with client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actual potential legal claim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed more than 6 months ago</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Was/will be cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal government project using CPARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No project activity 6 months or more</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client is an AECOM department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other reason</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PM_Status__c</fullName>
        <description>PM review status - confirm/reject</description>
        <inlineHelpText>PM review status - confirm/reject</inlineHelpText>
        <label>PM Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Survey Batch Projects</relationshipLabel>
        <relationshipName>Survey_Batch_Projects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending PM Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PM Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Qualtrics Submittal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Qualtrics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey_Batch__c</fullName>
        <label>Survey Batch</label>
        <referenceTo>CFM_Survey_Batch__c</referenceTo>
        <relationshipLabel>Survey Batch Projects</relationshipLabel>
        <relationshipName>Survey_Batch_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Batch Project</label>
    <nameField>
        <displayFormat>SBP-{000000}</displayFormat>
        <label>Survey Batch Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Batch Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>If this person moves to another account: (a) change this field to &quot;No Longer with Client,&quot; (b) enter a note in the &quot;Need to Know&quot; field below, and (c) create a new Contact record under the new account.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No longer with client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CFM_SurveyBatchPMReviewController.cls
public with sharing class CFM_SurveyBatchPMReviewController {

	public String surveyProjectId { get; set; }
	public String rejectReason { get; set; }
	public String otherRejectReason { get; set; }

	public CFM_SurveyBatch surveyBatch { get; set; }
	public CFM_SurveyBatchReview surveyBatchReview { get; set; }
	public List<CFM_SurveyBatchProject> surveyBatchProjects { get; set; }

	public CFM_SurveyBatchPMReviewController(ApexPages.StandardController sc) {
		surveyBatchReview = CFM_SurveyBatchReview.find.findById(sc.getId());
        surveyBatch = CFM_SurveyBatch.find.findById(surveyBatchReview.obj.Survey_Batch__c);
        surveyBatchProjects = CFM_SurveyBatchProject.find.findByPm(surveyBatch.getId(), UserInfo.getUserId());
    }


    public Boolean getIsClosed() {
    	return surveyBatch.isClosed();
    }

    public Boolean getIsCompleted() {
    	return surveyBatchReview.obj.Status__c == 'Completed';
    }

    public PageReference submitAction() {

    	Boolean allUpdated = true;

    	for (CFM_SurveyBatchProject project: surveyBatchProjects) {
    		if (String.isBlank(project.obj.PM_Status__c)) {
    			allUpdated = false;
    		}
    	}

    	if (allUpdated) {
    		surveyBatchReview.obj.Status__c = 'Completed';
    		update surveyBatchReview.obj;
    	}
    	else {
    		CFM_PageUtil.addError('Please confirm or reject all projects before submitting.');
    	}


    	return null;
    }


    public PageReference confirmAction() {
    	String projectId = CFM_PageUtil.getParam('projectId');
    	System.debug('### PARAM Project ID: ' + projectId);

    	for (CFM_SurveyBatchProject project : surveyBatchProjects) {
    		String rowProjectId = (String)project.obj.Id;

			if (projectId == rowProjectId) {	
				if (project.obj.Project__r.CFM_Survey_Contact__c != null) {
					project.obj.PM_Status__c = CFM_SurveyBatchProject.PM_STATUS_CONFIRM;
					project.obj.Status__c = CFM_SurveyBatchProject.STATUS_REVIEWED;
					project.obj.PM_Reject_Reason__c = '';
					project.obj.PM_Reject_Other__c = '';
					update project.obj;
				}
				else {
					CFM_PageUtil.addError(project.obj.Project__r.Name + ' does not have a survey contact. Please edit the project and add a survey contact.');
					return null;
				}
			}
		}

    	return null;
    }

    public PageReference rejectAction() {
		if (String.isBlank(surveyProjectId)) {
			System.debug('Survey project ID is blank');
			return null;
		}

		for (CFM_SurveyBatchProject project : surveyBatchProjects) {
			if (project.getId() == surveyProjectId) {
				project.obj.PM_Status__c = CFM_SurveyBatchProject.PM_STATUS_REJECT;
				project.obj.Status__c = CFM_SurveyBatchProject.STATUS_REVIEWED;
				project.obj.PM_Reject_Reason__c = rejectReason;
				project.obj.PM_Reject_Other__c = otherRejectReason;
				project.save();
			}
		}

    	return null;
    }

    public PageReference editContactAction() {
    	String projectId = CFM_PageUtil.getParam('projectId');

    	for (CFM_SurveyBatchProject project : surveyBatchProjects) {
    		String rowProjectId = (String)project.obj.Id;

			if (projectId == rowProjectId) {
				String projectProfileId = project.obj.Project__c;
				String retUrl = EncodingUtil.urlEncode('/apex/CFM_SurveyBatchPMReview?id=' + surveyBatchReview.getId(), 'UTF-8');
				PageReference pg = new PageReference('/' + projectProfileId + '/e?retURL=' + retUrl);
				pg.setRedirect(true);
				return pg;
			}
		}


		return null;
    }


    public List<SelectOption> getRejectionReasons() {
    	Schema.DescribeFieldResult rejectReason = CFM_Survey_Batch_Project__c.PM_Reject_Reason__c.getDescribe();

		List<Schema.PicklistEntry> rejectReasonList = rejectReason.getPicklistValues();

		List<SelectOption> result = new List<SelectOption>();
		result.add(new SelectOption('', '-- Select --'));
		for (Schema.PicklistEntry entry : rejectReasonList) {
			result.add(new SelectOption(entry.getValue(), entry.getLabel()));
		}

		return result;
    }

}