src/objects/CFM_Survey_Batch_Project__c.object
<CustomObject>
    <description>CFM: Projects that are included in a Survey Batch</description>
    <fields>
        <fullName>Do_Not_Survey__c</fullName>
        <formula>Project__r.CFM_Survey_Contact__r.CFM_Do_Not_Survey__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Do Not Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Status__c</fullName>
        <description>PM review status - confirm/reject</description>
        <inlineHelpText>PM review status - confirm/reject</inlineHelpText>
        <label>PM Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Survey Batch Projects</relationshipLabel>
        <relationshipName>Survey_Batch_Projects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending PM Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PM Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Qualtrics Submittal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Qualtrics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey_Batch__c</fullName>
        <label>Survey Batch</label>
        <referenceTo>CFM_Survey_Batch__c</referenceTo>
        <relationshipLabel>Survey Batch Projects</relationshipLabel>
        <relationshipName>Survey_Batch_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Contact__c</fullName>
        <formula>Project__r.CFM_Survey_Contact__r.FirstName &amp; &apos; &apos; &amp; Project__r.CFM_Survey_Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Survey Contact</label>
        <type>Text</type>
    </fields>
    <label>Survey Batch Project</label>
    <nameField>
        <displayFormat>SBP-{000000}</displayFormat>
        <label>Survey Batch Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Batch Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Do_Not_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check box if the contact has indicated that he or she does not want to receive surveys.</inlineHelpText>
        <label>Do Not Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>If this person moves to another account: (a) change this field to &quot;No Longer with Client,&quot; (b) enter a note in the &quot;Need to Know&quot; field below, and (c) create a new Contact record under the new account.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No longer with client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CFM_Do_Not_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check box if the contact has indicated that he or she does not want to receive surveys.</inlineHelpText>
        <label>Do Not Survey</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <fields>
        <fullName>OracleDepartment__c</fullName>
        <description>From Oracle Feed</description>
        <inlineHelpText>From Oracle Feed</inlineHelpText>
        <label>Oracle Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The project owner (the entity that is paying for the work).</description>
        <inlineHelpText>Also called End Client - the entity that is paying for the work, not necessarily the account AECOM bills to. See Prime account field also.</inlineHelpText>
        <label>Owner/End Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CFM_SurveyBatchProject.cls
public with sharing class CFM_SurveyBatchProject extends CFM_BaseModel {
	public static Finder find = new Finder();

	public static final String STATUS_NEW = 'New';
	public static final String STATUS_PENDING_REVIEW = 'Pending PM Review';
	public static final String STATUS_REVIEWED = 'PM Reviewed';
	public static final String STATUS_PENDING_QSUBMIT = 'Pending Qualtrics Submittal';
	public static final String STATUS_SENT = 'Sent to Qualtrics';

    public static final String PM_STATUS_CONFIRM = 'Confirmed';
    public static final String PM_STATUS_REJECT  = 'Rejected';

	public CFM_Survey_Batch_Project__c obj { 
        get { 
            return (CFM_Survey_Batch_Project__c)mObj; 
        } 
    }

	public CFM_SurveyBatchProject(CFM_Survey_Batch_Project__c sObj) {
		super(sObj);
	}

    public String getSurveyBatchName() {
        return obj.Survey_Batch__r.Name;
    }

    public Id getContactId() {
        return obj.Project__r.CFM_Survey_Contact__c;
    }

    public Id getProjectId() {
        return obj.Project__c;
    }

    public Id getAccountId() {
        return obj.Project__r.Owner__c;
    }

    public Id getSurveyBatchId() {
        return obj.Survey_Batch__c;
    }
    public void setSurveyBatchId(Id surveyBatchId) {
        obj.Survey_Batch__c = surveyBatchId;
    }

    public String getOracleDepartment() {
        return obj.Project__r.OracleDepartment__c;
    }

    public Boolean getDoNotSurvey() {
        return obj.Project__r.CFM_Do_Not_Survey__c          //---Project
            || obj.Do_Not_Survey__c                         //---Formula field for contact
            || obj.Project__r.CFM_Account_Do_Not_Survey__c; //---Account
    }

    public Boolean getProjectHasContact() {
        return String.isNotBlank(obj.Survey_Contact__c);
    }

    public Boolean getIsProjectConfirmed() {
        return obj.PM_Status__c == PM_STATUS_CONFIRM;
    }

    
	public static List<CFM_SurveyBatchProject> decorate(List<CFM_Survey_Batch_Project__c> sList) {
		List<CFM_SurveyBatchProject> result = new List<CFM_SurveyBatchProject>();
		for (CFM_Survey_Batch_Project__c row : sList) result.add(new CFM_SurveyBatchProject(row));
		return result;
	}

    //---TODO - what is the exact criteria for determinig duplicates?
    public static List<CFM_SurveyBatchProject> removeDuplicatesAndDoNotSurvey(List<CFM_SurveyBatchProject> projects) {
        List<CFM_SurveyBatchProject> uniques = new List<CFM_SurveyBatchProject>();
        Map<String, CFM_SurveyBatchProject> projectsByAccountId = new Map<String, CFM_SurveyBatchProject>();
        
        //---Get unique batch projects using lookup to project
        for (CFM_SurveyBatchProject project : projects) {
            //---Make sure project was confirmed, project has contact selected,
            //---And none of the Do Not Survey flags are set
            Boolean shouldAdd = project.getIsProjectConfirmed() 
                             && project.getProjectHasContact()
                             && !project.getDoNotSurvey();
            if (shouldAdd) {
                projectsByAccountId.put(project.obj.Project__c, project);
            }
        }

        return projectsByAccountId.values();
    }

	public class Finder extends CFM_BaseFinder {
		public Finder() {
			super('CFM_Survey_Batch_Project__c');
		}

        public List<CFM_SurveyBatchProject> findProjectsPendingSubmit(Id surveyBatchId) {
            Set<String> newFields = new Set<String>();
            for (String newField : CFM_SurveyBatchProjectCSVGenerator.getAllFields()) {
                newFields.add(newField.toLowerCase());
            }
            newFields.add('project__r.cfm_account_do_not_survey__c');
            newFields.add('project__r.cfm_do_not_survey__c');
            newFields.add('project__r.oracledepartment__c');
            newFields.add('project__r.cfm_survey_contact__c');
            newFields.add('project__r.owner__c');
            addFields(newFields);

			String status = CFM_SurveyBatchProject.STATUS_PENDING_QSUBMIT;
			List<CFM_Survey_Batch_Project__c> result = Database.query(getSelect() + ' where Survey_Batch__c = :surveyBatchId and Status__c = :status ');
			return CFM_SurveyBatchProject.decorate(result);
		}

		public List<CFM_SurveyBatchProject> findConfirmedProjects(Id surveyBatchId) {
			List<CFM_Survey_Batch_Project__c> result = Database.query(getSelect() + ' where Survey_Batch__c = :surveyBatchId and PM_Status__c != null and PM_Status__c = \'Confirmed\' ');
			return CFM_SurveyBatchProject.decorate(result);
		}

		public List<CFM_SurveyBatchProject> findByPm(Id surveyBatchId, Id userId) {
			addField('project__r.name');
            addField('project__r.cfm_survey_contact__c');
			List<CFM_Survey_Batch_Project__c> result = Database.query(getSelect() + ' where Survey_Batch__c = :surveyBatchId and Project__r.Oracle_Project_Manager_lookup__c = :userId');
			return CFM_SurveyBatchProject.decorate(result);
		}

		public List<CFM_Survey_Batch_Project__c> findSurveyProjectsForNotification(Id surveyBatchId) {
			List<CFM_Survey_Batch_Project__c> surveyProjects = [Select 
								Id, 
								Project__r.Oracle_Project_Manager_lookup__c 
								from CFM_Survey_Batch_Project__c 
								where 
								Survey_Batch__c = :surveyBatchId
								and Status__c = :CFM_SurveyBatchProject.STATUS_NEW];
								
			return surveyProjects;
		}
	}
}