src/objects/CommunicationPlan__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Audience__c</fullName>
        <label>Audience</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>How__c</fullName>
        <label>How</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewTaskNeedsToBeCreated__c</fullName>
        <formula>IF(AND(TODAY() &gt;=  NextCreateTaskDate__c,  GenerateTask__c), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New Task Needs To Be Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectIsActive__c</fullName>
        <formula>AND(NOT(ISPICKVAL(Project__r.pse__Stage__c,&quot;Closed&quot;)),NOT(ISPICKVAL(Project__r.pse__Stage__c,&quot;Completed&quot;)),NOT(ISPICKVAL(Project__r.pse__Stage__c,&quot;Canceled&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Communication Plans</relationshipLabel>
        <relationshipName>CommunicationPlans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TaskLastGenerated__c</fullName>
        <label>Task Last Generated</label>
        <type>Date</type>
    </fields>
    <label>Communication Plan</label>
    <nameField>
        <displayFormat>Comm-{00000000}</displayFormat>
        <label>Communication Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_ProjectCommunicationPlanBatch.cls
global class ECO_ProjectCommunicationPlanBatch implements Database.Batchable<sObject>{

	private String query = 'select Id, Name, TaskLastGenerated__c, Audience__c, Activity__c, How__c, Project__c from CommunicationPlan__c where NewTaskNeedsToBeCreated__c = true and ProjectIsActive__c = true';
	
    global Database.QueryLocator start(Database.BatchableContext projectHealthCheckBatchContext)
    {   
    	System.Debug(LoggingLevel.Info, 'Query ' + query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext projectHealthCheckBatchContext, List<CommunicationPlan__c> communicationPlans)
    {  	
    	list<Task> tasks = new list<Task>();
		for(CommunicationPlan__c plan:communicationPlans)  
		{
			Task newTask = new Task(Description = 'Audience: ' + plan.Audience__c + '\n' + 'How: ' + plan.How__c,
                                    Priority = 'Normal', 
                                    Subject = 'Comm Plan - ' + plan.Activity__c, 
                                    IsReminderSet = false, 
                                    ReminderDateTime = System.now()+1, 
                                    WhatId = plan.Project__c    );             
             tasks.add(newTask);
             plan.TaskLastGenerated__c = DateTime.Now();		
		} 			
		insert tasks;
		update communicationPlans;
    }	
    
    global void finish(Database.BatchableContext projectHealthCheckBatchContext)
    {   	
    	
        system.debug('Batch completed');
    }    
}