src/objects/ComplianceConditionsofApproval__c.object
<CustomObject>
    <fields>
        <fullName>ComplianceStatusDate__c</fullName>
        <label>Compliance Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ComplianceStatus__c</fullName>
        <label>Compliance Status</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Compliant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ConditionsCompletedDate__c</fullName>
        <label>Conditions Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ConditionsCompleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Conditions Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DOAApprovalRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOA Approval Request</label>
        <referenceTo>DOAApprovalRequest__c</referenceTo>
        <relationshipName>ComplianceConditionsofApprovals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GeneralComments__c</fullName>
        <label>General Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Conditions of Approval Compliance</label>
    <nameField>
        <displayFormat>Condition-{0}</displayFormat>
        <label>Conditions of Approval Compliance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions of Approval Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DOAApprovalRequest__c.object
<CustomObject>
    <fields>
        <fullName>AECOMHubApprovalsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AECOM Hub</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AECOMHubCountofApprovers__c</fullName>
        <label>AECOM Hub Count of Approvers</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <inlineHelpText>This field is manually determined by the ORM rep to indicate the overall status of the approval process.</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AssigntoDoAApprovalQueue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assign to DoA Approval Queue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DCSHubApprovalsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DCS Hub</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DCSHubCountofApprovers__c</fullName>
        <label>DCS Hub Count of Approvers</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EnterpriseApprovalsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enterprise</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnterpriseCountofApprovers__c</fullName>
        <label>Enterprise Count of Approvers</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GeoCountOfApprovers__c</fullName>
        <label>Geo Count Of Approvers</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GeographyApprovalsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Geography</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GroupApprovalsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GroupCountofApprovers__c</fullName>
        <label>Group Count of Approvers</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubmitAECOMHubForApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submit AECOM Hub For Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubmitDCSHubforApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submit DCS Hub for Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubmitEnterpriseforApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submit Enterprise for Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubmitGeographyforApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submit Geography for Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubmitGroupforApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submit Group for Approval</label>
        <type>Checkbox</type>
    </fields>
    <label>DOA Approval Request</label>
    <nameField>
        <displayFormat>DOA-{0}</displayFormat>
        <label>DOA Request For Approval Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DOA Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DOAConditions__c.object
<CustomObject>
    <fields>
        <fullName>ComplianceStatus__c</fullName>
        <label>Compliance Status</label>
        <picklist>
            <picklistValues>
                <fullName>TBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DOAApprovalRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOA Approval Request</label>
        <referenceTo>DOAApprovalRequest__c</referenceTo>
        <relationshipLabel>DOA Conditions (DOA Approval Request)</relationshipLabel>
        <relationshipName>DOAConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOARegister__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOA Register</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DOARegister__c.DOAApprovalRequest__c</field>
                <operation>equals</operation>
                <valueField>$Source.DOAApprovalRequest__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DOARegister__c</referenceTo>
        <relationshipLabel>DOA Conditions</relationshipLabel>
        <relationshipName>DOAConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mitigation_Plan__c</fullName>
        <label>Mitigation Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>DOA Condition</label>
    <nameField>
        <label>Condition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DOA Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DOARegister__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DCSsubDOA__c</fullName>
        <label>DCS sub-DOA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOAApprovalRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOA Approval Request</label>
        <referenceTo>DOAApprovalRequest__c</referenceTo>
        <relationshipLabel>DOA Register</relationshipLabel>
        <relationshipName>DOA_Register</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOATrigger__c</fullName>
        <label>DOA Trigger</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EnterpriseDOA__c</fullName>
        <label>Enterprise DOA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RiskTitle__c</fullName>
        <label>Risk Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DOA Register</label>
    <nameField>
        <displayFormat>DOA-{0}</displayFormat>
        <label>DOA Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DOA Register</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <formula>TEXT( DOAApprovalRequest__r.ApprovalStatus__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOAApprovalRequest__c</fullName>
        <label>DOA Approval Request</label>
        <referenceTo>DOAApprovalRequest__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Form</label>
    <nameField>
        <displayFormat>Form-{0}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>isDoaAdmin__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This box should be checked for all DoA Admins managing the DoA Approval queue. This box will enable users to access the admin view of DoA</description>
        <inlineHelpText>This box should be checked for all DoA Admins managing the DoA Approval queue. This box will enable users to access the admin view of DoA</inlineHelpText>
        <label>isDoa Admin</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ECO_DOAApprovalsController.cls
public with sharing class ECO_DOAApprovalsController {
    public DOAApprovalRequest__c oDOA {get;set;}
    public List<Form__c> lForm {get;set;}
    public List<DOARegister__c> lDOARegister {get;set;}
    public List<DOAConditions__c> lDOAConditions {get;set;}
    public List<ComplianceConditionsofApproval__c> lCompliance {get;set;}
    public Boolean isDOAAdmin {get;set;}
    public Boolean inQueue {get;set;}
    public String doaId {get;set;}
    public Group oGroup {get;set;}
    public ECO_DOAApprovalsController(ApexPages.StandardController stdcontroller) {
    doaId = ApexPages.currentPage().getParameters().get('Id');
        init();
    }
    public void init(){
        Map<String, Schema.SObjectField> objfieldMap = DOAApprovalRequest__c.sObjectType.getDescribe().fields.getMap();
 
        String strfieldName = '';
        
        for(Schema.SObjectField Field : objfieldMap.Values()){
             Schema.DescribeFieldResult fieldResult = Field.getDescribe();
             strfieldName += fieldResult.getName() + ',';
        }
         
        strfieldName = strfieldName.substring(0, strfieldName.length()-1);
        
        List<DOAApprovalRequest__c> lDOA = Database.query('Select ' + strfieldName + ' From DOAApprovalRequest__c Where Id = :doaId');
        oDOA = lDOA[0];
        oGroup = [Select Id, DeveloperName From Group Where DeveloperName = 'DOAApprovalQueue'];
        if(oDOA.OwnerId == oGroup.Id)
            inQueue = true;
        lForm = [Select Id, Name, CreatedById, CreatedDate From Form__c Where DOAApprovalRequest__c =: oDOA.Id];
        lDOARegister = [Select Id, EnterpriseDOA__c, DCSsubDOA__c, RiskTitle__c, DOATrigger__c, ApprovalStatus__c From DOARegister__c Where DOAApprovalRequest__c = :oDOA.Id];
        lDOAConditions = [Select Id, Name, CreatedBy__c, Mitigation_Plan__c, CreatedDate From DOAConditions__c Where DOAApprovalRequest__c = :oDOA.Id];
        lCompliance = [Select Id, Name, ComplianceStatus__c, GeneralComments__c, ComplianceStatusDate__c, ConditionsCompleted__c, ConditionsCompletedDate__c From ComplianceConditionsofApproval__c Where DOAApprovalRequest__c = :oDOA.Id];
        System.debug('oDOA id is :'+oDOA.Id);
        User oUser = [Select Id, isDoaAdmin__c From User Where Id = :UserInfo.getUserId()];
        isDOAAdmin = oUser.isDoaAdmin__c;
        System.debug('isDOAAdmin:'+isDOAAdmin);
        System.debug('oUser.isDoaAdmin__c:   '+oUser.isDoaAdmin__c);
    }
    public PageReference saveDOA(){
        try{
            update oDOA;
            init();
            System.debug('oDOA:   '+oDOA);
            //PageReference pageRef = new PageReference('/apex/ECO_DOAApprovals?Id=' + oDOA.Id);
            //System.debug('pageRef:   '+pageRef);
            //return ApexPages.currentPage();
            return null;
        }catch(Exception e) {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attempting to update DOA Approval Request. Please contact your administrator with the following error: ' + e);
            ApexPages.addMessage(oMsg);
            return null;
        }
    }
    public PageReference submitAECOMHub(){
        try{
            if(oDOA.SubmitAECOMHubForApproval__c==false && oDOA.AECOMHubCountofApprovers__c >0 && oDOA.AECOMHubApprovalsRequired__c ==true ){ 
                oDOA.SubmitAECOMHubforApproval__c = true ;
                update oDOA; 
            } 
            else{ 
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error,'Please ensure that AECOM Hub has Approvers and that AECOM Hub Checkbox is selected.');
                ApexPages.addMessage(myMsg); 
                //alert('Please ensure that AECOM Hub has Approvers and that AECOM Hub Checkbox is selected.'); 
            } 
            return null;
         }catch(Exception e) {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attempting to update DOA Approval Request. Please contact your administrator with the following error: ' + e);
            ApexPages.addMessage(oMsg);
            return null;
        }
    }
    public PageReference submitGeography(){
        system.debug('inside geography');
        try{
            if(oDOA.SubmitGeographyforApproval__c==false && oDOA.GeoCountOfApprovers__c >0 && oDOA.GeographyApprovalsRequired__c ==true ){ 
                system.debug('inside geography if');
                oDOA.SubmitGeographyforApproval__c = true ;
                update oDOA; 
            } 
            else{ 
                system.debug('inside geography else');
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error,'Please ensure that Geography has Approvers and that Geography Checkbox is selected.');
                ApexPages.addMessage(myMsg); 
                //alert('Please ensure that AECOM Hub has Approvers and that AECOM Hub Checkbox is selected.'); 
            } 
            return null;
        }catch(Exception e) {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attempting to update DOA Approval Request. Please contact your administrator with the following error: ' + e);
            ApexPages.addMessage(oMsg);
            return null;
        }
    }
    public PageReference submitGroup(){
        system.debug('inside group');
        try{
            if(oDOA.SubmitGroupforApproval__c==false && oDOA.GroupCountofApprovers__c >0 && oDOA.GroupApprovalsRequired__c ==true ){ 
                system.debug('inside group if');
                oDOA.SubmitGroupforApproval__c = true ;
                update oDOA; 
                return null;
            } 
            else{ 
                system.debug('inside group else');
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error,'Please ensure that Group has Approvers and that Group Checkbox is selected.');
                ApexPages.addMessage(myMsg); 
                //alert('Please ensure that AECOM Hub has Approvers and that AECOM Hub Checkbox is selected.'); 
                return null;
            } 
         }catch(Exception e) {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attempting to update DOA Approval Request. Please contact your administrator with the following error: ' + e);
            ApexPages.addMessage(oMsg);
            return null;
        }
        
    }
    public PageReference submitEnterprise(){
        try{
            if(oDOA.SubmitEnterpriseforApproval__c==false && oDOA.EnterpriseCountofApprovers__c >0 && oDOA.EnterpriseApprovalsRequired__c ==true ){ 
                oDOA.SubmitEnterpriseforApproval__c = true ;
                update oDOA; 
            } 
            else{ 
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error,'Please ensure that Enterprise has Approvers and that Enterprise Checkbox is selected.');
                ApexPages.addMessage(myMsg); 
                //alert('Please ensure that AECOM Hub has Approvers and that AECOM Hub Checkbox is selected.'); 
            } 
            return null;
         }catch(Exception e) {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attempting to update DOA Approval Request. Please contact your administrator with the following error: ' + e);
            ApexPages.addMessage(oMsg);
            return null;
        }
    }
    public PageReference submitDCSHub(){
        try{
            if(oDOA.SubmitDCSHubforApproval__c==false && oDOA.DCSHubCountofApprovers__c >0 && oDOA.DCSHubApprovalsRequired__c ==true ){ 
                oDOA.SubmitDCSHubforApproval__c = true ;
                update oDOA; 
            } 
            else{ 
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error,'Please ensure that DCS Hub has Approvers and that DCS Hub Checkbox is selected.');
                ApexPages.addMessage(myMsg); 
                //alert('Please ensure that AECOM Hub has Approvers and that AECOM Hub Checkbox is selected.'); 
            } 
            return null;
         }catch(Exception e) {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attempting to update DOA Approval Request. Please contact your administrator with the following error: ' + e);
            ApexPages.addMessage(oMsg);
            return null;
        }
    }
    public PageReference submitDOA(){
        try{
            System.debug('inside submitDOA before update:   '+oDOA.Id+'    '+oDOA.AssigntoDoAApprovalQueue__c);
            if(oDOA.AssigntoDoAApprovalQueue__c != true){
                oDOA.AssigntoDoAApprovalQueue__c = true;
              update oDOA;
            }
            System.debug('inside submitDOA after update:   '+oDOA.Id+'    '+oDOA.AssigntoDoAApprovalQueue__c);
            return null;
        }catch(Exception e) {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attempting to update DOA Approval Request. Please contact your administrator with the following error: ' + e);
            ApexPages.addMessage(oMsg);
            return null;
        }
    }
    public PageReference submitDOAQueue(){
        try{
            system.debug('before update: '+oDOA.Id+'    '+oDOA.AssigntoDoAApprovalQueue__c);
            if(oDOA.AssigntoDoAApprovalQueue__c != true){
                oDOA.AssigntoDoAApprovalQueue__c = true;
                update oDOA;
                init();
            }
            System.debug('after update:   '+oDOA.Id+'    '+oDOA.AssigntoDoAApprovalQueue__c);    
            return null;
        }catch(Exception e) {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attempting to update DOA Approval Request. Please contact your administrator with the following error: ' + e);
            ApexPages.addMessage(oMsg);
            return null;
        }
    }
}