src/objects/Configuration__c.object
<CustomObject>
    <description>Used to arrange icons on Ecosystem Portal landing page.</description>
    <label>Configuration</label>
    <nameField>
        <displayFormat>CONFIG-{0000000}</displayFormat>
        <label>Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurations</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ECO_PortalSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>OnAWANJavascriptPath__c</fullName>
        <description>Needs to be fully qualified path, including protocol.  Ex:  http://www.aecom.com/onAwan.js</description>
        <label>On AWAN Javascript Path</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ECO Portal Settings</label>
</CustomObject>

src/objects/ECO_Smart_Search_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Analytics_End_Point__c</fullName>
        <description>This is the data-endpoint that is used by CoveoAnalytics Component</description>
        <inlineHelpText>This is the data-endpoint that is used by CoveoAnalytics Component</inlineHelpText>
        <label>Analytics End Point</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveoTab_All_Expression1__c</fullName>
        <description>This is the data-expression that is used by the CoveoTab for All Information search.</description>
        <inlineHelpText>This is the data-expression that is used by the CoveoTab for All Information search.</inlineHelpText>
        <label>CoveoTab All Expression1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveoTab_All_Expression2__c</fullName>
        <description>This is the data-expression that is used by the CoveoTab for All Information search. This is the second part of the expression. This is needed because Salesforce has a limit of 255 characters for Text Data Type.</description>
        <inlineHelpText>This is the data-expression that is used by the CoveoTab for All Information search. This is the second part of the expression. This is needed because Salesforce has a limit of 255 characters for Text Data Type.</inlineHelpText>
        <label>CoveoTab All Expression2</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveoTab_People_Expression__c</fullName>
        <description>This is the expression used by the CoveoTab People</description>
        <inlineHelpText>This is the expression used by the CoveoTab People</inlineHelpText>
        <label>CoveoTab People Expression</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveoTab_Practice_Expression_1__c</fullName>
        <description>This is the expression that is used by the Practice CoveoTab</description>
        <inlineHelpText>This is the expression that is used by the Practice CoveoTab</inlineHelpText>
        <label>CoveoTab Practice Expression 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveoTab_Practice_Expression_2__c</fullName>
        <description>This is the expression that is used by the Practice CoveoTab and this is the second part of the search. This is needed because of the 255 chracter limit on the Text data type field.</description>
        <inlineHelpText>This is the expression that is used by the Practice CoveoTab and this is the second part of the search. This is needed because of the 255 chracter limit on the Text data type field.</inlineHelpText>
        <label>CoveoTab Practice Expression 2</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveoTab_Projects_Expression__c</fullName>
        <description>This is the expression that is used by the Projects CoveoTab.</description>
        <inlineHelpText>This is the expression that is used by the Projects CoveoTab.</inlineHelpText>
        <label>CoveoTab Projects Expression</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter_By_File_Type_Allowed_Values__c</fullName>
        <description>These are the file types that are allowed in the Facet</description>
        <inlineHelpText>These are the file types that are allowed in the Facet</inlineHelpText>
        <label>Filter By File Type Allowed Values</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>This is the Key that is passed to the Coveo to retrieve the token for authentication</description>
        <label>Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Search_CoveoSearchInterface_Expression__c</fullName>
        <description>This is the data-hidden-expression for the search CoveoSearchInterface.</description>
        <inlineHelpText>This is the data-hidden-expression for the search CoveoSearchInterface.</inlineHelpText>
        <label>Search CoveoSearchInterface Expression</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TPN_Search_Expression1__c</fullName>
        <description>This is the data-hidden-expression for the TPNSearch. This is what controls what is displayed on the FROM THE TPN section on the landing page of SmartSearch page.</description>
        <inlineHelpText>This is the data-hidden-expression for the TPNSearch. This is what controls what is displayed on the FROM THE TPN section on the landing page of SmartSearch page.</inlineHelpText>
        <label>TPN Search Expression 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TPN_Search_Expression_2__c</fullName>
        <description>This is the second part of data-hidden-expression for the TPNSearch. This is what controls what is displayed on the FROM THE TPN section on the landing page of SmartSearch page. We have two because we have a character limit of 255 on a Text field on Salesforce. In the code both are concatenated with an OR and then passed to the front end.</description>
        <inlineHelpText>This is the second part of data-hidden-expression for the TPNSearch. This is what controls what is displayed on the FROM THE TPN section on the landing page of SmartSearch page. We have two because we have a character limit of 255 on a Text field on Sales</inlineHelpText>
        <label>TPN Search Expression 2</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endPointURL__c</fullName>
        <description>This will be the endPoint URL used to authenticate user with Coveo</description>
        <label>endPointURL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ECO Smart Search Settings</label>
</CustomObject>

src/objects/PortalMessage__c.object
<CustomObject>
    <description>Used by the ECO_Portal pages to display User Alerts, News Feed Items, and News Ticker.</description>
    <label>Portal Message</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Portal Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Project Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Director 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Accountant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Accountant Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Lead 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFO or Delegate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discipline Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HS&amp;E Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000000}</displayFormat>
        <label>Project Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>smartSearchMyRecentSearch__c</fullName>
        <description>This field is used by the SmartSearch app to store the last 10 searches that were done by this user.</description>
        <inlineHelpText>This field is used by the SmartSearch app to store the last 10 searches that were done by this user.</inlineHelpText>
        <label>smartSearchMyRecentSearch</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>smartSearchMyRecentlyViewed__c</fullName>
        <description>This field is used by the SmartSearch app to store the last 10 documents that were clicked by the user</description>
        <label>smartSearchMyRecentlyViewed</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ECO_SmartSearchController_SS.cls
public with sharing class ECO_SmartSearchController_SS extends ECO_PageControllerBase {
	
    public List<pse__Proj__c> projects					{ get; set; }
	public List<Configuration__c> reports				{ get; set; }
	public List<Configuration__c> applications			{ get; set; }
	public User theUser									{ get; set; }
	public List<ProcessInstanceWorkitem> approvals		{ get; set; }
	public List<Task> tasks								{ get; set; }
	public List<PortalMessage__c> alerts				{ get; set; }
	public List<PortalMessage__c> tickerMessages		{ get; set; }
	public List<SelectOption> projectOutputTypes		{ get; set; }
	public String selectedOutputType					{ get; set; }
	public List<Schema.FieldSetMember> fieldSetFields	{ get; set; }
	public Boolean showClosed							{ get; set; }
	public ProjectTeamMember__c ptmPickListProvider		{ get; set; }
	public String photoUrl								{ get; set; }
	public List<PortalMessage__c> newsFeed				{ get; set; }
	public String awanJSPath							{ get; set; }
    
    public String coveoToken							{get; set;}
    public String endPointURL							{get; set;}
    public String analyticsEndPoint						{get; set;}
    public String tpnSearchExpression					{get; set;}
    public String searchCoveoSearchInterfaceExpression 	{get; set;}
    public String coveoTabAllExpression					{get; set;}
    public String coveoTabPeopleExpression				{get; set;}
    public String coveoTabProjectsExpression			{get; set;}
    public String coveoTabPracticeExpression			{get; set;}
    public String filterByFileTypeAllowedValues			{get; set;}
    
    public String collaborationGroups					{get; set;}

    private class ECO_SmartSearchControllerException extends Exception {}    
    private System.LoggingLevel debugLevel = LoggingLevel.INFO;
    
    public ECO_SmartSearchController_SS() {
        
        Apexpages.currentPage().getHeaders().put('X-UA-Compatible', 'IE=10');
		
		projectOutputTypes = new List<SelectOption>();
		projectOutputTypes.add(new SelectOption('ECO_QuickFields', 'Quick View'));
		projectOutputTypes.add(new SelectOption('ECO_GeneralFields', 'General'));
		projectOutputTypes.add(new SelectOption('ECO_FinancialFields', 'Detailed Financial'));
		projectOutputTypes.add(new SelectOption('ECO_BillingFields', 'Billing'));
		projectOutputTypes.add(new SelectOption('ECO_ProgressFields', 'Progress'));
		
		ptmPickListProvider = new ProjectTeamMember__c();
		
		selectedOutputType = 'ECO_GeneralFields';
		
		changeProjectOutputType();
		
		awanJSPath = ECO_PortalSettings__c.getInstance().OnAWANJavascriptPath__c;
		
		showClosed = false;
		
		theUser = ECO_Service_Users.getUserInfoById(UserInfo.getUserId());
		approvals = ECO_Service_Users.getApprovalsForUser(theUser.Id);
		tasks = ECO_Service_Users.getOpenTasksForUser(theUser.Id);
		alerts = ECO_Utils_Alerts.getPortalMessagesForUser(theUser.Id);
		tickerMessages = ECO_Utils_Alerts.getTickerMessages();
		refreshProjects();
		reports = ECO_Service_Reports.getReportsForUser(theUser.Id);
		newsFeed = ECO_Utils_Alerts.getNewsFeedForPortal();
		if (!Test.isRunningTest()) {
			photoUrl = ConnectApi.ChatterUsers.getPhoto(null, theUser.Id).smallPhotoUrl;
		}
        setCollaborationGroups();
    }
    
    public void setCollaborationGroups(){
        List<CollaborationGroupMember> cgmList = [select CollaborationGroupId from CollaborationGroupMember where MemberId=:UserInfo.getUserId()];

		List<Id> cgmIdsList = new List<Id>();
        for (CollaborationGroupMember cgm : cgmList){
        	cgmIdsList.add(cgm.CollaborationGroupId);
        }
		collaborationGroups = String.join(cgmIdsList, ',');
    }
    
    public PageReference getSearchToken() {
        setCollaborationGroups();
        
        applications = ECO_Service_Applications.getSortedList(theUser);
        ECO_Smart_Search_Settings__c smartSearchSetting = ECO_Smart_Search_Settings__c.getInstance('SmartSearch');
        endPointURL = smartSearchSetting.endPointURL__c;
        analyticsEndPoint = smartSearchSetting.Analytics_End_Point__c;
        tpnSearchExpression = smartSearchSetting.TPN_Search_Expression1__c;
        if(smartSearchSetting.TPN_Search_Expression_2__c != null && smartSearchSetting.TPN_Search_Expression_2__c != '') {
            tpnSearchExpression = tpnSearchExpression + ' OR ' + smartSearchSetting.TPN_Search_Expression_2__c;            
        }
        tpnSearchExpression = tpnSearchExpression.replace('{!collaborationGroups}', collaborationGroups);
        
        searchCoveoSearchInterfaceExpression = smartSearchSetting.Search_CoveoSearchInterface_Expression__c;
        
        coveoTabAllExpression = smartSearchSetting.CoveoTab_All_Expression1__c;
        if(smartSearchSetting.CoveoTab_All_Expression2__c != null && smartSearchSetting.CoveoTab_All_Expression2__c != '') {
            coveoTabAllExpression = coveoTabAllExpression + ' OR ' + smartSearchSetting.CoveoTab_All_Expression2__c;
        }
        
        coveoTabAllExpression = coveoTabAllExpression.replace('{!collaborationGroups}', collaborationGroups);
        
        coveoTabPeopleExpression = smartSearchSetting.CoveoTab_People_Expression__c;
        coveoTabProjectsExpression = smartSearchSetting.CoveoTab_Projects_Expression__c;
        coveoTabPracticeExpression = smartSearchSetting.CoveoTab_Practice_Expression_1__c;
		if(smartSearchSetting.CoveoTab_Practice_Expression_2__c != null && smartSearchSetting.CoveoTab_Practice_Expression_2__c != '') {
            coveoTabPracticeExpression = coveoTabPracticeExpression + ' OR ' + smartSearchSetting.CoveoTab_Practice_Expression_2__c;
        }       
        coveoTabPracticeExpression = coveoTabPracticeExpression.replace('{!collaborationGroups}', collaborationGroups);
        
        filterByFileTypeAllowedValues = smartSearchSetting.Filter_By_File_Type_Allowed_Values__c;
        
        String randomKey = smartsearchSetting.Key__c;
        String orgId = UserInfo.getOrganizationId();
        
        
        
        Id profileId = UserInfo.getProfileId();
		String profileName = [SELECT Id, Name FROM Profile WHERE Id=:profileId].Name;
        
        // Make endpointURL and key passed to the server configurable.
    	Http http = new Http();
        String orgIdFilter = '(@sforganizationid=('+orgId.substring(0, 15)+') OR NOT @sforganizationid)';//every saleforce document from current org  + everything  that is not Salesforce conent
        String jsonReq = '{"userIds": [{"name":"' + UserInfo.getUserEmail() + '", "provider" : "Email Security Provider", "type" : "User"}],"filter": "'+orgIdFilter+'","userGroups": ["' + profileName + '"]}';
        System.debug('jsonReq: ' + jsonReq);
        String endPoint = endPointURL + 'token';
        
        HttpRequest request = new HttpRequest();
        
        request.setMethod('POST');
        
        request.setHeader('content-type', 'application/json');
        request.setHeader('Authorization', 'Bearer ' + randomKey);
        request.setEndpoint(endPoint);
        request.setBody(jsonReq);
        
        HTTPResponse response = http.send(request);
        system.debug('Response: ' + response.getBody());
        
        System.debug('response.getStatusCode(): ' + response.getStatusCode());
		if(response.getStatusCode() == 200) {
            System.debug('parsing record');
            JSONParser parser = JSON.createParser(response.getBody());
            parser.nextToken();
			parser.nextValue();
            coveoToken = parser.getText();
        }
        else {
            coveoToken = null;
        }
        system.debug('coveoToken: ' + coveoToken);
        
        return null;
    }
    
    @RemoteAction
    public static String getMyRecentSearch() {
        User usr = [SELECT Id, smartSearchMyRecentSearch__c FROm User WHERE Id =: UserInfo.getUserId()];
        
        return usr.smartSearchMyRecentSearch__c;
    }
    
    @RemoteAction
    public static void pushMyRecentSearch(String smartSearchMyRecentSearch) {
        User usr = [SELECT Id, smartSearchMyRecentSearch__c FROm User WHERE Id =: UserInfo.getUserId()];
        usr.smartSearchMyRecentSearch__c = smartSearchMyRecentSearch;
        
        update usr;
    }
    
    @RemoteAction
    public static String getMyRecentlyViewed() {
        User usr = [SELECT Id, smartSearchMyRecentlyViewed__c FROm User WHERE Id =: UserInfo.getUserId()];
        
        return usr.smartSearchMyRecentlyViewed__c;
    }
    
    @RemoteAction
    public static void pushMyRecentlyViewed(String smartSearchMyRecentlyViewed) {
        User usr = [SELECT Id, smartSearchMyRecentlyViewed__c FROm User WHERE Id =: UserInfo.getUserId()];
        usr.smartSearchMyRecentlyViewed__c = smartSearchMyRecentlyViewed;
        
        update usr;
    }
    /*
    @RemoteAction
    public static void DocumentSearchPush(String documentTitle, String documentURL, String sysurihash) {
        String documentDetailToStore = documentTitle + '@@@' + documentURL + '@@@' + sysurihash;
        List<String> recentlyViewed = new List<String>(); 
        
        User usr = [SELECT Id, smartSearchMyRecentlyViewed__c FROM User WHERE Id =: UserInfo.getUserId()];
        
        if(usr.smartSearchMyRecentlyViewed__c != null && usr.smartSearchMyRecentlyViewed__c != '') {
            recentlyViewed = usr.smartSearchMyRecentlyViewed__c.split(',');
        
            if(recentlyViewed.size() >= 10) {
                recentlyViewed.remove(0);
            }
        }
        
        recentlyViewed.add(documentDetailToStore);
        
        String smartSearchMyRecentlyViewed = String.join(recentlyViewed, ',');
        
        usr.smartSearchMyRecentlyViewed__c = smartSearchMyRecentlyViewed;
        
        update usr;
    }
    
    @RemoteAction
    public static String DocumentSearchPull() {
        User usr = [SELECT Id, smartSearchMyRecentlyViewed__c FROM User WHERE Id =: UserInfo.getUserId()];
        
        return usr.smartSearchMyRecentlyViewed__c;
    }*/
    
    public PageReference refreshProjects () {
		projects = ECO_Service_Projects.getProdjectsForUser(theUser.Id, showClosed, ptmPickListProvider.Role__c);
		return null;
	}
	
	public PageReference changeProjectOutputType () {
		
		Schema.DescribeSObjectResult d = pse__Proj__c.sObjectType.getDescribe();
		Schema.FieldSet fs = d.fieldSets.getMap().get(selectedOutputType);
		
		fieldSetFields = fs.getFields();
		
		return null;
	}
	
	public PageReference goToApplicationConfiguration () {
		PageReference returnPR = Page.ECO_ApplicationCustomizer;
		returnPR.getParameters().put('retURL', EncodingUtil.urlEncode('/apex/ECO_Portal', 'UTF-8'));
		return returnPR;
	}
 
	public PageReference goToApplicationConfigurationv2 () {
		PageReference returnPR = Page.ECO_ApplicationCustomizer;
		returnPR.getParameters().put('retURL', EncodingUtil.urlEncode('/apex/ECO_Portalv2', 'UTF-8'));
		return returnPR; 
	}
	
	public PageReference goToReportBuilder () {
		PageReference returnPR = Page.ECO_ReportFinder;
		returnPR.getParameters().put('retURL', EncodingUtil.urlEncode('/apex/ECO_Portal', 'UTF-8'));
		return returnPR;
	}

	public PageReference goToReportBuilderv2 () {
		PageReference returnPR = Page.ECO_ReportFinder;
		returnPR.getParameters().put('retURL', EncodingUtil.urlEncode('/apex/ECO_Portalv2', 'UTF-8'));
		return returnPR;
	}
	
	public PageReference goToNewProject () {
		
		//PageReference pageRef = Page.ECO_ProjectSetup;
		PageReference pageRef = new PageReference('/'+pse__Proj__c.sObjectType.getDescribe().getKeyPrefix()+'/e');
		pageRef.getParameters().put('retURL', EncodingUtil.urlEncode('/apex/ECO_Portal', 'UTF-8'));
		return pageRef;
	}
	
	public PageReference goToNewOpportunity () {
		//PageReference pageRef = new PageReference('/setup/ui/recordtypeselect.jsp?ent=Opportunity&retURL=%2F006%2Fo&save_new_url=%2F006%2Fe%3FretURL%3D%252F006%252Fo');
		PageReference pageRef = new PageReference('/'+Opportunity.sObjectType.getDescribe().getKeyPrefix()+'/e');
		return pageRef;
	}

	public PageReference goToHome () {
		PageReference pageRef = new PageReference('/home/');
		return pageRef;
	}
}