src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>JobName__c</fullName>
        <label>Job Name</label>
        <picklist>
            <picklistValues>
                <fullName>Queen Bee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Accountant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foreman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Designer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ECO_Job_Name__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ECO Job Name</label>
</CustomObject>

src/classes/ECO_JobNameBatch.cls
global class ECO_JobNameBatch implements Database.Batchable<sObject> {
	
	String query;
	
	global ECO_JobNameBatch() {
		query = 'select id, JobName__c from Contact where JobName__c != null';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Contact> scope) {
		Map<String, ECO_Job_Name__c> jobNameMap = ECO_Job_Name__c.getAll();

		Set<String> oldJobNames = new Set<String>();

		Integer highest = 0;

		for (ECO_Job_Name__c jobName : jobNameMap.values()) {
			oldJobNames.add(jobName.name__c);

			Integer current = Integer.valueOf(jobName.name);

			if (current > highest)
				highest = current;
		}

		Set<String> newJobNames = new Set<String>();

		for (Contact con : scope) {
			if (con.JobName__c.trim().equals(''))
				continue;

			if (oldJobNames.contains(con.JobName__c))
				continue;

			newJobNames.add(con.JobName__c);
		}

		Integer i = highest + 1;

		List<ECO_Job_Name__c> jobNameList = new List<ECO_Job_Name__c>();

		for (String jobNameString : newJobNames) {
			ECO_Job_Name__c jobName = new ECO_Job_Name__c();

			jobName.name = String.valueOf(i);
			jobName.name__c = jobNameString;

			jobNameList.add(jobName);

			i++;
		}

		upsert jobNameList;
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}