src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Shared_Services_Is_Executive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the current User a senior executive?  This will affect the prioritization of incoming requests for help.</description>
        <inlineHelpText>Is the current User a senior executive?  This will affect the prioritization of incoming requests for help.</inlineHelpText>
        <label>Shared Services Is Executive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the Contact to the User object.  This is for the representation of Employees.  Specifically, this is for the Shared Services Case Management.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Record Type for External Vendor Contact</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ssh_User_Contact_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting used to determine the record type being used for Employee vs Vendor Contacts. Also determines the name of the default internal account vs vendor account to which Contacts should belong after they are initially generated.</description>
    <fields>
        <fullName>Employee_Record_Type__c</fullName>
        <description>The record type for all AECOM employees</description>
        <label>Employee Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Vendor_Record_Type__c</fullName>
        <description>The record type for all External Vendors</description>
        <label>External Vendor Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Vendor_Uncategorized_Account__c</fullName>
        <description>Default Account to which External Vendor Contacts will be assigned since we don&apos;t know what account they belong to.</description>
        <label>External Vendor Uncategorized Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_User_Account__c</fullName>
        <description>Name of the Account with which all Contacts created for internal AECOM Users will be associated.</description>
        <label>Internal User Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SS-AP User/Contact Settings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Shared_Services_Is_Executive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the current User a senior executive?  This will affect the prioritization of incoming requests for help.</description>
        <inlineHelpText>Is the current User a senior executive?  This will affect the prioritization of incoming requests for help.</inlineHelpText>
        <label>Shared Services Is Executive</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/sshUpdateUserContactTest.cls
@isTest
private class sshUpdateUserContactTest {
	
	@isTest static void testUserContactUpdate() {
		Test.startTest();
		Account acct = new Account(Name = 'AECOM Internal Account');
		insert acct;

		Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];

		User u = new User(Alias = 'tboone', Email='SFDCTestCase@aecom.com', 
                        EmailEncodingKey='UTF-8', FirstName = 'Tony', LastName='Boone', LanguageLocaleKey='en_US', 
                        LocaleSidKey='en_US', ProfileId = p.Id, Department = 'Fake Department',
                        TimeZoneSidKey='America/Los_Angeles', UserName= 'tboone@ssh.com.test', Shared_Services_Is_Executive__c = true);

		insert u;

		ssh_User_Contact_Settings__c custSetting = new ssh_User_Contact_Settings__c();
		custSetting.Name = 'Default';
		custSetting.External_Vendor_Uncategorized_Account__c = 'Uncategorized Vendor';
		custSetting.External_Vendor_Record_Type__c = 'Vendor';
		custSetting.Employee_Record_Type__c = 'AECOM Employee';
		custSetting.Internal_User_Account__c = 'AECOM Internal Account';
		insert custSetting;

		//insert a Contact record
		Contact ct = new Contact(FirstName = 'Tony', LastName = 'Boone', Email = 'SFDCTestCase@aecom.com', Department = 'Fake Department',
			Shared_Services_Is_Executive__c = true, User__c = u.Id, Phone = '602-123-4567');

		insert ct;

		u.Phone = '602-867-5309';
		u.Department = 'Super Science';
		u.Shared_Services_Is_Executive__c = false;

		update u;		

		Test.stopTest();

		//requery OUTSIDE of the Test() block as the method called on User update is @future

		u = [select Phone, Department, Shared_Services_Is_Executive__c from User where Id = :u.Id];

		Contact ct2 = [select Phone, Department, Shared_Services_Is_Executive__c from Contact where Email = 'SFDCTestCase@aecom.com'];

		System.assertEquals(ct2.Phone, u.Phone);
		System.assertEquals(ct2.Department, u.Department);
		System.assertEquals(ct2.Shared_Services_Is_Executive__c, u.Shared_Services_Is_Executive__c);
	}
	
}