src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Used in reporting, to determine number of contacts associated with an account.</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the Contact to the User object.  This is for the representation of Employees.  Specifically, this is for the Shared Services Case Management.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectRole__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays only PSA resouces</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>PSA Resource</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Role</label>
        <referenceTo>ProjectRole__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersRole</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Project Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Director 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Accountant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Accountant Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Lead 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFO or Delegate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discipline Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HS&amp;E Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User must be active</description>
        <inlineHelpText>User must be active</inlineHelpText>
        <label>Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>User must be active</errorMessage>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>User must be active</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectTeamMemberUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000000}</displayFormat>
        <label>Project Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_Service_ProjectTeam.cls
public with sharing class ECO_Service_ProjectTeam {


    public static Id getActiveProjectAccountantId(Id projectId)
    {
    	list<ProjectTeamMember__c> teamMembers = [select Id, User__c, Contact__r.pse__Salesforce_User__c from ProjectTeamMember__c where ProjectRole__r.Name = 'Project Accountant' and Project__c = :projectId and Active__c = true];
		if(!teamMembers.isEmpty())
		{
			return teamMembers[0].Contact__r.pse__Salesforce_User__c;
		}
    	return null;
    }


    public static Id getActiveProjectApproverId(Id projectId)
    {
    	list<ProjectTeamMember__c> teamMembers = [select Id, User__c, Contact__r.pse__Salesforce_User__c from ProjectTeamMember__c where ProjectRole__r.Name = 'Project Approver' and Project__c = :projectId and Active__c = true];
		if(!teamMembers.isEmpty())
		{
			return teamMembers[0].Contact__r.pse__Salesforce_User__c;
		}
    	return null;
    }
    
    public static Id getActiveProjectFinanceLead(Id projectId)
    {
    	list<ProjectTeamMember__c> teamMembers = [select Id, User__c, Contact__r.pse__Salesforce_User__c from ProjectTeamMember__c where ProjectRole__r.Name = 'Finance Lead' and Project__c = :projectId and Active__c = true];
		if(!teamMembers.isEmpty())
		{
			return teamMembers[0].Contact__r.pse__Salesforce_User__c;
		}
    	return null;
    }    
    
    public static Id getActiveCFODelegate(Id projectId)
    {
    	list<ProjectTeamMember__c> teamMembers = [select Id, User__c, Contact__r.pse__Salesforce_User__c from ProjectTeamMember__c where ProjectRole__r.Name = 'CFO or Delegate' and Project__c = :projectId and Active__c = true];
		if(!teamMembers.isEmpty())
		{
			return teamMembers[0].Contact__r.pse__Salesforce_User__c;
		}
    	return null;
    }     

    public static Id getProjectManagerFromProjectTeam(Id projectId)
    {
        ProjectRole__c role = [select Id from ProjectRole__c where Name = 'Project Manager'];

        list<ProjectTeamMember__c> projectTeamMembers = [select Id, Role__c, Active__c, Contact__r.pse__Salesforce_User__c from ProjectTeamMember__c 
                                                         where Project__c = :projectId and Active__c = true 
                                                            and ProjectRole__c = :role.Id];    
                                                                     
        if(!projectTeamMembers.isEmpty())
            return projectTeamMembers[0].Contact__r.pse__Salesforce_User__c;
                
        return null;
    }

    public static Id populateProjectAccountant(Id projectId)
    {
        list<ProjectTeamMember__c> teamMembers = [select Id, User__c, Contact__r.pse__Salesforce_User__c from ProjectTeamMember__c where ProjectRole__r.Name = 'Project Accountant' and Project__c = :projectId and Active__c = true];
        if(!teamMembers.isEmpty())
        {
            return teamMembers[0].Contact__r.pse__Salesforce_User__c;
        }
        return null;
    }

    public static Id populateProjectFinanceLead(Id projectId)
    {
        list<ProjectTeamMember__c> teamMembers = [select Id, User__c, Contact__r.pse__Salesforce_User__c from ProjectTeamMember__c where ProjectRole__r.Name = 'Finance Lead' and Project__c = :projectId and Active__c = true];
        if(!teamMembers.isEmpty())
        {
            return teamMembers[0].Contact__r.pse__Salesforce_User__c;
        }
        return null;
    }    

}