src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Used in reporting, to determine number of contacts associated with an account.</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the Contact to the User object.  This is for the representation of Employees.  Specifically, this is for the Shared Services Case Management.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectRole__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Key Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays only PSA resouces</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>PSA Resource</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Role</label>
        <referenceTo>ProjectRole__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersRole</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User must be active</description>
        <inlineHelpText>User must be active</inlineHelpText>
        <label>Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>User must be active</errorMessage>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>User must be active</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectTeamMemberUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000000}</displayFormat>
        <label>Project Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_Project_TeamMember_Triggers.cls
public class ECO_Project_TeamMember_Triggers {
	
	public static void handleBeforeInsert(list<ProjectTeamMember__c> newTeamMembers)
	{
		/*map<Id, Id> projectTeamContactMap = new map<Id, Id>();
		
		for(ProjectTeamMember__c ptm: newTeamMembers)
			projectTeamContactMap.put(ptm.id, ptm.Contact__c);
		
		map<Id, Contact> contactsMap = new map<Id, Contact>([select Id, FirstName, LastName from Contact where Id in :projectTeamContactMap.values()]);
		
		for(ProjectTeamMember__c ptm: newTeamMembers)
		{
			ptm.Name = contactsMap.get(projectTeamContactMap.get(ptm.Id)).FirstName + ' ' + contactsMap.get(projectTeamContactMap.get(ptm.Id)).LastName;
		}*/

        //map<Id, Id> projectTeamContactMap = new map<Id, Id>();
        set<id> sContacts = new set<id>();
        
        for(ProjectTeamMember__c ptm: newTeamMembers){
           // projectTeamContactMap.put(ptm.id, ptm.Contact__c);
            sContacts.add(ptm.Contact__c);
        }
        
        map<Id, Contact> contactsMap = new map<Id, Contact>([select Id, FirstName, LastName from Contact where Id in :sContacts]);
        
        for(ProjectTeamMember__c ptm: newTeamMembers)
        {
            ptm.Name = contactsMap.get(ptm.Contact__c).FirstName + ' ' + contactsMap.get(ptm.Contact__c).LastName;
        }

	}

    public static void CreateSharingForTeamMembers(list<ProjectTeamMember__c> updatedTeamMembers){
                        
			system.debug( 'CreateSharingForTeamMembers called ' + updatedTeamMembers );
        
            List<pse__Proj__Share> projectShare = new List<pse__Proj__Share>();
        
        	Map<ID, ProjectRole__c> mapOfProjectRoles = new Map<ID, ProjectRole__c> ( [SELECT Active__c, Type__c, Id, Name FROM ProjectRole__c Where Active__c = true] );
        
        	Set<Id> contactIds = new Set<Id>();
        	    
			for(ProjectTeamMember__c ptm : updatedTeamMembers){ 
                
	        	ProjectRole__c pr = mapOfProjectRoles.get( ptm.projectrole__c );
                
                if ( pr.Type__c == 'Key Member' )
                {                    
                	contactIds.add(ptm.contact__c);		
                }
          	}
        
        	Map<ID, Contact> mapOfContacts = new Map<ID, Contact>([SELECT Id, pse__Salesforce_User__c FROM Contact where id in :contactIds]);
 
            for (ProjectTeamMember__c projectTeamMember : updatedTeamMembers) {
                
                Contact c = mapOfContacts.get(projectTeamMember.contact__c);

				if(c != null)
				{
	            	system.debug( 'projectTeamMember.contact__c ' + c + ' SF User =>' + c.pse__Salesforce_User__c );				
                
                	if( c.pse__Salesforce_User__c != null )
                	{                    
                    	system.debug( 'Inside projectTeamMember.contact__c ' + projectTeamMember.contact__c + ' ' +  projectTeamMember.project__c + ' ' + projectTeamMember.User__c );				

                    	pse__Proj__Share ps = new pse__Proj__Share();
                    	ps.AccessLevel = 'Edit';
                    	ps.ParentId = projectTeamMember.project__c;
                    	ps.UserOrGroupId =  c.pse__Salesforce_User__c;	
                    	ps.RowCause = Schema.pse__Proj__Share.RowCause.KeyMember__c;                    
                    	projectShare.add(ps);                   
                	}      
            	}
            }
        
    		if (!projectShare.isEmpty())
            {                      			
                upsert projectShare;
                
                system.debug( 'projectShare => ' + projectShare );
            }                
        }
}