src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>pse__Is_Resource_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resource Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse__Is_Resource__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resource</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EarnedValueSnapshot__c.object
<CustomObject>
    <label>Earned Value Snapshot</label>
    <nameField>
        <displayFormat>EVS-{00000000}</displayFormat>
        <label>Earned Value Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Earned Value Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>EarnedValueCurve__c</fullName>
        <label>Earned Value Curve</label>
        <picklist>
            <picklistValues>
                <fullName>Back Loaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bell Shaped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Even</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Front Loaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S Curve</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotalApprovedCost__c</fullName>
        <label>Total Approved Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pse__End_Date_Time__c</fullName>
        <description>The date &amp; time on which work for this Task is supposed to end.  Timecards may still be entered for a Task after this date as long as it is not closed for time entry.</description>
        <inlineHelpText>The date &amp; time on which work for this Task is supposed to end.  Timecards may still be entered for a Task after this date as long as it is not closed for time entry.</inlineHelpText>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project that the Task is a part of.</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Start_Date_Time__c</fullName>
        <description>The date &amp; time on which work for this Task is supposed to start.  Timecards may still be entered for a Task before this date as long as it is not closed for time entry.</description>
        <inlineHelpText>The date &amp; time on which work for this Task is supposed to start.  Timecards may still be entered for a Task before this date as long as it is not closed for time entry.</inlineHelpText>
        <label>Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_Service_EarnedValueTest.cls
@isTest
private class ECO_Service_EarnedValueTest {

    static testMethod void sCurveTest () {
        Account testAccount = new Account();
		testAccount.Name = 'test account';
		insert testAccount;
		
		Contact testContact = new Contact();
		testContact.AccountId = testAccount.Id;
		testContact.RecordTypeId = ECO_Utils_Meta.getRecordTypeId(Contact.sObjectType, ECO_Constants.Contact_PSAResourceRecordTypeName);
		testContact.LastName = 'test last';
		testContact.pse__Is_Resource_Active__c = true;
		testContact.pse__Is_Resource__c = true;
		insert testContact;
		
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.pse__Account__c = testAccount.Id;
		insert testProject;
		
		pse__Project_Task__c projTask = new pse__Project_Task__c();
		projTask.pse__Project__c = testProject.Id;
		projTask.EarnedValueCurve__c = 'S Curve';
		projTask.pse__Start_Date_Time__c = Date.today();
		projTask.pse__End_Date_Time__c = Date.today().addDays(21); // 3 weeks
		projTask.TotalApprovedCost__c = 10000;
		
		test.startTest();
		insert projTask;
		test.stopTest();
		
		List<EarnedValueSnapshot__c> evsAfterTest = [SELECT Id FROM EarnedValueSnapshot__c];
		system.assertEquals(false, evsAfterTest.isEmpty());
    }
    
    static testMethod void frontLoadedTest () {
        Account testAccount = new Account();
		testAccount.Name = 'test account';
		insert testAccount;
		
		Contact testContact = new Contact();
		testContact.AccountId = testAccount.Id;
		testContact.RecordTypeId = ECO_Utils_Meta.getRecordTypeId(Contact.sObjectType, ECO_Constants.Contact_PSAResourceRecordTypeName);
		testContact.LastName = 'test last';
		testContact.pse__Is_Resource_Active__c = true;
		testContact.pse__Is_Resource__c = true;
		insert testContact;
		
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.pse__Account__c = testAccount.Id;
		insert testProject;
		
		pse__Project_Task__c projTask = new pse__Project_Task__c();
		projTask.pse__Project__c = testProject.Id;
		projTask.EarnedValueCurve__c = 'Front Loaded';
		projTask.pse__Start_Date_Time__c = Date.today();
		projTask.pse__End_Date_Time__c = Date.today().addDays(21); // 3 weeks
		projTask.TotalApprovedCost__c = 10000;
		
		test.startTest();
		insert projTask;
		test.stopTest();
		
		List<EarnedValueSnapshot__c> evsAfterTest = [SELECT Id FROM EarnedValueSnapshot__c];
		system.assertEquals(false, evsAfterTest.isEmpty());
    }
    
    static testMethod void backLoadedTest () {
        Account testAccount = new Account();
		testAccount.Name = 'test account';
		insert testAccount;
		
		Contact testContact = new Contact();
		testContact.AccountId = testAccount.Id;
		testContact.RecordTypeId = ECO_Utils_Meta.getRecordTypeId(Contact.sObjectType, ECO_Constants.Contact_PSAResourceRecordTypeName);
		testContact.LastName = 'test last';
		testContact.pse__Is_Resource_Active__c = true;
		testContact.pse__Is_Resource__c = true;
		insert testContact;
		
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.pse__Account__c = testAccount.Id;
		insert testProject;
		
		pse__Project_Task__c projTask = new pse__Project_Task__c();
		projTask.pse__Project__c = testProject.Id;
		projTask.EarnedValueCurve__c = 'Back Loaded';
		projTask.pse__Start_Date_Time__c = Date.today();
		projTask.pse__End_Date_Time__c = Date.today().addDays(21); // 3 weeks
		projTask.TotalApprovedCost__c = 10000;
		
		test.startTest();
		insert projTask;
		test.stopTest();
		
		List<EarnedValueSnapshot__c> evsAfterTest = [SELECT Id FROM EarnedValueSnapshot__c];
		system.assertEquals(false, evsAfterTest.isEmpty());
    }
    
    static testMethod void bellShapedTest () {
        Account testAccount = new Account();
		testAccount.Name = 'test account';
		insert testAccount;
		
		Contact testContact = new Contact();
		testContact.AccountId = testAccount.Id;
		testContact.RecordTypeId = ECO_Utils_Meta.getRecordTypeId(Contact.sObjectType, ECO_Constants.Contact_PSAResourceRecordTypeName);
		testContact.LastName = 'test last';
		testContact.pse__Is_Resource_Active__c = true;
		testContact.pse__Is_Resource__c = true;
		insert testContact;
		
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.pse__Account__c = testAccount.Id;
		insert testProject;
		
		pse__Project_Task__c projTask = new pse__Project_Task__c();
		projTask.pse__Project__c = testProject.Id;
		projTask.EarnedValueCurve__c = 'Bell Shaped';
		projTask.pse__Start_Date_Time__c = Date.today();
		projTask.pse__End_Date_Time__c = Date.today().addDays(21); // 3 weeks
		projTask.TotalApprovedCost__c = 10000;
		
		test.startTest();
		insert projTask;
		test.stopTest();
		
		List<EarnedValueSnapshot__c> evsAfterTest = [SELECT Id FROM EarnedValueSnapshot__c];
		system.assertEquals(false, evsAfterTest.isEmpty());
    }
    
    static testMethod void evenTest () {
        Account testAccount = new Account();
		testAccount.Name = 'test account';
		insert testAccount;
		
		Contact testContact = new Contact();
		testContact.AccountId = testAccount.Id;
		testContact.RecordTypeId = ECO_Utils_Meta.getRecordTypeId(Contact.sObjectType, ECO_Constants.Contact_PSAResourceRecordTypeName);
		testContact.LastName = 'test last';
		testContact.pse__Is_Resource_Active__c = true;
		testContact.pse__Is_Resource__c = true;
		insert testContact;
		
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.pse__Account__c = testAccount.Id;
		insert testProject;
		
		pse__Project_Task__c projTask = new pse__Project_Task__c();
		projTask.pse__Project__c = testProject.Id;
		projTask.EarnedValueCurve__c = 'Even';
		projTask.pse__Start_Date_Time__c = Date.today();
		projTask.pse__End_Date_Time__c = Date.today().addDays(21); // 3 weeks
		projTask.TotalApprovedCost__c = 10000;
		
		test.startTest();
		insert projTask;
		test.stopTest();
		
		List<EarnedValueSnapshot__c> evsAfterTest = [SELECT Id FROM EarnedValueSnapshot__c];
		system.assertEquals(false, evsAfterTest.isEmpty());
    }
}