src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EnrollmentParticipant__c.object
<CustomObject>
    <fields>
        <fullName>EmployeeName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>PSA Resource, AECOM Employee</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Salesforce_User__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollment Participants</relationshipLabel>
        <relationshipName>Enrollment_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EmployeeStatus__c</fullName>
        <formula>If(OR(TEXT(EmployeeName__r.Status__c)=&quot;Employee - Active&quot;,TEXT(EmployeeName__r.Status__c)=&quot;Active&quot;, TEXT(EmployeeName__r.Status__c)=&quot;A&quot;), &quot;Active&quot;,
&quot;Inactive&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employee Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnrollmentPlan__c</fullName>
        <label>Enrollment Plan</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Enrollment Participants</relationshipLabel>
        <relationshipName>EnrollmentParticipants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TargetIncentivePoolAllocated__c</fullName>
        <inlineHelpText>Target % Incentive Pool Allocated</inlineHelpText>
        <label>Target %</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Enrollment Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EnrollmentPlan__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW Enrollment Plans under review by Approvers</description>
    <fields>
        <fullName>ApplicationType__c</fullName>
        <inlineHelpText>ENR: Initial Application
CCR: Combined Request for both Participant and Metrics Changes
MOD: Modeling Application that allows performance projections
PAY: Payment Request Application, the final stage in an active app lifecycle</inlineHelpText>
        <label>Form Type</label>
        <picklist>
            <picklistValues>
                <fullName>ENR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>CCR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending PM Action</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 1 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 2 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 3 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending DTW Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected for Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unenrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Corp Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - No Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt-Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ExceptionComments__c</fullName>
        <inlineHelpText>If there are exceptions listed above, a brief explanation should be provided for the next approver.  Enter one here, then hit save.  The comment will move to the history section below, and you will then be able to advance the form.</inlineHelpText>
        <label>Exception Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IncentiveProject__c</fullName>
        <label>Project Name</label>
        <referenceTo>IncentiveProject__c</referenceTo>
        <relationshipLabel>Enrollment Applications</relationshipLabel>
        <relationshipName>Enrollment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MA_Comments__c</fullName>
        <inlineHelpText>Edit field for entering Management Adjustment comments. Text will be archived in the Enrollment Comments section and this field will be cleared.</inlineHelpText>
        <label>MA Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ParentApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to Enrolled Application related to this Change request</inlineHelpText>
        <label>Parent Application</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Change Request Applications</relationshipLabel>
        <relationshipName>Enrollment_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment Application</label>
    <nameField>
        <label>Enrollment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Applications</pluralLabel>
    <recordTypes>
        <fullName>Enrolled</fullName>
        <active>true</active>
        <label>Enrolled</label>
    </recordTypes>
    <recordTypes>
        <fullName>Exception</fullName>
        <active>true</active>
        <label>Exception</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IncentiveProject__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW eligible projects to be considered for enrollment in DTW Incentive Plans</description>
    <fields>
        <fullName>ChangeRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change Request</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Incentive Projects (Change Request)</relationshipLabel>
        <relationshipName>Incentive_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enrollment Application</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Incentive Projects</relationshipLabel>
        <relationshipName>IncentiveProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <formula>IF( PaymentRequest__c &lt;&gt; &quot;&quot;,  Text(PaymentRequest__r.EnrollmentStatus__c),

IF(
    AND(
       (EnrollmentPlan__c=&quot;&quot;), 
        OR(
           TEXT(FPPOverallEligibility__c)=&quot;Yes&quot;,
           TEXT(TMPlanOverallEligibility__c)=&quot;Yes&quot;
           )
         ),
&quot;Pending DTW Action&quot;, 
IF(
   (EnrollmentPlan__c=&quot;&quot;), &quot;Not Eligible&quot;,
   TEXT(EnrollmentPlan__r.EnrollmentStatus__c)
   )
   )
)</formula>
        <label>Enrollment Status</label>
        <type>Text</type>
    </fields>
    <label>Incentive Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ParticipantAcknowledgement__c.object
<CustomObject>
    <description>Used by DTW Project Incentive as a placeholder for a Digital Acknowledgement as well as for participants , refer to User Story 00864 and related work items.</description>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <formula>TEXT(ParticipantID__r.EnrollmentPlan__r.EnrollmentStatus__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Enrollment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IncentiveProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incentive Project</label>
        <referenceTo>IncentiveProject__c</referenceTo>
        <relationshipLabel>Participant Acknowledgements</relationshipLabel>
        <relationshipName>Participant_Acknowledgements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParticipantID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant ID</label>
        <referenceTo>EnrollmentParticipant__c</referenceTo>
        <relationshipName>Acknowledgments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Acknowledgement</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Participant Acknowledgement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Acknowledgements</pluralLabel>
    <recordTypes>
        <fullName>Sent</fullName>
        <active>true</active>
        <label>Sent</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/INC_EnrollmentPlanTriggers.cls
public with sharing class INC_EnrollmentPlanTriggers {

    Private Static Boolean beforeRun = true;
    Public Static Boolean afterRun = true;
    
    Public Static Boolean beforeRunOnce() {
        if(beforeRun) {
            beforeRun = false;
            return true;
        }else {
            return beforeRun;
        }    
    }
    
    Public Static Boolean afterRunOnce() {
        if(afterRun) {
            afterRun = false;
            System.Debug(logginglevel.error,'afterRunOnce true');
            return true;
        }else {
        	System.Debug(logginglevel.error,'afterRunOnce false');
            return afterRun;
        }    
    }
    
	public INC_EnrollmentPlanTriggers() {
		
	}

	public void createEnrollmentCommentsFromExceptionandMA(list<EnrollmentPlan__c> listEnrollmentPlans){
		INC_Service_EnrollmentPlan.createEnrollmentcomment(listEnrollmentplans);
		for(EnrollmentPlan__c ep: listEnrollmentplans){
			ep.ExceptionComments__c = null;
			ep.MA_Comments__c = null;
		}
	}

	public void createApprovalComments(map<id,EnrollmentPlan__c> mapNew, map<id,EnrollmentPlan__c> mapOld){
	
		set<id> setChangedEnrollmentPlans = new set<id>();
		set<String> setStatuses = new set<String>{'Pending PM Action'	
												  	,'Pending Approver 1 Action'
												  	,'Pending Approver 2 Action'	
													,'Pending Approver 3 Action'
													,'Pending DTW Admin'
													,'Enrolled'
													,'Rejected'
													,'Rejected for Correction'
												};
		for(EnrollmentPlan__c ep: mapNew.Values()){
			System.debug(logginglevel.error,'ep.EnrollmentStatus__c ' + ep.EnrollmentStatus__c + ' old: ' + mapOld.get(ep.id).EnrollmentStatus__c);
			if(ep.EnrollmentStatus__c != mapOld.get(ep.id).EnrollmentStatus__c){
				if(setStatuses.Contains(ep.EnrollmentStatus__c)){
					System.Debug(logginglevel.error,'Adding app to set to create comments');
					setChangedEnrollmentPlans.add(ep.id);
				}
			}
		}

		if(setChangedEnrollmentPlans != null && setChangedEnrollmentPlans.size() > 0){
			System.Debug(logginglevel.error,'Calling create comments code');
			INC_Service_EnrollmentPlan.createEnrollmentCommentsFromApproval(setChangedEnrollmentPlans);
		}
	} 

	public void setParticipantstoReadOnly(map<id,EnrollmentPlan__c> mapNew, map<id,EnrollmentPlan__c> mapOld){
		set<id> enrollmentPlans = new set<id>();
		set<id> rejectedPlans = new set<id>();
		for(EnrollmentPlan__c EnrollPlan: mapNew.Values()){
			if(EnrollPlan.EnrollmentStatus__c == 'Enrolled' && 
				(EnrollPlan.EnrollmentStatus__c != mapOld.get(EnrollPlan.ID).EnrollmentStatus__c)){
				enrollmentPlans.add(EnrollPlan.ID);
			}
		}
		System.Debug(logginglevel.error,'Plans to fix participants ' + enrollmentPlans);
		if(enrollmentPlans != null && enrollmentPlans.size() > 0){
			list<EnrollmentParticipant__c> listUpdates = new list<EnrollmentParticipant__c>();
			Id readOnlyTypeId = ECO_Utils_sObject.getRecordTypeId(EnrollmentParticipant__c.sObjectType,'Read Only Participant');
			System.Debug(logginglevel.error,'Readonly ID ' + readOnlyTypeId);

			for(EnrollmentParticipant__c EP: [Select id
													   ,RecordTypeId
				       						  From EnrollmentParticipant__c
				       						  Where EnrollmentPlan__c =: enrollmentPlans]){
				System.Debug(logginglevel.error,'Found participants: ' + EP);
				EP.RecordTypeId = readOnlyTypeId;
				listUpdates.add(EP);
			}

			if(listUpdates != null && listUpdates.size() > 0){
				System.Debug(logginglevel.error,'Saving participants' + listUpdates.size());
				System.savePoint sp = Database.setSavePoint();
		        try{
		            Update listUpdates;
		        }catch(Exception e){
		            system.debug('Handling Exception:  '+e.getMessage() + ' ' + e.getStackTraceString());
		            system.debug(logginglevel.error, 'enrollmentPlan creation error: ' + e);
		            Database.rollBack(sp);
		        }
			}
		}

	}

	public void finishenrollmentOfChangeRequest(map<id,EnrollmentPlan__c>mapNew, map<id,EnrollmentPlan__c>mapOld){
		map<id,id> mapIncentiveByEnrollment = new map<id,id>();
		set<id> enrollmentAppsToUpdate = new set<id>();
		set<id> rejectedPlans = new set<id>();
		for(EnrollmentPlan__c enr: mapNew.Values()){
			if(enr.ApplicationType__c == 'CCR'){
				if(enr.EnrollmentStatus__c == 'Enrolled' && mapOld.get(enr.ID).EnrollmentStatus__c != 'Enrolled'){
					if(mapNew.containsKey(enr.ParentApplication__c)){
						mapNew.get(enr.ParentApplication__c).EnrollmentStatus__c = 'Archived';
					}else{
						enrollmentAppsToUpdate.add(enr.ParentApplication__c);
					}
					mapIncentiveByEnrollment.put(enr.IncentiveProject__c,enr.Id);
				}else{
					if(enr.EnrollmentStatus__c == 'Rejected' && 
				  	(mapOld.get(enr.ID).EnrollmentStatus__c != 'Rejected')){
						rejectedPlans.add(enr.ID);
						mapIncentiveByEnrollment.put(enr.IncentiveProject__c,enr.Id);
					}
				}
			}
		}

		if(enrollmentAppsToUpdate != null && enrollmentAppsToUpdate.size()> 0){
			list<EnrollmentPlan__c> listEnrollments = new list<EnrollmentPlan__c>();
			for(EnrollmentPlan__c EP: [Select ID
												, EnrollmentStatus__c
									   From EnrollmentPlan__c
									   Where id =: enrollmentAppsToUpdate]){
				EP.EnrollmentStatus__c = 'Archived';
				listEnrollments.add(EP);
			}
			System.SavePoint sp = Database.setSavePoint();
			if(listEnrollments != null && listEnrollments.size() > 0){
				try{
					update listEnrollments;
				}catch(Exception E){
					System.Debug(logginglevel.error,'Problem updateing enrollmentPlans ' + e.getMessage());
				}
			}
		}

		if(mapIncentiveByEnrollment != null && mapIncentiveByEnrollment.size() > 0){
			list<IncentiveProject__c> listIncentive = new list<IncentiveProject__c>();
			for(IncentiveProject__c INC: [Select ID
												   , ChangeRequest__c
												   , EnrollmentPlan__c
										  From IncentiveProject__c
										  where ID =: mapIncentiveByEnrollment.KeySet()]){
				if(!rejectedPlans.Contains(mapIncentiveByEnrollment.get(INC.ID))){
					INC.EnrollmentPlan__c = mapIncentiveByEnrollment.get(INC.ID);
				}
				INC.ChangeRequest__c = null;
				listIncentive.add(INC);
			}
			System.SavePoint sp = Database.setSavePoint();
			if(listIncentive != null && listIncentive.size() > 0){
				try{
					update listIncentive;
				}catch(Exception E){
					System.Debug(logginglevel.error,'Problem updateing listIncentive ' + e.getMessage());
				}
			}
		}


	}
    
    /**
     * This method is responsible for creating Participant Acknowledgement records
     * Work Item: WI-003593
     * Built By: Sanchivan Sivadasan 
     */
    public void createParticipantAcknowledgement(Map<Id, EnrollmentPlan__c> newMap, Map<Id, EnrollmentPlan__c> oldMap ) {
        System.Debug(logginglevel.error,'creating acknowledgements' + newMap);
        Set<Id> ePlanIdsEnrolled = new Set<Id>();
        // Collect all Enrollments that are enrolled
        for(EnrollmentPlan__c ePlan : newMap.values()) {
            System.debug('Looping through Enrollment Plan');
            System.debug('ePlan.EnrollmentStatus__c:' + ePlan.EnrollmentStatus__c);
            System.debug('oldMap.get(ePlan.Id).EnrollmentStatus__c:' + oldMap.get(ePlan.Id).EnrollmentStatus__c);
            if(ePlan.EnrollmentStatus__c == 'Enrolled' && oldMap.get(ePlan.Id).EnrollmentStatus__c != 'Enrolled') {
                ePlanIdsEnrolled.add(ePlan.Id);
            }
        }
        System.Debug(logginglevel.error,'ePlanIdsEnrolled ' + ePlanIdsEnrolled);

        List<ParticipantAcknowledgement__c> participantAcknowledgementsToCreate = new List<ParticipantAcknowledgement__c>();
        
        // Retrieve all Enrollment Participants for the Enrolled Enrollments which has a Status of Active and Target Allocation > 0
        // Then prepare Participant Acknowledgement records that needs to be inserted
        for(EnrollmentParticipant__c ePar : [SELECT Id
        											, EmployeeName__r.Email
        											, EmployeeName__r.pse__Salesforce_User__c 
        											, EmployeeName__r.pse__Salesforce_User__r.ManagerId
        											, EmployeeStatus__c
        											, TargetIncentivePoolAllocated__c
        											, EnrollmentPlan__c 
        											, CurrencyISOCode
                                             FROM EnrollmentParticipant__c 
                                             WHERE EnrollmentPlan__c in : ePlanIdsEnrolled AND EmployeeStatus__c = 'Active' AND TargetIncentivePoolAllocated__c > 0]) {
        	System.Debug(logginglevel.error,'Found participant ' + ePar.EmployeeName__r.pse__Salesforce_User__r.ManagerId);
            ParticipantAcknowledgement__c pA = new ParticipantAcknowledgement__c();
			pA.RecordTypeId = Schema.SObjectType.ParticipantAcknowledgement__c.getRecordTypeInfosByName().get('Sent').getRecordTypeId();
			pA.OwnerId = ePar.EmployeeName__r.pse__Salesforce_User__c;
			pA.Manager__c = ePar.EmployeeName__r.pse__Salesforce_User__r.ManagerId;
			pA.ParticipantID__c = ePar.Id;
			pA.CurrencyISOCode = ePar.CurrencyISOCode;
                                                 
			participantAcknowledgementsToCreate.add(pA);
        }
        
        // Create the Participant Acknowledgements
        System.debug(logginglevel.error,'participantAcknowledgementsToCreate ' + participantAcknowledgementsToCreate.size());
        if(participantAcknowledgementsToCreate != null && participantAcknowledgementsToCreate.size() > 0){
            System.Debug(logginglevel.error,'Creating participant acknowledgements' + participantAcknowledgementsToCreate.size());
            System.savePoint sp = Database.setSavePoint();
            
            try{
                Insert participantAcknowledgementsToCreate;
            }catch(Exception e){
                system.debug('Handling Exception:  ' + e.getMessage() + ' ' + e.getStackTraceString());
                system.debug(logginglevel.error, 'participant acknowledgement creation error: ' + e);
                Database.rollBack(sp);
            }
        }
    }	
}