src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Used in reporting, to determine number of contacts associated with an account.</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays only PSA resouces</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>PSA Resource</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000000}</displayFormat>
        <label>Project Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchDeleteProjectSharing.cls
global without sharing class BatchDeleteProjectSharing implements Database.Batchable<SObject>, Database.Stateful {

    private System.LoggingLevel debugLevel = LoggingLevel.INFO;
    private Date billingDate;
    
    Map<Id, Account> mapServiceAccountsMissingAccountIdentifierType; 
    
    global String query;

    global BatchDeleteProjectSharing (){
		this.query = 'SELECT Active__c, StartDate__c, EndDate__c, Contact__c, Id, Project__c, contact__r.name, contact__r.pse__Salesforce_User__c FROM ProjectTeamMember__c where Active__c = false and EndDate__c <= TODAY order by EndDate__c desc Limit 1000' ;    	
        system.debug( 'BatchDeleteProjectSharing Constructor' );
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        system.debug(debugLevel, 'Beginning BatchPreBillingValidation Execution.');
       
        return Database.getQueryLocator(query);
    }
    
    global void execute( Database.BatchableContext BC, List<SObject> projectTeamMemberItemsToProcess ) {
            
        Set<Id> projectIds = new Set<Id> (); 
        Set<String> listOfKeysToDelete = new Set<String> ();
        
        system.debug( 'projectTeamMemberItemsToProcess size ' + projectTeamMemberItemsToProcess.size() );
        
        string keyToDel;
        for(ProjectTeamMember__c thisProjectTeamMember : (List<ProjectTeamMember__c>) projectTeamMemberItemsToProcess){
        	 projectIds.add( thisProjectTeamMember.Project__c );
             keyToDel = String.Valueof(thisProjectTeamMember.contact__r.pse__Salesforce_User__c) + String.ValueOf(thisProjectTeamMember.Project__c);
             listOfKeysToDelete.add( keyToDel );
        }     
        
        system.debug( 'listOfKeysToDelete ' + listOfKeysToDelete + ' projectIds ' + projectIds );
        
      	List<pse__Proj__Share> listProjShare = [SELECT id, ParentId, UserOrGroupId, RowCause, AccessLevel from pse__Proj__Share where RowCause = 'KeyMember__c'  and ParentId in : projectIds ];
        
		Map <String,  pse__Proj__Share> mapSearchIdProjectShare = new Map <String,  pse__Proj__Share>();
        
        for(pse__Proj__Share thisProjectShare : (List<pse__Proj__Share>) listProjShare){
            string key = String.Valueof(thisProjectShare.UserOrGroupId) + String.ValueOf(thisProjectShare.ParentId);
            system.debug( 'mapSearchIdProjectShare ' + key );
        	mapSearchIdProjectShare.put( key, thisProjectShare );         
        }  

		List<pse__Proj__Share> projectSharesToDelete = new List<pse__Proj__Share>();
        
		for(string idToDelete: listOfKeysToDelete){
    		if( mapSearchIdProjectShare.get(idToDelete) != null )	
            {
				projectSharesToDelete.add(mapSearchIdProjectShare.get(idToDelete));                              
            }                
   		}  
        
        system.debug( 'projectSharesToDelete ' + projectSharesToDelete + ' projectSharesToDelete size ' + projectSharesToDelete.size() );
        
        delete projectSharesToDelete;
    }  
    
    global void finish(Database.BatchableContext BC) {
        
    }    
        
}