src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>JobName__c</fullName>
        <label>Job Name</label>
        <picklist>
            <picklistValues>
                <fullName>Queen Bee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Accountant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foreman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Designer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>If this person moves to another account: (a) change this field to &quot;No Longer with Client,&quot; (b) enter a note in the &quot;Need to Know&quot; field below, and (c) create a new Contact record under the new account.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No longer with client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the Contact to the User object.  This is for the representation of Employees.  Specifically, this is for the Shared Services Case Management.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IntegrationMessageQueue__c.object
<CustomObject>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>JobName__c</fullName>
        <label>Job Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SuccessMessage__c</fullName>
        <label>Success Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Message Queue</label>
    <nameField>
        <displayFormat>IMQ-{0000000}</displayFormat>
        <label>Integration Message Queue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Message Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>OracleSyncErrorMessage__c</fullName>
        <label>Oracle Sync Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OracleSyncStatus__c</fullName>
        <label>Oracle Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>P</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipName>ProjectSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Site</label>
    <nameField>
        <displayFormat>ProjectSite-{0000000000}</displayFormat>
        <label>Project Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProjectTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>OracleProjectNumber__c</fullName>
        <formula>Project__r.OracleProjectnumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Oracle Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OracleSyncErrorMessage__c</fullName>
        <label>Oracle Sync Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OracleSyncStatus__c</fullName>
        <description>P = Pending
T = Transfer (Success)
E = Error
S = Successful</description>
        <inlineHelpText>P = Pending
T = Transfer (Success)
E = Error
S = Successful</inlineHelpText>
        <label>Oracle Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Project Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Director 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Accountant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Accountant Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Lead 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFO or Delegate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discipline Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HS&amp;E Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User must be active</description>
        <inlineHelpText>User must be active</inlineHelpText>
        <label>Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>User must be active</errorMessage>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>User must be active</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectTeamMemberUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000000}</displayFormat>
        <label>Project Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <recordTypes>
        <fullName>KeyMember</fullName>
        <active>true</active>
        <label>Key Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>OracleLastSyncDateTime__c</fullName>
        <description>timestamp of when last successful sync took place</description>
        <label>Oracle Last Sync DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OracleSyncErrorMessage__c</fullName>
        <label>Oracle Sync Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OracleSyncStatus__c</fullName>
        <description>P = Pending
T = Transfer (Success)
E = Error
S = Successful</description>
        <inlineHelpText>P = Pending
T = Transfer (Success)
E = Error
S = Successful</inlineHelpText>
        <label>Oracle Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project that the Task is a part of.</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>JobName__c</fullName>
        <label>Job Name</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the overall profile</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ECO_IntegrationMessageQueueTriggers.cls
public without sharing class ECO_IntegrationMessageQueueTriggers {
	public static Boolean run = true;
	
	private static System.LoggingLevel debugLevel = LoggingLevel.INFO;

	private static final String ORACLE_SYNC_STATUS_SUCCESS = 'S';
	private static final String ORACLE_SYNC_STATUS_ERROR = 'E';
	private static final String ORACLE_SYNC_STATUS_PENDING = 'P';
	private static final String ORACLE_SYNC_STATUS_TRANSFER = 'T';
	
	public static void updateProjectNumber (List<IntegrationMessageQueue__c> messages) {
		List<pse__Proj__c> projectsToUpdate = new List<pse__Proj__c>();

		Set<Id> succesfulProjectSyncsIds = new Set<Id>();
		Set<Id> failedProjectSyncsIds = new Set<Id>();
		Map<Id, DateTime> successfulProjectSyncIdLastModDate = new Map<Id, DateTime>();

		for (IntegrationMessageQueue__c imq : messages) {
			if ('Project Number'.equalsIgnoreCase(imq.JobName__c) 
				&& 'Success'.equalsIgnoreCase(imq.Status__c)) {
					system.debug('success project number found');
					//upon successful creation of project in oracle initiated from a project number request in salesforce,
					//both oracle project number and project id will be returned seperated by a "|" (ProjectNumber|ProjectID)
					pse__Proj__c projectToUpdate = new pse__Proj__c();
					projectToUpdate.Id = (Id)imq.RecordId__c;
					String successMsg = imq.SuccessMessage__c;
					if(!String.isEmpty(successMsg)){						
						List<String> oracleValues = successMsg.split('\\|');
						system.debug('successMsg = ' + successMsg);
						system.debug('oracleValues size = ' + oracleValues.size());
						projectToUpdate.OracleProjectnumber__c = oracleValues.get(0);
						if(oracleValues.size() > 1){
							projectToUpdate.OracleProjectId__c = oracleValues.get(1);
						}
						system.debug('OracleProjectnumber__c = ' + projectToUpdate.OracleProjectnumber__c);
						system.debug('OracleProjectId__c = ' + projectToUpdate.OracleProjectId__c);
						projectsToUpdate.add(projectToUpdate);
					}	
			} else if ('Project Sync'.equalsIgnoreCase(imq.JobName__c) ){

				system.debug('DEBUG****: START2');
				if('Success'.equalsIgnoreCase(imq.Status__c)) {
					system.debug('DEBUG****: START3');
					pse__Proj__c projectSuccess = new pse__Proj__c();
					projectSuccess.Id = (Id)imq.RecordId__c;
					projectSuccess.OracleSyncStatus__c = ORACLE_SYNC_STATUS_SUCCESS;
					projectSuccess.OracleSyncErrorMessage__c = null;
					projectsToUpdate.add(projectSuccess);
					succesfulProjectSyncsIds.add(projectSuccess.Id);
					successfulProjectSyncIdLastModDate.put(projectSuccess.Id, imq.LastModifiedDate);
				} else if ('Error'.equalsIgnoreCase(imq.Status__c) || 'Attempted'.equalsIgnoreCase(imq.Status__c)){
					system.debug('DEBUG****: START4');
					pse__Proj__c projectError = new pse__Proj__c();
					projectError.Id = (Id)imq.RecordId__c;
					projectError.OracleSyncStatus__c = ORACLE_SYNC_STATUS_ERROR;
					projectError.OracleSyncErrorMessage__c = imq.ErrorMessage__c;
					projectsToUpdate.add(projectError);
					failedProjectSyncsIds.add(projectError.Id);
				} else if ('Initiated'.equalsIgnoreCase(imq.Status__c)) {
					system.debug('DEBUG****: START5');
					pse__Proj__c projectInitiated = new pse__Proj__c();
					projectInitiated.Id = (Id)imq.RecordId__c;
					projectInitiated.OracleSyncStatus__c = ORACLE_SYNC_STATUS_PENDING;
					projectInitiated.OracleSyncErrorMessage__c = null;
					projectsToUpdate.add(projectInitiated);
				} else if ('Sent'.equalsIgnoreCase(imq.Status__c)) {
					system.debug('DEBUG****: START6');
					pse__Proj__c projectSent = new pse__Proj__c();
					projectSent.Id = (Id)imq.RecordId__c;
					projectSent.OracleSyncStatus__c = ORACLE_SYNC_STATUS_TRANSFER;
					projectSent.OracleSyncErrorMessage__c = imq.ErrorMessage__c;
					projectsToUpdate.add(projectSent);
				}
			}

			/*
			todo - per specs once a project gets created in oracle subsequent webservice commits will have limited sections of payload
			that can be manipulated. If we need to update any flags in the project we can do it here.
			*/

			/*
			NOTE: if an error occurs on the error side the record will be updated with Status__c - "Error" and the ErrorMessage__c should
			should contain the error msg. A workflow will then send an email to the user who initiated the request
			*/
		}

		//Advance status on first successful sync

		system.debug('DEBUG****: HERE');
		if(!succesfulProjectSyncsIds.isEmpty()){
			map<id, pse__Proj__c> mSuccessfulProjects = new map<id, pse__Proj__c>([SELECT Id, RecordTypeId, pse__Stage__c FROM pse__Proj__c WHERE id in :succesfulProjectSyncsIds]);
			system.debug('DEBUG****: HERE2');
			id sPlanning = ECO_Utils_Meta.getRecordTypeId(pse__Proj__c.sObjectType, 'Customer Project (Planning)');
			id sApproved = ECO_Utils_Meta.getRecordTypeId(pse__Proj__c.sObjectType, 'Customer Project (Approved)');

			for(pse__Proj__c oProject : projectsToUpdate){
				system.debug('DEBUG****: HERE3');
				pse__Proj__c oProjectToCheck = mSuccessfulProjects.get(oProject.Id);

				if(ECO_Utils_String.NullChecK(oProjectToCheck.RecordTypeId) == sPlanning){
					oProject.RecordTypeId = sApproved;
					oProject.pse__Stage__c = 'Execution';
				}
			}
		}

		if(!projectsToUpdate.isEmpty()){
			update projectsToUpdate;
		}
		
		//update oracle sync status on related items for successful syncs, current status should be 'T'
		if(!succesfulProjectSyncsIds.isEmpty()){
			updateProjectTasksSyncStatus(succesfulProjectSyncsIds, ORACLE_SYNC_STATUS_TRANSFER, ORACLE_SYNC_STATUS_SUCCESS, successfulProjectSyncIdLastModDate);
			updateKeyMemberSyncStatus(succesfulProjectSyncsIds, ORACLE_SYNC_STATUS_TRANSFER, ORACLE_SYNC_STATUS_SUCCESS, successfulProjectSyncIdLastModDate);
			updateProjectSitesSyncStatus(succesfulProjectSyncsIds, ORACLE_SYNC_STATUS_TRANSFER, ORACLE_SYNC_STATUS_SUCCESS, successfulProjectSyncIdLastModDate);
		}
		
		//update oracle sync status on related items for failed syncs, current status should be 'T'
		if(!failedProjectSyncsIds.isEmpty()){
			updateProjectTasksSyncStatus(failedProjectSyncsIds, ORACLE_SYNC_STATUS_TRANSFER, ORACLE_SYNC_STATUS_ERROR, successfulProjectSyncIdLastModDate);
			updateKeyMemberSyncStatus(failedProjectSyncsIds, ORACLE_SYNC_STATUS_TRANSFER, ORACLE_SYNC_STATUS_ERROR, successfulProjectSyncIdLastModDate);
			updateProjectSitesSyncStatus(failedProjectSyncsIds, ORACLE_SYNC_STATUS_TRANSFER, ORACLE_SYNC_STATUS_ERROR, successfulProjectSyncIdLastModDate);
		}
	}
	
	public static void updatePMOwnerFromKeymembers (List<IntegrationMessageQueue__c> messages) {
		Set<Id> allProjectIds = new Set<Id>();
		for (IntegrationMessageQueue__c imq : messages) {
			if ('Project Number'.equalsIgnoreCase(imq.JobName__c) 
				&& 'Success'.equalsIgnoreCase(imq.Status__c)) {
					allProjectIds.add((Id)imq.RecordId__c);
			}
		}
		
		List<pse__Proj__c> projectWithKeyMembersList = [SELECT Id
																, (SELECT Id
																		, User__c
																		, User__r.ContactId
																		, Role__c 
																	FROM ProjectTeamMembers__r
																	WHERE Role__c = 'Project Manager')  
														FROM pse__Proj__c 
														WHERE Id IN :allProjectIds ];

		for (pse__Proj__c proj : projectWithKeyMembersList) {
			if (!proj.ProjectTeamMembers__r.isEmpty()) {
				ProjectTeamMember__c ptm = proj.ProjectTeamMembers__r[0];
				proj.OwnerId = ptm.User__c;
				proj.pse__Project_Manager__c = ptm.User__r.ContactId;  //This field is a contact
			}
		}
		
		update projectWithKeyMembersList;
	}


	private static void updateProjectTasksSyncStatus(Set<Id> projectIds, String syncSourceStatus, String syncTargetStatus, Map<Id, DateTime> syncDateTimes){
		List<pse__Project_Task__c> lTasks =  [SELECT Id, 
													OracleSyncStatus__c,
													OracleLastSyncDateTime__c,
													pse__Project__c
												FROM pse__Project_Task__c
												WHERE pse__Project__c IN :projectIds
												AND OracleSyncStatus__c = :syncSourceStatus];

		if(!lTasks.isEmpty()){
			for(pse__Project_Task__c task : lTasks){
				task.OracleSyncStatus__c = syncTargetStatus;
				if(syncTargetStatus == ORACLE_SYNC_STATUS_SUCCESS && syncDateTimes.containsKey(task.pse__Project__c)){
					task.OracleLastSyncDateTime__c = syncDateTimes.get(task.pse__Project__c);
				}
			}
			update lTasks;
		}		
	}

	public static void updateKeyMemberSyncStatus(Set<Id> projectIds, String syncSourceStatus, String syncTargetStatus, Map<Id, DateTime> syncDateTimes){
		List<ProjectTeamMember__c> lKeyMembers = [SELECT Id, 
														OracleSyncStatus__c,
														OracleLastSyncDateTime__c,
														Project__c
													FROM ProjectTeamMember__c
													WHERE Project__c IN :projectIds
													AND OracleSyncStatus__c = :syncSourceStatus];

		if(!lKeyMembers.isEmpty()){
			for(ProjectTeamMember__c keyMember : lKeyMembers){
				keyMember.OracleSyncStatus__c = syncTargetStatus;
				if(syncTargetStatus == ORACLE_SYNC_STATUS_SUCCESS && syncDateTimes.containsKey(keyMember.Project__c)){
					keyMember.OracleLastSyncDateTime__c = syncDateTimes.get(keyMember.Project__c);
				}
			}
			update lKeyMembers;
		}
		
	}

	public static void updateProjectSitesSyncStatus(Set<Id> projectIds, String syncSourceStatus, String syncTargetStatus, Map<Id, DateTime> syncDateTimes){
		List<Project_Site__c> lProjectSites = [SELECT Id, 
														OracleSyncStatus__c,
														OracleLastSyncDateTime__c,
														Project__c
													FROM Project_Site__c
													WHERE Project__c IN :projectIds
													AND OracleSyncStatus__c = :syncSourceStatus];

		if(!lProjectSites.isEmpty()){
			for(Project_Site__c site : lProjectSites){
				site.OracleSyncStatus__c = syncTargetStatus;
				if(syncTargetStatus == ORACLE_SYNC_STATUS_SUCCESS && syncDateTimes.containsKey(site.Project__c)){
					site.OracleLastSyncDateTime__c = syncDateTimes.get(site.Project__c);
				}
			}
			update lProjectSites;
		}
		
	}
}