src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Shared_Services_Is_Executive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the current User a senior executive?  This will affect the prioritization of incoming requests for help.</description>
        <inlineHelpText>Is the current User a senior executive?  This will affect the prioritization of incoming requests for help.</inlineHelpText>
        <label>Shared Services Is Executive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the Contact to the User object.  This is for the representation of Employees.  Specifically, this is for the Shared Services Case Management.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Record Type for External Vendor Contact</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ssh_User_Contact_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting used to determine the record type being used for Employee vs Vendor Contacts. Also determines the name of the default internal account vs vendor account to which Contacts should belong after they are initially generated.</description>
    <fields>
        <fullName>Employee_Record_Type__c</fullName>
        <description>The record type for all AECOM employees</description>
        <label>Employee Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Vendor_Record_Type__c</fullName>
        <description>The record type for all External Vendors</description>
        <label>External Vendor Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Vendor_Uncategorized_Account__c</fullName>
        <description>Default Account to which External Vendor Contacts will be assigned since we don&apos;t know what account they belong to.</description>
        <label>External Vendor Uncategorized Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_User_Account__c</fullName>
        <description>Name of the Account with which all Contacts created for internal AECOM Users will be associated.</description>
        <label>Internal User Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SS-AP User/Contact Settings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Shared_Services_Is_Executive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the current User a senior executive?  This will affect the prioritization of incoming requests for help.</description>
        <inlineHelpText>Is the current User a senior executive?  This will affect the prioritization of incoming requests for help.</inlineHelpText>
        <label>Shared Services Is Executive</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/sshCaseUserToContactTest.cls
@isTest
private class sshCaseUserToContactTest {

	@isTest static void testUserToContact() {

		Account acct = new Account(Name = 'AECOM Internal Account');
		insert acct;

		Account acct2 = new Account(Name = 'Uncategorized Vendor');
		insert acct2;

		Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];

		User u = new User(Alias = 'tboone', Email = 'sfdctestcase@aecom.com',
		                  EmailEncodingKey = 'UTF-8', FirstName = 'Tony', LastName = 'Boone', LanguageLocaleKey = 'en_US',
		                  LocaleSidKey = 'en_US', ProfileId = p.Id, Department = 'Fake Department',
		                  TimeZoneSidKey = 'America/Los_Angeles', UserName = 'tboone@ssh.com.test', Shared_Services_Is_Executive__c = true);

		insert u;

		ssh_User_Contact_Settings__c custSetting = new ssh_User_Contact_Settings__c();
		custSetting.Name = 'Default';
		custSetting.External_Vendor_Uncategorized_Account__c = 'Uncategorized Vendor';
		custSetting.External_Vendor_Record_Type__c = 'Vendor';
		custSetting.Employee_Record_Type__c = 'AECOM Employee';
		custSetting.Internal_User_Account__c = 'AECOM Internal Account';
		insert custSetting;

		Case c1 = new Case(SuppliedName = 'Tony Boone', SuppliedEmail = 'sfdctestcase@aecom.com');
		insert c1;

		Contact ct = [select Name, Email, AccountId, Shared_Services_Is_Executive__c, User__c from Contact where Email = :c1.SuppliedEmail];

		System.assertEquals(ct.Name, c1.SuppliedName);
		System.assertEquals(ct.Email, c1.SuppliedEmail);
		System.assertEquals(ct.AccountId, acct.Id);
		System.assertEquals(ct.User__c, u.Id);
		System.assertEquals(ct.Shared_Services_Is_Executive__c, u.Shared_Services_Is_Executive__c);
	}

}