src/objects/CostDistLine__c.object
<CustomObject>
    <fields>
        <fullName>GLDate__c</fullName>
        <label>GL Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PADate__c</fullName>
        <label>PA Date</label>
        <type>Date</type>
    </fields>
    <label>Cost Distribution Line</label>
    <nameField>
        <displayFormat>Dist-{0}</displayFormat>
        <label>Cost Distribution Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Distribution Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/pse__Time_Period__c.object
<CustomObject>
    <customHelpPage>pse__TimePeriodHelp</customHelpPage>
    <description>The divisions of time that your services organization is concerned with. Time periods have types such as Month (e.g. November 2014), Quarter (e.g. Q4 2014), Year (e.g. 2014), or Perpetual (‘All Time’). Time periods drive how actuals are categorized, how forecasting is done, how billing events are generated, and most other time-specific functions within FinancialForce PSA. Always create one perpetual time period with an end date well into the future.</description>
    <fields>
        <fullName>TimePeriodCode__c</fullName>
        <description>For months: FY2015-01 for the first fiscal month in fiscal 2015. For quarters: FY2015Q1 for the first quarter in fiscal 2015. For years: FY2015 for fiscal 2015.</description>
        <inlineHelpText>For months: FY2015-01 for the first fiscal month in fiscal 2015. For quarters: FY2015Q1 for the first quarter in fiscal 2015. For years: FY2015 for fiscal 2015.</inlineHelpText>
        <label>Time Period Code</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pse__End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>pse__Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>pse__Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perpetual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SemiMonthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Time Period</label>
    <nameField>
        <label>Time Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_CostDistributionLineTriggersTest.cls
@isTest	
private class ECO_CostDistributionLineTriggersTest {
	
	@testSetup static void setupTestData() {	
		pse__Time_Period__c timePeriod = new pse__Time_Period__c();
		timePeriod.pse__Start_Date__c = Date.Today();
		timePeriod.pse__End_Date__c = Date.Today().addDays(7);
		timePeriod.TimePeriodCode__c = 'FY2015-02';
		timePeriod.pse__Type__c = 'Month';
		insert timePeriod;
		
		
		timePeriod = new pse__Time_Period__c();
		timePeriod.pse__Start_Date__c = Date.Today().AddDays(-8);
		timePeriod.pse__End_Date__c = Date.Today().addDays(-1);
		timePeriod.TimePeriodCode__c = 'FY2015-01';
		timePeriod.pse__Type__c = 'Month';
		insert timePeriod;
	}
	
	
	static testMethod void testcalculateFiscalMonths() {
		
		Test.startTest();
		CostDistLine__c costDistLine = new CostDistLine__c();
		costDistLine.PADate__c = Date.Today();
		costDistLine.GLDate__c = Date.Today();
		insert costDistLine;
		Test.stopTest();
		//[SELECT Id FROM CostDistLine__c LIMIT 1];
		
	}

}