src/objects/CostDistributionLine__c.object
<CustomObject>
    <description>Object used to store cost distribution line items from Oracle</description>
    <fields>
        <fullName>AcctRawCost__c</fullName>
        <label>Acct Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpenditureItemID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expenditure Item</label>
        <referenceTo>ExpenditureItem__c</referenceTo>
        <relationshipName>Cost_Distribution_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpenditureType__c</fullName>
        <formula>ExpenditureItemID__r.ExpenditureType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expenditure Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipName>Cost_Distribution_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TaskNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Task Project must match Cost Distribution Project.</errorMessage>
            <filterItems>
                <field>pse__Project_Task__c.pse__Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.ProjectNumber__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipName>CostDistributionLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>xxCost Distribution Line</label>
    <nameField>
        <label>Cost Distribution Line #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>xxCost Distribution Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ExpenditureItem__c.object
<CustomObject>
    <description>decommission this object.</description>
    <fields>
        <fullName>ExpenditureItemID__c</fullName>
        <externalId>true</externalId>
        <label>Expenditure Item ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpenditureType__c</fullName>
        <label>Expenditure Type</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>xxExpenditure Item</label>
    <nameField>
        <label>Expenditure Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>xxExpenditure Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExpenditureType__c.object
<CustomObject>
    <label>Expenditure Type</label>
    <nameField>
        <label>Expenditure Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenditure Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Revenue__c.object
<CustomObject>
    <description>Object used to track revenue information from Oracle</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Revenue</relationshipLabel>
        <relationshipName>Revenue</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TaskNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task Number</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Revenue</relationshipLabel>
        <relationshipName>Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue</label>
    <nameField>
        <label>Revenue Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_Service_Actuals.cls
public without sharing class ECO_Service_Actuals {
	public class ActualsHolder {
		public ActualsHolder () {
			totalCostLabor = 0;
			totalCostSubs = 0;
			totalCostFees = 0;
			totalCostContingency = 0;
			totalRevenue = 0;
			totalCost = 0;
			taskTotalMap = new Map<Id, Decimal>();
			taskPerTypeTotalMap = new Map<Id, PerTaskActualsHolder>();
		}
		public Decimal totalCost {get;set;}
		public Decimal totalCostLabor {get;set;}
		public Decimal totalCostSubs {get;set;}
		public Decimal totalCostFees {get;set;}
		public Decimal totalCostContingency {get;set;}
		public Decimal totalRevenue {get;set;}
		
		public Map<Id, Decimal> taskTotalMap {get;set;}
		public Map<Id, PerTaskActualsHolder> taskPerTypeTotalMap {get;set;}
	}
	
	public class PerTaskActualsHolder {
		public PerTaskActualsHolder () {
			totalCostLabor = 0;
			totalCostSubs = 0;
			totalCostFees = 0;
			totalCostContingency = 0;
		}
		public Decimal totalCostLabor {get;set;}
		public Decimal totalCostSubs {get;set;}
		public Decimal totalCostFees {get;set;}
		public Decimal totalCostContingency {get;set;}
	}
	
	public static ActualsHolder getActualsForProjectId (Id projectId) {
		ActualsHolder returnHolder = new ActualsHolder();
		
		List<AggregateResult> totalRevenue = [SELECT SUM(Amount__c) totalAmount
											FROM Revenue__c 
											WHERE ProjectNumber__c = :projectId];
											
		returnHolder.totalRevenue = (Decimal)totalRevenue[0].get('totalAmount');
		
		if (returnHolder.totalRevenue == null) {
			returnHolder.totalRevenue = 0;
		}
		
		system.debug('this Project number:  '+projectId);
		
		List<AggregateResult> totalActualCosts = [SELECT ExpenditureItemID__r.ExpenditureType__c 
														, TaskNumber__c
														, SUM(AcctRawCost__c) totalCost
												FROM CostDistributionLine__c
												WHERE ProjectNumber__c = :projectId
													AND (
														ExpenditureItemID__r.ExpenditureType__c LIKE 'LAB%'
														OR ExpenditureItemID__r.ExpenditureType__c LIKE 'FEE%'
														OR ExpenditureItemID__r.ExpenditureType__c LIKE 'SUB%'
														OR ExpenditureItemID__r.ExpenditureType__c LIKE 'CON%'
													)
												GROUP BY ROLLUP (ExpenditureItemID__r.ExpenditureType__c
																, TaskNumber__c)];
		
		for (AggregateResult ar : totalActualCosts) {
			
			system.debug('Summing this AR:  '+ar);
			
			Decimal amount = (Decimal)ar.get('totalCost');
			
			String expenditureType = (String)ar.get('ExpenditureType__c');
			Id projectTaskId = (Id)ar.get('TaskNumber__c');
			
			if (expenditureType == null || projectTaskId == null) {
				system.debug('Breaking out:  '+ar);
				continue;  // This avoids us using the subtotal/total lines
			}
			
			if (!returnHolder.taskTotalMap.keySet().contains(projectTaskId) 
				&& projectTaskId != null) {
					returnHolder.taskTotalMap.put(projectTaskId, 0);
					returnHolder.taskPerTypeTotalMap.put(projectTaskId, new PerTaskActualsHolder());
			}
			
			returnHolder.taskTotalMap.put(projectTaskId, returnHolder.taskTotalMap.get(projectTaskId) + amount);
			
			if (expenditureType.toUpperCase().startsWith('LAB')) {
				returnHolder.totalCostLabor += amount;
				returnHolder.taskPerTypeTotalMap.get(projectTaskId).totalCostLabor += amount;
			} else if (expenditureType.toUpperCase().startsWith('SUB')) {
				returnHolder.totalCostSubs += amount;
				returnHolder.taskPerTypeTotalMap.get(projectTaskId).totalCostSubs += amount;
			} else if (expenditureType.toUpperCase().startsWith('FEE')) {
				returnHolder.totalCostFees += amount;
				returnHolder.taskPerTypeTotalMap.get(projectTaskId).totalCostFees += amount;
			} else { // Contingency
				returnHolder.totalCostContingency += amount;
				returnHolder.taskPerTypeTotalMap.get(projectTaskId).totalCostContingency += amount;
			}
			
			returnHolder.totalCost += amount;
		}
		
		return returnHolder;
	}
}