src/objects/CountryRisk__c.object
<CustomObject>
    <label>Country Risk</label>
    <nameField>
        <label>Country Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Risk</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PortalMessage__c.object
<CustomObject>
    <description>Used by the ECO_Portal pages to display User Alerts, News Feed Items, and News Ticker.</description>
    <label>Portal Message</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Portal Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectCountry_Risk__c.object
<CustomObject>
    <fields>
        <fullName>Change_in_Risk__c</fullName>
        <formula>ABS(Safety_Rating__c -  Last_Country_Risk__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Change in Risk</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CountryRisk__c</fullName>
        <label>Country Risk</label>
        <referenceTo>CountryRisk__c</referenceTo>
        <relationshipLabel>Country Risks</relationshipLabel>
        <relationshipName>CountryRisks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Country_Risk__c</fullName>
        <label>Last Country Risk</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Country Risks</relationshipLabel>
        <relationshipName>ProjectCountryRisks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Safety_Rating__c</fullName>
        <formula>CountryRisk__r.SafetyRating__c</formula>
        <label>Safety Rating</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Project Country Risk</label>
    <nameField>
        <displayFormat>PCR-{00000000}</displayFormat>
        <label>Project Country Risk Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Country Risks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_ProjectCountryAlertBatch.cls
global class ECO_ProjectCountryAlertBatch implements Database.Batchable<sObject> {
	
	String query = 'SELECT ID, Project__r.EcoSystemReferenceNumber__c, Project__r.name, Project__r.ownerid, Last_Country_Risk__c, Safety_Rating__c, CountryRisk__r.name FROM ProjectCountry_Risk__c WHERE Change_in_Risk__c > 0.5';
	
	global ECO_ProjectCountryAlertBatch() {
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		
   		list<PortalMessage__c>  alertsToInsert = new list<PortalMessage__c>();
   		list<ProjectCountry_Risk__c> projectRiskToInsert = new list<ProjectCountry_Risk__c>();
   		ECO_ProjectCountryRiskBatchHelper helper = new ECO_ProjectCountryRiskBatchHelper();

		for(sobject s : scope){
			ProjectCountry_Risk__c item = (ProjectCountry_Risk__c)s;

			alertsToInsert.add(helper.createNewAlert(item.Project__r, date.today(), 'COUNTRY: ' + item.CountryRisk__r.name + ' RISK HAS CHANGED FROM ' + string.valueof(item.Last_Country_Risk__c) + ' to ' + string.valueof(item.Safety_Rating__c))); 

			item.Last_Country_Risk__c = item.Safety_Rating__c;

			projectRiskToInsert.add(item);
		}

		insert alertsToInsert;
		upsert projectRiskToInsert;

	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
}