src/objects/Distribution__c.object
<CustomObject>
    <fields>
        <fullName>ExpenditureDate__c</fullName>
        <label>Expenditure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POLineItem__c</fullName>
        <label>PO Line Item</label>
        <referenceTo>POLineItem__c</referenceTo>
        <relationshipLabel>Distributions</relationshipLabel>
        <relationshipName>DistributionsPOLineItem</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Distribution</label>
    <nameField>
        <displayFormat>DN-{0}</displayFormat>
        <label>Distribution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/POLineItem__c.object
<CustomObject>
    <fields>
        <fullName>IsArchived__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true the record was created from a change request</description>
        <label>Is Archived</label>
        <type>Checkbox</type>
    </fields>
    <label>PO Line Item</label>
    <nameField>
        <displayFormat>POLI-{0000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_POLineItemTriggers.cls
public without sharing class ECO_POLineItemTriggers {


	public void createDistributions(List<POLineItem__c> poLineItems){
		List<Distribution__c> distributions = new List<Distribution__c>();

	
		Date todayDate = Date.today();

		for(POLineItem__c poLineItem : poLineItems){
			if(!poLineItem.isArchived__c){
				Distribution__c distribution = new Distribution__c();
				distribution.POLineItem__c = poLineItem.Id;
				distribution.ExpenditureDate__c = todayDate;			
				distributions.add(distribution);
			}
			
		}

		if(!distributions.isEmpty()){
			insert distributions;
		}
	}
}