src/objects/Distribution__c.object
<CustomObject>
    <fields>
        <fullName>POHeader__c</fullName>
        <formula>POLineItem__r.POHeader__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>POHeader</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POLineItem__c</fullName>
        <label>PO Line Item</label>
        <referenceTo>POLineItem__c</referenceTo>
        <relationshipLabel>Distributions</relationshipLabel>
        <relationshipName>DistributionsPOLineItem</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Distribution</label>
    <nameField>
        <displayFormat>DN-{0}</displayFormat>
        <label>Distribution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/POHeader__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>POHeadersProject</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VendorSite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>VendorSite__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/POLineItem__c.object
<CustomObject>
    <fields>
        <fullName>LineNumber__c</fullName>
        <label>Line Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LineType__c</fullName>
        <label>Line Type</label>
        <picklist>
            <picklistValues>
                <fullName>Unit Rate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Fee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>POHeader__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>POHeader__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>POLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Purchase Order Line Items</relationshipLabel>
        <relationshipName>POLineItemsProjectTask</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitofMeasure__c</fullName>
        <label>Unit of Measure</label>
        <picklist>
            <picklistValues>
                <fullName>Each</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lump Sum</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PO Line Item</label>
    <nameField>
        <displayFormat>POLI-{0000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/POStatus__c.object
<CustomObject>
    <fields>
        <fullName>POHeader__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Purchase Order</label>
        <referenceTo>POHeader__c</referenceTo>
        <relationshipLabel>PO Statuses</relationshipLabel>
        <relationshipName>PO_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO Status</label>
    <nameField>
        <displayFormat>POS-{000000}</displayFormat>
        <label>PO Status Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project that the Task is a part of.</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <description>Represents a customer/vendor site (address/location).</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Represents the account which is bound to the customer/vendor site (address/location).</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Site</label>
    <nameField>
        <displayFormat>Site-{0000000000}</displayFormat>
        <label>Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/VendorSite__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Vendors and Subs</relationshipLabel>
        <relationshipName>VendorSitesProject</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Vendor Sites</relationshipLabel>
        <relationshipName>VendorSitesSite</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Vendor Site</label>
    <nameField>
        <displayFormat>VS-{0}</displayFormat>
        <label>Vendor Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_Service_PurchaseOrdersTest.cls
@isTest
private class ECO_Service_PurchaseOrdersTest{

	private static final Integer numTestProjectTasks = 10;	
	private static final Integer numTeamMembers = 1;

	static testMethod void testCreatePurcaseOrderDTO () {

		//create account and project
		ECO_Utils_Testing.createTestDataForProjectSync(numTestProjectTasks, numTeamMembers);
		pse__Proj__c testProject = [SELECT Id, Name FROM pse__Proj__c LIMIT 1];

		List<pse__Project_Task__c> tasks = [SELECT Id FROM pse__Project_Task__c WHERE pse__Project__c = :testProject.Id];

		Account vendor = new Account();
		vendor.Name = 'test vendor';
		insert vendor;

		Site__c site = new Site__c();
		site.Account__c = vendor.Id;
		insert site;

		VendorSite__c vendorSite = new VendorSite__c();
		vendorSite.Site__c = site.Id;
		vendorSite.Project__c = testProject.Id;

		insert vendorSite;

		test.startTest();

		POHeader__c poHeader = new POHeader__c();
		poHeader.Project__c = testProject.Id;
		poHeader.VendorSite__c = vendorSite.Id;
		insert poHeader;

		POLineItem__c poLineItem = new POLineItem__c();
		poLineItem.ProjectTask__c = tasks.get(0).Id;
		poLineItem.POHeader__c = poHeader.Id;
		poLineItem.LineNumber__c = 1;
		poLineItem.LineType__c = 'Fixed Fee';
		poLineItem.UnitofMeasure__c = 'Lump SUm';

		insert poLineItem;

		List<Distribution__c> distributions = [SELECT Id FROM Distribution__c WHERE POLineItem__c = :poLineItem.Id];
		system.assertEquals(1, distributions.size());



		POStatus__c poStatus = new POStatus__c();
		poStatus.POHeader__c = poHeader.Id;
		insert poStatus;



		

		ECO_Service_PurchaseOrders.OR_PurchaseOrder purchaseOrderDTO = new ECO_Service_PurchaseOrders.OR_PurchaseOrder();
		ECO_Service_PurchaseOrders.OR_PurchaseOrderLineItem poLineItemDTO= new ECO_Service_PurchaseOrders.OR_PurchaseOrderLineItem();
		ECO_Service_PurchaseOrders.OR_Distribution distributionDTO = new ECO_Service_PurchaseOrders.OR_Distribution();
		ECO_Service_PurchaseOrders.OR_PurchaseOrderStatus poStatusDTO = new ECO_Service_PurchaseOrders.OR_PurchaseOrderStatus();
		ECO_Service_PurchaseOrders.OR_PurchaseOrderStatus poStatusDTO2 = new ECO_Service_PurchaseOrders.OR_PurchaseOrderStatus(poStatus);

		ECO_Service_PurchaseOrders.PurchaseOrderMessageWrapper wrapper = ECO_Service_PurchaseOrders.createPurchaseOrderMessageWrapper(poHeader.Id);

		Id msgQueueId = ECO_Service_PurchaseOrders.createMessageQueueForRequest(poHeader.Id, ECO_Service_PurchaseOrders.JOBNAME_PO_SYNC);
		system.assertNotEquals(null, msgQueueId);

		String testResponse = ECO_Service_PurchaseOrders.initiateOracleSyncRequest(poHeader.Id, 'https://test.ca', msgQueueId);

		List<POStatus__c> poStatuses = ECO_Service_PurchaseOrders.GetPurchaseOrderStatuses(poHeader.Id);
		system.assertEquals(1,poStatuses.size());


		Datetime syncDateTime = ECO_Service_PurchaseOrders.getLastSuccessfulSyncDateTime(poHeader.Id, ECO_Service_PurchaseOrders.JOBNAME_PO_SYNC);


		test.stopTest();
		//todo asserts

	}



}