src/objects/DOAApprovalRequest__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <inlineHelpText>This field is manually determined by the ORM rep to indicate the overall status of the approval process.</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>DOA Approval Requests</relationshipLabel>
        <relationshipName>DOAApprovalRequestsProject</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DOA Approval Request</label>
    <nameField>
        <displayFormat>DOA-{0}</displayFormat>
        <label>DOA Request For Approval Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DOA Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DOAConditions__c.object
<CustomObject>
    <fields>
        <fullName>DOAApprovalRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOA Approval Request</label>
        <referenceTo>DOAApprovalRequest__c</referenceTo>
        <relationshipLabel>DOA Conditions (DOA Approval Request)</relationshipLabel>
        <relationshipName>DOAConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOARegister__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOA Register</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DOARegister__c.DOAApprovalRequest__c</field>
                <operation>equals</operation>
                <valueField>$Source.DOAApprovalRequest__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DOARegister__c</referenceTo>
        <relationshipLabel>DOA Conditions</relationshipLabel>
        <relationshipName>DOAConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>DOA Conditions</relationshipLabel>
        <relationshipName>DOAConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DOA Condition</label>
    <nameField>
        <label>Condition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DOA Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DOARegister__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DOAApprovalRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOA Approval Request</label>
        <referenceTo>DOAApprovalRequest__c</referenceTo>
        <relationshipLabel>DOA Register</relationshipLabel>
        <relationshipName>DOA_Register</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>DOA Register</relationshipLabel>
        <relationshipName>DOARegister</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DOA Register</label>
    <nameField>
        <displayFormat>DOA-{0}</displayFormat>
        <label>DOA Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DOA Register</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <formula>TEXT( DOAApprovalRequest__r.ApprovalStatus__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOAApprovalRequest__c</fullName>
        <label>DOA Approval Request</label>
        <referenceTo>DOAApprovalRequest__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Form</label>
    <nameField>
        <displayFormat>Form-{0}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <recordTypes>
        <fullName>RCST</fullName>
        <active>true</active>
        <description>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia volupta</description>
        <label>RCST</label>
    </recordTypes>
    <recordTypes>
        <fullName>RFA</fullName>
        <active>true</active>
        <description>sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum</description>
        <label>RFA</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_DOA_ApprovalRequestController.cls
public with sharing class ECO_DOA_ApprovalRequestController {

	public list<DOA_TriggerWrapper> lstDOATriggers {get; set;}
	public list<DOAApprovalRequest__c> lstDOARequests {get; set;}
	public set<id> setRequestIds {get;set;}
	public list<DOAConditions__c> lstDOAConditions {get; set;}


	public string questionOne {get;set;}
	public string questionTwo {get;set;}
	public string questionThree {get;set;}

	public list<SelectOption> types { get; set; }

	public DOARegister__c newTrigger {get;set;}

	public id projectID {get;set;}
	public pse__Proj__c theProject {get; set;}

	public ECO_DOA_ApprovalRequestController() {
		lstDOATriggers = new list<DOA_TriggerWrapper>();
		lstDOARequests = new list<DOAApprovalRequest__c>();
		lstDOAConditions = new list<DOAConditions__c>();
		setRequestIds = new set<id>();

		String projID = ApexPages.currentPage().getParameters().get('projectID');
        if (projID != null) {
            this.projectID = projID;
            theProject = [select Id, Name from pse__Proj__c where Id = :projID];

            loadTriggers();
            loadApprovalRequest();
            loadConditions();
        }

        types = new List<SelectOption>();
        types.add(new SelectOption('No', 'No'));
        types.add(new SelectOption('Yes', 'Yes'));        

        newTrigger = new DOARegister__c();

	}

	private void loadTriggers(){

        string strSOQL = 'SELECT ';
            
        for (Schema.FieldSetMember fsmField: SObjectType.DOARegister__c.FieldSets.DOA_TriggerView.getFields()) {
            strSOQL += fsmField.getFieldPath() + ', ';
        }
        
        strSOQL += 'ID, DOAApprovalRequest__c FROM DOARegister__c WHERE Project__c = \'' + projectID + '\' order by DOAApprovalRequest__c ASC';

        list<DOARegister__c> lstRiskSearch = (list<DOARegister__c>)Database.query(strSOQL);

        for(DOARegister__c DOAR: lstRiskSearch){
        	lstDOATriggers.add(new DOA_TriggerWrapper(DOAR));
        }
	}

	private void loadApprovalRequest(){

        string strSOQL = 'SELECT ';
            
        for (Schema.FieldSetMember fsmField: SObjectType.DOAApprovalRequest__c.FieldSets.DOA_RequestView.getFields()) {
            strSOQL += fsmField.getFieldPath() + ', ';
        }
        
        strSOQL += 'ID FROM DOAApprovalRequest__c WHERE Project__c = \'' + projectID + '\'';

        lstDOARequests = (list<DOAApprovalRequest__c>)Database.query(strSOQL);

        for(DOAApprovalRequest__c AR: lstDOARequests){
        	setRequestIds.add(AR.id);
        }
        

	}

	private void loadConditions(){

		if(setRequestIds.size() >0){
	        string strSOQL = 'SELECT ';
	            
	        for (Schema.FieldSetMember fsmField: SObjectType.DOAConditions__c.FieldSets.DOA_ApprovalView.getFields()) {
	            strSOQL += fsmField.getFieldPath() + ', ';
	        }
	        
	        strSOQL += 'ID FROM DOAConditions__c WHERE DOAApprovalRequest__c IN: setRequestIds';

	        lstDOAConditions = (list<DOAConditions__c>)Database.query(strSOQL);
    	}
	}

	public pagereference addTrigger(){
		try{
			newTrigger.Project__c = projectID;
			insert newTrigger;

			newTrigger = new DOARegister__c();

			lstDOATriggers = new list<DOA_TriggerWrapper>();
			loadTriggers();

        } catch (Exception e) {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attempting to add a DOA Trigger. Please contact your administrator with the following error: ' + e);
            ApexPages.addMessage(oMsg);
            return null;
        }

        return null;
	}

	public pagereference  questions(){

		boolean found = false;

		for(DOA_TriggerWrapper t: lstDOATriggers ){
			if(t.bChecked){
				found = true;
				break;
			}
		}

		if(found){
			return new pagereference('/apex/ECO_DOA_ApprovalRequestCreation');
		} else {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Cannot make a request without selecting DOA Triggers.');
            ApexPages.addMessage(oMsg);			
			return null;
		}


		
	}

	public pagereference  back(){
		return new pagereference('/apex/ECO_DOA_ApprovalRequest');
	}

	public pagereference createRequest(){
		

		list<recordtype> lstDOART = [select id, name from recordtype where sObjectType='DOAApprovalRequest__c' and name='DOA Create'];

		DOAApprovalRequest__c oNewDOA = new DOAApprovalRequest__c();
		
		oNewDOA.Project__c = projectID;
		oNewDOA.recordtypeid = lstDOART[0].id;
		oNewDOA.ApprovalStatus__c = 'Unapproved';

		Savepoint oSavePoint = Database.setSavepoint();

        
        try {
			insert oNewDOA;
        } catch (Exception e) {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attempting to create a DOA Request. Please contact your administrator with the following error: ' + e);
            ApexPages.addMessage(oMsg);
            Database.rollback(oSavePoint);
            return null;
        }

		list<DOARegister__c> lstTriggersToUpdate = new list<DOARegister__c>();

		for(DOA_TriggerWrapper t: lstDOATriggers ){
			if(t.bChecked){
				t.oTrigger.DOAApprovalRequest__c = oNewDOA.id;
				lstTriggersToUpdate.add(t.oTrigger);
			}
		}

		try {
			update lstTriggersToUpdate;
        } catch (Exception e) {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attempting to Update DOA Triggers. Please contact your administrator with the following error: ' + e);
            ApexPages.addMessage(oMsg);
            Database.rollback(oSavePoint);
            return null;
        }

		list<recordtype> lstRecordTypes = [select id, name from recordtype where sObjectType ='Form__c'];
		map<string, id> mapRecType = new map<string, id>();

		for(recordtype r: lstRecordTypes){
			mapRecType.put(r.name, r.id);
		}

		list<form__c> lstFormsToInsert = new list<form__c>();

		form__c newForm = new form__c();
		form__c newForm2 = new form__c();
		newForm.DOAApprovalRequest__c = oNewDOA.id;
		newForm2.DOAApprovalRequest__c = oNewDOA.id;

		if(questionOne == 'No'){
			newForm.recordtypeid = mapRecType.get('RFA');
			lstFormsToInsert.add(newForm);
		} else if(questionTwo == 'Yes'){
			newForm.recordtypeid = mapRecType.get('ORM Memo');
			lstFormsToInsert.add(newForm);
		} else if (questionThree == 'Yes'){
			newForm.recordtypeid = mapRecType.get('RCST');
			lstFormsToInsert.add(newForm);
			newForm2.recordtypeid = mapRecType.get('ORM Memo');
			lstFormsToInsert.add(newForm2);
		} else if (questionThree == 'No'){
			newForm.recordtypeid = mapRecType.get('RFA');
			lstFormsToInsert.add(newForm);
		}


		try {
			insert lstFormsToInsert;
		} catch (Exception e) {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attempting to create a DOA Form. Please contact your administrator with the following error: ' + e);
            ApexPages.addMessage(oMsg);
            Database.rollback(oSavePoint);
            return null;
        }
		//return new pagereference('/' + oNewDOA.id);
		//return new pagereference('/'+ oNewDOA.id +'/e?retURL=/'+ oNewDOA.id);
		return new pagereference('/'+ lstFormsToInsert[0].id +'/e?retURL=/'+ oNewDOA.id);
	}

	public pagereference stub(){
		return null;
	}

	public pagereference answerone(){
		questionTwo = null;
		questionThree = null;
		return null;
	}

	public pagereference answertwo(){
		questionThree = null;
		return null;
	}

	public pagereference answerthree(){
		return null;
	}	


	public class DOA_TriggerWrapper {

		public boolean bChecked {get;set;}
		public DOARegister__c oTrigger {get;set;}

		public DOA_TriggerWrapper(DOARegister__c oTrigger){
			this.oTrigger = oTrigger;
			bChecked = false;
		}
	}
}