src/objects/DOAApprovalRequest__c.object
<CustomObject>
    <label>DOA Approval Request</label>
    <nameField>
        <displayFormat>DOA-{0}</displayFormat>
        <label>DOA Request For Approval Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DOA Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>DOAApprovalRequest__c</fullName>
        <label>DOA Approval Request</label>
        <referenceTo>DOAApprovalRequest__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Form</label>
    <nameField>
        <displayFormat>Form-{0}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <recordTypes>
        <fullName>RFA</fullName>
        <active>true</active>
        <description>sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum</description>
        <label>RFA</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_DOA_FormRedirectController.cls
public with sharing class ECO_DOA_FormRedirectController {

	public Form__c oForm {get;set;}

	public ECO_DOA_FormRedirectController(ApexPages.StandardController stdController) {
		this.oForm = (Form__c)stdController.getRecord();
		
	}

	public pagereference redirectForm(){

		list<RecordType> lstRT = [select id from recordtype where sObjectType='Form__c' and developername='RFA'];

		if(oForm.recordtypeid == lstRT[0].id){
			return new pagereference('/apex/ECO_RFA?id=' + oForm.id);
		} else {
			return new pagereference('/' + oForm.id + '?nooverride=1');
		}
	}

	public pagereference redirectFormEdit(){

		list<RecordType> lstRT = [select id from recordtype where sObjectType='Form__c' and developername='RFA'];

		if(oForm.recordtypeid == lstRT[0].id){
			return new pagereference('/apex/ECO_RFA?id=' + oForm.id);
		} else {
			return new pagereference('/' + oForm.id + '/e?retURL=/' + oForm.DOAApprovalRequest__c + '&nooverride=1');
		}
	}

}