src/objects/EarnedValueHeader__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Earned Value Report is committed when all the tasks are committed.</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Earned Value Report</label>
    <nameField>
        <displayFormat>EVH-{0000000}</displayFormat>
        <label>Earned Value Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Earned Value Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EarnedValueSnapshot__c.object
<CustomObject>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <label>As Of Date (DEPRECATED)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CompositeKey__c</fullName>
        <description>This should be Project Task Id + Week Number</description>
        <externalId>true</externalId>
        <label>Composite Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Earned Value Snapshots</relationshipLabel>
        <relationshipName>EarnedValueSnapshots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SnapshotKey__c</fullName>
        <externalId>true</externalId>
        <label>Snapshot Key</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ThisWeekAmount__c</fullName>
        <label>This Week Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ThisWeekNumber__c</fullName>
        <label>This Week Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ThisWeekRunningTotalAmount__c</fullName>
        <label>This Week Running Total Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ThisWeekTotalRemaining__c</fullName>
        <label>This Week Total Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WeekStartDate__c</fullName>
        <label>Week Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WeeklyRollupEntry__c</fullName>
        <label>Weekly Rollup Entry</label>
        <referenceTo>WeeklyRollupEntry__c</referenceTo>
        <relationshipLabel>Earned Value Snapshots</relationshipLabel>
        <relationshipName>Earned_Value_Snapshots</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Earned Value Snapshot</label>
    <nameField>
        <displayFormat>EVS-{00000000}</displayFormat>
        <label>Earned Value Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Earned Value Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EarnedValueTask__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Describe why tasks are not progressing as planned or make additional notes for future reference.</inlineHelpText>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CostAccruals__c</fullName>
        <inlineHelpText>Enter here any costs which should be accrued for the purpose of calculating the EV metrics and trend EACs.  This would include the costs of subs work that is counted in the percent complete assessment, but not yet costed to the project actuals.</inlineHelpText>
        <label>Cost Accruals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EarnedValueHeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Earned Value Header</label>
        <referenceTo>EarnedValueHeader__c</referenceTo>
        <relationshipLabel>Earned Value Tasks</relationshipLabel>
        <relationshipName>Earned_Value_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EarnedValueSnapshot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Earned Value Snapshot</label>
        <referenceTo>EarnedValueSnapshot__c</referenceTo>
        <relationshipLabel>Earned Value Tasks</relationshipLabel>
        <relationshipName>EarnedValueTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NotifyTaskOwner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used to fire workflow to notify task owner</description>
        <label>Notify Task Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PercentComplete__c</fullName>
        <inlineHelpText>Review the work that has been completed and discuss with the task/deliverable owner the level of effort required to finalize the task/deliverable.</inlineHelpText>
        <label>Percent Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Earned Value Tasks</relationshipLabel>
        <relationshipName>Earned_Value_Tasks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Earned Value Task</label>
    <nameField>
        <displayFormat>EVT-{0000000}</displayFormat>
        <label>Earned Value Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Earned Value Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>TotalApprovedCost__c</fullName>
        <label>Total Approved Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pse__End_Date__c</fullName>
        <formula>DATEVALUE(pse__End_Date_Time__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project that the Task is a part of.</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Start_Date__c</fullName>
        <formula>DATEVALUE(pse__Start_Date_Time__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WeeklyRollupEntry__c.object
<CustomObject>
    <fields>
        <fullName>CompositeKey__c</fullName>
        <externalId>true</externalId>
        <label>Composite Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Weekly Rollup Entry</label>
    <nameField>
        <displayFormat>WRE-{0000000}</displayFormat>
        <label>Weekly Rollup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weekly Rollup Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_Service_EarnedValue.cls
public without sharing class ECO_Service_EarnedValue {


	public static List<EarnedValueTask__c> getEarnedValueTasksForEarnedValueSnapShot(Id earnedValueSnapShotId){
		
		List<EarnedValueTask__c> results = [SELECT Id,
												PercentComplete__c,
												ProjectTask__c,
												NotifyTaskOwner__c,
												Comments__c,
												Committed__c,
												CostAccruals__c
											FROM EarnedValueTask__c
											WHERE EarnedValueSnapshot__c = :earnedValueSnapShotId];

		return results;

	}

	public static List<EarnedValueTask__c> getEarnedValueTasksForEarnedValueReport(Id earnedValueHeaderId){
		List<EarnedValueTask__c> results = new List<EarnedValueTask__c>();

		Set<Id> snapshotIds = new Set<Id>();
		List<EarnedValueSnapshot__c> snapshots = getEarnedValueSnapShotsForReport(earnedValueHeaderId);
		if(!snapshots.isEmpty()){
			for(EarnedValueSnapshot__c snapshot : snapshots){
				snapshotIds.add(snapshot.Id);
			}
		}
		
		results = [SELECT Id,
						PercentComplete__c,
						ProjectTask__c,
						NotifyTaskOwner__c,
						Comments__c,
						Committed__c,
						CostAccruals__c,
						EarnedValueSnapshot__c 
					FROM EarnedValueTask__c
					WHERE EarnedValueSnapshot__c IN :snapshotIds
					ORDER BY EarnedValueSnapshot__r.AsOfDate__c ASC];

		return results;

	}


	public static List<EarnedValueSnapshot__c> getEarnedValueSnapShotsForReport(Id earnedValueHeaderId){

		List<EarnedValueSnapshot__c> results = [SELECT Id
													, AsOfDate__c
													//, EarnedValueHeader__c
													, Comments__c
												FROM EarnedValueSnapshot__c
												//WHERE EarnedValueHeader__c = :earnedValueHeaderId
												ORDER BY AsOfDate__c DESC];

		return results;

	}

	public static List<EarnedValueSnapshot__c> getEarnedValueSnapShotsForReportAsc(Id earnedValueHeaderId){

		List<EarnedValueSnapshot__c> results = [SELECT Id
													, AsOfDate__c
													//, EarnedValueHeader__c
													, Comments__c
												FROM EarnedValueSnapshot__c
												//WHERE EarnedValueHeader__c = :earnedValueHeaderId
												ORDER BY AsOfDate__c ASC];

		return results;

	}

	public static EarnedValueSnapshot__c getLatestEarnedValueSnapshot(Id earnedValueHeaderId){
		
		EarnedValueSnapshot__c result = null;

		List<EarnedValueSnapshot__c> snapshots = getEarnedValueSnapShotsForReport(earnedValueHeaderId);
		if(!snapshots.isEmpty()){
			result = snapshots.get(0);
		}

		return result;
	}

	public static Map<Id, EarnedValueSnapshot__c> getLatestEarnedValueSnapShotsForReports(Set<Id> earnedValueHeaderIds){
		Map<Id, EarnedValueSnapshot__c> results = new Map<Id, EarnedValueSnapshot__c>();

		List<EarnedValueSnapshot__c> snapshots = [SELECT Id
													, AsOfDate__c
													//, EarnedValueHeader__c
													, Comments__c
												FROM EarnedValueSnapshot__c
												//WHERE EarnedValueHeader__c IN :earnedValueHeaderIds
												ORDER BY AsOfDate__c DESC];

		
		for(EarnedValueSnapshot__c snapshot : snapshots){
			//if(!results.containsKey(snapshot.EarnedValueHeader__c)){
				//results.put(snapshot.EarnedValueHeader__c, snapshot);
			//}
		}	

		return results;

	}
	
	public static List<EVPoint> getAllEVPointsForProject (Id projectId) {
		List<EVPoint> returnList = new List<EVPoint>();
		
		for (AggregateResult ar : [SELECT WeekStartDate__c
										, SUM(ThisWeekAmount__c) totalAmountThisWeek
										, SUM(ThisWeekRunningTotalAmount__c) totalAmountSoFar
									FROM EarnedValueSnapshot__c
									WHERE ProjectTask__r.pse__Project__c = :projectId
									GROUP BY WeekStartDate__c
									ORDER BY WeekStartDate__c]) {
			EVPoint newPoint = new EVPoint();
			newPoint.weekStartDate = (Date)ar.get('WeekStartDate__c');
			newPoint.amountThisWeek = (Decimal)ar.get('totalAmountThisWeek'); 
			newPoint.amountSoFar = (Decimal)ar.get('totalAmountSoFar'); 
			returnList.add(newPoint);
		}
		
		return returnList;
	}
	
	public class EVPoint {
		public Date weekStartDate;
		public Decimal amountThisWeek;
		public Decimal amountSoFar;
	}
	
	public static Map<String, List<EarnedValueSnapshot__c>> calculateFrontLoadedCurveForTask (pse__Project_Task__c projTask, List<EarnedValueSnapshot__c> existingSnaps) {
		if (projTask.pse__Start_Date__c == null) {
			throw new EarnedValueException('Start Date cannot be null for task:  '+projTask.Id);
		}
		if (projTask.pse__End_Date__c == null) {
			throw new EarnedValueException('End Date cannot be null for task:  '+projTask.Id);
		}
		if (projTask.TotalApprovedCost__c == null) {
			return null;
			throw new EarnedValueException('Total Approved Cost cannot be null for task:  '+projTask.Id);
		}
		if (existingSnaps == null) {
			throw new EarnedValueException('Incoming Project Task must include Earned Value Snapshot Subquery for task:  '+projTask.Id);
		}
		
		Map<String, List<EarnedValueSnapshot__c>> returnMap = new Map<String, List<EarnedValueSnapshot__c>>();
		returnMap.put('Upsert', new List<EarnedValueSnapshot__c>());
		returnMap.put('Delete', new List<EarnedValueSnapshot__c>());
		
		Date startDateWeekStartDay = projTask.pse__Start_Date__c.toStartOfWeek();
		Date endDateWeekStartDay = projTask.pse__End_Date__c.toStartOfWeek();
		Integer daysBetween = startDateWeekStartDay.daysBetween(endDateWeekStartDay);
		Integer numOfWeeks = (daysBetween/7)+1;
		
		Decimal averageAmount = projTask.TotalApprovedCost__c / numOfWeeks;
		Decimal runningTotal = 0;
		Integer weekNum = 1;
		Date weekStartDateRunning = startDateWeekStartDay;
		
		List<EarnedValueSnapshot__c> evsToUpsert = new List<EarnedValueSnapshot__c>();
		List<EarnedValueSnapshot__c> evsToDelete = new List<EarnedValueSnapshot__c>();
		
		for (Decimal i = 0; i < numOfWeeks; i++) {
			
			system.debug('averageAmount:  '+averageAmount);
			
			Decimal taskAmount = Math.log(Math.pow((Double)averageAmount, (Double)i+1));
			
			taskAmount = taskAmount.setScale(2, System.RoundingMode.HALF_UP);
			
			system.debug('taskAmount:  '+taskAmount);
			
			runningTotal += taskAmount;
			
			EarnedValueSnapshot__c newEVSnap = new EarnedValueSnapshot__c();
			newEVSnap.ProjectTask__c = projTask.Id;
			newEVSnap.CompositeKey__c = projTask.Id+'_'+weekNum;
			newEVSnap.SnapshotKey__c = ECO_Service_Snapshots.DateToSnapshotKey(weekStartDateRunning, projTask.pse__Project__c, projTask.Id);
			newEVSnap.WeeklyRollupEntry__r = new WeeklyRollupEntry__c(CompositeKey__c = ECO_Service_Snapshots.DateToSnapshotKey(weekStartDateRunning, projTask.pse__Project__c));
			newEVSnap.WeekStartDate__c = weekStartDateRunning;
			newEVSnap.ThisWeekNumber__c = weekNum;
			newEVSnap.ThisWeekAmount__c = taskAmount;
			
			evsToUpsert.add(newEVSnap);
			
			weekNum++;
			weekStartDateRunning = weekStartDateRunning.addDays(7);
		}
		
		system.debug('projTask.TotalApprovedCost__c:  '+projTask.TotalApprovedCost__c);
		system.debug('runningTotal:  '+runningTotal);
		
		// now we have task amounts that are way too huge to be the final amount, but we have good ratios between them, step it down
		Decimal fixerRatio = projTask.TotalApprovedCost__c / runningTotal;
		
		system.debug('fixerRatio:  '+fixerRatio);
		
		// reset the running total
		runningTotal = 0;
		
		// with the ratio we can fix the amounts
		for (EarnedValueSnapshot__c evs : evsToUpsert) {
			evs.ThisWeekAmount__c = (evs.ThisWeekAmount__c * fixerRatio).setScale(2, System.RoundingMode.HALF_UP);
			
			//system.debug('fixed evs.ThisWeekAmount__c:  '+evs.ThisWeekAmount__c);
			
			runningTotal += evs.ThisWeekAmount__c;
			
			evs.ThisWeekRunningTotalAmount__c = runningTotal;
			evs.ThisWeekTotalRemaining__c = projTask.TotalApprovedCost__c - runningTotal;
		}
		
		// reset the running total
		runningTotal = 0;
		
		List<Decimal> valuesList = new List<Decimal>(); // We'll use this to hold values in the order we want them
		
		// Now we have the curve, let's reverse it for front loaded.
		for (Integer i = evsToUpsert.size()-1 ; i >= 0 ; i--) {
			
			valuesList.add(evsToUpsert[i].ThisWeekAmount__c);
			
			system.debug('reverse order:  '+evsToUpsert[i].ThisWeekAmount__c);
		}
		
		// Finally, let's loop once more in the proper order to replace all the values
		Integer listPos = 0;
		for (EarnedValueSnapshot__c evs : evsToUpsert) {
			evs.ThisWeekAmount__c = valuesList[listPos];
			
			runningTotal += evs.ThisWeekAmount__c;
			
			evs.ThisWeekRunningTotalAmount__c = runningTotal;
			evs.ThisWeekTotalRemaining__c = projTask.TotalApprovedCost__c - runningTotal;
			
			listPos++;
		}
		
		for (EarnedValueSnapshot__c ev : existingSnaps) {
			if (ev.ThisWeekNumber__c > numOfWeeks) {
				evsToDelete.add(ev);
			}
		}
		
		returnMap.get('Upsert').addAll(evsToUpsert);
		returnMap.get('Delete').addAll(evsToDelete);
		
		return returnMap;
	}
	
	public static Map<String, List<EarnedValueSnapshot__c>> calculateBackLoadedCurveForTask (pse__Project_Task__c projTask, List<EarnedValueSnapshot__c> existingSnaps) {
		if (projTask.pse__Start_Date__c == null) {
			throw new EarnedValueException('Start Date cannot be null for task:  '+projTask.Id);
		}
		if (projTask.pse__End_Date__c == null) {
			throw new EarnedValueException('End Date cannot be null for task:  '+projTask.Id);
		}
		if (projTask.TotalApprovedCost__c == null) {
			throw new EarnedValueException('Total Approved Cost cannot be null for task:  '+projTask.Id);
		}
		if (existingSnaps == null) {
			throw new EarnedValueException('Incoming Project Task must include Earned Value Snapshot Subquery for task:  '+projTask.Id);
		}
		
		Map<String, List<EarnedValueSnapshot__c>> returnMap = new Map<String, List<EarnedValueSnapshot__c>>();
		returnMap.put('Upsert', new List<EarnedValueSnapshot__c>());
		returnMap.put('Delete', new List<EarnedValueSnapshot__c>());
		
		Date startDateWeekStartDay = projTask.pse__Start_Date__c.toStartOfWeek();
		Date endDateWeekStartDay = projTask.pse__End_Date__c.toStartOfWeek();
		Integer daysBetween = startDateWeekStartDay.daysBetween(endDateWeekStartDay);
		Integer numOfWeeks = (daysBetween/7)+1;
		
		Decimal averageAmount = projTask.TotalApprovedCost__c / numOfWeeks;
		Decimal runningTotal = 0;
		Integer weekNum = 1;
		Date weekStartDateRunning = startDateWeekStartDay;
		
		List<EarnedValueSnapshot__c> evsToUpsert = new List<EarnedValueSnapshot__c>();
		List<EarnedValueSnapshot__c> evsToDelete = new List<EarnedValueSnapshot__c>();
		
		for (Decimal i = 0; i < numOfWeeks; i++) {
			
			system.debug('averageAmount:  '+averageAmount);
			
			Decimal taskAmount = Math.log(Math.pow((Double)averageAmount, (Double)i+1));
			
			taskAmount = taskAmount.setScale(2, System.RoundingMode.HALF_UP);
			
			system.debug('taskAmount:  '+taskAmount);
			
			runningTotal += taskAmount;
			
			EarnedValueSnapshot__c newEVSnap = new EarnedValueSnapshot__c();
			newEVSnap.ProjectTask__c = projTask.Id;
			newEVSnap.CompositeKey__c = projTask.Id+'_'+weekNum;
			newEVSnap.SnapshotKey__c = ECO_Service_Snapshots.DateToSnapshotKey(weekStartDateRunning, projTask.pse__Project__c, projTask.Id);
			newEVSnap.WeeklyRollupEntry__r = new WeeklyRollupEntry__c(CompositeKey__c = ECO_Service_Snapshots.DateToSnapshotKey(weekStartDateRunning, projTask.pse__Project__c));
			newEVSnap.WeekStartDate__c = weekStartDateRunning;
			newEVSnap.ThisWeekNumber__c = weekNum;
			newEVSnap.ThisWeekAmount__c = taskAmount;
			
			evsToUpsert.add(newEVSnap);
			
			weekNum++;
			weekStartDateRunning = weekStartDateRunning.addDays(7);
		}
		
		system.debug('projTask.TotalApprovedCost__c:  '+projTask.TotalApprovedCost__c);
		system.debug('runningTotal:  '+runningTotal);
		
		// now we have task amounts that are way too huge to be the final amount, but we have good ratios between them, step it down
		Decimal fixerRatio = projTask.TotalApprovedCost__c / runningTotal;
		
		system.debug('fixerRatio:  '+fixerRatio);
		
		// reset the running total
		runningTotal = 0;
		
		// with the ratio we can fix the amounts
		for (EarnedValueSnapshot__c evs : evsToUpsert) {
			evs.ThisWeekAmount__c = (evs.ThisWeekAmount__c * fixerRatio).setScale(2, System.RoundingMode.HALF_UP);
			
			system.debug('fixed evs.ThisWeekAmount__c:  '+evs.ThisWeekAmount__c);
			
			runningTotal += evs.ThisWeekAmount__c;
			
			evs.ThisWeekRunningTotalAmount__c = runningTotal;
			evs.ThisWeekTotalRemaining__c = projTask.TotalApprovedCost__c - runningTotal;
		}
		
		for (EarnedValueSnapshot__c ev : existingSnaps) {
			if (ev.ThisWeekNumber__c > numOfWeeks) {
				evsToDelete.add(ev);
			}
		}
		
		returnMap.get('Upsert').addAll(evsToUpsert);
		returnMap.get('Delete').addAll(evsToDelete);
		
		return returnMap;
	}
	
	public static Map<String, List<EarnedValueSnapshot__c>> calculateEvenCurveForTask (pse__Project_Task__c projTask, List<EarnedValueSnapshot__c> existingSnaps) {
		if (projTask.pse__Start_Date__c == null) {
			throw new EarnedValueException('Start Date cannot be null for task:  '+projTask.Id);
		}
		if (projTask.pse__End_Date__c == null) {
			throw new EarnedValueException('End Date cannot be null for task:  '+projTask.Id);
		}
		if (projTask.TotalApprovedCost__c == null) {
			return null;
			throw new EarnedValueException('Total Approved Cost cannot be null for task:  '+projTask.Id);
		}
		if (existingSnaps == null) {
			throw new EarnedValueException('Incoming Project Task must include Earned Value Snapshot Subquery for task:  '+projTask.Id);
		}
		
		Map<String, List<EarnedValueSnapshot__c>> returnMap = new Map<String, List<EarnedValueSnapshot__c>>();
		returnMap.put('Upsert', new List<EarnedValueSnapshot__c>());
		returnMap.put('Delete', new List<EarnedValueSnapshot__c>());
		
		Date startDateWeekStartDay = projTask.pse__Start_Date__c.toStartOfWeek();
		Date endDateWeekStartDay = projTask.pse__End_Date__c.toStartOfWeek();
		Integer daysBetween = startDateWeekStartDay.daysBetween(endDateWeekStartDay);
		Integer numOfWeeks = (daysBetween/7)+1;
		
		Decimal averageAmount = projTask.TotalApprovedCost__c / numOfWeeks;
		Decimal runningTotal = 0;
		Integer weekNum = 1;
		Date weekStartDateRunning = startDateWeekStartDay;
		
		List<EarnedValueSnapshot__c> evsToUpsert = new List<EarnedValueSnapshot__c>();
		List<EarnedValueSnapshot__c> evsToDelete = new List<EarnedValueSnapshot__c>();
		
		for (Decimal i = 0; i < numOfWeeks; i++) {
			
			Decimal taskAmount = averageAmount;
			
			taskAmount = taskAmount.setScale(2, System.RoundingMode.HALF_UP);
			
			runningTotal += taskAmount;
			
			EarnedValueSnapshot__c newEVSnap = new EarnedValueSnapshot__c();
			newEVSnap.ProjectTask__c = projTask.Id;
			newEVSnap.CompositeKey__c = projTask.Id+'_'+weekNum;
			newEVSnap.SnapshotKey__c = ECO_Service_Snapshots.DateToSnapshotKey(weekStartDateRunning, projTask.pse__Project__c, projTask.Id);
			newEVSnap.WeeklyRollupEntry__r = new WeeklyRollupEntry__c(CompositeKey__c = ECO_Service_Snapshots.DateToSnapshotKey(weekStartDateRunning, projTask.pse__Project__c));
			newEVSnap.WeekStartDate__c = weekStartDateRunning;
			newEVSnap.ThisWeekNumber__c = weekNum;
			newEVSnap.ThisWeekAmount__c = taskAmount;
			newEVSnap.ThisWeekRunningTotalAmount__c = runningTotal;
			newEVSnap.ThisWeekTotalRemaining__c = projTask.TotalApprovedCost__c - runningTotal;
			
			evsToUpsert.add(newEVSnap);
			
			weekNum++;
			weekStartDateRunning = weekStartDateRunning.addDays(7);
		}
		
		for (EarnedValueSnapshot__c ev : existingSnaps) {
			if (ev.ThisWeekNumber__c > numOfWeeks) {
				evsToDelete.add(ev);
			}
		}
		
		returnMap.get('Upsert').addAll(evsToUpsert);
		returnMap.get('Delete').addAll(evsToDelete);
		
		return returnMap;
	}

	public static Map<String, List<EarnedValueSnapshot__c>> calculateSCurveForTask (pse__Project_Task__c projTask, List<EarnedValueSnapshot__c> existingSnaps) {
		if (projTask.pse__Start_Date__c == null) {
			throw new EarnedValueException('Start Date cannot be null for task:  '+projTask.Id);
		}
		if (projTask.pse__End_Date__c == null) {
			throw new EarnedValueException('End Date cannot be null for task:  '+projTask.Id);
		}
		if (projTask.TotalApprovedCost__c == null) {
			return null;
			throw new EarnedValueException('Total Approved Cost cannot be null for task:  '+projTask.Id);
		}
		if (existingSnaps == null) {
			throw new EarnedValueException('Incoming Project Task must include Earned Value Snapshot Subquery for task:  '+projTask.Id);
		}
		
		Map<String, List<EarnedValueSnapshot__c>> returnMap = new Map<String, List<EarnedValueSnapshot__c>>();
		returnMap.put('Upsert', new List<EarnedValueSnapshot__c>());
		returnMap.put('Delete', new List<EarnedValueSnapshot__c>());
		
		Date startDateWeekStartDay = projTask.pse__Start_Date__c.toStartOfWeek();
		Date endDateWeekStartDay = projTask.pse__End_Date__c.toStartOfWeek();
		Integer daysBetween = startDateWeekStartDay.daysBetween(endDateWeekStartDay);
		Integer numOfWeeks = (daysBetween/7)+1;
		
		Decimal runningTotal = 0;
		Decimal totalAmount = projTask.TotalApprovedCost__c;
		Decimal numWeeksTotal = numOfWeeks;
		Decimal halfWeeks = numWeeksTotal/2;
		Decimal negWeekStart = halfWeeks*-1;
		
		List<EarnedValueSnapshot__c> evsToUpsert = new List<EarnedValueSnapshot__c>();
		List<EarnedValueSnapshot__c> evsToDelete = new List<EarnedValueSnapshot__c>();
		
		Date weekStartDateRunning = startDateWeekStartDay;
		
		Integer weekNum = 1;
		
		//system.debug('negWeekStart:  '+negWeekStart);
		//system.debug('halfWeeks:  '+halfWeeks);
		
		for (Decimal i = negWeekStart; i < halfWeeks; i++) {
		
			Decimal rawSigmoid = ECO_Utils_Math.sigmoid(i);
			system.debug('i number:  '+i);
			//system.debug('rawSigmoid:  '+rawSigmoid);
			Decimal taskAmount = ((rawSigmoid*totalAmount));
			
			taskAmount = taskAmount.setScale(2, System.RoundingMode.HALF_UP);
			
			runningTotal += taskAmount;
			
			system.debug('Task Amount:  '+taskAmount+', total:  '+runningTotal);
			//system.debug('Week Number:  '+weekNum);
			
			EarnedValueSnapshot__c newEVSnap = new EarnedValueSnapshot__c();
			newEVSnap.ProjectTask__c = projTask.Id;
			newEVSnap.CompositeKey__c = projTask.Id+'_'+weekNum;
			newEVSnap.SnapshotKey__c = ECO_Service_Snapshots.DateToSnapshotKey(weekStartDateRunning, projTask.pse__Project__c, projTask.Id);
			newEVSnap.WeeklyRollupEntry__r = new WeeklyRollupEntry__c(CompositeKey__c = ECO_Service_Snapshots.DateToSnapshotKey(weekStartDateRunning, projTask.pse__Project__c));
			newEVSnap.WeekStartDate__c = weekStartDateRunning;
			newEVSnap.ThisWeekNumber__c = weekNum;
			newEVSnap.ThisWeekAmount__c = taskAmount;
			
			evsToUpsert.add(newEVSnap);
			
			weekNum++;
			weekStartDateRunning = weekStartDateRunning.addDays(7);
		}
		
		// now we have task amounts that are way too huge to be the final amount, but we have good ratios between them, step it down
		Decimal fixerRatio = totalAmount / runningTotal;
		
		// reset the running total
		runningTotal = 0;
		
		// with the ratio we can fix the amounts
		for (EarnedValueSnapshot__c evs : evsToUpsert) {
			evs.ThisWeekAmount__c = (evs.ThisWeekAmount__c * fixerRatio).setScale(2, System.RoundingMode.HALF_UP);
			
			runningTotal += evs.ThisWeekAmount__c;
			
			evs.ThisWeekRunningTotalAmount__c = runningTotal;
			evs.ThisWeekTotalRemaining__c = totalAmount - runningTotal;
		}
		
		for (EarnedValueSnapshot__c ev : existingSnaps) {
			if (ev.ThisWeekNumber__c > numWeeksTotal) {
				evsToDelete.add(ev);
			}
		}
		
		system.debug('Total At End:  '+runningTotal);
		system.debug('totalAmount:  '+totalAmount);
		
		
		returnMap.get('Upsert').addAll(evsToUpsert);
		returnMap.get('Delete').addAll(evsToDelete);
		
		return returnMap;
	}
	
	public static Map<String, List<EarnedValueSnapshot__c>> calculateBellCurveForTask (pse__Project_Task__c projTask, List<EarnedValueSnapshot__c> existingSnaps) {
		if (projTask.pse__Start_Date__c == null) {
			throw new EarnedValueException('Start Date cannot be null for task:  '+projTask.Id);
		}
		if (projTask.pse__End_Date__c == null) {
			throw new EarnedValueException('End Date cannot be null for task:  '+projTask.Id);
		}
		if (projTask.TotalApprovedCost__c == null) {
			return null;
			throw new EarnedValueException('Total Approved Cost cannot be null for task:  '+projTask.Id);
		}
		if (existingSnaps == null) {
			throw new EarnedValueException('Incoming Project Task must include Earned Value Snapshot Subquery for task:  '+projTask.Id);
		}
		
		Map<String, List<EarnedValueSnapshot__c>> returnMap = new Map<String, List<EarnedValueSnapshot__c>>();
		returnMap.put('Upsert', new List<EarnedValueSnapshot__c>());
		returnMap.put('Delete', new List<EarnedValueSnapshot__c>());
		
		Date startDateWeekStartDay = projTask.pse__Start_Date__c.toStartOfWeek();
		Date endDateWeekStartDay = projTask.pse__End_Date__c.toStartOfWeek();
		Integer daysBetween = startDateWeekStartDay.daysBetween(endDateWeekStartDay);
		Integer numOfWeeks = (daysBetween/7)+1;
		
		Decimal runningTotal = 0;
		Decimal totalAmount = projTask.TotalApprovedCost__c;
		Decimal numWeeksTotal = numOfWeeks;
		Decimal meanWeeks = (numWeeksTotal+1)/2;
		
		List<EarnedValueSnapshot__c> evsToUpsert = new List<EarnedValueSnapshot__c>();
		List<EarnedValueSnapshot__c> evsToDelete = new List<EarnedValueSnapshot__c>();
		
		Date weekStartDateRunning = startDateWeekStartDay;
		
		Integer weekNum = 1;
		
		
		Decimal meanValue = totalAmount / numWeeksTotal;
		
		for (Decimal i = 0; i < numWeeksTotal; i++) {

			Decimal taskAmount = totalAmount - ((Math.abs(((i+1) - meanWeeks))) * meanValue);
			
			taskAmount = taskAmount.setScale(2, System.RoundingMode.HALF_UP);
			
			//system.debug('Calced Sigma:  '+(totalAmount - (Math.abs(((i+1) - meanWeeks))) * meanValue));
			//system.debug('Calced Sigma:  '+((Math.abs(((i+1) - meanWeeks))) * meanValue));
			
			runningTotal += taskAmount;
			
			system.debug('Task Amount:  '+taskAmount+', total:  '+runningTotal);
			//system.debug('Week Number:  '+weekNum);
			
			EarnedValueSnapshot__c newEVSnap = new EarnedValueSnapshot__c();
			newEVSnap.ProjectTask__c = projTask.Id;
			newEVSnap.CompositeKey__c = projTask.Id+'_'+weekNum;
			newEVSnap.SnapshotKey__c = ECO_Service_Snapshots.DateToSnapshotKey(weekStartDateRunning, projTask.pse__Project__c, projTask.Id);
			newEVSnap.WeeklyRollupEntry__r = new WeeklyRollupEntry__c(CompositeKey__c = ECO_Service_Snapshots.DateToSnapshotKey(weekStartDateRunning, projTask.pse__Project__c));
			newEVSnap.WeekStartDate__c = weekStartDateRunning;
			newEVSnap.ThisWeekNumber__c = weekNum;
			newEVSnap.ThisWeekAmount__c = taskAmount;
			
			evsToUpsert.add(newEVSnap);
			
			weekNum++;
			weekStartDateRunning = weekStartDateRunning.addDays(7);
		}
		
		// now we have task amounts that are way too huge to be the final amount, but we have good ratios between them, step it down
		
		Decimal fixerRatio = (runningTotal != 0) ? totalAmount / runningTotal : 0;
		
		// reset the running total
		runningTotal = 0;
		
		// with the ratio we can fix the amounts
		for (EarnedValueSnapshot__c evs : evsToUpsert) {
			evs.ThisWeekAmount__c = (evs.ThisWeekAmount__c * fixerRatio).setScale(2, System.RoundingMode.HALF_UP);
			
			system.debug('fixed evs.ThisWeekAmount__c :  '+evs.ThisWeekAmount__c );
			
			runningTotal += evs.ThisWeekAmount__c;
			
			evs.ThisWeekRunningTotalAmount__c = runningTotal;
			evs.ThisWeekTotalRemaining__c = totalAmount - runningTotal;
		}
		
		for (EarnedValueSnapshot__c ev : existingSnaps) {
			if (ev.ThisWeekNumber__c > numWeeksTotal) {
				evsToDelete.add(ev);
			}
		}
		
		system.debug('Total At End:  '+runningTotal);
		system.debug('totalAmount:  '+totalAmount);
		
		
		returnMap.get('Upsert').addAll(evsToUpsert);
		returnMap.get('Delete').addAll(evsToDelete);
		
		return returnMap;
	}

	private class EarnedValueException extends Exception {}

}