src/objects/EarnedValueHeader__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipName>EarnedValueReport</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SnapshotDate__c</fullName>
        <label>Snapshot Date</label>
        <type>Date</type>
    </fields>
    <label>Earned Value Report</label>
    <nameField>
        <displayFormat>EVH-{0000000}</displayFormat>
        <label>Earned Value Header Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Earned Value Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EarnedValueTask__c.object
<CustomObject>
    <fields>
        <fullName>EarnedValueHeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Earned Value Header</label>
        <referenceTo>EarnedValueHeader__c</referenceTo>
        <relationshipLabel>Earned Value Tasks</relationshipLabel>
        <relationshipName>Earned_Value_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EarnedValue__c</fullName>
        <formula>if (and(not(isblank(TaskTotalApprovedCostSnapshot__c)),PercentComplete__c&gt;0),
   TaskTotalApprovedCostSnapshot__c * (PercentComplete__c / 100),
   0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Earned Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SnapshotDate__c</fullName>
        <label>Snapshot Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TrendEAC1__c</fullName>
        <formula>IF(PercentComplete__c = 0, 0, ProjectTask__r.TotalProjectFunctionalBurdenedCost__c / PercentComplete__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is a predicted Forecast/EAC Cost calculated using the current Earned Value, presuming the current productivity rate continues through to completion.  Calculated as &quot;Total Cost / Percent Complete&quot;</inlineHelpText>
        <label>Trend EAC 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TrendEAC2__c</fullName>
        <formula>(ProjectTask__r.TotalProjectFunctionalBurdenedCost__c + ProjectTask__r.TotalApprovedCost__c)  * (1 - PercentComplete__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is a predicted Forecast/EAC Cost calculated using the current Earned Value, presuming the rest of the project proceeds as originally planned through to completion.   Calculated as &quot;Total Cost + Budget Cost x (1- Percent Complete)&quot;.</inlineHelpText>
        <label>Trend EAC 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Earned Value Task</label>
    <nameField>
        <displayFormat>EVT-{0000000}</displayFormat>
        <label>Earned Value Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Earned Value Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Revenue__c.object
<CustomObject>
    <description>Object used to track revenue information from Oracle</description>
    <label>Revenue</label>
    <nameField>
        <label>Revenue Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WeeklyRollupEntry__c.object
<CustomObject>
    <fields>
        <fullName>AcctBurdenedCost__c</fullName>
        <label>Acct Burdened Cost</label>
        <summarizedField>EarnedValueSnapshot__c.AcctBurdenedCost__c</summarizedField>
        <summaryForeignKey>EarnedValueSnapshot__c.WeeklyRollupEntry__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AcctRawCost__c</fullName>
        <label>Acct Raw Cost</label>
        <summarizedField>EarnedValueSnapshot__c.AcctRawCost__c</summarizedField>
        <summaryForeignKey>EarnedValueSnapshot__c.WeeklyRollupEntry__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AppliedAcctBurdenedCost__c</fullName>
        <formula>BLANKVALUE(OverrideAcctBurdenedCost__c, AcctBurdenedCost__c)</formula>
        <label>Applied Acct Burdened Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AppliedAcctRawCost__c</fullName>
        <formula>BLANKVALUE(OverrideAcctRawCost__c, AcctRawCost__c)</formula>
        <label>Applied Acct Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AppliedApprovedCost__c</fullName>
        <formula>BLANKVALUE( OverrideApprovedCost__c ,  ApprovedCost__c )</formula>
        <label>Applied Approved Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AppliedRevenue__c</fullName>
        <formula>BLANKVALUE(OverrideRevenue__c, Revenue__c)</formula>
        <label>Applied Cash In</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ApprovedCost__c</fullName>
        <label>Approved Cost</label>
        <summarizedField>EarnedValueSnapshot__c.ThisWeekAmount__c</summarizedField>
        <summaryForeignKey>EarnedValueSnapshot__c.WeeklyRollupEntry__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CPI__c</fullName>
        <formula>IF( AppliedAcctBurdenedCost__c != 0, EarnedValue__c / AppliedAcctBurdenedCost__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CPI</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompositeKey__c</fullName>
        <externalId>true</externalId>
        <label>Composite Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EarnedValue__c</fullName>
        <label>Earned Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideAcctBurdenedCost__c</fullName>
        <label>Override Acct Burdened Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideAcctRawCost__c</fullName>
        <label>Override Acct Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideApprovedCost__c</fullName>
        <label>Override Approved Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideRevenue__c</fullName>
        <label>Override Cash In</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PeriodStartDate__c</fullName>
        <label>Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectFunctionalBurdenedCost__c</fullName>
        <label>Project Functional Burdened Cost</label>
        <summarizedField>EarnedValueSnapshot__c.ProjectFunctionalBurdenedCost__c</summarizedField>
        <summaryForeignKey>EarnedValueSnapshot__c.WeeklyRollupEntry__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Weekly Rollup Entries</relationshipLabel>
        <relationshipName>Weekly_Rollup_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Cash In</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SPI__c</fullName>
        <formula>IF(AppliedApprovedCost__c != 0, EarnedValue__c / AppliedApprovedCost__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SPI</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Weekly Rollup Entry</label>
    <nameField>
        <displayFormat>WRE-{0000000}</displayFormat>
        <label>Weekly Rollup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weekly Rollup Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_CashFlowFlyoutController2.cls
public with sharing class ECO_CashFlowFlyoutController2 {
	public list<WeeklyRollupEntry__c> lWeeklyRollupEntries {get; set;}

	public String chartData {get; set;}

    public String chartJSON {get; set;}
    public String cpiAndSpiJSON {get; set;}

	public Decimal plannedCostTotal {get; set;}
	public Decimal cashInTotal {get; set;}

	public id sProjectId {
		get;

		set {
			sProjectId = value;

			reload(false);
		}
	}

	public void reload(Boolean force) {
		if ((lWeeklyRollupEntries == null) || force) {
			lWeeklyRollupEntries = new list<WeeklyRollupEntry__c>([
				SELECT Id
					 , Revenue__c
					 , AcctBurdenedCost__c
					 , AcctRawCost__c
					 , ApprovedCost__c
					 , PeriodStartDate__c
					 , OverrideRevenue__c
					 , OverrideAcctBurdenedCost__c
					 , OverrideAcctRawCost__c
					 , OverrideApprovedCost__c
					 , AppliedRevenue__c
					 , AppliedAcctBurdenedCost__c
					 , AppliedAcctRawCost__c
					 , AppliedApprovedCost__c
				FROM WeeklyRollupEntry__c
				WHERE
					Project__c = :sProjectId
				ORDER BY
					CompositeKey__c ASC]);
		}

		Decimal amountSoFar = 0;

		plannedCostTotal = 0.00;
		cashInTotal = 0.00;

		chartData = '[';
		
		chartData += '["Week", "Net Cash Position (In Period)", "Cash Flow (Cumulative)"],';
		
		for (WeeklyRollupEntry__c entry : lWeeklyRollupEntries) {
			Decimal approvedCost = (entry.AppliedApprovedCost__c != null) ? entry.AppliedApprovedCost__c : 0;
			Decimal revenue = (entry.AppliedRevenue__c != null) ? entry.AppliedRevenue__c : 0;

			Decimal netCashPosition = - approvedCost + revenue;
			amountSoFar += netCashPosition;

			plannedCostTotal += (entry.ApprovedCost__c != null) ? entry.ApprovedCost__c : 0;
			cashInTotal += (entry.Revenue__c != null) ? entry.Revenue__c : 0;

			chartData += '["' + entry.PeriodStartDate__c.format() + '", ' + netCashPosition + ', ' + amountSoFar + '],';
		}
		
		chartData = chartData.subString(0, chartData.length() - 1);
		
		chartData += ']';

		chartJSON = createEarnedValueGoogleChartJSON();
		cpiAndSpiJSON = createCpiAndSpiGoogleChartJSON();
	}

    private String createEarnedValueGoogleChartJSON(){	
    	list<WeeklyRollupEntry__c> lWeeklyRollupEntries = new list<WeeklyRollupEntry__c>([SELECT id
    																						   , PeriodStartDate__c
    																						   , AppliedApprovedCost__c
    																						   , ProjectFunctionalBurdenedCost__c
    																						   , EarnedValue__c
    																					 FROM WeeklyRollupEntry__c 
    																					 WHERE Project__c = :sProjectId]);

    	List<EarnedValueHeader__c> listOfEVRs = [SELECT Id 
												 	  , SnapshotDate__c
													  , (SELECT id
													  	      , TrendEAC1__c
													          , TrendEAC2__c
													     FROM Earned_Value_Tasks__r
													    )
												 FROM EarnedValueHeader__c
												 WHERE Project__c = :sProjectId
												 AND SnapshotDate__c != null
												 ORDER BY SnapshotDate__c DESC];
    	Decimal dTrendEAC1 = 0;
    	Decimal dTrendEAC2 = 0;

    	if (!listOfEVRs.isEmpty()) {
    		EarnedValueHeader__c existingReport = listOfEVRs.get(0);

    		for(EarnedValueTask__c oEarnedValueTask : existingReport.Earned_Value_Tasks__r){
    			dTrendEAC1 += ECO_Utils_String.NullCheck(oEarnedValueTask.TrendEAC1__c);
    			dTrendEAC2 += ECO_Utils_String.NullCheck(oEarnedValueTask.TrendEAC2__c);
    		}
    	}

    	String sTrendEAC1 = String.valueOf(dTrendEAC1);
    	String sTrendEAC2 = String.valueOf(dTrendEAC2);

    	list<list<String>> lResults = new list<list<String>>();

    	for(WeeklyRollupEntry__c oWeeklyRollupEntry : lWeeklyRollupEntries){
    		list<String> lResultLine = new list<String>();

    		lResultLine.add(String.valueOf(oWeeklyRollupEntry.PeriodStartDate__c));
    		lResultLine.add(String.valueOf(ECO_Utils_String.NullCheck(oWeeklyRollupEntry.AppliedApprovedCost__c)));
    		lResultLine.add(String.valueOf(ECO_Utils_String.NullCheck(oWeeklyRollupEntry.ProjectFunctionalBurdenedCost__c)));
    		lResultLine.add(String.valueOf(ECO_Utils_String.NullCheck(oWeeklyRollupEntry.EarnedValue__c)));
    		lResultLine.add(sTrendEAC1);
    		lResultLine.add(sTrendEAC2);

    		lResults.add(lResultLine);
    	}

    	return JSON.serialize(lResults);
    }

    private String createCpiAndSpiGoogleChartJSON(){	
    	list<WeeklyRollupEntry__c> lWeeklyRollupEntries = new list<WeeklyRollupEntry__c>([SELECT id
    																						   , PeriodStartDate__c
    																						   , SPI__c
    																						   , CPI__c
    																					 FROM WeeklyRollupEntry__c 
    																					 WHERE Project__c = :sProjectId]);

    	list<list<String>> lResults = new list<list<String>>();

    	for(WeeklyRollupEntry__c oWeeklyRollupEntry : lWeeklyRollupEntries){
    		list<String> lResultLine = new list<String>();

    		lResultLine.add(String.valueOf(oWeeklyRollupEntry.PeriodStartDate__c));
    		lResultLine.add(String.valueOf(ECO_Utils_String.NullCheck(oWeeklyRollupEntry.CPI__c)));
    		lResultLine.add(String.valueOf(ECO_Utils_String.NullCheck(oWeeklyRollupEntry.SPI__c)));

    		lResults.add(lResultLine);
    	}

    	return JSON.serialize(lResults);
    }

	public PageReference save() {
		update lWeeklyRollupEntries;

		reload(true);

		return null;
	}

	public PageReference clearAllOverrides() {
		for (WeeklyRollupEntry__c entry : lWeeklyRollupEntries) {
			entry.OverrideApprovedCost__c = null;
			entry.OverrideRevenue__c = null;
		}

		update lWeeklyRollupEntries;

		reload(true);

		return null;
	}
}