src/objects/ECO_DeleteSObjectSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ProjectRelationshipName__c</fullName>
        <label>Project Relationship Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ECO_DeleteSObjectSettings</label>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Risk Register</relationshipLabel>
        <relationshipName>Risks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RiskDescription__c</fullName>
        <inlineHelpText>Description of the potential risk.</inlineHelpText>
        <label>Risk Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Risk</label>
    <nameField>
        <label>Risk Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_MassDeleteControllerTest.cls
@isTest
private class ECO_MassDeleteControllerTest {

    static testMethod void testPageLoad () {
        PageReference pageRef = Page.ECO_MassDeleteRisks;
        Test.setCurrentPageReference(pageRef);
        
        ECO_DeleteSObjectSettings__c testSetting = new ECO_DeleteSObjectSettings__c();
        testSetting.Name = 'Risk__c';
        testSetting.ProjectRelationshipName__c = 'Project__c';
        insert testSetting;
        
        Account testAccount = new Account();
		testAccount.Name = 'test account';
		insert testAccount;
        
        pse__Proj__c testProject = new pse__Proj__c();
		testProject.pse__Account__c = testAccount.Id;
		insert testProject;
		
		ApexPages.currentPage().getParameters().put('id', testProject.Id);
		
		Risk__c testRisk = new Risk__c();
		testRisk.Project__c = testProject.Id;
		testRisk.Name = 'test risk';
		testRisk.RiskDescription__c = 'test risk';
		insert testRisk;
		
		User testUser = ECO_Utils_Testing.createTestUser('Standard User');
		insert testUser;
		
		Test.startTest();
		System.runAs(testUser) {
			// We have to re-query here since a workflow rule modifies the risk after we insert it, this is only way to get a clean standarsetcontroller
			ECO_MassDeleteController controller = new ECO_MassDeleteController(new ApexPages.StandardSetController([SELECT Id FROM Risk__c WHERE Id = :testRisk.Id]));
			controller.deleteStuff();
		}
		Test.stopTest();
		
		system.assertEquals(true, [SELECT Id FROM Risk__c].isEmpty());
    }
    
    static testMethod void testPageLoadNoSetting () {
        PageReference pageRef = Page.ECO_MassDeleteRisks;
        Test.setCurrentPageReference(pageRef);
        
        ECO_DeleteSObjectSettings__c testSetting = new ECO_DeleteSObjectSettings__c();
        testSetting.Name = 'Risk__c';
        testSetting.ProjectRelationshipName__c = 'Project__c';
        //insert testSetting;
        
        Account testAccount = new Account();
		testAccount.Name = 'test account';
		insert testAccount;
        
        pse__Proj__c testProject = new pse__Proj__c();
		testProject.pse__Account__c = testAccount.Id;
		insert testProject;
		
		ApexPages.currentPage().getParameters().put('id', testProject.Id);
		
		Risk__c testRisk = new Risk__c();
		testRisk.Project__c = testProject.Id;
		testRisk.Name = 'test risk';
		testRisk.RiskDescription__c = 'test risk';
		insert testRisk;
		
		User testUser = ECO_Utils_Testing.createTestUser('Standard User');
		insert testUser;
		
		Test.startTest();
		System.runAs(testUser) {
			// We have to re-query here since a workflow rule modifies the risk after we insert it, this is only way to get a clean standarsetcontroller
			ECO_MassDeleteController controller = new ECO_MassDeleteController(new ApexPages.StandardSetController([SELECT Id FROM Risk__c WHERE Id = :testRisk.Id]));
			controller.deleteStuff();
		}
		Test.stopTest();
		
		system.assertEquals(false, [SELECT Id FROM Risk__c].isEmpty());
    }
}