src/objects/ECO_TriggerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Controls the execution of triggers for the EcoSystem codebase.</description>
    <fields>
        <fullName>IsEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Enabled?</label>
        <type>Checkbox</type>
    </fields>
    <label>ECO Trigger Settings</label>
</CustomObject>

src/objects/IntegrationMessageQueue__c.object
<CustomObject>
    <fields>
        <fullName>JobName__c</fullName>
        <label>Job Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Integration Message Queue</label>
    <nameField>
        <displayFormat>IMQ-{0000000}</displayFormat>
        <label>Integration Message Queue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Message Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>FinancialTask__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This box should be checked if this project task is a financial task. Unchecked means the task represents a non-financial task.</description>
        <inlineHelpText>This box should be checked if this project task is a financial task. Unchecked means the task represents a non-financial task.</inlineHelpText>
        <label>Financial Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsChargeable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Chargeable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OracleSyncStatus__c</fullName>
        <description>P = Pending
T = Transfer (Success)
E = Error
S = Successful</description>
        <inlineHelpText>P = Pending
T = Transfer (Success)
E = Error
S = Successful</inlineHelpText>
        <label>Oracle Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pse__End_Date_Time__c</fullName>
        <description>The date &amp; time on which work for this Task is supposed to end.  Timecards may still be entered for a Task after this date as long as it is not closed for time entry.</description>
        <inlineHelpText>The date &amp; time on which work for this Task is supposed to end.  Timecards may still be entered for a Task after this date as long as it is not closed for time entry.</inlineHelpText>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>pse__Parent_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup captures Task hierarchies:  sub-Tasks have a Parent Task lookup value for the next higher-level Task in the Task hierarchy.  Note that this is separate and distinct from temporal (dependent/predecessor) relationships between Tasks.</description>
        <inlineHelpText>This lookup captures Task hierarchies:  sub-Tasks have a Parent Task lookup value for the next higher-level Task in the Task hierarchy.  Note that this is separate and distinct from temporal (dependent/predecessor) relationships between Tasks.</inlineHelpText>
        <label>Parent Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Project Tasks (Child Task)</relationshipLabel>
        <relationshipName>Immediate_Sub_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project that the Task is a part of.</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Start_Date_Time__c</fullName>
        <description>The date &amp; time on which work for this Task is supposed to start.  Timecards may still be entered for a Task before this date as long as it is not closed for time entry.</description>
        <inlineHelpText>The date &amp; time on which work for this Task is supposed to start.  Timecards may still be entered for a Task before this date as long as it is not closed for time entry.</inlineHelpText>
        <label>Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>pse__Status__c</fullName>
        <description>Pick list for Project Task status that may be customized as needed for possible Task status values</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_ProjectTaskValidatorTest.cls
@isTest
private class ECO_ProjectTaskValidatorTest {

	
	private static testMethod void testTaskValidation_TopLevelMustBeFinancial(){		

		pse__Project_Task__c task = new pse__Project_Task__c();
		task.Name = 'top task';
		task.pse__Project__c = createTestProject();
		task.pse__Start_Date_Time__c = DateTime.now();
		task.pse__End_Date_Time__c = DateTime.now().addDays(1);
		task.pse__Status__c = 'Draft';
		task.FinancialTask__c = false;

		enableProjecTaskTrigger();

		String expectedErrMsg = String.valueOf(System.Label.ECO_OracleTaskError_TopLevelFinancial).replace('##TASKNAME##', task.Name); 
      	String actualErrMsg = '';
      	insert task;

      	//confirm the task with no parent gets defaulted to financial
      	task = [SELECT Id, FinancialTask__c FROM pse__Project_Task__c WHERE Id = :task.Id];      	
      	system.assertEquals(true, task.FinancialTask__c);

		try{
			task.FinancialTask__c = false;
			update task;
		}catch(Exception e){
			actualErrMsg = e.getMessage();
		}
		system.assertEquals(true, actualErrMsg.contains(expectedErrMsg));
	}

	private static testMethod void testTaskValidation_IfChildrenAreFinancialMustBeFinancial(){		

		pse__Project_Task__c parenttask = new pse__Project_Task__c();
		parenttask.Name = 'top task';
		parenttask.pse__Project__c = createTestProject();
		parenttask.pse__Start_Date_Time__c = DateTime.now();
		parenttask.pse__End_Date_Time__c = DateTime.now().addDays(1);
		parenttask.pse__Status__c = 'Draft';
		parenttask.FinancialTask__c = true;
		insert parenttask;

		pse__Project_Task__c childTask1 = new pse__Project_Task__c();
		childTask1.Name = 'child1';
		childTask1.pse__Parent_Task__c = parenttask.Id;
		childTask1.pse__Start_Date_Time__c = DateTime.now();
		childTask1.pse__End_Date_Time__c = DateTime.now().addDays(1);
		childTask1.pse__Status__c = 'Draft';
		childTask1.FinancialTask__c = true;
		insert childTask1;

		pse__Project_Task__c childTask2 = new pse__Project_Task__c();
		childTask2.Name = 'child2';
		childTask2.pse__Parent_Task__c = childTask1.Id;
		childTask2.pse__Start_Date_Time__c = DateTime.now();
		childTask2.pse__End_Date_Time__c = DateTime.now().addDays(1);
		childTask2.pse__Status__c = 'Draft';
		childTask2.FinancialTask__c = true;
		insert childTask2;

		enableProjecTaskTrigger();

		String expectedErrMsg = String.valueOf(System.Label.ECO_OracleTaskError_NotFinancialWithChildren).replace('##TASKNAME##', childTask1.Name); 
      	String actualErrMsg = '';

		try{
			childTask1.FinancialTask__c = false;
			update childTask1;
		}catch(Exception e){
			actualErrMsg = e.getMessage();
		}
		system.assertEquals(true, actualErrMsg.contains(expectedErrMsg));
	}

	private static testMethod void testTaskValidation_ChargeableOnlyAtLowestLevel(){		

		pse__Project_Task__c parenttask = new pse__Project_Task__c();
		parenttask.Name = 'top task';
		parenttask.pse__Project__c = createTestProject();
		parenttask.pse__Start_Date_Time__c = DateTime.now();
		parenttask.pse__End_Date_Time__c = DateTime.now().addDays(1);
		parenttask.pse__Status__c = 'Draft';
		parenttask.FinancialTask__c = true;
		insert parenttask;

		pse__Project_Task__c childTask1 = new pse__Project_Task__c();
		childTask1.Name = 'child1';
		childTask1.pse__Parent_Task__c = parenttask.Id;
		childTask1.pse__Start_Date_Time__c = DateTime.now();
		childTask1.pse__End_Date_Time__c = DateTime.now().addDays(1);
		childTask1.pse__Status__c = 'Draft';
		childTask1.FinancialTask__c = true;
		insert childTask1;

		pse__Project_Task__c childTask2 = new pse__Project_Task__c();
		childTask2.Name = 'child2';
		childTask2.pse__Parent_Task__c = childTask1.Id;
		childTask2.pse__Start_Date_Time__c = DateTime.now();
		childTask2.pse__End_Date_Time__c = DateTime.now().addDays(1);
		childTask2.pse__Status__c = 'Draft';
		childTask2.FinancialTask__c = true;
		insert childTask2;

		enableProjecTaskTrigger();

		String expectedErrMsg = String.valueOf(System.Label.ECO_OracleTaskError_ChargeableAtLowestLevel).replace('##TASKNAME##', childTask1.Name); 
      	String actualErrMsg = '';
      	
		try{
			childTask1.IsChargeable__c = true;
			update childTask1;
		}catch(Exception e){
			actualErrMsg = e.getMessage();
		}
		system.assertEquals(true, actualErrMsg.contains(expectedErrMsg));
	}

	private static testMethod void testTaskValidation_PeersMustHaveSameFinancialSetting(){		

		pse__Project_Task__c parenttask = new pse__Project_Task__c();
		parenttask.Name = 'top task';
		parenttask.pse__Project__c = createTestProject();
		parenttask.pse__Start_Date_Time__c = DateTime.now();
		parenttask.pse__End_Date_Time__c = DateTime.now().addDays(1);
		parenttask.pse__Status__c = 'Draft';
		parenttask.FinancialTask__c = true;
		insert parenttask;

		pse__Project_Task__c childTask1 = new pse__Project_Task__c();
		childTask1.Name = 'child1';
		childTask1.pse__Parent_Task__c = parenttask.Id;
		childTask1.pse__Start_Date_Time__c = DateTime.now();
		childTask1.pse__End_Date_Time__c = DateTime.now().addDays(1);
		childTask1.pse__Status__c = 'Draft';
		childTask1.FinancialTask__c = true;
		insert childTask1;

		pse__Project_Task__c childTask2 = new pse__Project_Task__c();
		childTask2.Name = 'child2';
		childTask2.pse__Parent_Task__c = parenttask.Id;
		childTask2.pse__Start_Date_Time__c = DateTime.now();
		childTask2.pse__End_Date_Time__c = DateTime.now().addDays(1);
		childTask2.pse__Status__c = 'Draft';
		childTask2.FinancialTask__c = true;
		insert childTask2;

		enableProjecTaskTrigger();

		String expectedErrMsg = String.valueOf(System.Label.ECO_OracleTaskError_PeerFinancial).replace('##TASKNAME##', childTask1.Name); 
      	String actualErrMsg = '';
      	
		try{
			childTask1.FinancialTask__c = false;
			update childTask1;
		}catch(Exception e){
			actualErrMsg = e.getMessage();
		}
		system.assertEquals(true, actualErrMsg.contains(expectedErrMsg));
	}

	private static testMethod void testTaskValidation_ChargeableMustBeFinancial(){		

		pse__Project_Task__c parenttask = new pse__Project_Task__c();
		parenttask.Name = 'top task';
		parenttask.pse__Project__c = createTestProject();
		parenttask.pse__Start_Date_Time__c = DateTime.now();
		parenttask.pse__End_Date_Time__c = DateTime.now().addDays(1);
		parenttask.pse__Status__c = 'Draft';
		parenttask.FinancialTask__c = true;
		insert parenttask;

		pse__Project_Task__c childTask1 = new pse__Project_Task__c();
		childTask1.Name = 'child1';
		childTask1.pse__Parent_Task__c = parenttask.Id;
		childTask1.pse__Start_Date_Time__c = DateTime.now();
		childTask1.pse__End_Date_Time__c = DateTime.now().addDays(1);
		childTask1.pse__Status__c = 'Draft';
		childTask1.FinancialTask__c = false;
		insert childTask1;

		enableProjecTaskTrigger();

		String expectedErrMsg = String.valueOf(System.Label.ECO_OracleTaskError_FinancialNonChargeable).replace('##TASKNAME##', childTask1.Name); 
      	String actualErrMsg = '';

		try{
			childTask1.IsChargeable__c = true;
			update childTask1;
		}catch(Exception e){
			actualErrMsg = e.getMessage();
		}
		system.assertEquals(true, actualErrMsg.contains(expectedErrMsg));
	}

	private static testMethod void testTaskValidation_NoDeleteOfSynced(){		

		pse__Project_Task__c task = new pse__Project_Task__c();
		task.Name = 'top task';
		task.pse__Project__c = createTestProject();
		task.pse__Start_Date_Time__c = DateTime.now();
		task.pse__End_Date_Time__c = DateTime.now().addDays(1);
		task.pse__Status__c = 'Draft';
		task.FinancialTask__c = true;
		task.OracleSyncStatus__c = 'S';
		insert task;

		enableProjecTaskTrigger();

		String expectedErrMsg = String.valueOf(System.Label.ECO_OracleTaskError_Synced).replace('##TASKNAME##', task.Name); 
      	String actualErrMsg = '';

		try{
			delete task;
		}catch(Exception e){
			actualErrMsg = e.getMessage();
		}
		system.assertEquals(true, actualErrMsg.contains(expectedErrMsg));
	}

	private static Id createTestProject(){
		Account testAccount = new Account();
		testAccount.Name = 'test Account';
		insert testAccount;

		//create create source project 
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.Name = 'test project 1';
		testProject.pse__Account__c = testAccount.Id;
		testProject.pse__Project_Type__c = 'Customer Project';
		testProject.pse__Billing_Type__c = 'Fixed Price';
		testProject.CurrencyIsoCode = 'USD';
		testProject.pse__Is_Active__c = true;	
		insert testProject;

		return testProject.Id;
	}

	private static void enableProjecTaskTrigger(){
		ECO_TriggerSettings__c triggerSetting = new ECO_TriggerSettings__c();
		triggerSetting.Name = 'ECO_ProjectTask_AllEvents';
		triggerSetting.IsEnabled__c = true;
        insert triggerSetting;
	}

	private static testMethod void testTaskSync(){		

		pse__Project_Task__c parenttask = new pse__Project_Task__c();
		parenttask.Name = 'top task';
		parenttask.pse__Project__c = createTestProject();
		parenttask.pse__Start_Date_Time__c = DateTime.now();
		parenttask.pse__End_Date_Time__c = DateTime.now().addDays(1);
		parenttask.pse__Status__c = 'Draft';
		parenttask.FinancialTask__c = true;
		insert parenttask;

		pse__Project_Task__c childTask1 = new pse__Project_Task__c();
		childTask1.Name = 'child1';
		childTask1.pse__Parent_Task__c = parenttask.Id;
		childTask1.pse__Start_Date_Time__c = DateTime.now();
		childTask1.pse__End_Date_Time__c = DateTime.now().addDays(1);
		childTask1.pse__Status__c = 'Draft';
		childTask1.FinancialTask__c = true;
		childTask1.IsChargeable__c = true;
		insert childTask1;

		childTask1.OracleSyncStatus__c = 'S';
		update childTask1;

		pse__Project_Task__c childTask2 = new pse__Project_Task__c();
		childTask2.Name = 'child2';
		childTask2.pse__Parent_Task__c = parenttask.Id;
		childTask2.pse__Start_Date_Time__c = DateTime.now();
		childTask2.pse__End_Date_Time__c = DateTime.now().addDays(1);
		childTask2.pse__Status__c = 'Draft';
		childTask2.FinancialTask__c = true;
		childTask2.IsChargeable__c = false;
		insert childTask2;

		childTask2.OracleSyncStatus__c = 'S';
		update childTask2;

		enableProjecTaskTrigger();

		test.StartTest();

		childTask1.IsChargeable__c = false;
		update childTask1;

		childTask2.IsChargeable__c = true;
		update childTask2;

		test.StopTest();

		IntegrationMessageQueue__c task1MsgQueue = [SELECT Id, JobName__c FROM IntegrationMessageQueue__c WHERE RecordId__c = :childTask1.Id];
		IntegrationMessageQueue__c task2MsgQueue = [SELECT Id, JobName__c FROM IntegrationMessageQueue__c WHERE RecordId__c = :childTask2.Id];


		system.assertEquals(ECO_Service_ProjectSync.JOBNAME_TASK_SYNC_LATER, task1MsgQueue.JobName__c);
		system.assertEquals(ECO_Service_ProjectSync.JOBNAME_TASK_SYNC_NOW, task2MsgQueue.JobName__c);
	}


	private static testMethod void TestTaskSyncSchedulable() {

	   // CRON expression: midnight on March 15.
	   // Because this is a test, job executes
	   // immediately after Test.stopTest().
	   	String CRON_EXP = '0 0 0 15 3 ? 2022';

		enableProjecTaskTrigger();
		
  		pse__Project_Task__c parenttask = new pse__Project_Task__c();
		parenttask.Name = 'top task';
		parenttask.pse__Project__c = createTestProject();
		parenttask.pse__Start_Date_Time__c = DateTime.now();
		parenttask.pse__End_Date_Time__c = DateTime.now().addDays(1);
		parenttask.pse__Status__c = 'Draft';
		parenttask.FinancialTask__c = true;
		insert parenttask;

		pse__Project_Task__c childTask1 = new pse__Project_Task__c();
		childTask1.Name = 'child1';
		childTask1.pse__Parent_Task__c = parenttask.Id;
		childTask1.pse__Start_Date_Time__c = DateTime.now();
		childTask1.pse__End_Date_Time__c = DateTime.now().addDays(1);
		childTask1.pse__Status__c = 'Draft';
		childTask1.FinancialTask__c = true;
		childTask1.IsChargeable__c = true;

		insert childTask1;


		childTask1.OracleSyncStatus__c = 'S';
		update childTask1;

		

      	Test.startTest();


      	childTask1.IsChargeable__c = false;
		update childTask1;

      	// Schedule the test job
      	String jobId = System.schedule('ECO_TaskSyncSchedulable',
      	                     			CRON_EXP, 
                        				new ECO_TaskSyncSchedulable());
         
      	// Get the information from the CronTrigger API object
      	CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];

      	// Verify the expressions are the same
      	System.assertEquals(CRON_EXP, ct.CronExpression);

      	// Verify the job has not run
     	System.assertEquals(0, ct.TimesTriggered);

	    // Verify the next time the job will run
	    System.assertEquals('2022-03-15 00:00:00', String.valueOf(ct.NextFireTime));

	    // Verify the scheduled job hasn't run yet.
	    IntegrationMessageQueue__c task1MsgQueue = [SELECT Id, JobName__c, Status__c FROM IntegrationMessageQueue__c WHERE RecordId__c = :childTask1.Id];
		
	  	system.assertEquals(ECO_Service_ProjectSync.STATUS_INITIATED, task1MsgQueue.Status__c);
	
	    Test.stopTest();

	    /*
	    // Now that the scheduled job has executed after Test.stopTest(),
	    task1MsgQueue = [SELECT Id, JobName__c, Status__c FROM IntegrationMessageQueue__c WHERE RecordId__c = :childTask1.Id];
		
	  	system.assertNotEquals(ECO_Service_ProjectSync.STATUS_INITIATED, task1MsgQueue.Status__c);
		*/
   }

}