src/objects/ECO_Smart_Search_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Analytics_End_Point__c</fullName>
        <description>This is the data-endpoint that is used by CoveoAnalytics Component</description>
        <inlineHelpText>This is the data-endpoint that is used by CoveoAnalytics Component</inlineHelpText>
        <label>Analytics End Point</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveoTab_All_Expression1__c</fullName>
        <description>This is the data-expression that is used by the CoveoTab for All Information search.</description>
        <inlineHelpText>This is the data-expression that is used by the CoveoTab for All Information search.</inlineHelpText>
        <label>CoveoTab All Expression1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveoTab_All_Expression2__c</fullName>
        <description>This is the data-expression that is used by the CoveoTab for All Information search. This is the second part of the expression. This is needed because Salesforce has a limit of 255 characters for Text Data Type.</description>
        <inlineHelpText>This is the data-expression that is used by the CoveoTab for All Information search. This is the second part of the expression. This is needed because Salesforce has a limit of 255 characters for Text Data Type.</inlineHelpText>
        <label>CoveoTab All Expression2</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveoTab_People_Expression__c</fullName>
        <description>This is the expression used by the CoveoTab People</description>
        <inlineHelpText>This is the expression used by the CoveoTab People</inlineHelpText>
        <label>CoveoTab People Expression</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveoTab_Practice_Expression_1__c</fullName>
        <description>This is the expression that is used by the Practice CoveoTab</description>
        <inlineHelpText>This is the expression that is used by the Practice CoveoTab</inlineHelpText>
        <label>CoveoTab Practice Expression 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveoTab_Practice_Expression_2__c</fullName>
        <description>This is the expression that is used by the Practice CoveoTab and this is the second part of the search. This is needed because of the 255 chracter limit on the Text data type field.</description>
        <inlineHelpText>This is the expression that is used by the Practice CoveoTab and this is the second part of the search. This is needed because of the 255 chracter limit on the Text data type field.</inlineHelpText>
        <label>CoveoTab Practice Expression 2</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveoTab_Projects_Expression__c</fullName>
        <description>This is the expression that is used by the Projects CoveoTab.</description>
        <inlineHelpText>This is the expression that is used by the Projects CoveoTab.</inlineHelpText>
        <label>CoveoTab Projects Expression</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter_By_File_Type_Allowed_Values__c</fullName>
        <description>These are the file types that are allowed in the Facet</description>
        <inlineHelpText>These are the file types that are allowed in the Facet</inlineHelpText>
        <label>Filter By File Type Allowed Values</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>This is the Key that is passed to the Coveo to retrieve the token for authentication</description>
        <label>Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Search_CoveoSearchInterface_Expression__c</fullName>
        <description>This is the data-hidden-expression for the search CoveoSearchInterface.</description>
        <inlineHelpText>This is the data-hidden-expression for the search CoveoSearchInterface.</inlineHelpText>
        <label>Search CoveoSearchInterface Expression</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TPN_Search_Expression1__c</fullName>
        <description>This is the data-hidden-expression for the TPNSearch. This is what controls what is displayed on the FROM THE TPN section on the landing page of SmartSearch page.</description>
        <inlineHelpText>This is the data-hidden-expression for the TPNSearch. This is what controls what is displayed on the FROM THE TPN section on the landing page of SmartSearch page.</inlineHelpText>
        <label>TPN Search Expression 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TPN_Search_Expression_2__c</fullName>
        <description>This is the second part of data-hidden-expression for the TPNSearch. This is what controls what is displayed on the FROM THE TPN section on the landing page of SmartSearch page. We have two because we have a character limit of 255 on a Text field on Salesforce. In the code both are concatenated with an OR and then passed to the front end.</description>
        <inlineHelpText>This is the second part of data-hidden-expression for the TPNSearch. This is what controls what is displayed on the FROM THE TPN section on the landing page of SmartSearch page. We have two because we have a character limit of 255 on a Text field on Sales</inlineHelpText>
        <label>TPN Search Expression 2</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endPointURL__c</fullName>
        <description>This will be the endPoint URL used to authenticate user with Coveo</description>
        <label>endPointURL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ECO Smart Search Settings</label>
</CustomObject>

src/classes/ECO_Temp_PortalControllerTest.cls
@isTest
public with sharing class ECO_Temp_PortalControllerTest {
	
    static testMethod void testPageLoadAndNavigation () {
        PageReference pageRef = Page.ECO_Temp_Portal;
		
		Account testAccount = new Account();
		testAccount.Name = 'test account';
		insert testAccount;
		
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.pse__Account__c = testAccount.Id;
		insert testProject;
		
		ECO_Smart_Search_Settings__c smartSearchCS = new ECO_Smart_Search_Settings__c();
		smartSearchCS.Name='SmartSearch';
		smartSearchCS.Analytics_End_Point__c = 'https://smartsearchrest-test.aecom.com:8443/rest/analytics';
		smartSearchCS.CoveoTab_All_Expression1__c = 'NOT @sfid OR @objecttype==("User","ProjectC","Opportunity","Account", "ServiceCatalogEntryC", "FeedItem")';
		smartSearchCS.CoveoTab_All_Expression2__c = '@objecttype==("FeedComment")';
		smartSearchCS.CoveoTab_People_Expression__c = '@objecttype==("User")';
		smartSearchCS.CoveoTab_Practice_Expression_1__c = '(@objecttype==("FeedItem") @sfparentname=(TPN,TPG)) OR (@sysspsitename = TPN) OR (@objecttype==("ServiceCatalogEntryC"))';
		smartSearchCS.CoveoTab_Practice_Expression_2__c = '(@objecttype==("FeedComment") @sffeeditemid=[[@sfid] @objecttype==("FeedItem","FeedComment") @sfparentname=(TPN,TPG) ])';
		smartSearchCS.CoveoTab_Projects_Expression__c = '(@objecttype==("ProjectC")) OR (NOT(@sysspsitename = TPN) AND @sysconnectortype == ("Sharepoint") AND @syscollection = ("Projects"))';
		smartSearchCS.endPointURL__c = 'https://smartsearchrest-test.aecom.com:8443/rest/search/';
		smartSearchCS.Filter_By_File_Type_Allowed_Values__c = 'doc,pdf,ppt,xls,Zip,xlsx,exe,wav,swf,rtf,msg,html,vsd,mp4';
		smartSearchCS.Key__c = 'anyrandomstringffjkfajl;akf0452098234790dklqer098923498aslsdk2340';
		smartSearchCS.Search_CoveoSearchInterface_Expression__c = 'NOT(@sysfiletype==("spuserprofile"))';
		smartSearchCS.TPN_Search_Expression1__c = '(@objecttype==("FeedItem") @sfparentname=(TPN,TPG) @sfcollaborationgroupid=({!collaborationGroups}))';
		smartSearchCS.TPN_Search_Expression_2__c = '(@objecttype==("FeedComment") @sffeeditemid=[[@sfid] @objecttype==("FeedItem","FeedComment") @sfparentname=(TPN,TPG) @sfcollaborationgroupid=({!collaborationGroups}) ])';
		   
		insert smartSearchCS;
		
		Test.startTest();

		ECO_Temp_PortalController controller = new ECO_Temp_PortalController();
		controller.onLoad();
		controller.retrieveCustomSettingParameters();
		
		// If the call below is made, the whole test is skipped because it is making a webservice callout.
		// Message produced: Methods defined as TestMethod do not support Web service callouts, test skipped
		// controller.getSearchToken();
		
		controller.goToApplicationConfiguration();
		controller.goToReportBuilder();
		controller.goToNewProject();
		controller.goToNewOpportunity();
		
		Test.stopTest();
    }
}