src/objects/EnrollmentPlan__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW Enrollment Plans under review by Approvers</description>
    <fields>
        <fullName>ContractType__c</fullName>
        <description>Displays the contract type as per AECOM Insight.  For Oracle projects, this will reflect the Oracle contract type.  DTW data is updated weekly by Insight.</description>
        <formula>IncentiveProject__r.ContractType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the contract type as per AECOM Insight.  For Oracle projects, this will reflect the Oracle contract type.  DTW data is updated weekly by Insight.</inlineHelpText>
        <label>Contract Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending PM Action</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 1 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 2 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 3 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending DTW Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected for Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unenrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Corp Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - No Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt-Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FPPOverallEligibility_c__c</fullName>
        <description>Indicates whether the project meets current eligibility requirements for the Fixed Price Plan.</description>
        <formula>TEXT(IncentiveProject__r.FPPOverallEligibility__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Indicates whether the project meets current eligibility requirements for the Fixed Price Plan.</inlineHelpText>
        <label>Eligible for Fixed Price Plan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IncentiveProject__c</fullName>
        <label>Project Name</label>
        <referenceTo>IncentiveProject__c</referenceTo>
        <relationshipLabel>Enrollment Applications</relationshipLabel>
        <relationshipName>Enrollment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectGeography__c</fullName>
        <formula>IncentiveProject__r.GeographyDescription__c

/*IncentiveProject__r.GeographyDescription__c*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TMPlanOverallEligibility__c</fullName>
        <description>Indicates whether the project meets current eligibility requirements for the T&amp;M Price Plan.</description>
        <formula>TEXT( IncentiveProject__r.TMPlanOverallEligibility__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Indicates whether the project meets current eligibility requirements for the T&amp;M Price Plan.</inlineHelpText>
        <label>Eligible for T&amp;M Plan</label>
        <type>Text</type>
    </fields>
    <label>Enrollment Application</label>
    <nameField>
        <label>Enrollment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IncentivePlanTemplate__c.object
<CustomObject>
    <fields>
        <fullName>ContractSubType__c</fullName>
        <label>Margin Type</label>
        <picklist>
            <picklistValues>
                <fullName>Gross Margin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net Margin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ContractType__c</fullName>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time &amp; Material</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GeographyAllocation__c</fullName>
        <label>Geography Allocation</label>
        <picklist>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA&amp;I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Worldwide</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Incentive Plan Template</label>
    <nameField>
        <label>Incentive Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Plan Template</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/IncentiveProject__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW eligible projects to be considered for enrollment in DTW Incentive Plans</description>
    <fields>
        <fullName>ContractType__c</fullName>
        <description>Displays the contract type as per AECOM&apos;s Insight.  For Oracle projects, this will reflect the Oracle contract type</description>
        <inlineHelpText>Displays the contract type as per AECOM&apos;s Insight.  For Oracle projects, this will reflect the Oracle contract type</inlineHelpText>
        <label>Contract Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTWAdminInitiated__c</fullName>
        <description>Date DTW Admin validated Incentive Project and initiated the Enrollment Process.</description>
        <inlineHelpText>Date DTW Admin validated Incentive Project and initiated the Enrollment Process.</inlineHelpText>
        <label>DTW Admin Initiated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EnrollmentPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enrollment Application</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Incentive Projects</relationshipLabel>
        <relationshipName>IncentiveProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <formula>IF( PaymentRequest__c &lt;&gt; &quot;&quot;,  Text(PaymentRequest__r.EnrollmentStatus__c),

IF(
    AND(
       (EnrollmentPlan__c=&quot;&quot;), 
        OR(
           TEXT(FPPOverallEligibility__c)=&quot;Yes&quot;,
           TEXT(TMPlanOverallEligibility__c)=&quot;Yes&quot;
           )
         ),
&quot;Pending DTW Action&quot;, 
IF(
   (EnrollmentPlan__c=&quot;&quot;), &quot;Not Eligible&quot;,
   TEXT(EnrollmentPlan__r.EnrollmentStatus__c)
   )
   )
)</formula>
        <label>Enrollment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Incentive_Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RegionDescription__c</fullName>
        <label>Sub-Region or Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TMPlanOverallEligibility__c</fullName>
        <description>Indicates whether or not the project meets all current eligibility requirements for the T&amp;M Plan.</description>
        <inlineHelpText>Indicates whether or not the project meets all current eligibility requirements for the T&amp;M Plan.</inlineHelpText>
        <label>T&amp;M Plan Overall Eligibility</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Incentive Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the overall profile</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/INC_ChoseIncentivePlanControllerTest.cls
@isTest
private class INC_ChoseIncentivePlanControllerTest
{
    @isTest
    static void testChoseIncentivePlanTemplate()
    {
        User RunningUser1 = INC_Utils_Testing.createTestUser('System Administrator');
        User ProjectManager1 = INC_Utils_Testing.createTestUser('System Administrator');
        list<User> lUser = new list<User>();
        lUser.add(RunningUser1);
        lUser.add(ProjectManager1);
        insert lUser;

        Test.StartTest();
        System.runAs(RunningUser1){
                IncentiveProject__c oIncentiveProject = INC_Utils_Testing.createIncentiveProject();
                oIncentiveProject.ProjectManager__c = ProjectManager1.ID;
                oIncentiveProject.RegionDescription__c = 'Midwest';            
                insert oIncentiveProject;
                
                INC_IncentiveProjectCreateEnrollment.createEnrollmentForm(oIncentiveProject.ID);
            }
            
        Test.StopTest();

        map<id,IncentiveProject__c> mapIncentives = new map<id,IncentiveProject__c>();
        For(IncentiveProject__c inp: [Select ID, Name, OwnerID, DTWAdminInitiated__c from IncentiveProject__c]){
            System.assert(inp.OwnerID == ProjectManager1.ID,'Owner Should be project Manager! Owner: ' +inp.OwnerID + ' PM: ' + ProjectManager1.ID);
            Date d = System.Today();
            System.assert(inp.DTWAdminInitiated__c == d, 'DTWAdminInitiated__c should be today: ' + inp.DTWAdminInitiated__c + ' d: ' + d);
            mapIncentives.put(inp.id,inp);
        }
        Integer iCnt = 0;
        EnrollmentPlan__c enrollmentPlan;
        For(EnrollmentPlan__c ep: [Select ID, Name, EnrollmentStatus__c, IncentiveProject__c, FPPOverallEligibility_c__c, TMPlanOverallEligibility__c, ProjectGeography__c from EnrollmentPlan__c where IncentiveProject__c =: mapIncentives.Keyset()]){
            iCnt ++;
            String sIncName = mapIncentives.get(ep.IncentiveProject__c).Name;
            String sEpName = ep.Name;
            sIncName = 'ENR: ' + sIncName;
            System.assert(sIncName == sEpName,'Names not equal');
            System.assert(ep.EnrollmentStatus__c == 'Pending PM Action', 'Status should be Pending PM Action not: ' + ep.EnrollmentStatus__c);
			enrollmentPlan = ep;
        }
        System.assert(icnt == 1,'There should only be 1 enrollment plan: ' + iCnt);
        
        IncentivePlanTemplate__c incentivePlanTemplate = new IncentivePlanTemplate__c();
        incentivePlanTemplate.GeographyAllocation__c = 'Americas';
        incentivePlanTemplate.ContractType__c = 'Fixed Price';
        incentivePlanTemplate.ContractSubType__c = 'Gross Margin';
        incentivePlanTemplate.Status__c = 'Active';
        insert incentivePlanTemplate;
        
        incentivePlanTemplate = new IncentivePlanTemplate__c();
        incentivePlanTemplate.GeographyAllocation__c = 'Americas';
        incentivePlanTemplate.ContractType__c = 'Fixed Price';
        incentivePlanTemplate.ContractSubType__c = 'Net Margin';
        incentivePlanTemplate.Status__c = 'Active';
        insert incentivePlanTemplate;
        
        incentivePlanTemplate = new IncentivePlanTemplate__c();
        incentivePlanTemplate.GeographyAllocation__c = 'Americas';
        incentivePlanTemplate.ContractType__c = 'Time & Material';
        incentivePlanTemplate.ContractSubType__c = 'Gross Margin';
        incentivePlanTemplate.Status__c = 'Active';
        insert incentivePlanTemplate;
        
        incentivePlanTemplate = new IncentivePlanTemplate__c();
        incentivePlanTemplate.GeographyAllocation__c = 'Americas';
        incentivePlanTemplate.ContractType__c = 'Time & Material';
        incentivePlanTemplate.ContractSubType__c = 'Net Margin';
        incentivePlanTemplate.Status__c = 'Active';
        insert incentivePlanTemplate;                

        ApexPages.StandardController sc = new ApexPages.StandardController(enrollmentPlan);      
        INC_ChoseIncentivePlanController controller = new INC_ChoseIncentivePlanController(sc);
                
        System.assertEquals(2, controller.getYesNoOptions().size());
        System.assertEquals(2, controller.getSelectionMethods().size());
        controller.getIsFixedPriceEligible();
        controller.getIsTMEligible();
        controller.getIsANZRegion();
        // System.AssertEquals('Americas', controller.getGeographyAllocation('Midwest'));
        // System.AssertEquals('EMEA', controller.getGeographyAllocation('UK & Ireland'));
        // System.AssertEquals('APAC', controller.getGeographyAllocation('SE Asia'));
        controller.getIsMultiPlanEligible();
        controller.selectedSelectionMethod = 'Guided';
        controller.submitQuestionnairre();
        controller.clearResults();
        controller.selectPlanForEnrollment();
        

    }
}