src/objects/EnrollmentPlan__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW Enrollment Plans under review by Approvers</description>
    <fields>
        <fullName>IncentiveProject__c</fullName>
        <label>Project Name</label>
        <referenceTo>IncentiveProject__c</referenceTo>
        <relationshipLabel>Enrollment Applications</relationshipLabel>
        <relationshipName>Enrollment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MetricWarningActive__c</fullName>
        <label>Metric Warning Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Enrollment Application</label>
    <nameField>
        <label>Enrollment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IncentiveProject__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW eligible projects to be considered for enrollment in DTW Incentive Plans</description>
    <fields>
        <fullName>EnrollmentPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enrollment Application</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Incentive Projects</relationshipLabel>
        <relationshipName>IncentiveProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Incentive Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/INC_IncentiveProject_Triggers.cls
public with sharing class INC_IncentiveProject_Triggers {

	public INC_IncentiveProject_Triggers() {
		
	}

	public void checkForKeyMetricChanges(map<id,IncentiveProject__c>mapNew, map<id,IncentiveProject__c> mapOld){
		System.Debug(logginglevel.error,'check for changes');
		set<id> setIncentivesChanges = INC_Service_EnrollmentPlan.checkMetricChanges(mapNew,mapOld);
		List<EnrollmentPlan__c> listChangedEnroll = new list<EnrollmentPlan__c>();
		System.debug(logginglevel.error,'setIncentivesChanges: ' + setIncentivesChanges);
		if(setIncentivesChanges != null && setIncentivesChanges.size() > 0){
			for(EnrollmentPlan__c Enroll: [Select id
														   , MetricWarningActive__c
												  From EnrollmentPlan__c
												  Where IncentiveProject__c =: setIncentivesChanges]){
				Enroll.MetricWarningActive__c = 'Yes';
				listChangedEnroll.add(Enroll);
			}

			if(listChangedEnroll != null && listChangedEnroll.size() > 0){
				INC_Service_EnrollmentPlan.updateEnrollmentApplications(listChangedEnroll);
			}
		}
	}
	
}