src/objects/EnrollmentParticipant__c.object
<CustomObject>
    <fields>
        <fullName>EmployeeName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>PSA Resource, AECOM Employee</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Salesforce_User__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollment Participants</relationshipLabel>
        <relationshipName>Enrollment_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentPlan__c</fullName>
        <label>Enrollment Plan</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Enrollment Participants</relationshipLabel>
        <relationshipName>EnrollmentParticipants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TargetIncentivePoolAllocated__c</fullName>
        <inlineHelpText>Target % Incentive Pool Allocated</inlineHelpText>
        <label>Target %</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Enrollment Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EnrollmentPlan__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW Enrollment Plans under review by Approvers</description>
    <fields>
        <fullName>Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Enrollment_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BaselineGMofNSR__c</fullName>
        <description>For projects enrolled in the Fixed Price plan only, Baseline Margin% will change if Budgeted Margin% changes (and therefore Threshold Margin% and Threshold Margin will change)</description>
        <formula>BaselineMarginCalculated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>For projects enrolled in the Fixed Price plan only, Baseline Margin% will change if Budgeted Margin% changes (and therefore Threshold Margin% and Threshold Margin will change)</inlineHelpText>
        <label>Baseline Margin % of NSR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>BaselineGrossMargin__c</fullName>
        <description>Used for purposes of Deliver To Win only.  Displays budgeted margin inclusive of mgmt adjustments, and represents expected margin for the project.</description>
        <formula>CASE(IncentivePlan__r.ContractSubType__c
	,&apos;Gross Margin&apos;
	,(
		IF(
			AND(ISPICKVAL(IncentivePlan__r.ContractType__c, &apos;Time &amp; Material&apos;),
			OR(NOT(ISPICKVAL(ApplicationType__c,&apos;ENR&apos;)),Enrolled__c))
			,ApprovedGrossMarginBudgetatSnapshot__c
			,IncentiveProject__r.ApprovedGrossMarginBudget__c
		)
			
	)
	,(
		IF(
			AND(ISPICKVAL(IncentivePlan__r.ContractType__c, &apos;Time &amp; Material&apos;),
			OR(NOT(ISPICKVAL(ApplicationType__c,&apos;ENR&apos;)),ISPICKVAL(EnrollmentStatus__c,&apos;Enrolled&apos;)))
			,ApprovedNetMarginBudgetatSnapshot__c
			,IncentiveProject__r.ApprovedNetMarginBudget__c
		)
	)
) + (GrossMarginAmountScopeChange__c + GrossMarginAmountAdjustment__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Used for purposes of Deliver To Win only.  Displays budgeted margin inclusive of mgmt adjustments, and represents expected margin for the project.</inlineHelpText>
        <label>Baseline Margin</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContractType__c</fullName>
        <description>Displays the contract type as per AECOM Insight.  For Oracle projects, this will reflect the Oracle contract type.  DTW data is updated weekly by Insight.</description>
        <formula>IncentiveProject__r.ContractType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the contract type as per AECOM Insight.  For Oracle projects, this will reflect the Oracle contract type.  DTW data is updated weekly by Insight.</inlineHelpText>
        <label>Contract Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DSOTarget__c</fullName>
        <description>Displays target Days Sales Outstanding, a measure of the time to collect cash for costs incurred.  For the purposes of Deliver to Win, a target must be set that reflects the billing cycle time, client payment terms, and local cash flow expectations for the project.</description>
        <inlineHelpText>Displays target Days Sales Outstanding, a measure of the time to collect cash for costs incurred.  For the purposes of DTW, a target must be set that reflects the billing cycle time, client payment terms, and local cash flow expectations for the project.</inlineHelpText>
        <label>DSO Target</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IncentivePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incentive Plan</label>
        <referenceTo>IncentivePlanTemplate__c</referenceTo>
        <relationshipName>Enrollment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IncentiveProject__c</fullName>
        <label>Project Name</label>
        <referenceTo>IncentiveProject__c</referenceTo>
        <relationshipLabel>Enrollment Applications</relationshipLabel>
        <relationshipName>Enrollment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Application</label>
    <nameField>
        <label>Enrollment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IncentivePlanTemplate__c.object
<CustomObject>
    <label>Incentive Plan Template</label>
    <nameField>
        <label>Incentive Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Plan Template</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/IncentiveProject__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW eligible projects to be considered for enrollment in DTW Incentive Plans</description>
    <label>Incentive Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/INC_EnrollmentLetterController.cls
public with sharing class INC_EnrollmentLetterController {

	public EnrollmentParticipant__c oEP;
	public calcHolder oCH;
	public string epID {get;set;}



	public class calcHolder{
		public date letterDate{get;set;}
		public decimal V {get;set;}
		public decimal Y {get;set;}
		public decimal AF {get;set;}
		public decimal W {get;set;}
		public decimal Z {get;set;}
		public decimal AG {get;set;}
		public decimal X {get;set;}
		public decimal AA {get;set;}
		public decimal AH {get;set;}
		public decimal AC {get;set;}
		public decimal AD {get;set;}
		public decimal AE {get;set;}	
		public string gmtm {get;set;}	

		public void calculate(EnrollmentParticipant__c ep){
			letterDate = date.today();

			if(ep.EnrollmentPlan__r.IncentivePlan__r.ContractSubType__c == 'Gross Margin'){
				gmtm = 'GM';
			} else {
				gmtm = 'NM';
			}


			V = EP.EnrollmentPlan__r.BaselineGrossMargin__c * 1.1;
			Y = EP.EnrollmentPlan__r.BaselineGrossMargin__c * 1.25;
			AE = EP.EnrollmentPlan__r.BaselineGrossMargin__c * 1.5;
			AF = AE - EP.EnrollmentPlan__r.BaselineGrossMargin__c;
			W = V - EP.EnrollmentPlan__r.BaselineGrossMargin__c;
			Z = Y - EP.EnrollmentPlan__r.BaselineGrossMargin__c;
			AG = AF * EP.EnrollmentPlan__r.IncentivePlan__r.ProfitSharingPercent__c;
			X =  W * EP.EnrollmentPlan__r.IncentivePlan__r.ProfitSharingPercent__c;
			AA = Z * EP.EnrollmentPlan__r.IncentivePlan__r.ProfitSharingPercent__c;

			if(EP.TargetIncentivePoolAllocated__c != null){
				AH = AG * EP.TargetIncentivePoolAllocated__c;
				AC = X  * EP.TargetIncentivePoolAllocated__c;
				AD = AA * EP.TargetIncentivePoolAllocated__c;	
			}		
		}
	}


	private void getEP(){
		if(oEP == null){
			oEP  = [select id
								, name
								, CurrencyIsoCode
								, TargetIncentivePoolAllocated__c
								, EnrollmentPlan__r.Approver1__r.name
								, EmployeeName__r.name
								, EmployeeName__r.firstname
								, EnrollmentPlan__r.IncentiveProject__r.name
								, EnrollmentPlan__r.IncentiveProject__r.contracttype__c
								, EnrollmentPlan__r.IncentivePlan__r.name
								, EnrollmentPlan__r.IncentivePlan__r.ProfitSharingPercent__c
								, EnrollmentPlan__r.IncentivePlan__r.ContractSubType__c
								, EnrollmentPlan__r.BaselineGrossMargin__c
								, EnrollmentPlan__r.BaselineGMofNSR__c	
								, EnrollmentPlan__r.DSOTarget__c					

						from EnrollmentParticipant__c
						where id=:epID];
		}		
	}

	public EnrollmentParticipant__c getoEP(){
		getEP();
		return oEP;
	}

	public calcHolder getoCH(){
		getEP();

		if(oCH == null){
			oCH = new calcHolder();
			oCH.calculate(oEP);
		}

		return oCH;
	}


	public INC_EnrollmentLetterController() {

	}

}