src/objects/EnrollmentPlan__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW Enrollment Plans under review by Approvers</description>
    <fields>
        <fullName>ApprovedNSRBudget__c</fullName>
        <description>Displays the budgeted Net Service Revenue (NSR).  Budget reflects as sold plus change orders.</description>
        <formula>IncentiveProject__r.ApprovedNSRBudget__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the budgeted Net Service Revenue (NSR).  Budget reflects as sold plus change orders.</inlineHelpText>
        <label>Budgeted NSR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CustomerName__c</fullName>
        <formula>IncentiveProject__r.CustomerName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending PM Action</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 1 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 2 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 3 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending DTW Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected for Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unenrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Corp Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - No Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt-Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IncentiveProject__c</fullName>
        <label>Project Name</label>
        <referenceTo>IncentiveProject__c</referenceTo>
        <relationshipLabel>Enrollment Applications</relationshipLabel>
        <relationshipName>Enrollment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectID__c</fullName>
        <formula>IncentiveProject__r.ProjectID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <label>Enrollment Application</label>
    <nameField>
        <label>Enrollment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IncentiveProject__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW eligible projects to be considered for enrollment in DTW Incentive Plans</description>
    <fields>
        <fullName>ApprovedNSRBudget__c</fullName>
        <description>Approved NSR Budget</description>
        <label>Approved NSR Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CustomerName__c</fullName>
        <label>Customer Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnrollmentPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enrollment Application</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Incentive Projects</relationshipLabel>
        <relationshipName>IncentiveProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <formula>IF( PaymentRequest__c &lt;&gt; &quot;&quot;,  Text(PaymentRequest__r.EnrollmentStatus__c),

IF(
    AND(
       (EnrollmentPlan__c=&quot;&quot;), 
        OR(
           TEXT(FPPOverallEligibility__c)=&quot;Yes&quot;,
           TEXT(TMPlanOverallEligibility__c)=&quot;Yes&quot;
           )
         ),
&quot;Pending DTW Action&quot;, 
IF(
   (EnrollmentPlan__c=&quot;&quot;), &quot;Not Eligible&quot;,
   TEXT(EnrollmentPlan__r.EnrollmentStatus__c)
   )
   )
)</formula>
        <label>Enrollment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectID__c</fullName>
        <externalId>true</externalId>
        <label>Project Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProjectManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Incentive_Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Incentive Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/INC_IncentiveSearch_Controller.cls
public without sharing class INC_IncentiveSearch_Controller {
	
	public String projectNumber{get;set;}
	public String projectName {get;set;}
	public String projectManager {get;set;}
	public String customerName {get;set;}
	public String blankValue{get;set;}
	public List<criteriaRow> searchCriteria{get;set;}
	public list<IncentiveProject__c> lResults {get;set;}
	public Integer removeRow {
        get;
        // *** setter is NOT being called ***
        set {
            removeRow = value;
            System.debug('value: '+value);
        }
    }
	private String sProjectName;
	private String sProjectNumber;
	private String sCustomerName;
	private String sProjectManager;

	public INC_IncentiveSearch_Controller() {
		searchCriteria = new list<criteriaRow>();
		addRow();
		
	}

	public PageReference addRow(){
		criteriaRow ocriteriaRow;
		if(searchCriteria != null && searchCriteria.size() > 0){
			/*if(searchCriteria[searchCriteria.size() -1].criteria == 'PM'){
				if(IncProj.ProjectManager__c != null){
		   			searchCriteria[searchCriteria.size() -1].value = IncProj.ProjectManager__c;
				}else{
					searchCriteria[searchCriteria.size() -1].value = '';
		   		}
			} */

			if((searchCriteria[searchCriteria.size() -1].value != null && searchCriteria[searchCriteria.size() -1].value !='') ||
				searchCriteria[searchCriteria.size() -1].IncProj.ProjectManager__c != null){
			  	if(searchCriteria.size() <4){
			  		ocriteriaRow = new criteriaRow(searchCriteria[searchCriteria.size() -1]);
					searchCriteria.add(oCriteriaRow);
				}
			}
		}else{
			ocriteriaRow = new criteriaRow(null);
			searchCriteria.add(ocriteriaRow);
		}

		return null;
	}

	public PageReference removeRow(){
		if(searchCriteria != null && searchCriteria.size() == 1){
			return null;
		}
		Integer iCurrentRow = 0;
		Integer rowToRemove = 0;
		criteriaRow removalrow;
		for(criteriaRow CR: searchCriteria){
			if(CR.Row == removeRow){
				rowToRemove = iCurrentRow;
				removalrow = CR;
			}else{
				if(CR.Row > removeRow){
					CR.Row = CR.Row - 1;
				}
			}
			iCurrentRow ++;
		}
		searchCriteria.remove(rowToRemove);

		return null;
	}

	public PageReference search(){
		if(validateCriteria()){
			String sQuery = buildQuery();
			System.Debug(logginglevel.error,'sQuery: ' + sQuery + ' ' + sProjectManager);
			if(sQuery != null && sQuery.length() > 0){
				lResults = Database.query(sQuery);
			}
			if(lResults.size() > 200){
				apexPages.addMessage(new apexPages.message(apexPages.Severity.Info,'Your search returned more that 200 results.  Only the first 200 are displayed.'));
			}
			if(lResults == null || lResults.size() == 0){
				apexPages.addMessage(new apexPages.message(apexPages.Severity.Info,'Your search returned no results.'));
			}
			System.Debug(logginglevel.error,'lResults: ' + lResults);
		}else{
			apexPages.addMessage(new apexPages.message(apexPages.Severity.Error,'Please review your criteria for duplicates or missing values'));
		}
		return null;
	}

	public boolean validateCriteria(){
		set<String> sCompare = new set<String>();
		boolean bReturn = true;
		for(criteriaRow CR: searchCriteria){
			if(sCompare != null && sCompare.contains(CR.criteria)){
				bReturn = false;
				break;
			}else{
				sCompare.add(Cr.criteria);
			}
			System.Debug(logginglevel.error,'CR: ' + CR);
			if((Cr.value == null || CR.value =='') &&
			   CR.IncProj.ProjectManager__c == null){
				bReturn = false;
				break;
			}

		}

		return bReturn;
	}
/*
    Project Numberx
    Project Namex
    Project Managerx
    Customer Namex
    Aggregated Number
    Aggregated Projects
    Approved NSR Budgetx
    Owner
    Enrollment Statusx
*/

	private String buildQuery(){
		String sQuery = 'Select ID' + 
								+',EnrollmentPlan__c'
								+',EnrollmentStatus__c'
								+',Name'
								+',ProjectID__c'
								+',ProjectManager__c'
								+',CustomerName__c'
								+',ApprovedNSRBudget__c'
								+',OwnerID'
								+' From IncentiveProject__c'
								+' Where ';
		Integer i = 0;
		System.Debug(logginglevel.error,'searchCriteria ' + searchCriteria.size());
		for(criteriaRow CR: searchCriteria){
			boolean blank = false;
			i ++;
			if(CR.criteria == 'PM'){
			 	sProjectManager = cr.Value;
				if(cr.Value == null || cr.Value == ''){
						sProjectManager = Cr.IncProj.ProjectManager__c;
				}
				if(sProjectManager != null || sProjectManager == ''){
					sQuery += 'ProjectManager__c =: sProjectManager';
				}else{
					blank = true;
				}
				
			}
			if(CR.criteria == 'PN')
			{
				if(cr.Value != null && cr.Value != ''){
					sProjectName = '%'+ CR.value + '%';
					sQuery += 'Name LIKE : sProjectName';
				}else{
					blank = true;
				}
			}
			if(CR.criteria == 'CN'){
				if(cr.Value != null && cr.Value != ''){
					sCustomerName = '%'+ CR.Value + '%';
					System.Debug(logginglevel.error,'sCustomerName ' + sCustomerName);
					sQuery += 'CustomerName__c LIKE : sCustomerName';
				}else{
					blank = true;
				}
			}
			if(CR.criteria== 'PNUM'){
				if(cr.Value != null && cr.Value != ''){
					sProjectNumber = CR.Value;
					sQuery += 'ProjectID__c =: sProjectNumber';
				}else{
					blank = true;
				}
			}

			if(i < searchCriteria.size() && !blank){
				sQuery += ' AND ';
			}
		}
		sQuery += ' limit 201';
		return sQuery;
	}

	public boolean isNull(String s){
		boolean bReturn = false;
		if(s == null || s == ''){bReturn = true;}
		return bReturn; 
	}

	public class criteriaRow{
		public Integer row{get;set;}
		public string criteria{get;set;}
		public string value{get;set;}
		public list<SelectOption> criteriaRowlist {get;set;}
		public IncentiveProject__c IncProj{get;set;}
	
		public criteriaRow(criteriaRow previousRow){

			if(previousRow != null){
				System.Debug(logginglevel.error,'Row: ' + previousRow.Row);
				row = previousRow.row + 1;
			}else{
				row = 1;
			}
			IncProj = new IncentiveProject__c();
			criteriaRowlist = new list<SelectOption>();
			buildSelectOptions(previousRow);


		}
	
		private void buildSelectOptions(criteriaRow previousRow){
				criteriaRowList.add(new SelectOption('',''));
				criteriaRowlist.add(new SelectOption('PM','Project Manager'));
				criteriaRowlist.add(new SelectOption('PN','Project Name'));
				criteriaRowlist.add(new SelectOption('PNUM','Project Number'));
				criteriaRowlist.add(new SelectOption('CN','Customer Name'));
		}

	}

}