src/objects/EnrollmentPlan__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW Enrollment Plans under review by Approvers</description>
    <fields>
        <fullName>Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Enrollment_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Enrollment_Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approver 3 will be required only when the project contains an exception to current plan guidelines.  These exceptions will be acknowledged prior to submittal.</description>
        <inlineHelpText>Approver 3 will be required only when the project contains an exception to current plan guidelines.  These exceptions will be acknowledged prior to submittal.</inlineHelpText>
        <label>Approver 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Enrollment_Applications2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending PM Action</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 1 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 2 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 3 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending DTW Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected for Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unenrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Corp Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - No Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt-Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IncentiveProject__c</fullName>
        <label>Project Name</label>
        <referenceTo>IncentiveProject__c</referenceTo>
        <relationshipLabel>Enrollment Applications</relationshipLabel>
        <relationshipName>Enrollment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OrgCarryingOutProject__c</fullName>
        <formula>IncentiveProject__r.OrgCarryingOutProject__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Owning Department</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>IncentiveProject__r.RegionDescription__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <label>Enrollment Application</label>
    <nameField>
        <label>Enrollment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IncentiveProject__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW eligible projects to be considered for enrollment in DTW Incentive Plans</description>
    <fields>
        <fullName>BusinessLineDescription__c</fullName>
        <label>Business Line</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTWAdminInitiated__c</fullName>
        <description>Date DTW Admin validated Incentive Project and initiated the Enrollment Process.</description>
        <inlineHelpText>Date DTW Admin validated Incentive Project and initiated the Enrollment Process.</inlineHelpText>
        <label>DTW Admin Initiated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DistrictDescription__c</fullName>
        <label>District Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnrollmentApprover1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enrollment Approver1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Incentive_Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enrollment Application</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Incentive Projects</relationshipLabel>
        <relationshipName>IncentiveProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <formula>IF( PaymentRequest__c &lt;&gt; &quot;&quot;,  Text(PaymentRequest__r.EnrollmentStatus__c),

IF(
    AND(
       (EnrollmentPlan__c=&quot;&quot;), 
        OR(
           TEXT(FPPOverallEligibility__c)=&quot;Yes&quot;,
           TEXT(TMPlanOverallEligibility__c)=&quot;Yes&quot;
           )
         ),
&quot;Pending DTW Action&quot;, 
IF(
   (EnrollmentPlan__c=&quot;&quot;), &quot;Not Eligible&quot;,
   TEXT(EnrollmentPlan__r.EnrollmentStatus__c)
   )
   )
)</formula>
        <label>Enrollment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GeographyDescription__c</fullName>
        <label>Geography</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgCarryingOutProject__c</fullName>
        <label>Project Owning Department</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationString__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization String</label>
        <referenceTo>OrganizationString__c</referenceTo>
        <relationshipLabel>Incentive Projects</relationshipLabel>
        <relationshipName>Incentive_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Incentive_Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RegionDescription__c</fullName>
        <label>Sub-Region or Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Incentive Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OrganizationString__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLineName__c</fullName>
        <label>Business Line Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GeographyName__c</fullName>
        <label>Geography Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <externalId>true</externalId>
        <label>Organization Name</label>
        <length>240</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Organization String</label>
    <nameField>
        <label>Organization String Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization String</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RoutingMember__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>&quot;...how we would want to be able to program DTW administrator assignments based on certain attributes of the organization string of a project&quot;</description>
    <fields>
        <fullName>Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RoutingMembers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RoutingMembers2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RoutingMembers3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BusinessLineDescription__c</fullName>
        <label>Business Line</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DistrictDescription__c</fullName>
        <label>District</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GeographyDescription__c</fullName>
        <label>Geography</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>GlobalDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This marks one record as the global default for DTW Admin in case of invalid data.</description>
        <label>Global Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RegionDescription__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Routing Member</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>RoutingMember</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RoutingMembers</pluralLabel>
    <recordTypes>
        <fullName>Approver1</fullName>
        <active>true</active>
        <label>Approver 1</label>
    </recordTypes>
    <recordTypes>
        <fullName>Approver2</fullName>
        <active>true</active>
        <label>Approver 2</label>
    </recordTypes>
    <recordTypes>
        <fullName>Approver3</fullName>
        <active>true</active>
        <label>Approver 3</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <inlineHelpText>District name</inlineHelpText>
        <label>District</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <inlineHelpText>Region name</inlineHelpText>
        <label>Region</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/INC_ProjectCreateEnrollment_Test.cls
@isTest
private class INC_ProjectCreateEnrollment_Test
{
	
	@isTest
	static void testDTWAdminEnrollment()
	{
		/*
		To Do:  
		      1. Create Running User to insert Incentive project for
		      2. Create User to assign as PM
		      3. Create Incentive Project as running user
		      4. Assign PM User and PM
		      5. Call webservice to create Enrollment
		*/

		/*
		To do for changes:
			  1. Create Users for Approvers 1,2,3
			  2. Create Org String(s)
			  3. Create Routing Members
			  	 1. Routing Member that matches Org String
			  	 2. Routing Member that doesn't match Org String
			  4. Validate that created Enrollment App as correct Approvers
			  5. Validate that updated Incentive Project has correct Approver attached
		*/
	
		list<User> lusers = new list<User>();
		User Approver1 = INC_Utils_Testing.createTestUser('Standard User');
		User Approver2 = INC_Utils_Testing.createTestUser('Standard User');
		User Approver3 = INC_Utils_Testing.createTestUser('Standard User');
		User DTWAdminWater = INC_Utils_Testing.createTestUser('Standard User');

		lUsers.add(DTWAdminWater);
		lUsers.add(Approver1);
		lUsers.add(Approver2);
		lUsers.add(Approver3);
		insert lUsers;

		list<OrganizationString__c> lOrgStrings = new list<OrganizationString__c>();
		lOrgStrings = INC_Utils_Testing.createOrganizationString();
		insert lOrgStrings;
		
		OrganizationString__c Org1;
		OrganizationString__c Org2;
		for(OrganizationString__c org: lOrgStrings){
			if(org.OrganizationName__c == 'Water Organization'){
				Org2 = org;
			}else{
				Org1 = org;
			}
		}
		
		//routing members
		list<RoutingMember__c> lRouting = new list<RoutingMember__c>();
		RoutingMember__c DefaultRout = INC_Utils_Testing.CreateRoutingMember(DTWAdminWater);
		DefaultRout.GeographyDescription__c = 'Water Geo';
		DefaultRout.GlobalDefault__c = true;
		lRouting.add(DefaultRout);
		RoutingMember__c DTWAdminActualWater = INC_Utils_Testing.CreateRoutingMember(DTWAdminWater);
		DTWAdminActualWater.GeographyDescription__c = Org2.GeographyName__c;
		DTWAdminActualWater.RegionDescription__c = Org2.Region__c;
		DTWAdminActualWater.BusinessLineDescription__c = Org2.BusinessLineName__c;
		DTWAdminActualWater.DistrictDescription__c = Org2.District__c;
		DTWAdminActualWater.Approver1__c = Approver1.id;
		DTWAdminActualWater.Approver2__c = Approver2.id;
		DTWAdminActualWater.Approver3__c = Approver3.id;
	
		lRouting.Add(DTWAdminActualWater);
	
		RoutingMember__c  TestingRouting = INC_Utils_Testing.createRoutingMember(Approver1);
		TestingRouting.GeographyDescription__c = Org1.GeographyName__c;
		TestingRouting.RegionDescription__c = Org1.Region__c;
		TestingRouting.BusinessLineDescription__c = Org1.BusinessLineName__c;
		TestingRouting.DistrictDescription__c = Org1.District__c;

		lRouting.add(TestingRouting);
		insert lRouting;

		User RunningUser = INC_Utils_Testing.createTestUser('System Administrator');
		User ProjectManager = INC_Utils_Testing.createTestUser('System Administrator');
		list<User> lUser = new list<User>();
		lUser.add(RunningUser);
		lUser.add(ProjectManager);
		insert lUser;

		Test.StartTest();
		System.runAs(RunningUser){
				IncentiveProject__c oIncentiveProject = INC_Utils_Testing.createIncentiveProject();
				oIncentiveProject.GeographyDescription__c = DTWAdminActualWater.GeographyDescription__c;
				oIncentiveProject.RegionDescription__c = DTWAdminActualWater.RegionDescription__c;
				oIncentiveProject.BusinessLineDescription__c = DTWAdminActualWater.BusinessLineDescription__c;
				oIncentiveProject.DistrictDescription__c = DTWAdminActualWater.DistrictDescription__c;

				oIncentiveProject.ProjectManager__c = ProjectManager.ID;
				oIncentiveProject.OrgCarryingOutProject__c = Org2.Name;
				insert oIncentiveProject;
				INC_IncentiveProjectCreateEnrollment.createEnrollmentForm(oIncentiveProject.ID);
				
				 //covering the approver 1 code since it's not used in production yet
		  		INC_Service_Matching IncMatch = new INC_Service_Matching();
		  		Map<id,INC_Service_Matching.RoutingMember_Wrapper> mapReturn = IncMatch.findApprover1(new List<IncentiveProject__c>{oIncentiveProject});
		

				RoutingMember__c DTWAdminActualWater2 = INC_Utils_Testing.CreateRoutingMember(DTWAdminWater);
				DTWAdminActualWater2.GeographyDescription__c = Org2.GeographyName__c;
				DTWAdminActualWater2.RegionDescription__c = Org2.Region__c;
				DTWAdminActualWater2.BusinessLineDescription__c = Org2.BusinessLineName__c;
				DTWAdminActualWater2.Approver1__c = Approver1.id;
				DTWAdminActualWater2.Approver2__c = Approver2.id;
				DTWAdminActualWater2.Approver3__c = Approver3.id;
				insert DTWAdminActualWater2;

				IncentiveProject__c oIncentiveProject2 = INC_Utils_Testing.createIncentiveProject();
				oIncentiveProject2.ProjectManager__c = ProjectManager.ID;
				oIncentiveProject2.OrgCarryingOutProject__c = Org2.Name;
				oIncentiveProject2.GeographyDescription__c = DTWAdminActualWater.GeographyDescription__c;
				oIncentiveProject2.RegionDescription__c = DTWAdminActualWater.RegionDescription__c;
				oIncentiveProject2.BusinessLineDescription__c = DTWAdminActualWater.BusinessLineDescription__c;
				oIncentiveProject2.DistrictDescription__c = DTWAdminActualWater.DistrictDescription__c;
				
				insert oIncentiveProject2;
				INC_IncentiveProjectCreateEnrollment.createEnrollmentForm(oIncentiveProject2.ID);
				
				 //covering the approver 1 code since it's not used in production yet
		  		mapReturn = IncMatch.findApprover1(new List<IncentiveProject__c>{oIncentiveProject});
				
				oIncentiveProject2.OrgCarryingOutProject__c = null;
				update oIncentiveProject2;
				INC_IncentiveProjectCreateEnrollment.createEnrollmentForm(oIncentiveProject2.ID);

			}
			
		Test.StopTest();

		map<id,IncentiveProject__c> mapIncentives = new map<id,IncentiveProject__c>();
		For(IncentiveProject__c inp: [Select ID
											   , Name
											   , OwnerID
											   , DTWAdminInitiated__c
											   , EnrollmentApprover1__c
											   , GeographyDescription__c
											   , DistrictDescription__c
											   , BusinessLineDescription__c
											   , RegionDescription__c
											    from IncentiveProject__c]){
			System.assert(inp.OwnerID == ProjectManager.ID,'Owner Should be project Manager! Owner: ' +inp.OwnerID + ' PM: ' + ProjectManager.ID);
			Date d = System.Today();
			System.assert(inp.DTWAdminInitiated__c == d, 'DTWAdminInitiated__c should be today: ' + inp.DTWAdminInitiated__c + ' d: ' + d);
			System.assert(inp.EnrollmentApprover1__c == Approver1.id, 'Incentive Project should be ' + Approver1.id + ' not: ' + inp.EnrollmentApprover1__c);
			mapIncentives.put(inp.id,inp);
		}
		System.Debug(logginglevel.error,'mapIncentives ' + mapIncentives);
		Integer iCnt = 0;
		For(EnrollmentPlan__c ep: [Select ID
											, Name
											, EnrollmentStatus__c
											, IncentiveProject__c 
											, Approver1__c
											, Approver2__c
											, Approver3__c
											from EnrollmentPlan__c where IncentiveProject__c =: mapIncentives.Keyset()]){
			iCnt ++;
			String sIncName = mapIncentives.get(ep.IncentiveProject__c).Name;
			String sEpName = ep.Name;
			sIncName = 'ENR: ' + sIncName;
			System.assert(sIncName == sEpName,'Names not equal');
			System.assert(ep.EnrollmentStatus__c == 'Pending PM Action', 'Status should be Pending PM Action not: ' + ep.EnrollmentStatus__c);
			System.Assert(ep.Approver1__c == Approver1.id,' Enrollment Approver 1 shoud be : '+ Approver1.id + ' not: ' + ep.Approver1__c);
			System.Assert(ep.Approver2__c == Approver2.id,' Enrollment Approver 2 shoud be : '+ Approver2.id + ' not: ' + ep.Approver2__c);
			System.Assert(ep.Approver3__c == Approver3.id,' Enrollment Approver 3 shoud be : '+ Approver3.id + ' not: ' + ep.Approver3__c);

		}
		System.assert(icnt == 3,'There should only be 3 enrollment plans: ' + iCnt);

	}
	
}