src/objects/Enrollment_Comments__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <fields>
        <fullName>ApplicationType__c</fullName>
        <label>Application Type</label>
        <picklist>
            <picklistValues>
                <fullName>FP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T&amp;M</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EnrollmentApplication__c</fullName>
        <label>Enrollment Application</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Enrollment Comments</relationshipLabel>
        <relationshipName>Enrollment_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Comment Type</label>
        <picklist>
            <controllingField>IsRejection__c</controllingField>
            <picklistValues>
                <fullName>General</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Exception</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejection for Corrections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interim Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Enrollment Comment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>EC-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EnrollmentParticipant__c.object
<CustomObject>
    <fields>
        <fullName>EmployeeName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>PSA Resource, AECOM Employee</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Salesforce_User__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollment Participants</relationshipLabel>
        <relationshipName>Enrollment_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentPlan__c</fullName>
        <label>Enrollment Plan</label>
        <referenceTo>EnrollmentPlan__c</referenceTo>
        <relationshipLabel>Enrollment Participants</relationshipLabel>
        <relationshipName>EnrollmentParticipants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExistedAtEnrollment__c</fullName>
        <label>ExistedAtEnrollment</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ParticipantCategory__c</fullName>
        <label>Participant Category</label>
        <picklist>
            <picklistValues>
                <fullName>Client Account Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deputy Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Leader</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ParticipantType__c</fullName>
        <label>Participant Type</label>
        <picklist>
            <picklistValues>
                <fullName>Incentive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discretionary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TargetIncentivePoolAllocated__c</fullName>
        <inlineHelpText>Target % Incentive Pool Allocated</inlineHelpText>
        <label>Target %</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Enrollment Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EnrollmentPlan__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW Enrollment Plans under review by Approvers</description>
    <fields>
        <fullName>ApplicationType__c</fullName>
        <inlineHelpText>ENR: Initial Application
CCR: Combined Request for both Participant and Metrics Changes
MOD: Modeling Application that allows performance projections
PAY: Payment Request Application, the final stage in an active app lifecycle</inlineHelpText>
        <label>Form Type</label>
        <picklist>
            <picklistValues>
                <fullName>ENR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>CCR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ContractType__c</fullName>
        <description>Displays the contract type as per AECOM Insight.  For Oracle projects, this will reflect the Oracle contract type.  DTW data is updated weekly by Insight.</description>
        <formula>IncentiveProject__r.ContractType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the contract type as per AECOM Insight.  For Oracle projects, this will reflect the Oracle contract type.  DTW data is updated weekly by Insight.</inlineHelpText>
        <label>Contract Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending PM Action</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 1 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 2 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approver 3 Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending DTW Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected for Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unenrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Corp Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - No Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt-Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EstimatedPoolBaseline10__c</fullName>
        <formula>MAX(
 IF( (BaselineGrossMargin__c * 0.10) * (IncentivePlan__r.ProfitSharingPercent__c) &gt; IncentivePlan__r.MaxPoolCap__c, IncentivePlan__r.MaxPoolCap__c,
(BaselineGrossMargin__c * 0.10) * (IncentivePlan__r.ProfitSharingPercent__c)),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Used as a reference point only, for modeling T&amp;M plan applications.  It is a valuation of the incentive pool that would be available to participants if they were able to grow the project&apos;s baseline margin $ by 10%.</inlineHelpText>
        <label>Sample Pool @ Baseline + 10%</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EstimatedPoolBaseline__c</fullName>
        <description>Used as a reference point only, for modeling Fixed Price plan applications.  It is a valuation of the incentive pool that would be available to participants if they were able to increase the project&apos;s baseline margin % by 3%.</description>
        <formula>MaxIncentivePool__c /2</formula>
        <inlineHelpText>The sample pool reflects the calculated incentive pool assuming final GM% is 3% above baseline, all operational metrics are achieved and there are no changes to current project scope.</inlineHelpText>
        <label>Sample Pool if Baseline +3%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IncentivePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incentive Plan</label>
        <referenceTo>IncentivePlanTemplate__c</referenceTo>
        <relationshipName>Enrollment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MinParticipantPayout__c</fullName>
        <formula>IncentivePlan__r.MinAllocationAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Minimum Amount of Participant Award at Sample Pool</inlineHelpText>
        <label>Min Participant Payout $</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Enrollment Application</label>
    <nameField>
        <label>Enrollment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Applications</pluralLabel>
    <recordTypes>
        <fullName>Enrolled</fullName>
        <active>true</active>
        <label>Enrolled</label>
    </recordTypes>
    <recordTypes>
        <fullName>Exception</fullName>
        <active>true</active>
        <label>Exception</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IncentivePlanTemplate__c.object
<CustomObject>
    <fields>
        <fullName>ContractType__c</fullName>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time &amp; Material</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Incentive Plan Template</label>
    <nameField>
        <label>Incentive Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Plan Template</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/INC_EnrollmentParticipantEntryController.cls
public with sharing class INC_EnrollmentParticipantEntryController {

	public EnrollmentPlan__c oEnrollmentPlan {get;set;}
    public ID enrollID {get;set;}
    public list<EnrollmentParticipant__c> listParticipant {get;set;}
    public list<EnrollmentParticipant__c> listParticipantDelete {get;set;}
    public String partComments {get;set;}
    public Boolean editParticipants {get;set;}
    public Boolean bChangeRequest{get;set;}
    public String fromWizard{get;set;}
    public Boolean bPaidAndEnrolled{get;set;}
    public Boolean bPaid{get;set;}
    public Boolean bTMorFixed{get;set;}
    public Boolean bFixed{get;set;}
    public Boolean bTM{get;set;}
    public Boolean bEnableCCR{get;set;}

    public integer rowNumber {get;set;}

    public INC_EnrollmentParticipantEntryController(){

        bFixed = false;
        bTM = false;

        enrollID = ApexPages.CurrentPage().getParameters().get('id');
        oEnrollmentPlan = INC_Service_EnrollmentPlan.getEnrollmentPlan(new set<id>{enrollID})[0];
        setUpPage();

        bEnableCCR = false;
        if(oEnrollmentPlan.ApplicationType__c == 'CCR'){
            bEnableCCR = true;
        }

        if(oEnrollmentPlan.ContractType__c == 'AMPS - Fixed Price'  || 
            oEnrollmentPlan.ContractType__c == 'CPFF - Hard Bid' || 
            oEnrollmentPlan.ContractType__c == 'CPFF - Negotiated' || 
            oEnrollmentPlan.ContractType__c == 'Unassigned'
            ){
            bTMorFixed = false;
        } else {
            bTMorFixed = true;

            if(oEnrollmentPlan.IncentivePlan__r.ContractType__c == 'Fixed Price'){
                bFixed = true;
            } else if (oEnrollmentPlan.IncentivePlan__r.ContractType__c == 'Time & Material'){
                bTM = true;
            }            
        }

        
    }

    public INC_EnrollmentParticipantEntryController(ApexPages.StandardController stdController) {
        System.Debug(logginglevel.error,'Start Controller ' + System.Now());
        oEnrollmentPlan = (EnrollmentPlan__c)stdController.getRecord();
        oEnrollmentPlan = INC_Service_EnrollmentPlan.getEnrollmentPlan(new set<id>{oEnrollmentPlan.id})[0];
        setUpPage();
    }

    private void setUpPage(){
        editParticipants = true;
        if(oEnrollmentPlan.EnrollmentStatus__c == 'Enrolled' ||
           oEnrollmentPlan.EnrollmentStatus__c == 'Archived'){
            editParticipants = false;
        }
        if(oEnrollmentPlan.Name.StartsWith('CCR')){
            bChangeRequest = true;
           // editParticipants = false;
        }else{
            bChangeRequest = false;
        }
        System.Debug(logginglevel.error,'Start loadExistingParticipants ' + System.Now());
        loadExistingParticipants();
        System.Debug(logginglevel.error,'Start addblankRows ' + System.Now());
        addblankRows();
        System.Debug(logginglevel.error,'End Controller ' + System.Now());

        if(oEnrollmentPlan.ApplicationType__c == 'PAY'){
            bPaid = true;
            if(oEnrollmentPlan.EnrollmentStatus__c == 'Enrolled'){
                bPaidAndEnrolled = true;
            } else {
                bPaidAndEnrolled = false;
            }
        } else {
            bPaid = false;
        }

        listParticipantDelete = new list<EnrollmentParticipant__c>();
    }

    private void addblankRows(){
    	Integer iSize = 0;

        if(oEnrollmentPlan.ApplicationType__c == 'PAY'){
            if(listParticipant != null && listParticipant.size() > 0){
                iSize = listParticipant.size();
            }else{
                listParticipant = new list<EnrollmentParticipant__c>();
            }

            //listParticipant.add(new EnrollmentParticipant__c(EnrollmentPlan__c = oEnrollmentPlan.ID, ParticipantType__c = 'Discretionary'));
            /*if(iSize > = 5){
                listParticipant.add(new EnrollmentParticipant__c(EnrollmentPlan__c = oEnrollmentPlan.ID, ParticipantType__c = 'Discretionary'));
            }else{
                for(Integer i = iSize; i<5; i++){
                    listParticipant.add(new EnrollmentParticipant__c(EnrollmentPlan__c = oEnrollmentPlan.ID, ParticipantType__c = 'Discretionary'));
                }
            }         */   
        }

        else if (oEnrollmentPlan.EnrollmentStatus__c != 'Enrolled'){
            if(listParticipant != null && listParticipant.size() > 0){
                iSize = listParticipant.size();
            }else{
                listParticipant = new list<EnrollmentParticipant__c>();
            }
        	if(iSize > = 5){
                if(oEnrollmentPlan.ApplicationType__c != 'CCR'){
        		  listParticipant.add(new EnrollmentParticipant__c(EnrollmentPlan__c = oEnrollmentPlan.ID));
                }else{
                    listParticipant.add(new EnrollmentParticipant__c(EnrollmentPlan__c = oEnrollmentPlan.ID,ExistedAtEnrollment__c = 'No'));
                }
        	}else{
        		for(Integer i = iSize; i<5; i++){
        			if(oEnrollmentPlan.ApplicationType__c != 'CCR'){
                        listParticipant.add(new EnrollmentParticipant__c(EnrollmentPlan__c = oEnrollmentPlan.ID));
                    }else{
                        listParticipant.add(new EnrollmentParticipant__c(EnrollmentPlan__c = oEnrollmentPlan.ID,ExistedAtEnrollment__c = 'No'));
                    }
        		}
        	}
        } 
    }

    private void loadExistingParticipants(){
        System.Debug(logginglevel.error,'Particpants load: ' + oEnrollmentPlan.ID);
        map<id,List<EnrollmentParticipant__c>> mapEnrollmentParticipants = INC_Service_EnrollmentPlan.getPlanParticipants(new set<id>{oEnrollmentPlan.id});
        System.Debug(logginglevel.error,'parts: ' + mapEnrollmentParticipants);
        listParticipant = mapEnrollmentParticipants.get(oEnrollmentPlan.Id);
    }

    public void addBlankRow(){
        System.Debug(logginglevel.error,'listParticipant.size '+ listParticipant.size());
        //if(listParticipant[listParticipant.size()-1].EmployeeName__c != null){
         if(oEnrollmentPlan.ApplicationType__c == 'PAY'){
            listParticipant.add(new EnrollmentParticipant__c(EnrollmentPlan__c = oEnrollmentPlan.ID, ParticipantType__c = 'Discretionary',ExistedAtEnrollment__c='No'));
         }
         else if(oEnrollmentPlan.ApplicationType__c == 'CCR'){
              listParticipant.add(new EnrollmentParticipant__c(EnrollmentPlan__c = oEnrollmentPlan.ID, ExistedAtEnrollment__c='No'));
            } else if (oEnrollmentPlan.EnrollmentStatus__c != 'Enrolled'){
            listParticipant.add(new EnrollmentParticipant__c(EnrollmentPlan__c = oEnrollmentPlan.ID));
         }
         
        //}
        System.Debug(logginglevel.error,'listParticipant.size after'+ listParticipant.size());
    }

    public void addParticipant(){
        listParticipant.add(new EnrollmentParticipant__c(EnrollmentPlan__c = oEnrollmentPlan.ID));
    }

    public pageReference Cancel(){
        return getReturnPage();
    }

    public pageReference SaveAndContinue(){


        if(!save()){
            return null;
        }
        

        if(partComments != null && partComments.length() > 0){
                createEnrollmentComments();
        }
          
        return getReturnPage();
    }

    public pageReference SaveandRecalc(){

        save();

        return null;
    }

    public boolean save(){
        list<EnrollmentParticipant__c> lSave = prepareForSave();

        if(!validate(lSave)){
            return false;
        }

        System.savePoint sp = Database.setSavePoint();
        try{
            upsert lSave;

            if(listParticipantDelete.size() > 0){
                delete listParticipantDelete;
                listParticipantDelete = new list<EnrollmentParticipant__c>();
            }


            loadExistingParticipants();
            addblankRows();
            oEnrollmentPlan = INC_Service_EnrollmentPlan.getEnrollmentPlan(new set<id>{enrollID})[0];
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm,'Save Successful.'));
        }catch(Exception e){
            system.debug('Handling Exception:  '+e.getMessage());
            Database.rollBack(sp);
            ApexPages.addMessages(e);
            return false;
        }

        return true;
    }

    private void createEnrollmentComments(){
       Enrollment_Comments__c comment = new Enrollment_Comments__c(EnrollmentApplication__c = oEnrollmentPlan.ID);
       comment.comments__c = partComments;
       comment.Type__c = 'Participant';
        System.savePoint sp = Database.setSavePoint();
        try{
            insert comment;
        }catch(Exception e){
            system.debug('Handling Exception:  '+e.getMessage());
            Database.rollBack(sp);
            ApexPages.addMessages(e);
        }
    }

    private boolean validate(list<EnrollmentParticipant__c>lSave){

        decimal pool = null;
        if(bTM){
            pool = oEnrollmentPlan.EstimatedPoolBaseline10__c;
        }
        if(bFixed){
            pool = oEnrollmentPlan.EstimatedPoolBaseline__c;
        }


        for(EnrollmentParticipant__c oEnrollmentParticipant: lSave){
            if(oEnrollmentParticipant.ParticipantCategory__c == null){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'All Participants must have a defined role.'));
                return false;
            }
            if((oEnrollmentParticipant.TargetIncentivePoolAllocated__c == null || oEnrollmentParticipant.TargetIncentivePoolAllocated__c <= 0) && (oEnrollmentParticipant.ParticipantType__c != 'Discretionary' && oEnrollmentPlan.ApplicationType__c == 'ENR')){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'All Participants must have an allocation greater than 0'));
                return false;
            }

            if(bTM || bFixed){
                if(oEnrollmentPlan.ApplicationType__c != 'Pay'){
                    if((((oEnrollmentParticipant.TargetIncentivePoolAllocated__c * pool/100) < oEnrollmentPlan.MinParticipantPayout__c)) && oEnrollmentPlan.ApplicationType__c == 'ENR'){
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'All Participants estimated payout must be >= $' + oEnrollmentPlan.MinParticipantPayout__c + ', Currently: $' + oEnrollmentParticipant.TargetIncentivePoolAllocated__c * pool/100));
                        return false;
                    }
                }
            }

            if(oEnrollmentParticipant.EmployeeName__c == null){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'All Participants must have an employee name'));
                return false;
            }

        }

        return true;
    }

    /*private String validateCode(list<EnrollmentParticipant__c>lSave){

        String sReturnMessage = '';
        boolean binValidPercent = False;
        boolean bMissingPercent = False;
        Double iPercent = 0;
        for(EnrollmentParticipant__c oEnrollmentParticipant: lSave){
            if(oEnrollmentParticipant.TargetIncentivePoolAllocated__c == null || oEnrollmentParticipant.TargetIncentivePoolAllocated__c == 0){
                bMissingPercent = true;
            }else{
                if(!bMissingPercent){
                    iPercent += oEnrollmentParticipant.TargetIncentivePoolAllocated__c;
                }
            } 
        }
        if(!bMissingPercent){
            if(iPercent > 100){
                binValidPercent = true;
            }
        }

        if(!bMissingPercent){
            sReturnMessage = 'One or more lines is missing Target %.';
        }else{
            if(binValidPercent){
                sReturnMessage = 'Total Target % is greater than 100.';
            }
        }

        return sReturnMessage;
    }*/

    public PageReference RemoveEP(){
        EnrollmentParticipant__c ep = listParticipant[rowNumber-1];

        if(ep.id != null){
            listParticipantDelete.add(ep);
        }

        listParticipant.remove(rowNumber-1);

        return null;

    }

    private pageReference getReturnPage(){
        PageReference Enroll = new pageReference('/apex/INC_EnrollmentApp?id=' + oEnrollmentPlan.id);
        Enroll.setRedirect(true);
        return Enroll;
    }

    private list<EnrollmentParticipant__c> prepareForSave(){
        list<EnrollmentParticipant__c> lReturn = new list<EnrollmentParticipant__c>();
        for(EnrollmentParticipant__c oPart: listParticipant){
            System.Debug(logginglevel.error,'Enrollment plan: ' + oPart.EnrollmentPlan__c);
            System.Debug(logginglevel.error,'EmployeeName__c: ' + oPart.EmployeeName__c);
            if(oPart.EmployeeName__c != null){
                oPart.CurrencyIsoCode = oEnrollmentPlan.CurrencyIsoCode;
                lReturn.add(oPart);
            }
        }

        return lReturn;
    } 
    
}