src/objects/ExpendItem__c.object
<CustomObject>
    <fields>
        <fullName>ExpenditureDateFiscalMonth__c</fullName>
        <label>Expenditure Date Fiscal Month</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExpenditureDatePreviousFiscalMonth__c</fullName>
        <label>Expenditure Date Previous Fiscal Month</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExpenditureItemDate__c</fullName>
        <label>Expenditure Item Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpenditureResourceType__c</fullName>
        <label>Expenditure Resource Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExpenditureTypeCategory__c</fullName>
        <label>Expenditure Type Category</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExpenditureType__c</fullName>
        <label>Expenditure Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PLReportCategory__c</fullName>
        <label>P&amp;L Report Category</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Expenditure Item</label>
    <nameField>
        <displayFormat>Exp-{0}</displayFormat>
        <label>Expenditure Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenditure Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ExpenditureType__c.object
<CustomObject>
    <fields>
        <fullName>ExpenditureCategory__c</fullName>
        <label>Expenditure Category</label>
        <picklist>
            <picklistValues>
                <fullName>Subcontractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Related Expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fringe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actual Fringe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acutal Fringe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overhead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Reserves</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Centre Allocations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subconsultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Usages</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PLReportCategory__c</fullName>
        <label>P&amp;L Report Category</label>
        <picklist>
            <picklistValues>
                <fullName>ODC - Exps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODC - Subs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODC - Contingency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fringe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overhead</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ResourceType__c</fullName>
        <label>Resource Type</label>
        <picklist>
            <picklistValues>
                <fullName>SUBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Expenditure Type</label>
    <nameField>
        <label>Expenditure Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenditure Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Time_Period__c.object
<CustomObject>
    <customHelpPage>pse__TimePeriodHelp</customHelpPage>
    <description>The divisions of time that your services organization is concerned with. Time periods have types such as Month (e.g. November 2014), Quarter (e.g. Q4 2014), Year (e.g. 2014), or Perpetual (‘All Time’). Time periods drive how actuals are categorized, how forecasting is done, how billing events are generated, and most other time-specific functions within FinancialForce PSA. Always create one perpetual time period with an end date well into the future.</description>
    <fields>
        <fullName>TimePeriodCode__c</fullName>
        <description>For months: FY2015-01 for the first fiscal month in fiscal 2015. For quarters: FY2015Q1 for the first quarter in fiscal 2015. For years: FY2015 for fiscal 2015.</description>
        <inlineHelpText>For months: FY2015-01 for the first fiscal month in fiscal 2015. For quarters: FY2015Q1 for the first quarter in fiscal 2015. For years: FY2015 for fiscal 2015.</inlineHelpText>
        <label>Time Period Code</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pse__End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>pse__Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>pse__Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perpetual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SemiMonthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Time Period</label>
    <nameField>
        <label>Time Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_ExpenditureItem_TriggerDispatcher.cls
/* 	When a record is saved AND the Expenditure Type value is changed (from null or another value), 
	take the Expenditure Type value, look it up in ExpenditureType.Name. Pick up the Group, Subgroup, 
	and Resource Type values and set them on the corresponding fields in the Expenditure Item object.
*/
public with sharing class ECO_ExpenditureItem_TriggerDispatcher
{
	public static void Main(List<ExpendItem__c> newList, Map<Id, ExpendItem__c> newMap, 
		List<ExpendItem__c> oldList, Map<Id, ExpendItem__c> oldMap, Boolean isBefore, Boolean isAfter, 
		Boolean isInsert, Boolean isUpdate, Boolean isDelete, Boolean isExecuting)
	{
		if (isBefore) {
			
			List<ExpendItem__c> expItemListToSave = new List<ExpendItem__c>();
			for (ExpendItem__c expItem : newList) {
				if (expItem.ExpenditureType__c != null) {
					if (isInsert) {
						System.debug('___isInsert: expItem='+expItem);
						expItemListToSave.add(expItem);
					}
					else if (isUpdate) {
	                    if (expItem.ExpenditureType__c != oldMap.get(expItem.id).ExpenditureType__c) {
	                    	System.debug('___isUpdate: expItem='+expItem);
							expItemListToSave.add(expItem);
	                    }
					}
				}
			}
			adjustExpenditureItems(expItemListToSave);
			
			if (!isDelete){
				calculateFiscalMonths(newList); 
			}
		} 
	}
		

	private static void adjustExpenditureItems(List<ExpendItem__c> expItemList) {
		System.debug('___START adjustExpenditureItems');
		if (expItemList != null && expItemList.size() > 0) {
			try {
				Set<String> expTypeSet = new Set<String>();
				for (ExpendItem__c expItem : expItemList) {
					expTypeSet.add(expItem.ExpenditureType__c);
				}
				System.debug('___expTypeSet='+expTypeSet);
				
				Map<String, ExpenditureType__c> expTypeMap = new Map<String, ExpenditureType__c>();
				List<ExpenditureType__c> expTypeList =
					[SELECT Name, ExpenditureCategory__c, PLReportCategory__c, ResourceType__c 
					 FROM ExpenditureType__c WHERE Name IN: expTypeSet];
				for (ExpenditureType__c et : expTypeList) {
					expTypeMap.put(et.Name, et);
				}
				System.debug('___expTypeMap='+expTypeMap);

				for (ExpendItem__c expItem : expItemList) {
					String expTypeName = expItem.ExpenditureType__c;
					ExpenditureType__c expType = (ExpenditureType__c) expTypeMap.get(expTypeName);
					System.debug('___expType='+expType);
					if (expType != null) {
						expItem.ExpenditureResourceType__c = expType.ResourceType__c;
						expItem.ExpenditureTypeCategory__c = expType.ExpenditureCategory__c;
						expItem.PLReportCategory__c = expType.PLReportCategory__c;
						System.debug('___Adjusted expItem='+expItem);
					}
				}
			}
			catch(Exception e) {
				System.debug(e.getStackTraceString());
			}
		}
		System.debug('___END adjustExpenditureItems');
	}
	
	private static void calculateFiscalMonths(list<ExpendItem__c> expendItems)
	{
		// Time period
		List<pse__Time_Period__c> timePeriods = [select Id, pse__Start_Date__c, pse__End_Date__c, TimePeriodCode__c 
													from pse__Time_Period__c 
													where pse__Type__c = 'Month'
													order by pse__End_Date__c asc];
		for (ExpendItem__c ei : expendItems){
			if (ei.ExpenditureItemDate__c != null){										
				for (Integer i = 0; i < timePeriods.size(); i++){
					if (ei.ExpenditureItemDate__c <= timePeriods[i].pse__End_Date__c  &&
						ei.ExpenditureItemDate__c >= timePeriods[i].pse__Start_Date__c){
						ei.ExpenditureDateFiscalMonth__c = timePeriods[i].TimePeriodCode__c;
						if (i > 0){
							ei.ExpenditureDatePreviousFiscalMonth__c = timePeriods[i-1].TimePeriodCode__c;
						}
					}
				}
			}
		}
	}
}