src/objects/ExpenditureType__c.object
<CustomObject>
    <label>Expenditure Type</label>
    <nameField>
        <label>Expenditure Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenditure Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/POHeader__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>POHeadersProject</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/POLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Line Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpenditureType__c</fullName>
        <label>Expenditure Type</label>
        <picklist>
            <picklistValues>
                <fullName>SUBC- IT Outside Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Architechtural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Audit Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Civil Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Director Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Drafting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Electrical Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Estimating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-IT Prof. Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Inter Project Manual Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Interco Receiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Interco Service Provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Interproject Service Prov</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Land Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Legal Fees - Allowable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Legal Fees - E&amp;O</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Legal Fees - Unallw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Major Trades</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Mechanical Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Outside Services - Allow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Outside Services - Unallw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Professional Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Purchased Labor - Fringe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Purchased Labor - OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Purchased Labor - Premium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Purchased Labor - Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Structural Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Subconsultant Accrual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBC-Subconsultant Exempt</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LineDescription__c</fullName>
        <label>Line Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LineNumber__c</fullName>
        <label>Line Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LineType__c</fullName>
        <label>Line Type</label>
        <picklist>
            <picklistValues>
                <fullName>Unit Rate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Fee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OracleSyncDatetime__c</fullName>
        <description>Timestamp when oracle sync attempt last occurred</description>
        <label>Oracle Sync Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>POHeader__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>POHeader__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>POLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>pse__Project_Task__c</referenceTo>
        <relationshipLabel>Purchase Order Line Items</relationshipLabel>
        <relationshipName>POLineItemsProjectTask</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PO Line Item</label>
    <nameField>
        <displayFormat>POLI-{0000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_PurchaseOrderLineItemControllerTest.cls
@isTest
private class ECO_PurchaseOrderLineItemControllerTest{

	private static final Integer numTestProjectTasks = 10;	
	private static final Integer numTeamMembers = 1;


	static testMethod void testCreateAndUpdatePurchaseOrderLineItem() {
		ECO_Utils_Testing.createTestDataForProjectSync(numTestProjectTasks, numTeamMembers);
		pse__Proj__c testProject = [SELECT Id, pse__Account__c FROM pse__Proj__c];

		POHeader__c poHeader = new POHeader__c();
		poHeader.Project__c = testProject.Id;
		insert poHeader;

		PageReference pageRef = new PageReference('/apex/ECO_PurchaseOrderLineItem');
		pageRef.getParameters().put('poHeaderId', poHeader.Id);
		pageRef.getParameters().put('projectId', testProject.Id);

		test.setCurrentPage(pageRef);

		ECO_PurchaseOrderLineItemController con = new ECO_PurchaseOrderLineItemController(new ApexPages.StandardController(new POLineItem__c()));

		system.assertEquals(10, con.projectTasks.size());

        con.currentPOLineItem.LineDescription__c = 'test';
        con.currentPOLineItem.ExpenditureType__c = 'SUBC-Land Survey';
		con.currentPOLineItem.LineType__c = 'Unit Rate';
    	con.currentPOLineItem.LineNumber__c = 1;
    	con.currentPOLineItem.Quantity__c = 1;
    	con.currentPOLineItem.UnitPrice__c = 99.99;
    	con.currentPOLineItem.ProjectTask__c = con.projectTasks.get(0).Id;
        con.currentPOLineItem_TaskId = String.valueOf(con.projectTasks.get(0).Id);

    	PageReference savePageRef = con.saveCurrentPOLineItem();

    	POLineItem__c savedPOLineItem = [SELECT Id, LineType__c, LineNumber__c, Quantity__c, UnitPrice__c, ProjectTask__c, Amount__c
    										FROM POLineItem__c
    										WHERE POHeader__c = :poHeader.Id];

    	system.assertEquals(savedPOLineItem.LineType__c, 'Unit Rate');
    	system.assertEquals(savedPOLineItem.LineNumber__c, 1);
    	system.assertEquals(savedPOLineItem.Quantity__c, 1);
    	system.assertEquals(savedPOLineItem.UnitPrice__c, 99.99);
    	system.assertEquals(savedPOLineItem.ProjectTask__c, con.projectTasks.get(0).Id);
    	system.assertEquals(savedPOLineItem.Amount__c, 99.99);

    	PageReference editPageRef = new PageReference('/apex/ECO_PurchaseOrderLineItem');
    	editPageRef.getParameters().put('id',savedPOLineItem.Id);
    	test.setCurrentPage(editPageRef);

    	ECO_PurchaseOrderLineItemController con2 = new ECO_PurchaseOrderLineItemController(new ApexPages.StandardController(savedPOLineItem));

    	con2.currentPOLineItem.Quantity__c = 2;
    	savePageRef = con2.saveCurrentPOLineItem();

    	savedPOLineItem = [SELECT Id, LineType__c, LineNumber__c, Quantity__c, UnitPrice__c, ProjectTask__c, Amount__c
    										FROM POLineItem__c
    										WHERE POHeader__c = :poHeader.Id];

    	system.assertEquals(2, savedPOLineItem.Quantity__c);

    	savedPOLineItem.OracleSyncDateTime__c = Date.today();
    	update savedPOLineItem;

    	//test change request

    	ECO_PurchaseOrderLineItemController con3 = new ECO_PurchaseOrderLineItemController(new ApexPages.StandardController(savedPOLineItem));
    	con3.currentPOLineItem.Quantity__c = 3;
    	savePageRef = con3.saveCurrentPOLineItem();

    	List<POLineItem__c> poLineItems = [SELECT Id FROM POLineItem__c WHERE POHeader__c = :poHeader.Id];
    	system.assertEquals(2, poLineItems.size());

    	savePageRef = con3.cancelPurchaseOrderLineItem();

    	savedPOLineItem.OracleSyncDateTime__c = null;
    	update savedPOLineItem;

    	savePageRef = con3.cancelPurchaseOrderLineItem();

    	PageReference backPageRef = con3.returnToPurchaseOrder();

    }

   static testMethod void testCreateNewControllerInstance() {
		ECO_Utils_Testing.createTestDataForProjectSync(numTestProjectTasks, numTeamMembers);
		pse__Proj__c testProject = [SELECT Id, pse__Account__c FROM pse__Proj__c];

		POHeader__c poHeader = new POHeader__c();
		poHeader.Project__c = testProject.Id;
		insert poHeader;

		PageReference pageRef = new PageReference('/apex/ECO_PurchaseOrderLineItem');
		pageRef.getParameters().put('poHeaderId', poHeader.Id);
		pageRef.getParameters().put('projectId', testProject.Id);

		test.setCurrentPage(pageRef);

		ECO_PurchaseOrderLineItemController con = new ECO_PurchaseOrderLineItemController();

	}

}