src/objects/ExportControl__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Export Controls</relationshipLabel>
        <relationshipName>ExportControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionnaireSet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questionnaire Set</label>
        <referenceTo>QuestionnaireSet__c</referenceTo>
        <relationshipLabel>Export Controls</relationshipLabel>
        <relationshipName>ExportControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Export Control</label>
    <nameField>
        <displayFormat>EC-{000000000}</displayFormat>
        <label>Export Control Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Export Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Site__r.Account__r.Name</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Primary_End__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary End</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipName>ProjectSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipName>ProjectSites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Site</label>
    <nameField>
        <displayFormat>ProjectSite-{0000000000}</displayFormat>
        <label>Project Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProjectCity__c.object
<CustomObject>
    <fields>
        <fullName>CityName__c</fullName>
        <label>City Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Cities</relationshipLabel>
        <relationshipName>ProjectCities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project City</label>
    <nameField>
        <displayFormat>ProjCity-{00000000}</displayFormat>
        <label>Project City Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionnaireSet__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Risk and Market Assessments</relationshipLabel>
        <relationshipName>QuestionnaireSet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk and Market Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk and Market Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SFDC_Acct_Plan__c.object
<CustomObject>
    <description>Overall goals, objectives, and challenges for penetrating an account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <description>Represents a customer/vendor site (address/location).</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Represents the account which is bound to the customer/vendor site (address/location).</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Site</label>
    <nameField>
        <displayFormat>Site-{0000000000}</displayFormat>
        <label>Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_ExportControlController.cls
public with sharing class ECO_ExportControlController {

	public ExportControl__c oExportControl {get; set;}
	public ApexPages.StandardController oStandardController {get; set;}
	public list<SelectOption> lAnswerValues {get; set;}
	public Id sQuestionnaireSetId {get; set;}
	public Id sProjectId {get; set;}
	public list<Project_Site__c> lProjectSites {get; set;}
	public Project_Site__c oUltimateEndUser {get; set;}
	public Project_Site__c oClient {get; set;}
	public list<SelectOption> lCities {get; set;}
	public boolean bShowUltimateEndUserAddress {get; set;}
	public boolean bShowClientAddress {get; set;}
	
	public ECO_ExportControlController(ApexPages.StandardController oStandardController)
	{
		list<string> lFields = new list<string>();
        lFields.add('QuestionnaireSet__c');
        lFields.add('Project__c');
        oStandardController.addFields(lFields);
        
        this.oExportControl = (ExportControl__c)oStandardController.getRecord();
        this.oStandardController = oStandardController;
        this.sQuestionnaireSetId = oExportControl.QuestionnaireSet__c;
        this.sProjectId = oExportControl.Project__c;
        bShowUltimateEndUserAddress = false;
        bShowClientAddress = false;
        
        lAnswerValues = new list<SelectOption>{
            new SelectOption('Yes', 'Yes'),
            new SelectOption('No', 'No')
        };
        
        if(sQuestionnaireSetId == null)
        {
			ApexPages.Message oPageMessage = new ApexPages.Message(ApexPages.Severity.WARNING,'You have reached this page improperly, please access it from the Project screen.');
            ApexPages.addMessage(oPageMessage);
            return;
		}
		
		if(sProjectId != null)
		{
			lProjectSites = new list<Project_Site__c>([Select Is_Primary_End__c, 
															Is_Billing__c, 
															Site__r.Account__r.Id,
															Site__r.Account__r.Website, 
															Site__r.Account__r.Name, 
															Site__r.Account__r.BillingStreet, 
															Site__r.Account__r.BillingState, 
															Site__r.Account__r.BillingPostalCode, 
															Site__r.Account__r.BillingCountry, 
															Site__r.Account__r.BillingCity 
														From Project_Site__c
														Where Project__c = :sProjectId
														And (Is_Primary_End__c = true
															Or Is_Billing__c = true)
														Order By Account_Name__c]);
			for(Project_Site__c p : lProjectSites)
			{
				if(p.Is_Primary_End__c)
				{
					oUltimateEndUser = p;
					bShowUltimateEndUserAddress = true;
					break;
				}
			}

			for(Project_Site__c p : lProjectSites)
			{
				if(p.Is_Billing__c && p.Site__r.Account__r.Id != oUltimateEndUser.Site__r.Account__r.Id)
				{
					oClient = p;
					bShowClientAddress = true;
					break;
				}
			}
			lCities = new list<SelectOption>();
			lCities.add(new SelectOption('', 'Please Choose'));


			for(ProjectCity__c c : [Select Id, CityName__c From ProjectCity__c Where Project__c = :sProjectId Order By CityName__c])
			{
				lCities.add(new SelectOption(c.Id, c.CityName__c));
			}
		}
	}
	
	public PageReference SaveRecord()
	{
    	oStandardController.save();
    	return null;
    }
    
	public PageReference ReturnToSummary()
	{
    	PageReference oPageReference = Page.ECO_RMASummary;

    	oPageReference.getParameters().put('Id', oExportControl.QuestionnaireSet__c);
    	oPageReference.setRedirect(true);

    	return oPageReference;
    }
}