src/objects/Go_No_Go_Conversation__c.object
<CustomObject>
    <description>Discussions and decisions related to the Go / No-Go process</description>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <inlineHelpText>Displays the account manager from the account associated with this opportunity</inlineHelpText>
        <label>Account Manager</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <inlineHelpText>Automatically updated as GNG goes through Approval Process</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval - Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bid_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Go_No_Go_Conversation5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bid_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Capture Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Go_No_Go_Conversation4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bid_Proposal_Budget__c</fullName>
        <label>Bid &amp; Proposal Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Line__c</fullName>
        <description>Opportunity&apos;s Business Line</description>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Capital_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>if applicable</inlineHelpText>
        <label>Capital Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Go/No Go Conversation</relationshipLabel>
        <relationshipName>Go_No_Go_Conversation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Decision__c</fullName>
        <description>Final decision or pending status of decision</description>
        <inlineHelpText>Select final decision, or mark as Pending if discussion is still in progress.</inlineHelpText>
        <label>Decision</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <color>#FFCC33</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>GNG FastPass</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Go</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>No-Go</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Go Pending</fullName>
                <color>#57F17C</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market_Position_Q11__c</fullName>
        <description>What is the assessed likelihood of the project going ahead (% GO)?</description>
        <inlineHelpText>What is the assessed likelihood of the project going ahead (% GO)?</inlineHelpText>
        <label>% GO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Market_Position_Q12__c</fullName>
        <description>If the project goes ahead, what is the likelihood of the company winning (% GET)?</description>
        <inlineHelpText>If the project goes ahead, what is the likelihood of the company winning (% GET)?</inlineHelpText>
        <label>% GET</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Net_Revenue_Program__c</fullName>
        <label>Net Revenue (Program)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Revenue_TO_Project__c</fullName>
        <label>Net Revenue (TO/Project)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Opportunity for which the Go - No-Go decision is being made</description>
        <inlineHelpText>Opportunity for which the Go - No-Go decision is being made</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Go/No Go Conversation</relationshipLabel>
        <relationshipName>G_NG_Conversations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nominated Project Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Go_No_Go_Conversation3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Duration__c</fullName>
        <label>Work End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nominated Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Go_No_Go_Conversation2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Scope_Summary__c</fullName>
        <label>Project Scope Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <label>Estimated Work Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposal_Due_Date__c</fullName>
        <label>Proposal Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFT_Issue_Date__c</fullName>
        <label>Date RFP Expected</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Staff_Time_FBLR_Fee__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Staff Time (FBLR) Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subs_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Subs Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subs_Fee__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Subs Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Go/No Go Conversation</label>
    <nameField>
        <displayFormat>GNG-{0000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go/No Go Conversation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>B_P_Budget__c</fullName>
        <label>Bid &amp; Proposal Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Line_of_Primary_AECOM_Dept__c</fullName>
        <formula>AECOM_Primary_Dept_Lookup__r.Business_Line_Lookup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Read Only. To change, click Opportunity Departments at the top of the page, then click the &apos;New/Edit Opportunity Departments&apos; button. The primary BL depends on the department selected as primary.</inlineHelpText>
        <label>Primary Business Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Capture_Manager_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Person who is responsible for overall opportunity; manages entire pursuit.</inlineHelpText>
        <label>Capture Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Capture_Manager_Opportunities_User</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Construction_cost__c</fullName>
        <inlineHelpText>Owner’s capital cost for the entire project</inlineHelpText>
        <label>Construction cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_RFP_expected__c</fullName>
        <label>Date RFP expected</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_work_start_date__c</fullName>
        <description>Date billable work will begin.</description>
        <inlineHelpText>Required for opportunities in Stages 2, 3, 4, 5, and 6. Enter the estimated (future) book date.</inlineHelpText>
        <label>Estimated work start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Go_Probability__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Enter probability that the client will fund and award this project.</inlineHelpText>
        <label>Go Probability</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Net_Revenue_Program__c</fullName>
        <description>old formula: Ceiling_Amount_Total__c  -  Subs_Other_Revenue__c
May 2013 - changed to Program Estimated Revenue - Subs/Other Revenue (if Program Estimated Revenue is filled in)</description>
        <formula>IF(  Program_Estimated_Revenue__c    &gt; 0, Program_Estimated_Revenue__c   -  Subs_Other_Revenue__c, 
IF( Ceiling_Amount_ReadOnly__c   &gt; 0, Ceiling_Amount_Total__c  -  Subs_Other_Revenue__c, 
0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>North America: Program Estimated Revenue minus Subs/Other Revenue
All Others: Ceiling Amt minus Subs/Other Revenue</inlineHelpText>
        <label>Net Revenue (Program)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Revenue_TO_Project__c</fullName>
        <description>Gross AECOM Contract Rev (Project/TO)
original formula: Amount  -  Subs_Other_Revenue__c</description>
        <formula>IF( Amount   &gt; 0, Amount  -  Subs_Other_Revenue__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Gross AECOM Contract Rev. minus Subs/Other Revenue</inlineHelpText>
        <label>Net Revenue (TO/Project)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Probability_Stage__c</fullName>
        <defaultValue>IF(CONTAINS($RecordType.Name ,&quot;Middle East&quot;) = TRUE,0,NULL)</defaultValue>
        <inlineHelpText>Enter probability of winning if the client proceeds. Guidance: 
1 Lead 10% 
2 Capture 20% 
3 Submitted 30% 
4 On Hold 20% 
5 SNB 90% 
(Enter Go Probability in the $$ fields section below)</inlineHelpText>
        <label>Probability</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Project_DirectorUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly Principal in Charge</description>
        <inlineHelpText>Principal in charge of project delivery if we win.</inlineHelpText>
        <label>Project Director</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AECOM_Employee__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AECOM_Employee__c</referenceTo>
        <relationshipLabel>Opportunities (Principal in Charge)</relationshipLabel>
        <relationshipName>Opportunities8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person who will manage project if we win</description>
        <inlineHelpText>Select the person who will manage project if we win; person responsible for delivery of the project.</inlineHelpText>
        <label>Project Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AECOM_Employee__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <infoMessage>Please select the Project Manager</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AECOM_Employee__c</referenceTo>
        <relationshipLabel>Opportunities (Project Manager)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subs_Other_Revenue__c</fullName>
        <inlineHelpText>Enter any amount other than billed labour, such as sub-consultants and expenses</inlineHelpText>
        <label>Subs/Other Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Work_end_date_del__c</fullName>
        <description>The new work end date field which is a data input rather than a formula</description>
        <label>Work end date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/gng_OppToGNGC.cls
/*************************************************************************
*
* PURPOSE: Creating/Modifying Go/No-Go records based on Opportunity
*
* CLASS: gng_OppToGNGC
* CREATED: 10/15/2014 Ethos Solutions - www.ethos.com
* AUTHOR: Raghuveer Mandali
***************************************************************************/
public with sharing class gng_OppToGNGC {
	//Field map for Opp field => GNG field
	private static final Map<String, List<String>> ANZFieldMap = new Map<String, List<String>>{
		'CurrencyIsoCode' => new List<String>{'CurrencyIsoCode'},
		'Go_Probability__c' => new List<String>{'Market_Position_Q11__c'},
		'Probability_Stage__c' => new List<String>{'Market_Position_Q12__c'},
		'Construction_cost__c' => new List<String>{'Capital_Value__c'},
		'Project_DirectorUser__c' => new List<String>{'Project_Director__c', 'Bid_Director__c'},
		'Project_Director_EMEA__c' => new List<String>{'Project_Director__c'},
		'Capture_Manager_User__c' => new List<String>{'Bid_Manager__c', 'Project_Manager__c'},
		'Date_RFP_expected__c' => new List<String>{'RFT_Issue_Date__c'},
		'Estimated_work_start_date__c' => new List<String>{'Project_Start_Date__c'},
		//Removed mapping per AEGNG-133
		//'CloseDate' => 'Proposal_Due_Date__c',
		'Work_end_date_del__c' => new List<String>{'Project_Duration__c'},
		'Net_Revenue_To_Project__c' => new List<String>{'Staff_Time_FBLR_Fee__c'},
		'Business_Line_of_Primary_AECOM_Dept__c' => new List<String>{'Business_Line__c'},
		'Net_Revenue_Program__c' => new List<String>{'Net_Revenue_Program__c'},
		'Net_Revenue_TO_Project__c' => new List<String>{'Net_Revenue_TO_Project__c'},
		'B_P_Budget__c' => new List<String>{'Bid_Proposal_Budget__c'},
		'Account_Manager__c' => new List<String>{'Account_Manager__c'}
	};

	public static Set<Id> hasRanOpp = new Set<Id>();

	//Creating new Go/No-Go records from opportunites
	public static void createGNGFromOpportunity(Map<String, List<Opportunity>> oppMap) {
		List<RecordType> recordTypes = [select Id, Name from RecordType where sObjectType = 'Go_No_Go_Conversation__c'];
		Map<String, RecordType> recordTypeMap = new Map<String, RecordType>();
		List<Go_No_Go_Conversation__c> gng = new List<Go_No_Go_Conversation__c>();
		Set<Id> oppIds = new Set<Id>();

		for(List<Opportunity> oppList : oppMap.values()) {
			for(Opportunity o : oppList) {
				oppIds.add(o.Id);
			}
		}

		for(RecordType r : recordTypes) recordTypeMap.put(r.Name, r);
		for(String region : oppMap.keySet()) {
			for(Opportunity o : oppMap.get(region)) {
				if(hasRanOpp.contains(o.Id)) continue;
				Go_No_Go_Conversation__c newGNG = new Go_No_Go_Conversation__c();
				if(region == 'ANZ') newGNG.RecordTypeId = recordTypeMap.get('ANZ Why Go').Id;
				else if(region == 'North America') newGNG.RecordTypeId = recordTypeMap.get('Americas GNG').Id;
				else if(region == 'Europe') newGNG.RecordTypeId = recordTypeMap.get('Europe GNG').Id;
				else if(region == 'Asia' || region == 'Africa' || region == 'Middle East') newGNG.RecordTypeId = recordTypeMap.get('View Only').Id;
				newGNG.Opportunity__c = o.Id;
				newGNG.Client_Name__c = o.AccountId;
				newGNG.Subs_Fee__c = o.Subs_Other_Revenue__c;
				newGNG.Subs_Cost__c = o.Subs_Other_Revenue__c;
				newGNG.Project_Scope_Summary__c = o.Description;
				setFields(newGNG, o);
				hasRanOpp.add(o.Id);
				gng.add(newGNG); 
			}
		}
		insert gng;
	}

	//update existing Go/No-Go records
	public static void updateGNGFromOpportunity(Map<String, Opportunity> oppMap) {
    	Set<String> ids = oppMap.keySet();
    	String query = buildQueryString('Go_No_Go_Conversation__c')+ ', RecordType.Name' + ' from Go_No_Go_Conversation__c where Opportunity__c in: ids';
		Map<Id,Id> gngIdsToPD = new Map<Id,Id>();
		List<Go_No_Go_Conversation__c> gngsToUpdate = new List<Go_No_Go_Conversation__c>();
		Set<Id> lockedGNGs = new Set<Id>();
		gng_ApprovalProcessDao appDao = gng_ApprovalProcessDao.getInstance();

		Map<Id,Task> existingUserTask = new Map<Id,Task>();
		List<Task> tasks = new List<Task>();

		for(Go_No_Go_Conversation__c g : (List<Go_No_Go_Conversation__c>)Database.query(query)) {
			
			if(compareFields(g, oppMap.get(g.Opportunity__c))) {
				if(g.Approval_Status__c != 'Submitted for Approval - Pending') {
					gngsToUpdate.add(setFields(g, oppMap.get(g.Opportunity__c)));
				}
				else {
					if(appDao.recallWorkItem(g.Id, 'Recalling to Update')) lockedGNGs.add(g.Id);
					gngsToUpdate.add(setFields(g, oppMap.get(g.Opportunity__c)));
				}	
			}
			if(!gngIdsToPD.containsKey(g.Id) && !oppMap.get(g.Opportunity__c).StageName.startsWith('1') && !oppMap.get(g.Opportunity__c).StageName.startsWith('8') && !oppMap.get(g.Opportunity__c).StageName.startsWith('7') && !oppMap.get(g.Opportunity__c).StageName.startsWith('9') && g.RecordType.Name == 'Europe GNG' && g.Decision__c != 'Go' && g.Decision__c != 'No-Go') gngIdsToPD.put(g.Id,g.Project_Director__c);

		}
		update gngsToUpdate;
		for(Id gngId : lockedGNGs) appDao.submitApprovalProcess(gngId, 'Resubmitting for approval');
		for(Task t : [Select OwnerId,WhatId,Subject from Task where OwnerId IN: gngIdsToPD.values() AND WhatId IN: gngIdsToPD.keySet() AND Subject =: 'Opportunity has reached Stage 2 and Go/No Go record has not been approved or rejected.']) {
			existingUserTask.put(t.WhatId,t);
		}
		for(Id gngId : gngIdsToPD.keySet()) {
			Task existTask = existingUserTask.get(gngId);
			if(String.isNotBlank(gngIdsToPD.get(gngId)) // Checks if Opp has a PD
				&& (existTask == null ||  //Checks if there exists a Task already for OPP
					(existTask != null && existTask.OwnerId != gngIdsToPD.get(gngId)) // Checks if existing task matches Project director
			    )){
				tasks.add(createGNGTask(gngIdsToPD.get(gngId),gngId));
			}
		}
		insert tasks;
	}

	//delete existing Go/No-Go records
	public static void deleteGNGFromOpportunity(Set<Id> oppIds) {
		delete [select Id,Name from Go_No_Go_Conversation__c where Opportunity__c in: oppIds];
	}

	//set ANZ fields (TODO: update to encompass all regions)
	private static Go_No_Go_Conversation__c setFields(Go_No_Go_Conversation__c g, Opportunity o) {
		for(String oppField : ANZFieldMap.keySet()) {
			if(oppField == 'Project_DirectorUser__c' && (o.Geography_Formula__c == 'Europe' || o.Geography_Formula__c == 'Middle East' || o.Geography_Formula__c == 'Africa')) continue;
			else {
				for(String gngField : ANZFieldMap.get(oppField)) {
					g.put(gngField, o.get(oppField));
				}
			}
		}
		return g;
	} 

	//compares the fields between GNG and Opp to see if we need to update the GNG record
	private static Boolean compareFields(Go_No_Go_Conversation__c g, Opportunity o) {
		Boolean isUpdate = false;
		for(String oppField : ANZFieldMap.keySet()) {
			if(oppField == 'Project_DirectorUser__c' && (o.Geography_Formula__c == 'Europe' || o.Geography_Formula__c == 'Middle East' || o.Geography_Formula__c == 'Africa')) continue;
			else {
				for(String gngField : ANZFieldMap.get(oppField)) {
					if(g.get(gngField) != o.get(oppField)) isUpdate = true;
				}
			}
		}
		return isUpdate;
	}

	//build query string
	private static String buildQueryString(String objectName){
		SObjectType objToken = Schema.getGlobalDescribe().get(objectName);
    	DescribeSObjectResult objDef = objToken.getDescribe();
    	String fieldList = String.join(new List<String>(objDef.fields.getMap().keySet()), ',').toLowerCase();

    	return 'select ' + fieldList;
	}

	private static Task createGNGTask(Id ownerId, Id gngId) {
		Task newTask = new Task();
		newTask.Subject = 'Opportunity has reached Stage 2 and Go/No Go record has not been approved or rejected.';
		newTask.Status = 'Not Started';
		newTask.Priority = 'Normal';
		newTask.Type = 'Other';
		newTask.ActivityDate = Date.today();
		newTask.OwnerId = ownerId;
		newTask.WhatId = gngId;
		return newTask;
	}
}