src/objects/IncentiveProject__c.object
<CustomObject>
    <customHelpPage>INC_HelpRedirect</customHelpPage>
    <description>DTW eligible projects to be considered for enrollment in DTW Incentive Plans</description>
    <fields>
        <fullName>DTWAdminAttempted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag is for bulk insert of IP&apos;s so that the batch process can work for smaller batches.</description>
        <label>DTWAdminAttempted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FPPOverallEligibility__c</fullName>
        <description>Indicates whether or not a project meets eligibility requirements for the Fixed Price Plan.</description>
        <inlineHelpText>Indicates whether or not a project meets eligibility requirements for the Fixed Price Plan.</inlineHelpText>
        <label>FP Plan Overall Eligibility</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RoutingMemberRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Routing Member Rule Applied to Determine the Incentive Project DTW Admin</inlineHelpText>
        <label>Routing Member Rule</label>
        <referenceTo>RoutingMember__c</referenceTo>
        <relationshipLabel>Incentive Projects</relationshipLabel>
        <relationshipName>Incentive_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TMPlanOverallEligibility__c</fullName>
        <description>Indicates whether or not the project meets all current eligibility requirements for the T&amp;M Plan.</description>
        <inlineHelpText>Indicates whether or not the project meets all current eligibility requirements for the T&amp;M Plan.</inlineHelpText>
        <label>T&amp;M Plan Overall Eligibility</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Incentive Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/INC_FindDTWAdminForNewIncentiveProjects.cls
global class INC_FindDTWAdminForNewIncentiveProjects implements Database.Batchable<sObject> {
	
	String query;
	
	global INC_FindDTWAdminForNewIncentiveProjects() {
		query = getQuery();
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		System.Debug(logginglevel.error,'Starting execute of batch process');
		INC_Service_Matching Inc_Match = new INC_Service_Matching();
		list<IncentiveProject__c> lNew = Inc_Match.FindDTWAdmin(scope);
		lNew = INC_Service_EnrollmentPlan.assignIneligibleQueue(lNew);

		update lNew;
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
	private String getQuery(){
		INC_Service_Matching serviceMatch = new INC_Service_Matching();
		list<Schema.FieldSetMember> DTWAdmin = serviceMatch.getFieldSet(true);
		String sReturn = 'Select ID, RoutingMemberRule__c,FPPOverallEligibility__c,TMPlanOverallEligibility__c';
		for(Schema.FieldSetMember FSM: DTWAdmin){
			sReturn += ',' + (String) FSM.getFieldPath();
		}
		sReturn += ' From IncentiveProject__c where DTWAdminAttempted__c = false';
		return sReturn;
	}
}