src/objects/KPI_Metric__c.object
<CustomObject>
    <description>The definition of a KPI metric in terms of it&apos;s name, data type, and database field mapping</description>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>KPI Metric</label>
    <nameField>
        <label>KPI Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPI Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PortalMessage__c.object
<CustomObject>
    <description>Used by the ECO_Portal pages to display User Alerts, News Feed Items, and News Ticker.</description>
    <label>Portal Message</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Portal Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Review_Trigger__c.object
<CustomObject>
    <description>Where project KPIs and their thresholds are configured to create alerts.</description>
    <fields>
        <fullName>Alert_Message__c</fullName>
        <description>The message to generate as an alert if the evaluation is true</description>
        <label>Alert Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comparator_1__c</fullName>
        <description>the value the KPI metric is being compared to</description>
        <label>Comparator 1</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comparator_2__c</fullName>
        <description>the second (optional) value the KPI metric is being compared to</description>
        <label>Comparator 2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Evaluation_Frequency__c</fullName>
        <label>Evaluation Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KPI_Metric__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The metric being evaluated.</description>
        <label>KPI Metric</label>
        <referenceTo>KPI_Metric__c</referenceTo>
        <relationshipLabel>Project Review Triggers</relationshipLabel>
        <relationshipName>Project_Review_Triggers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater than or equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less than or equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>between</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>outside</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Review Trigger</label>
    <nameField>
        <label>Project Review Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Review Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_ProjectHealthCheckBatchTest.cls
@isTest
public class ECO_ProjectHealthCheckBatchTest {

    static testMethod void testProjectHealthCareBatch() {
		final Integer numTestRisks = 50;

		Account testAccount = new Account();
		testAccount.Name = 'test Account';
		insert testAccount;

		//create create source project 
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.Name = 'test project 1';
		testProject.pse__Account__c = testAccount.Id;
		testProject.pse__Project_Type__c = 'Customer Project';
		testProject.pse__Billing_Type__c = 'Fixed Price';
		testProject.CurrencyIsoCode = 'USD';
		testProject.pse__Is_Active__c = true;
		testProject.pse__End_Date__c = Date.today().addDays(5);
		insert testProject;
		
		list<KPI_Metric__c> kpiMetrics = new list<KPI_Metric__c>();
		KPI_Metric__c metric1 = new KPI_Metric__c(Name='Is PM certified', Data_Type__c = 'Boolean', Is_Active__c = true, Unit_Of_Measure__c = 'true/false'); //a5ne00000004ENqAAM
		KPI_Metric__c metric2 = new KPI_Metric__c(Name='Scheduled end date < today', Data_Type__c = 'Boolean', Is_Active__c = true, Unit_Of_Measure__c = 'true/false');
		kpiMetrics.add(metric1); //a5ne00000004ENqAAM
		kpiMetrics.add(metric2); //a5ne00000004ENvAAM
		insert kpiMetrics;

//		list<Project_Review_Trigger__c> projectReviewTriggers = new list<Project_Review_Trigger__c>();		
//		projectReviewTriggers.add(new Project_Review_Trigger__c(Name='Project Manager', Alert_Message__c = 'PM not certified', Comparator_1__c = 'false', Comparator_2__c = null, 
//									Evaluation_Frequency__c = null, Is_Active__c = true, KPI_Metric__c = metric1.Id, Operator__c = 'equal to'));
//		projectReviewTriggers.add(new Project_Review_Trigger__c(Name='Scheduled End Date', Alert_Message__c = 'Scheduled end date occurs in the past', Comparator_1__c='false', Comparator_2__c = null, 
//									Evaluation_Frequency__c = null, Is_Active__c = true, KPI_Metric__c = metric2.Id, Operator__c = 'equal to'));
//		insert projectReviewTriggers;
		 		
		Test.StartTest();                
        ECO_ProjectHealthCheckBatch projectHealthCheckBatch = new ECO_ProjectHealthCheckBatch();
        Id batchprocessid = Database.executeBatch(projectHealthCheckBatch);    
        Test.StopTest(); 
        
        System.AssertEquals(false, testProject.isClosed__c);
        
        list<PortalMessage__c> portalMessage = [select Id from PortalMessage__c];
        
        System.AssertEquals(0, portalMessage.size());
        //System.AssertEquals('Test', portalMessage[0]);
        //System.AssertEquals(true,  portalMessages[0])  
    }
    
    static testMethod void testProjectHealthCareBatch2() {
		final Integer numTestRisks = 50;

		Account testAccount = new Account();
		testAccount.Name = 'test Account';
		insert testAccount;

		//create create source project 
		pse__Proj__c testProject = new pse__Proj__c();
		testProject.Name = 'test project 1';
		testProject.pse__Account__c = testAccount.Id;
		testProject.pse__Project_Type__c = 'Customer Project';
		testProject.pse__Billing_Type__c = 'Fixed Price';
		testProject.CurrencyIsoCode = 'USD';
		testProject.pse__Is_Active__c = true;
		testProject.pse__End_Date__c = Date.today().addDays(5);
		insert testProject;
		
		list<KPI_Metric__c> kpiMetrics = new list<KPI_Metric__c>();
		kpiMetrics.add( new KPI_Metric__c(Name='Is PM certified', Data_Type__c = 'Boolean', Is_Active__c = true, Unit_Of_Measure__c = 'true/false')); //a5ne00000004ENqAAM
		kpiMetrics.add( new KPI_Metric__c(Name='Scheduled end date < today', Data_Type__c = 'Boolean', Is_Active__c = true, Unit_Of_Measure__c = 'true/false')); //a5ne00000004ENvAAM
		insert kpiMetrics;

		list<Project_Review_Trigger__c> projectReviewTriggers = new list<Project_Review_Trigger__c>();		
		projectReviewTriggers.add(new Project_Review_Trigger__c(Name='Project Manager', Alert_Message__c = 'PM not certified', Comparator_1__c = 'true', Comparator_2__c = null, 
									Evaluation_Frequency__c = null, Is_Active__c = true, KPI_Metric__c = kpiMetrics[0].Id, Operator__c = 'equal to'));
/*		projectReviewTriggers.add(new Project_Review_Trigger__c(Name='Scheduled End Date', Alert_Message__c = 'Scheduled end date occurs in the past', Comparator_1__c='false', Comparator_2__c = null, 
									Evaluation_Frequency__c = null, Is_Active__c = true, KPI_Metric__c = kpiMetrics[1].Id, Operator__c = 'equal to'));
	*/	insert projectReviewTriggers;
 		
		Test.StartTest();                
        ECO_ProjectHealthCheckBatch projectHealthCheckBatch = new ECO_ProjectHealthCheckBatch();
        Id batchprocessid = Database.executeBatch(projectHealthCheckBatch);    
        Test.StopTest(); 
        
        System.AssertEquals(false, testProject.isClosed__c);
        
        list<PortalMessage__c> portalMessage = [select Id, Name from PortalMessage__c];
        
        System.AssertEquals(0, portalMessage.size());
        //System.AssertEquals('Test', portalMessage[0].Name);
        
        //System.AssertEquals(true,  portalMessages[0])  
    }
}