src/objects/KPI_Metric__c.object
<CustomObject>
    <description>The definition of a KPI metric in terms of it&apos;s name, data type, and database field mapping</description>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Database_Field_Mapping_API_Name__c</fullName>
        <description>The API names of the table and field the KPI metric maps to. Ex. &quot;BudgetHeader__c.TotalRevenue__c&quot;</description>
        <inlineHelpText>The API names of the table and field the KPI metric maps to. Ex. &quot;BudgetHeader__c.TotalRevenue__c&quot;</inlineHelpText>
        <label>Database Field Mapping (API Name)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>KPI Metric</label>
    <nameField>
        <label>KPI Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPI Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Review_Trigger__c.object
<CustomObject>
    <description>Where project KPIs and their thresholds are configured to create alerts.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KPI_Metric__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The metric being evaluated.</description>
        <label>KPI Metric</label>
        <referenceTo>KPI_Metric__c</referenceTo>
        <relationshipLabel>Project Review Triggers</relationshipLabel>
        <relationshipName>Project_Review_Triggers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Review Trigger</label>
    <nameField>
        <label>Project Review Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Review Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_ProjectReviewTriggersController.cls
public with sharing class ECO_ProjectReviewTriggersController 
{
	public ApexPages.StandardController oStandardController {get; set;}
	public Project_Review_Trigger__c oProjectReviewTrigger {get; set;}
	public List<KPI_Metric__c> lKPIMetrics {get; set;}
	public Map<Id, KPI_Metric__c> mKPIMetrics {get; set;}
	public List<SelectOption> lMetricOptions {get; set;}
	public String unitOfMeasure {get; set;}
	
	public ECO_ProjectReviewTriggersController(ApexPages.StandardController oStandardController) 
	{
		this.oStandardController = oStandardController;
		oProjectReviewTrigger = (Project_Review_Trigger__c)oStandardController.getRecord();
		lKPIMetrics = new List<KPI_Metric__c>([Select Unit_of_Measure__c, Name, Is_Active__c, Database_Field_Mapping_API_Name__c, Data_Type__c From KPI_Metric__c Where Is_Active__c = true Order By Name]);
		lMetricOptions = new List<SelectOption>();
		mKPIMetrics = new Map<Id, KPI_Metric__c>();
		lMetricOptions.add(new SelectOption('', '-- Choose --'));
		for(KPI_Metric__c kpi : lKPIMetrics)
		{
			lMetricOptions.add(new SelectOption(kpi.Id, kpi.Name));
			mKPIMetrics.put(kpi.Id, kpi);
		}
		loadMetric();
	}

	public void loadMetric()
	{
		if(mKPIMetrics.containsKey(oProjectReviewTrigger.KPI_Metric__c))
		{
			unitOfMeasure = mKPIMetrics.get(oProjectReviewTrigger.KPI_Metric__c).Unit_of_Measure__c;
		}
	}

	public PageReference doSave()
	{
		PageReference pr;
		try
		{
			oStandardController.save();
			String recordID = oProjectReviewTrigger.Id;
			String prefix = recordID.substring(0,3);
			pr = new PageReference('/' + prefix + '/o');
			pr.setRedirect(true);
		}
		catch(Exception e)
		{
			ApexPages.addMessages(e);
		}
		return pr;
	}
}