src/objects/Packages__c.object
<CustomObject>
    <fields>
        <fullName>ChangeManagerIsChanged__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Change Manager Is Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scope</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Scope and Packages</relationshipLabel>
        <relationshipName>Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utilize_BMI_Technology__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Projects that answer yes will need to provide additional data to determine if a BIM Health Start Review is required. Complete the BIM intake form for review by your Geography Director.</inlineHelpText>
        <label>Will this project utilize BIM technology</label>
        <type>Checkbox</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectReview__c.object
<CustomObject>
    <fields>
        <fullName>ChangeManagerIsChanged__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Change Manager Is Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectReviewTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Review Template</label>
        <referenceTo>ProjectReviewTemplate__c</referenceTo>
        <relationshipLabel>Project Reviews</relationshipLabel>
        <relationshipName>ProjectReviewsTemplate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Reviews</relationshipLabel>
        <relationshipName>ProjectReviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Review</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProjectReviewTemplate__c.object
<CustomObject>
    <fields>
        <fullName>TemplateType__c</fullName>
        <description>Must match the record types of project reviews.  To be fixed dynamically later.</description>
        <inlineHelpText>Must match the record types of project reviews.  To be fixed dynamically later.</inlineHelpText>
        <label>Template Type</label>
        <picklist>
            <picklistValues>
                <fullName>BIM Healthy Start/Restart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthy Restart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthy Start/Restart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Project Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Performance Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Closeout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Kickoff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Go/No Go</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Review Template</label>
    <nameField>
        <label>Project Review Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Review Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_PackageTriggerHelper.cls
public with sharing class ECO_PackageTriggerHelper {
	public ECO_PackageTriggerHelper() {
		
	}
	
	public static void setChangeManagerIsChanged(map<Id, Packages__c> oldMap, list<Packages__c> updatedScope)
	{
		for(Packages__c scope:updatedScope)
			if(!oldMap.get(scope.Id).ChangeManagerIsChanged__c)
				scope.ChangeManagerIsChanged__c = true;		
	}

	public static void attachHealthStart(list<Packages__c> newList, map<id, Packages__c> oldMap){
		
		list<ProjectReviewTemplate__c> lstPRT = [select id from ProjectReviewTemplate__c where TemplateType__c = 'BIM Healthy Start'];
		id RTid = Schema.Sobjecttype.ProjectReview__c.getRecordTypeInfosByName().get('BIM Healthy Start').getRecordTypeId();

		list<ProjectReview__c> prToInsert = new list<ProjectReview__c>();

		for(Packages__c p: newList){
			if(p.Utilize_BMI_Technology__c && (oldMap == null || p.Utilize_BMI_Technology__c != oldMap.get(p.id).Utilize_BMI_Technology__c)){

				if(lstPRT.size() == 0){
					p.adderror('Cannot find BIM Healthy Start/Restart Project Review Template to create BIM Project Review');
					return;
				}

				ProjectReview__c newPR = new ProjectReview__c();
				newPR.name = 'BIM Healthy Start Review';
				newPR.Project__c = p.Scope__c;
				newPR.ProjectReviewTemplate__c = lstPRT[0].id;
				newPR.recordtypeid = RTid;
				prToInsert.add(newPR);
			}

		}

		try{
			insert prToInsert;
        } catch (Exception e) {
            newList[0].adderror('Error while trying to insert BIM Healthy Start review');
            return;
        }     

	}
}