src/objects/PortalMessage__c.object
<CustomObject>
    <description>Used by the ECO_Portal pages to display User Alerts, News Feed Items, and News Ticker.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FullImageUrl__c</fullName>
        <label>Full Image Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinkToRecord__c</fullName>
        <label>Link to Record</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PortalMessages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portal Message</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Portal Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_Utils_Alerts.cls
public without sharing class ECO_Utils_Alerts {
	private System.LoggingLevel debugLevel = LoggingLevel.INFO;
	
	public static List<PortalMessage__c> getPortalMessagesForUser (Id userId, Date theDate) {
		List<PortalMessage__c> returnMessages = [SELECT Id 
														, EndDate__c
														, LinkToRecord__c
														, LongDescription__c
														, StartDate__c
														, User__c
														, Name
														, RecordTypeId
														, RecordType.Name
														, Subject__c 
												FROM PortalMessage__c 
												WHERE EndDate__c >= :theDate
													AND StartDate__c <= :theDate
													AND User__c = :userId
													AND RecordType.Name = :ECO_Constants.PortalMessage_AlertRecordTypeName
												ORDER BY CreatedDate DESC];
		
		return returnMessages;
	}
	
	public static List<PortalMessage__c> getNewsFeedForPortal () {
		Date theDate = Date.today();
		
		return [SELECT Id
						, User__c
						, User__r.Name
						, Subject__c
						, StartDate__c
						, LongDescription__c
						, LinkToRecord__c
						, FullImageUrl__c
						, EndDate__c
				FROM PortalMessage__c
				WHERE RecordType.Name = :ECO_Constants.PortalMessage_FeedItemRecordTypeName
					AND (EndDate__c >= :theDate OR EndDate__c = null)
					AND StartDate__c <= :theDate
				ORDER BY StartDate__c DESC, CreatedDate DESC];
	}
	
	public static List<PortalMessage__c> getPortalMessagesForUser (Id userId) {
		return getPortalMessagesForUser(userId, Date.today());
	}
	
	public static List<PortalMessage__c> getTickerMessages (Date theDate) {
		List<PortalMessage__c> returnMessages = [SELECT Id 
														, EndDate__c
														, LinkToRecord__c
														, LongDescription__c
														, StartDate__c
														, User__c
														, Name
														, RecordTypeId
														, RecordType.Name
														, Subject__c 
												FROM PortalMessage__c 
												WHERE EndDate__c >= :theDate
													AND StartDate__c <= :theDate
													AND RecordType.Name = :ECO_Constants.PortalMessage_NewsTickerRecordTypeName
												ORDER BY CreatedDate DESC];
		
		return returnMessages;
	}
	
	public static List<PortalMessage__c> getTickerMessages () {
		return getTickerMessages(Date.today());
	}
}