src/objects/PortalMessage__c.object
<CustomObject>
    <description>Used by the ECO_Portal pages to display User Alerts, News Feed Items, and News Ticker.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LinkToRecord__c</fullName>
        <label>Link to Record</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LongDescriptionMaxLength__c</fullName>
        <label>Long Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PortalMessages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portal Message</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Portal Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ECO_ProjectExtendClosureDateBatch.cls
global class ECO_ProjectExtendClosureDateBatch implements Database.Batchable<sObject>{

	private String query = 'select Id, Name, OracleProjectNumber__c, pse__Project_Manager__r.Name, Project_Manager_User__c, CMProjectClosureIsApproved__c from pse__Proj__c where CMProjectClosureIsApproved__c = false and ClosureDate__c <= TODAY';
	
    global Database.QueryLocator start(Database.BatchableContext projectClosureBatchContext)
    {   
    	System.Debug(LoggingLevel.Info, 'Query ' + query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext projectClosureBatchContext, List<pse__Proj__c> projects)
    {  	
		list<Messaging.SingleEmailMessage> emailList = new list <Messaging.SingleEmailMessage>();
		list<PortalMessage__c> alerts = new list<PortalMessage__c>();
		
		Id alertRecordTypeId = ECO_Utils_Meta.getRecordTypeId(PortalMessage__c.sObjectType, ECO_Constants.PortalMessage_AlertRecordTypeName);
		
		for(pse__Proj__c project:projects)  
		{
  			alerts.add(new PortalMessage__c(RecordTypeId = alertRecordTypeId
   											, User__c = project.Project_Manager_User__c 
   											, StartDate__c = Date.today()
   											, EndDate__c = Date.today().addDays(1)
   											, LongDescriptionMaxLength__c = ECO_Constants.PortalMessage_OpenProjectReviewMessage
   											, Subject__c = project.Name
   											, LinkToRecord__c = '/' + project.Id
   											));
		} 	
		
		if(alerts.size() > 0)
			insert alerts;
    }	
    
    global void finish(Database.BatchableContext projectClosureBatchContext)
    {   	   	
        system.debug('Batch completed');
    }    
}