src/objects/PortalMessage__c.object
<CustomObject>
    <description>Used by the ECO_Portal pages to display User Alerts, News Feed Items, and News Ticker.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LinkToRecord__c</fullName>
        <label>Link to Record</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LongDescriptionMaxLength__c</fullName>
        <label>Long Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PortalMessages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portal Message</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Portal Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectReview__c.object
<CustomObject>
    <fields>
        <fullName>IsOpen__c</fullName>
        <formula>IF(OR( ISPICKVAL(Status__c, &quot;Not Started&quot;), ISPICKVAL(Status__c, &quot;Assessing&quot;), ISPICKVAL(Status__c, &quot;In Progress&quot;), ISPICKVAL(Status__c, &quot;Submitted&quot;)), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Reviews</relationshipLabel>
        <relationshipName>ProjectReviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReviewFrequency__c</fullName>
        <label>Review Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>TBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Weekly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Review</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_ProjectReviewOpenStatusBatch.cls
global class ECO_ProjectReviewOpenStatusBatch implements Database.Batchable<sObject>{

	private String query = 'select Id, Name, pse__Project_Manager__r.User__c, Project_Manager_User__c from pse__Proj__c where isClosed__c = false';
	
    global Database.QueryLocator start(Database.BatchableContext projectHealthCheckBatchContext)
    {   
    	System.Debug(LoggingLevel.Info, 'Query ' + query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext projectHealthCheckBatchContext, List<pse__Proj__c> projects)
    {  	
    	System.Debug(LoggingLevel.Info, 'Projects Results Size' + projects.size());
    	map<Id, pse__Proj__c> projectMap = new map<Id, pse__Proj__c>();
    	for(pse__Proj__c project:projects)
    	{
    		projectMap.put(project.Id, project);	
    	}
    	
    	list<ProjectReview__c> openProjectReviews = [select Id, IsOpen__c, Project__c from ProjectReview__c where ReviewFrequency__c = :ECO_Constants.ProjectReview_BatchReviewFrequency and 
    													IsOpen__c = true and Project__c in :projects];
    	
    	set<Id> projectsWithOpenReview = new set<Id>();
    	for(ProjectReview__c review:openProjectReviews)
    	{
    		projectsWithOpenReview.add(review.Project__c);
    	}
    	
   		list<PortalMessage__c> alerts = new list<PortalMessage__c>();

		Id alertRecordTypeId = ECO_Utils_Meta.getRecordTypeId(PortalMessage__c.sObjectType, ECO_Constants.PortalMessage_AlertRecordTypeName);

		pse__Proj__c alertProject;
		for(Id projectId:projectsWithOpenReview)
		{
			alertProject = projectMap.get(projectId);
   			// TAL - To Author:  Please use the leading comma pattern (like I did below)... it hurts way less to manipulate in the future
   			alerts.add(new PortalMessage__c(RecordTypeId = alertRecordTypeId
   											, User__c = alertProject.Project_Manager_User__c 
   											, StartDate__c = Date.today()
   											, EndDate__c = Date.today().addDays(7)
   											, LongDescriptionMaxLength__c = ECO_Constants.PortalMessage_OpenProjectReviewMessage
   											, Subject__c = alertProject.Name
   											, LinkToRecord__c = '/' + alertProject.Id
   											));     				
   		}													

		// TAL - Always scope conditionals!!
		// Use IsEmpty instead of size() > 0 (faster, especially in batch)
		if(!alerts.isEmpty()) {
			insert alerts;
		}
    }	
    
    global void finish(Database.BatchableContext projectHealthCheckBatchContext)
    {   	
    	
        system.debug('Batch completed');
    }    
}