src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectRole__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Key Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays only PSA resouces</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>PSA Resource</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Contact__r.pse__Salesforce_User__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <formula>Contact__r.pse__Salesforce_User__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectRoleTitle__c</fullName>
        <label>Project Role Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Role</label>
        <referenceTo>ProjectRole__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembersRole</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000000}</displayFormat>
        <label>Project Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <fields>
        <fullName>PlanElement__c</fullName>
        <inlineHelpText>Which element of the project plan of the project does this affect? Select from the drop down list.</inlineHelpText>
        <label>Plan Element</label>
        <picklist>
            <picklistValues>
                <fullName>Agreements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closeout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deliverables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resilience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scope</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SH&amp;E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stakeholders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subs/Vendors</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Risk Register</relationshipLabel>
        <relationshipName>Risks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk</label>
    <nameField>
        <label>Risk Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_ProjectTeamFlyoutController.cls
public with sharing class ECO_ProjectTeamFlyoutController {

	public id sProjectId {get; set;}
	private boolean bInitialDefault;
	public List<SelectOption> lTeamRoleTypes {get; set;}	

	public ECO_ProjectTeamFlyoutController() {
		oProjectTeamMember = new ProjectTeamMember__c();
        bInitialDefault = true;
		lTeamRoleTypes = new List<SelectOption>();
		lTeamRoleTypes.add(new SelectOption('', '--None--'));     
		for(ProjectRole__c role:[Select Id, Name, Type__c From ProjectRole__c Where Active__c = true and Type__c = 'Team Member' Order By Name ASC]) 
		{
			lTeamRoleTypes.add(new SelectOption(role.Id, role.Name));
		}  
	}
	
	public ProjectTeamMember__c oProjectTeamMember {
    
    	get{
            if(bInitialDefault){
            	 oProjectTeamMember.Project__c = sProjectId;
                //oProjectTeamMember.PlanElement__c = sPlanElement;
                //sFilterCriteria = sPlanElement;
                bInitialDefault = false;
            }

            return oProjectTeamMember;
        }

        set;
	}
	
	public list<ProjectTeamMember__c> lProjectTeamMembers {
        get{
            string sSOQL = 'SELECT ';

            //for (Schema.FieldSetMember fsmField: SObjectType.Risk__c.FieldSets.RiskFlyoutDisplayFields.getFields()) {
            //     sSOQL += fsmField.getFieldPath() + ', ';
            //}

            sSOQL += ' Id, Name, Contact__c, ProjectRoleTitle__c, Email__c, Phone__c, ProjectRole__c, ProjectRole__r.Type__c FROM ProjectTeamMember__c WHERE Project__c =\'' + sProjectId + '\'';
//            sSOQL += ' and ProjectRole__r.Type__c = \'' + 'Team Member' + '\'';
            sSOQL += ' and (ProjectRole__r.Type__c = \'' + 'Team Member' + '\' or  (ProjectRole__r.Type__c = \'' + 'Key Member' + '\' AND Active__c = true))';


            
//            if(ECO_Utils_String.NullCheck(sFilterCriteria) != ''){
//                sSOQL += ' and PlanElement__c = \'' + sFilterCriteria + '\'';
//            }

            sSOQL += ' ORDER BY Name';

            return (list<ProjectTeamMember__c>)Database.query(sSOQL);
        }

        set;
	}
	


	public PageReference saveTeamMember()
	{
        try {
           
            insert oProjectTeamMember;
        } catch (Exception e) {
            ApexPages.Message oMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An Error has occurred while attmpting to save risk: ' + e);
            ApexPages.addMessage(oMsg);
            return null;
        }       

        oProjectTeamMember = new ProjectTeamMember__c();
        return null;		
	}	
}