src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WeeklyRollupEntry__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Weekly Rollup Entries</relationshipLabel>
        <relationshipName>Weekly_Rollup_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Weekly Rollup Entry</label>
    <nameField>
        <displayFormat>WRE-{0000000}</displayFormat>
        <label>Weekly Rollup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weekly Rollup Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_CreateWeeklyRollupEntriesController.cls
public with sharing class ECO_CreateWeeklyRollupEntriesController {
	public ApexPages.StandardController stdController {get; set;}

	public ECO_CreateWeeklyRollupEntriesController(ApexPages.StandardController stdController) {
		this.stdController = stdController;
	}

	public void recalculate() {
		Set<Id> projectIds = new Set<Id>();
		projectIds.add(stdController.getId());

		List<WeeklyRollupEntry__c> oldEntries = [select id from WeeklyRollupEntry__c where Project__c in :projectIds];
		delete oldEntries;

		ECO_ProjectTaskTriggers.recalculateProjects(projectIds, true);
	}
}