src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ReportDetails__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Report_Id__c</fullName>
        <label>Report Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Eco_Report Details</label>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <fields>
        <fullName>ContingencyDollars__c</fullName>
        <description>Automatic calculation of (pre-mitigation labor + pre-mitigation ODC cost)</description>
        <formula>IF(LaborCost__c +  ODCCost__c &gt; 0 ,LaborCost__c +  ODCCost__c ,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Calculated pre-mitigation contingency costs [Total Costs = Labor + Subs/ODCs]</inlineHelpText>
        <label>Pre-mitigation Contingency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CurrentStatus__c</fullName>
        <inlineHelpText>Select the current status of the risk from the drop down list.</inlineHelpText>
        <label>Current Status</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed - Unmitigated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed - Mitigated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EventPhase__c</fullName>
        <inlineHelpText>What phase of the project does the risk primarily apply to? Select from the drop down list.</inlineHelpText>
        <label>Event Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closure</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MitigationCostTotal__c</fullName>
        <formula>IF(MitigationCostLabor__c +  MitigationCostSubsODCs__c &gt; 0,MitigationCostLabor__c +  MitigationCostSubsODCs__c,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total estimated costs to mitigate the risk [Total Cost = AECOM Labor + Subs/ODCs]</inlineHelpText>
        <label>Mitigation Cost Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PostmitigationContingencyTotal__c</fullName>
        <formula>PostmitigationContingencyLabor__c +   PostmitigationContingencySubsODCs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Calculated post-mitigation contingency costs [Total  = Labor + Subs/ODCs]</inlineHelpText>
        <label>Post-mitigation Contingency Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Postmitigationrating__c</fullName>
        <inlineHelpText>Using the likelihood and consequence selections, refer to the Risk Matrix to determine the risk rating (High, Medium, Low).</inlineHelpText>
        <label>Post-mitigation rating</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Premitigationrating__c</fullName>
        <inlineHelpText>Using the likelihood and consequence selections, refer to the Risk Matrix to determine the risk rating (High, Medium, Low).</inlineHelpText>
        <label>Pre-mitigation rating</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Risk Register</relationshipLabel>
        <relationshipName>Risks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RiskMitigation__c</fullName>
        <inlineHelpText>Outline which measures you will employ to manage or mitigate the risk.</inlineHelpText>
        <label>Mitigation Strategy</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RiskOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Identify a resource that will have primary responsibility for owning and managing this risk.</inlineHelpText>
        <label>Risk Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Risks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Risk</label>
    <nameField>
        <label>Risk Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_RiskRegisterListController.cls
public class ECO_RiskRegisterListController {
    public pse__Proj__c thisProject {get; set;}
    public ApexPages.StandardController oStandardController {get; set;}
    public ECO_RiskRegisterListController(ApexPages.StandardController oStandardController){
        this.oStandardController = oStandardController; 
        thisProject = (pse__Proj__c)oStandardController.getRecord();
        
    }
    public PageReference returnProj(){
        return new PageReference('/' + thisProject.Id);
    }
    public PageReference newRisk(){
        Id riskId;
        Risk__C oRisk = new Risk__c();
        oRisk.Project__c = thisProject.id;
        oRisk.Name = 'New Risk';
        try{
            Insert oRisk;
        }catch (DmlException e){
            System.debug('Exception: '+e);
        }
        System.debug('oRisk id:  '+oRisk.Id);
        System.debug('oRisk project id:  '+oRisk.Project__c);
        //return new PageReference('/a4f/e?CF00Ne00000016atX='+thisProject.Name+'&CF00Ne00000016atX_lkid='+thisProject.id);
        return new PageReference('/'+oRisk.Id+'/e?retURL=/apex/ECO_RiskRegisterList?id='+thisProject.id);
    }
    public List<Risk__c> getRisks(){
        List <Risk__c> riskList = new List<Risk__c>([Select id, Name, CurrentStatus__c, EventPhase__c, RiskOwner__c, Premitigationrating__c, ContingencyDollars__c, RiskMitigation__c, MitigationCostTotal__c, Postmitigationrating__c, PostmitigationContingencyTotal__c From Risk__c Where Project__c = :thisProject.Id]);
        System.debug('riskList.size:  '+riskList.size());
        System.debug('thisProject.Id:  '+thisProject.Id);
        return riskList;
        
    }
    public PageReference deleteRisk(){
        Id riskId = ApexPages.currentPage().getParameters().get('recid');
        Risk__c riskRecord = [Select id From Risk__c where id = :riskId];
        System.debug('riskRecord id:  '+riskRecord.Id);
        if(riskRecord != null)
            delete riskRecord;
        return null;
    }
    public PageReference exportCSV(){
        String reportId = ReportDetails__c.getInstance('Project Risks').Report_Id__c;
        String projectId = thisProject.id;
        projectId = projectId.substring(0, 15);
        System.debug('reportId:  '+reportId);
        return new PageReference('/'+reportId+'?pv0='+projectId);
    }
}