src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Revenue__c.object
<CustomObject>
    <description>Object used to track revenue information from Oracle</description>
    <label>Revenue</label>
    <nameField>
        <label>Revenue Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WeeklyRollupEntry__c.object
<CustomObject>
    <fields>
        <fullName>AcctBurdenedCost__c</fullName>
        <label>Acct Burdened Cost</label>
        <summarizedField>EarnedValueSnapshot__c.AcctBurdenedCost__c</summarizedField>
        <summaryForeignKey>EarnedValueSnapshot__c.WeeklyRollupEntry__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AcctRawCost__c</fullName>
        <label>Acct Raw Cost</label>
        <summarizedField>EarnedValueSnapshot__c.AcctRawCost__c</summarizedField>
        <summaryForeignKey>EarnedValueSnapshot__c.WeeklyRollupEntry__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AppliedAcctBurdenedCost__c</fullName>
        <formula>BLANKVALUE(OverrideAcctBurdenedCost__c, AcctBurdenedCost__c)</formula>
        <label>Applied Acct Burdened Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AppliedAcctRawCost__c</fullName>
        <formula>BLANKVALUE(OverrideAcctRawCost__c, AcctRawCost__c)</formula>
        <label>Applied Acct Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AppliedApprovedCost__c</fullName>
        <formula>BLANKVALUE( OverrideApprovedCost__c ,  ApprovedCost__c )</formula>
        <label>Applied Approved Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AppliedRevenue__c</fullName>
        <formula>BLANKVALUE(OverrideRevenue__c, Revenue__c)</formula>
        <label>Applied Cash In</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ApprovedCost__c</fullName>
        <label>Approved Cost</label>
        <summarizedField>EarnedValueSnapshot__c.ThisWeekAmount__c</summarizedField>
        <summaryForeignKey>EarnedValueSnapshot__c.WeeklyRollupEntry__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CompositeKey__c</fullName>
        <externalId>true</externalId>
        <label>Composite Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OverrideAcctBurdenedCost__c</fullName>
        <label>Override Acct Burdened Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideAcctRawCost__c</fullName>
        <label>Override Acct Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideApprovedCost__c</fullName>
        <label>Override Approved Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverrideRevenue__c</fullName>
        <label>Override Cash In</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PeriodStartDate__c</fullName>
        <label>Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Weekly Rollup Entries</relationshipLabel>
        <relationshipName>Weekly_Rollup_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Cash In</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Weekly Rollup Entry</label>
    <nameField>
        <displayFormat>WRE-{0000000}</displayFormat>
        <label>Weekly Rollup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weekly Rollup Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_CashFlowFlyoutController.cls
public with sharing class ECO_CashFlowFlyoutController {
    public list<WeeklyRollupEntry__c> lWeeklyRollupEntries {get; set;}

    public String chartData {get; set;}

    public Decimal plannedCostTotal {get; set;}
    public Decimal cashInTotal {get; set;}

    public id sProjectId {
        get;

        set {
            sProjectId = value;

            reload(false);
        }
    }

    public void reload(Boolean force) {
        if ((lWeeklyRollupEntries == null) || force) {
            lWeeklyRollupEntries = new list<WeeklyRollupEntry__c>([
                SELECT Id
                     , Revenue__c
                     , AcctBurdenedCost__c
                     , AcctRawCost__c
                     , ApprovedCost__c
                     , PeriodStartDate__c
                     , OverrideRevenue__c
                     , OverrideAcctBurdenedCost__c
                     , OverrideAcctRawCost__c
                     , OverrideApprovedCost__c
                     , AppliedRevenue__c
                     , AppliedAcctBurdenedCost__c
                     , AppliedAcctRawCost__c
                     , AppliedApprovedCost__c
                     , Project__r.PercentageMargin__c

                FROM WeeklyRollupEntry__c
                WHERE
                    Project__c = :sProjectId
                ORDER BY
                    CompositeKey__c ASC]);
        }

        Decimal amountSoFar = 0;

        plannedCostTotal = 0.00;
        cashInTotal = 0.00;

        chartData = '[';
        
        chartData += '["Week", "Net Cash Position (In Period)", "Cash Flow (Cumulative)"],';
        
        for (WeeklyRollupEntry__c entry : lWeeklyRollupEntries) {
            Decimal approvedCost = (entry.AppliedApprovedCost__c != null) ? entry.AppliedApprovedCost__c : 0;
            Decimal revenue = (entry.AppliedRevenue__c != null) ? entry.AppliedRevenue__c : 0;

            Decimal netCashPosition = - approvedCost + revenue;
            amountSoFar += netCashPosition;

            plannedCostTotal += (entry.ApprovedCost__c != null) ? entry.ApprovedCost__c : 0;
            cashInTotal += (entry.Revenue__c != null) ? entry.Revenue__c : 0;

            chartData += '["' + entry.PeriodStartDate__c.format() + '", ' + netCashPosition + ', ' + amountSoFar + '],';
        }
        
        chartData = chartData.subString(0, chartData.length() - 1);
        
        chartData += ']';
    }

    public PageReference save() {
        update lWeeklyRollupEntries;

        reload(true);

        return null;
    }

    public PageReference clearAllOverrides() {
        for (WeeklyRollupEntry__c entry : lWeeklyRollupEntries) {
            entry.OverrideApprovedCost__c = null;
            entry.OverrideRevenue__c = null;
        }

        update lWeeklyRollupEntries;

        reload(true);

        return null;
    }
}