src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WeeklyRollupEntry__c.object
<CustomObject>
    <fields>
        <fullName>AppliedAcctBurdenedCost__c</fullName>
        <formula>BLANKVALUE(OverrideAcctBurdenedCost__c, AcctBurdenedCost__c)</formula>
        <label>Applied Acct Burdened Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AppliedAcctRawCost__c</fullName>
        <formula>BLANKVALUE(OverrideAcctRawCost__c, AcctRawCost__c)</formula>
        <label>Applied Acct Raw Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AppliedApprovedCost__c</fullName>
        <formula>BLANKVALUE( OverrideApprovedCost__c ,  ApprovedCost__c )</formula>
        <label>Applied Approved Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AppliedEstimatedCost__c</fullName>
        <formula>BLANKVALUE( OverrideEstimatedCost__c , EstimatedCost__c )</formula>
        <label>Applied Estimated Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AppliedRevenue__c</fullName>
        <formula>BLANKVALUE(OverrideRevenue__c, Revenue__c)</formula>
        <label>Applied Cash In</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CPI__c</fullName>
        <formula>IF( AppliedAcctBurdenedCost__c != 0, EarnedValue__c / AppliedAcctBurdenedCost__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CPI</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompositeKey__c</fullName>
        <externalId>true</externalId>
        <label>Composite Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EarnedValue__c</fullName>
        <label>Earned Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PeriodStartDate__c</fullName>
        <label>Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Weekly Rollup Entries</relationshipLabel>
        <relationshipName>Weekly_Rollup_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SPI__c</fullName>
        <formula>IF(AppliedApprovedCost__c != 0, EarnedValue__c / AppliedApprovedCost__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SPI</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Weekly Rollup Entry</label>
    <nameField>
        <displayFormat>WRE-{0000000}</displayFormat>
        <label>Weekly Rollup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weekly Rollup Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_EarnedValueFlyoutController.cls
public with sharing class ECO_EarnedValueFlyoutController {
    public list<WeeklyRollupEntry__c> lWeeklyRollupEntries {get; set;}
    public String chartData {get; set;}
    public String chartData2 {get; set;}
    
    public id sProjectId {
        get;

        set {
            sProjectId = value;

            reload(false);
        }
    }


    public void reload(Boolean force) {
        if ((lWeeklyRollupEntries == null) || force) {
            lWeeklyRollupEntries = new list<WeeklyRollupEntry__c>([
                SELECT Id
                     , PeriodStartDate__c
                     , AppliedEstimatedCost__c
                     , AppliedRevenue__c
                     , AppliedAcctBurdenedCost__c
                     , AppliedAcctRawCost__c
                     , AppliedApprovedCost__c
                	 , EarnedValue__c
                	 , CPI__c
                	 , SPI__c
                FROM WeeklyRollupEntry__c
                WHERE
                    Project__c = :sProjectId
                ORDER BY
                    CompositeKey__c ASC]);
        }

        chartData = '[';
        
        chartData += '["Week", "Planned", "Estimate", "Actual", "Earned Value"],';
        
        chartData2 = '[';
        
        chartData2 += '["Week", "CPI", "SPI"],';
        
        Decimal estimatedCostCumm = 0;
        Decimal approvedCostCumm = 0;
        Decimal actualCostCumm = 0;
            
        for (WeeklyRollupEntry__c entry : lWeeklyRollupEntries) {
            Decimal estimatedCost = (entry.AppliedEstimatedCost__c != null) ? entry.AppliedEstimatedCost__c : 0;
            Decimal approvedCost = (entry.AppliedApprovedCost__c != null) ? entry.AppliedApprovedCost__c : 0;
            Decimal earnedValue = (entry.EarnedValue__c != null) ? entry.EarnedValue__c : 0;
            Decimal actualCost = (entry.AppliedAcctBurdenedCost__c != null) ? entry.AppliedAcctBurdenedCost__c : 0;

            estimatedCostCumm += estimatedCost;
            approvedCostCumm += approvedCost;
            actualCostCumm += actualCost;

            chartData += '["' + entry.PeriodStartDate__c.format() + '", ' + approvedCostCumm + ', ' + estimatedCostCumm + ', ' + actualCostCumm + ', ' + earnedValue + '],';
            
            chartData2 += '["' + entry.PeriodStartDate__c.format() + '", ' + entry.CPI__c + ', ' + entry.SPI__c + '],';
        }
        
        chartData = chartData.subString(0, chartData.length() - 1);
        chartData2 = chartData2.subString(0, chartData2.length() - 1);
        
        chartData += ']';
        chartData2 += ']';
	}    
}