src/objects/ProjectReview__c.object
<CustomObject>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <formula>Project__r.ProjectNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <label>Project Review</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProjectSnapshot__c.object
<CustomObject>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectReview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Review</label>
        <referenceTo>ProjectReview__c</referenceTo>
        <relationshipLabel>Project Snapshots</relationshipLabel>
        <relationshipName>ProjectSnapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Snapshot</label>
    <nameField>
        <label>Project Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_ProjectReviewsControllerPdf.cls
public with sharing class ECO_ProjectReviewsControllerPdf extends ECO_ProjectReviewsController {
	
	//public String projectSnapshotRecord {get; set;}
	
	public ECO_ProjectReviewsControllerPdf(ApexPages.StandardController oStandardController) {
		super(oStandardController);
		// pdf file name format is {project-number}_{form}_{version-description}_{date}
		// TODO: find out what is {version-description}
		Datetime myDatetime = Datetime.now();
		String myDatetimeStr = myDatetime.format('yyyyMMdd');
		
		String pdfFileName = theProject.ProjectNumber__c + '_ProjectReview_' + oProjectReview.Name + '_' +  myDatetimeStr + '.pdf';
		Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename=' + pdfFileName);		
	}
	
	public String getProjectSnapshotRecord()
	{
		list<ProjectSnapshot__c> projectSnapshotRecords = [select Id from ProjectSnapshot__c where ProjectReview__c = :oProjectReview.Id order by Id desc];
		
		if(projectSnapshotRecords.size() > 0)
			return(new PageReference('/apex/ECO_ProjectSnapshot?Id='+ projectSnapshotRecords[0].Id).getContent().toString());
		return '';
	}
}