src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuestionnaireSet__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Risk and Market Assessments</relationshipLabel>
        <relationshipName>QuestionnaireSet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk and Market Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk and Market Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_RMAChooserController.cls
public with sharing class ECO_RMAChooserController {

	private pse__Proj__c oProject {get; set;}
    private String ProjID {get; set;}
    private String QSId {get; set;}
    private Boolean createNew {get; set;}

    public ECO_RMAChooserController(ApexPages.StandardController stdController)
    {
        this.oProject = (pse__Proj__c)stdController.getRecord();
        this.ProjID = oProject.Id;
        this.createNew = false;
    }

    public PageReference doRedirect() 
    {
        System.debug('ProjID: ' + ProjID);
        if(ProjID != null)
        {
            List<QuestionnaireSet__c> lQS = [Select Id From QuestionnaireSet__c Where Project__c = :ProjID Order By LastModifiedDate DESC Limit 1];
            if(lQS.isEmpty())
            {
                //create new R&M Assessment
                System.debug('ECO_RMAChooserController: create new R&M Assessment');
                QuestionnaireSet__c oQS = new QuestionnaireSet__c();
                oQS.Name = 'Initial Assessment';
                oQS.Project__c = ProjID;
                insert oQS;
                this.QSId = oQS.Id;
                this.createNew = true;
            }
            else
            {
                this.QSId = lQS[0].Id;
            }
        }

        PageReference oPR = Page.ECO_RMASummary;
        System.debug('doRedirect: QSId: ' + QSId);
        if(this.createNew)
        {
            System.debug('ECO_RMAChooserController: go to new R&M Assessment');
            oPR.getParameters().put('begin', 'true');
        }
        else
        {
            System.debug('ECO_RMAChooserController: go to existing R&M Assessment');
        }
        oPR.getParameters().put('Id', QSId);
        oPR.setRedirect(true);
        return oPR;
    }
}