src/objects/Project__c.object
<CustomObject>
    <description>The AECOM Project repository for project descriptions for use in proposals</description>
    <label>Project Profile</label>
    <nameField>
        <label>Project Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profiles</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>ProjectTeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000000}</displayFormat>
        <label>Project Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Eco_Project_TeamMember_Trigger_Test.cls
@isTest (seeAllData=false) 

private class Eco_Project_TeamMember_Trigger_Test {

    	static testMethod void testCreateSharingForTeamMembers(){

		User testUser = ECO_Utils_Testing.createTestUser('System Administrator');
		
		insert testUser;
                        
            ECO_Utils_Testing.createTestDataForProjectSync( 2, 2 );
            
            /*Project__c p = new Project__c();
            p.Name = 'Proj';
            p.ownerId = testUser.id;
            insert p;*/
            
            pse__Proj__c projectOne = ECO_Utils_Testing.createTestProject('Project One');
            Insert projectOne;
            
            list<ProjectTeamMember__c> lptm = [select id from ProjectTeamMember__c];
            
            system.debug( 'lp size ' + lptm.size() );

            for(ProjectTeamMember__c p : lptm)
            {
                //p.Active__c = false;
                p.EndDate__c = Date.today().addDays(-4);
                p.StartDate__c = Date.today().addDays(-14);
            }
            
            update lptm;
            
            BatchDeleteProjectSharing myBatchObject = new BatchDeleteProjectSharing();
            Database.executeBatch(myBatchObject);            
            
            //ProjectTeamMember__c tm1 = new ProjectTeamMember__c();
            //insert tm1;
        }
}