src/objects/pse__Time_Period__c.object
<CustomObject>
    <customHelpPage>pse__TimePeriodHelp</customHelpPage>
    <description>The divisions of time that your services organization is concerned with. Time periods have types such as Month (e.g. November 2014), Quarter (e.g. Q4 2014), Year (e.g. 2014), or Perpetual (‘All Time’). Time periods drive how actuals are categorized, how forecasting is done, how billing events are generated, and most other time-specific functions within FinancialForce PSA. Always create one perpetual time period with an end date well into the future.</description>
    <fields>
        <fullName>TimePeriodCode__c</fullName>
        <description>For months: FY2015-01 for the first fiscal month in fiscal 2015. For quarters: FY2015Q1 for the first quarter in fiscal 2015. For years: FY2015 for fiscal 2015.</description>
        <inlineHelpText>For months: FY2015-01 for the first fiscal month in fiscal 2015. For quarters: FY2015Q1 for the first quarter in fiscal 2015. For years: FY2015 for fiscal 2015.</inlineHelpText>
        <label>Time Period Code</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Time Period</label>
    <nameField>
        <label>Time Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WeeklyRollupEntry__c.object
<CustomObject>
    <fields>
        <fullName>FiscalMonth__c</fullName>
        <description>The name of the fiscal month, following the naming convention: FY2015-01, FY2015-02, ..., FY2015-12, etc.</description>
        <inlineHelpText>The name of the fiscal month, following the naming convention: FY2015-01, FY2015-02, ..., FY2015-12, etc.</inlineHelpText>
        <label>Fiscal Month</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PeriodStartDate__c</fullName>
        <label>Period Start Date</label>
        <type>Date</type>
    </fields>
    <label>Weekly Rollup Entry</label>
    <nameField>
        <displayFormat>WRE-{0000000}</displayFormat>
        <label>Weekly Rollup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weekly Rollup Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_WeeklyRollupEntryTriggers.cls
public class ECO_WeeklyRollupEntryTriggers{

public static void calculateFiscalMonths(list<WeeklyRollupEntry__c> weeklyrollupentries){
     list<date> enddatelist = new list<date>();
        for (WeeklyRollupEntry__c ba : weeklyrollupentries){
             if (ba.PeriodStartDate__c != null){ 
                 
                 enddatelist.add((ba.PeriodStartDate__c).addmonths(2));
                 enddatelist.add((ba.PeriodStartDate__c).addmonths(-3));
             }
        }
         List<pse__Time_Period__c> timePeriods  = new  List<pse__Time_Period__c>();
        if(enddatelist.size()>0)
        {
            // Time period
          timePeriods = ECO_Utils_Date.calcTimePeriods(enddatelist,'Month');
           pse__Time_Period__c fm = null;
            for (WeeklyRollupEntry__c ba : weeklyrollupentries){
                if (ba.PeriodStartDate__c != null){ 
                    fm = ECO_Utils_Date.getFiscalPeriod(ba.PeriodStartDate__c, 0, timePeriods);                     
                    if (fm != null){
                        ba.FiscalMonth__c = fm.TimePeriodCode__c;
                    }
                    
                    
                }
            }
        }

}



}