src/objects/pse__Time_Period__c.object
<CustomObject>
    <customHelpPage>pse__TimePeriodHelp</customHelpPage>
    <description>The divisions of time that your services organization is concerned with. Time periods have types such as Month (e.g. November 2014), Quarter (e.g. Q4 2014), Year (e.g. 2014), or Perpetual (‘All Time’). Time periods drive how actuals are categorized, how forecasting is done, how billing events are generated, and most other time-specific functions within FinancialForce PSA. Always create one perpetual time period with an end date well into the future.</description>
    <fields>
        <fullName>TimePeriodCode__c</fullName>
        <description>For months: FY2015-01 for the first fiscal month in fiscal 2015. For quarters: FY2015Q1 for the first quarter in fiscal 2015. For years: FY2015 for fiscal 2015.</description>
        <inlineHelpText>For months: FY2015-01 for the first fiscal month in fiscal 2015. For quarters: FY2015Q1 for the first quarter in fiscal 2015. For years: FY2015 for fiscal 2015.</inlineHelpText>
        <label>Time Period Code</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Time Period</label>
    <nameField>
        <label>Time Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Revenue__c.object
<CustomObject>
    <description>Object used to track revenue information from Oracle</description>
    <fields>
        <fullName>GLDateFiscalMonth__c</fullName>
        <label>GL Date Fiscal Month</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLDatePreviousFiscalMonth__c</fullName>
        <label>GL Date Previous Fiscal Month</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLDate__c</fullName>
        <label>GL Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PADateFiscalMonth__c</fullName>
        <label>PA Date Fiscal Month</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PADatePreviousFiscalMonth__c</fullName>
        <label>PA Date Previous Fiscal Month</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PADate__c</fullName>
        <label>PA Date</label>
        <type>Date</type>
    </fields>
    <label>Revenue</label>
    <nameField>
        <label>Revenue Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECO_RevenueTriggers.cls
public without sharing class ECO_RevenueTriggers {
	
	public static void calculateFiscalMonths(list<Revenue__c> revenues)
	{
		// Time period
		List<pse__Time_Period__c> timePeriods = ECO_ProjectTaskService.calcTimePeriods;
		
		pse__Time_Period__c fm = null;
		for (Revenue__c r : revenues){
			
			if (r.GLDate__c != null){	
				fm = ECO_Utils_Date.getFiscalPeriod(r.GLDate__c, 0, timePeriods);  
				if (fm != null){
					r.GLDateFiscalMonth__c = fm.TimePeriodCode__c;
				}
				
				fm = ECO_Utils_Date.getFiscalPeriod(r.GLDate__c, 1, timePeriods);  
				if (fm != null){
					r.GLDatePreviousFiscalMonth__c = fm.TimePeriodCode__c;
				}
			}
			
			if (r.PADate__c != null){	
				fm = ECO_Utils_Date.getFiscalPeriod(r.PADate__c, 0, timePeriods);  
				if (fm != null){
					r.PADateFiscalMonth__c = fm.TimePeriodCode__c;
				}
				
				fm = ECO_Utils_Date.getFiscalPeriod(r.PADate__c, 1, timePeriods);  
				if (fm != null){
					r.PADatePreviousFiscalMonth__c = fm.TimePeriodCode__c;
				}
			}						
		}
	}

}