src/objects/rs_Profile_Part__c.object
<CustomObject>
    <fields>
        <fullName>Date_Time_Sent_for_Review__c</fullName>
        <description>Date/Time when this profile part was sent to CM Review</description>
        <label>Date Time Sent for Review</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Degree_Specialty__c</fullName>
        <inlineHelpText>Major field of study as recorded on diploma</inlineHelpText>
        <label>Degree Specialty</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <inlineHelpText>Completed degree or qualification, e.g., BS, BSc</inlineHelpText>
        <label>Degree</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution_Country__c</fullName>
        <inlineHelpText>Country where school is located</inlineHelpText>
        <label>Institution Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <inlineHelpText>School that awarded this degree</inlineHelpText>
        <label>Institution</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Obtained__c</fullName>
        <inlineHelpText>Year degree was awarded</inlineHelpText>
        <label>Year Obtained</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Profile Part</label>
    <nameField>
        <displayFormat>PP-{0000000000}</displayFormat>
        <label>Profile Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profile Parts</pluralLabel>
    <recordTypes>
        <fullName>Education</fullName>
        <active>true</active>
        <label>Education</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Date_Time_Sent_for_Review__c</fullName>
        <description>Date/Time when any profile part belonging to this user was sent to CM Review. Set when first part sent and cleared when all parts are approved.</description>
        <label>Date Time Sent for Review</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/rsEducationControllerTest.cls
/*******************************************************************************
*
* PURPOSE: Test controller for the Education section in Skills & Qualifications 
*
* CREATED: 2014 Ethos Solutions - www.ethos.com
* AUTHOR: Kyle Johnson
********************************************************************************/
@isTest
private class rsEducationControllerTest {
	
	@isTest static void testSavePart() {
		User u = [Select Id, Date_Time_Sent_for_Review__c from User where Id =: UserInfo.getUserId()];
		rsProfile profile = new rsProfile(u);
		rsEducationController cont = new rsEducationController();
		cont.profile = profile;
		cont.newPart();
		cont.CurrentPart.setInstitution('Test Institution');
		cont.CurrentPart.setDegree('Degree');
		cont.CurrentPart.setDegreeSpecialty('Test Specialty');
		cont.CurrentPart.setInstitutionCountry('United States');
		cont.CurrentPart.setYearObtained(1992);

		Test.startTest();
		PageReference pf = cont.savePart();
		Test.stopTest();

		rs_Profile_Part__c pp = [Select Institution__c, Degree__c, Degree_Specialty__c, Institution_Country__c, Year_Obtained__c from rs_Profile_Part__c];

		System.assertEquals( null, pf);
		System.assertEquals( pp.Institution__c, cont.CurrentPart.getInstitution());
		System.assertEquals( pp.Degree__c, cont.CurrentPart.getDegree());
		System.assertEquals( pp.Degree_Specialty__c, cont.CurrentPart.getDegreeSpecialty());
		System.assertEquals( pp.Institution_Country__c, cont.CurrentPart.getInstitutionCountry());
		System.assertEquals( pp.Year_Obtained__c, cont.CurrentPart.getYearObtained());
	}

	@isTest static void testCancelPart() {
		User u = [Select Id, Date_Time_Sent_for_Review__c from User where Id =: UserInfo.getUserId()];
		rsProfile profile = new rsProfile(u);
		rsEducationController cont = new rsEducationController();
		cont.profile = profile;
		cont.newPart();
		cont.CurrentPart.setInstitution('Test Institution');		
		cont.CurrentPart.setDegree('Degree');
		cont.CurrentPart.setDegreeSpecialty('Test Specialty');
		cont.CurrentPart.setInstitutionCountry('United States');
		cont.CurrentPart.setYearObtained(1992);
		cont.savePart();
		rs_Profile_Part__c pp = [Select Institution__c, Degree__c, Degree_Specialty__c, Institution_Country__c, Year_Obtained__c
									from rs_Profile_Part__c];
		ApexPages.currentPage().getParameters().put('partId', pp.Id);
		cont.editPart();

		cont.CurrentPart.setInstitution('Another Institution');
		cont.CurrentPart.setDegree('Different Degree');
		cont.CurrentPart.setDegreeSpecialty('Fake Specialty');		
		cont.CurrentPart.setInstitutionCountry('Canada');
		cont.CurrentPart.setYearObtained(2008);

		Test.startTest();
		PageReference pf = cont.cancelPart();
		cont.editPart();
		Test.stopTest();

		System.assertEquals( null, pf);
		System.assertEquals( cont.CurrentPart.getInstitution(), 'Test Institution');
		System.assertEquals( cont.CurrentPart.getDegree(), 'Degree');
		System.assertEquals( cont.CurrentPart.getDegreeSpecialty(), 'Test Specialty');
		System.assertEquals( cont.CurrentPart.getInstitutionCountry(), 'United States');
		System.assertEquals( cont.CurrentPart.getYearObtained(), 1992);		
	}
	
}