src/objects/rs_Profile_Part__c.object
<CustomObject>
    <fields>
        <fullName>Date_Time_Sent_for_Review__c</fullName>
        <description>Date/Time when this profile part was sent to CM Review</description>
        <label>Date Time Sent for Review</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Publication_Author__c</fullName>
        <description>Author of the Publication article</description>
        <inlineHelpText>Co-authors, if any (if it&apos;s included in your profile, you are assumed to be an author)</inlineHelpText>
        <label>Publication Author</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_Date__c</fullName>
        <description>Date article was published</description>
        <inlineHelpText>The date the article was published or presentation presented</inlineHelpText>
        <label>Publication Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publication_Title__c</fullName>
        <description>Title of the article in the Publication</description>
        <inlineHelpText>Title of the publication or presentation</inlineHelpText>
        <label>Article Title/Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <description>Name of the Publication article is published</description>
        <inlineHelpText>Where the article was published or presentation was given</inlineHelpText>
        <label>Name of Publication</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Profile Part</label>
    <nameField>
        <displayFormat>PP-{0000000000}</displayFormat>
        <label>Profile Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profile Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Date_Time_Sent_for_Review__c</fullName>
        <description>Date/Time when any profile part belonging to this user was sent to CM Review. Set when first part sent and cleared when all parts are approved.</description>
        <label>Date Time Sent for Review</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Is_Profile_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Profile Locked</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/rsPublicationControllerTest.cls
@isTest
private class rsPublicationControllerTest {
	
	@isTest static void test_method_one() {
		User u = [Select Id, Is_Profile_Locked__c, Date_Time_Sent_for_Review__c from User where Id =: UserInfo.getUserId()];
		rsProfile profile = new rsProfile(u);
		rsPublicationController cont = new rsPublicationController();
		cont.profile = profile;
		cont.newPart();
		cont.CurrentPart.setPublicationTitle('Test Title');
		cont.CurrentPart.setPublication('test Pub');
		cont.CurrentPart.setPublicationDate('12/12/2013');
		cont.CurrentPart.setPublicationAuthor('Test Author');

		Test.startTest();
		PageReference pf = cont.savePart();
		Test.stopTest();

		rs_Profile_Part__c pp = [Select Publication_Title__c, Publication__c, Publication_Date__c, Publication_Author__c
							from rs_Profile_Part__c];

		System.assertEquals( null, pf);
		System.assertEquals( pp.Publication_Title__c, cont.CurrentPart.getPublicationTitle());
		System.assertEquals( pp.Publication__c, cont.CurrentPart.getPublication());
		System.assertEquals( true, pp.Publication_Date__c.isSameDay(Date.parse(cont.CurrentPart.getPublicationDate())));
		System.assertEquals( pp.Publication_Author__c, cont.CurrentPart.getPublicationAuthor());

	}
	
}