src/objects/rs_Profile_Part__c.object
<CustomObject>
    <fields>
        <fullName>Skill_Area__c</fullName>
        <description>Describes what area an employee&apos;s skills lie in.</description>
        <inlineHelpText>Skill area, e.g., Water or Bridges</inlineHelpText>
        <label>Skill Area</label>
        <picklist>
            <picklistValues>
                <fullName>Acoustics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airport Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternative Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analytical Chemistry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architecture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Big Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biosolids</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemical Oxidation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate Change Adapation &amp; Resiliency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coastal &amp; Marine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Combined Heat &amp; Power (CHP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Engagement &amp; Consultation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complex Bridges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Condition Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contaminated Sediments &amp; Waterways</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cost Estimating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cultural Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution &amp; Collection Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document Management &amp; Collaboration Technologies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economics and Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EHS Auditing &amp; Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EHS Management Information Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Efficiency</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <description>Exact skill the employee has.</description>
        <inlineHelpText>Select or enter a skill</inlineHelpText>
        <label>Skill</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Profile Part</label>
    <nameField>
        <displayFormat>PP-{0000000000}</displayFormat>
        <label>Profile Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profile Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/rsAutoCompleteController.cls
/*************************************************************************
*
* PURPOSE: Auto complete Controller
*
* CREATED: 2014 Ethos Solutions - www.ethos.com
* AUTHOR: Brian Lau
***************************************************************************/
global with sharing class rsAutoCompleteController {
	public rsAutoCompleteController() {
		
	}

	@RemoteAction
    global static List<String> getValues(String prefix, String fieldName) { 

    	List<String> values = new List<String>();
    	prefix = '%' + prefix + '%';
    	List<AggregateResult> parts = new List<AggregateResult>();
    	if(fieldName != 'Skill__c') {
    	    parts = (List<AggregateResult>)Database.query('Select ' + fieldName + ' from rs_Profile_Part__c where ' + fieldName + ' LIKE ' +
    																				rsStringUtil.quote(prefix) + ' group by ' + fieldName + ' limit 10');
    	    for(AggregateResult part : parts) {
		        values.add(String.valueOf(part.get(fieldName)));
		    }
    	} else {
    		parts = (List<AggregateResult>)Database.query('Select ' + fieldName + ', Skill_Area__c from rs_Profile_Part__c where ' + fieldName + ' LIKE ' +
    																				rsStringUtil.quote(prefix) + ' group by ' + fieldName + ', Skill_Area__c limit 10');
    		for(AggregateResult part : parts) {
    			if(part.get('Skill_Area__c') != null) {
		        	values.add(String.valueOf(part.get('Skill_Area__c')) + ' - ' + String.valueOf(part.get(fieldName)));
    			} else {
    				values.add(String.valueOf(part.get(fieldName)));
    			}
		    }
    	}
	    

	    values.sort();
    	return values;


    }
}