src/objects/ssh_User_Contact_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting used to determine the record type being used for Employee vs Vendor Contacts. Also determines the name of the default internal account vs vendor account to which Contacts should belong after they are initially generated.</description>
    <fields>
        <fullName>Employee_Record_Type__c</fullName>
        <description>The record type for all AECOM employees</description>
        <label>Employee Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Vendor_Record_Type__c</fullName>
        <description>The record type for all External Vendors</description>
        <label>External Vendor Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Vendor_Uncategorized_Account__c</fullName>
        <description>Default Account to which External Vendor Contacts will be assigned since we don&apos;t know what account they belong to.</description>
        <label>External Vendor Uncategorized Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_User_Account__c</fullName>
        <description>Name of the Account with which all Contacts created for internal AECOM Users will be associated.</description>
        <label>Internal User Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SS-AP User/Contact Settings</label>
</CustomObject>

src/classes/sshCustomSettings.cls
/*************************************************************************
* COMPONENT: Shared Services Helpdesk
* CLASS: sshCustomSettings
* PURPOSE: 
* CREATED: 07/10/15 Ethos Solutions - www.ethos.com
* AUTHOR: Joe DePetro
***************************************************************************/
public with sharing class sshCustomSettings 
{
	public sshCustomSettings() {}

	/**
    * @Description This method will get all the needed Custom Settings for the Case trigger functionality and
    *                 build a CaseTriggerSettings object that holds all the needed settings
    * @return CaseTriggerSettings - the CaseTriggerSettings object will have all the settings needed for the Case trigger
    */    
	public static CaseTriggerSettings getCaseTriggerSettings()
	{
		CaseTriggerSettings settings = new CaseTriggerSettings();

		if(ssh_User_Contact_Settings__c.getInstance('Default') != null)
		{
			String settingName = ssh_User_Contact_Settings__c.getInstance('Default').Internal_User_Account__c;
			if(settingName != null)
				settings.internalUserAccount = [select Id, Name from Account where Name = :settingName];	
			else
				System.debug('Custom Settings Error - Internal_User_Account__c not set');

			settingName = ssh_User_Contact_Settings__c.getInstance('Default').External_Vendor_Uncategorized_Account__c;
			if(settingName != null)
				settings.externalVendorAccount = [select Id, Name from Account where Name = :settingName];
			else
				System.debug('Custom Settings Error - External_Vendor_Uncategorized_Account__c not set');

			settingName = ssh_User_Contact_Settings__c.getInstance('Default').Employee_Record_Type__c;
			if(settingName != null)
				settings.internalUserContactRecordTypeId = sshUserContactUtils.getRecordTypeIdByName(settingName);
			else
				System.debug('Custom Settings Error - Employee_Record_Type__c not set');

			settingName	= ssh_User_Contact_Settings__c.getInstance('Default').External_Vendor_Record_Type__c;
			if(settingName != null)
				settings.vendorContactRecordTypeId = sshUserContactUtils.getRecordTypeIdByName(settingName);
			else
				System.debug('Custom Settings Error - External_Vendor_Record_Type__c not set');
		}
		else
		{
			System.debug('Custom Settings Error - SSH User Contact Settings needs to have a "Default" record.');
		}

		return settings;
	}

	/**
    * @Description Holder object for holding all the settings needed for the Case trigger
    */
	public class CaseTriggerSettings
	{
		public Account internalUserAccount { get; set; }
		public Account externalVendorAccount { get; set; }
		public String internalUserContactRecordTypeId { get; set; }
		public String vendorContactRecordTypeId { get; set; }

		/**
	    * @Description Helper method to make sure all the Custom Settings fields have values.
	    * @return Boolean - true if all the fields have values.
	    */ 
		public Boolean validationOk()
		{
			return internalUserAccount != null && externalVendorAccount != null && String.isNotBlank(internalUserContactRecordTypeId) && String.isNotBlank(vendorContactRecordTypeId);
		}
	}
}