src/objects/ssh_User_Contact_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting used to determine the record type being used for Employee vs Vendor Contacts. Also determines the name of the default internal account vs vendor account to which Contacts should belong after they are initially generated.</description>
    <fields>
        <fullName>Employee_Record_Type__c</fullName>
        <description>The record type for all AECOM employees</description>
        <label>Employee Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Vendor_Record_Type__c</fullName>
        <description>The record type for all External Vendors</description>
        <label>External Vendor Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Vendor_Uncategorized_Account__c</fullName>
        <description>Default Account to which External Vendor Contacts will be assigned since we don&apos;t know what account they belong to.</description>
        <label>External Vendor Uncategorized Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_User_Account__c</fullName>
        <description>Name of the Account with which all Contacts created for internal AECOM Users will be associated.</description>
        <label>Internal User Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SS-AP User/Contact Settings</label>
</CustomObject>

src/classes/sshCaseStatusUpdateTest.cls
@isTest
private class sshCaseStatusUpdateTest {

	@isTest static void testStatusUpdate() {

		Account acct = new Account(Name = 'Uncategorized Vendor');
		insert acct;

		Account acct2 = new Account(Name = 'AECOM Internal Account');
		insert acct2;

		ssh_User_Contact_Settings__c custSetting = new ssh_User_Contact_Settings__c();
		custSetting.Name = 'Default';
		custSetting.External_Vendor_Uncategorized_Account__c = 'Uncategorized Vendor';
		custSetting.External_Vendor_Record_Type__c = 'Vendor';
		custSetting.Employee_Record_Type__c = 'AECOM Employee';
		custSetting.Internal_User_Account__c = 'AECOM Internal Account';
		insert custSetting;

		Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];

		User u = new User(Alias = 'jtest', Email = 'SFDCTestCase@aecom.com',
		                  EmailEncodingKey = 'UTF-8', LastName = 'Tester', LanguageLocaleKey = 'en_US',
		                  LocaleSidKey = 'en_US', ProfileId = p.Id, Department = 'Fake Department',
		                  TimeZoneSidKey = 'America/Los_Angeles', UserName = 'joe@ssh.com.test');

		insert u;

		Group g1 = new Group(Name = 'SS-AP Cases', Type = 'Queue');
		insert g1;

		QueuesObject q1;
		System.runAs(new User(Id = UserInfo.getUserId())) {
			q1 = new QueueSObject(QueueID = g1.Id, SObjectType = 'Case');
			insert q1;
		}

		Case c1 = new Case(Status = 'Pending', OwnerId = g1.Id, SuppliedEmail = 'SFDCTestCase@aecom.com');
		insert c1;

		c1.OwnerId = u.Id;

		update c1;

		c1 = [select Status, OwnerId from Case where Id = :c1.Id];

		System.assertEquals(c1.Status, 'In Review');
		System.assertEquals(c1.OwnerId, u.Id);
	}
}